### ISSUE TITLE
Cannot receive notification sent via Firebase admin SDK

### ISSUE THREAD

**Issue by itssidhere** [rafaelsetragni/awesome_notifications#1]
Hello I am trying to send push notifications via firebase admin sdk , nothing happens when i do as stated in the example but when i change content to a string then this gets logged

> FCM received
> Invalid Firebase notification content

My question is why FCM received is not logged when I change the content as mentioned in the documentation?

**Comment by itssidhere** [comment]
Ok so I resolved my issue. Can you tell me if you plan to support notifications sent through admin sdk?

**Comment by rafaelsetragni** [comment]
Can you give me a example of what you are trying to sent via FCM?

Remember that you need to use the "data" content of FCM message to send your notification, because the "notification" object only supports "title" and "body" fields.

**Comment by rafaelsetragni** [comment]
And the data payload is  a Map<String:String> object. So, if you sent a FCM data thats disrespect that format, your payload will be discarted as invalid.

An example of how to send FCM data with payload object:

```dart
{
    "to" : "[APP_TOKEN]",
    "collapse_key" : "type_a",
    "data" : {
        "content": {
            "id": 100,
            "channelKey": "big_picture",
            "title": "Huston!\nThe eagle has landed!",
            "body": "A small step for a man, but a giant leap to Flutter's community!",
            "notificationLayout": "default",
            "showWhen": true,
            "autoCancel": true,
            "privacy": "Private",
            "payload": {
                "product_id": "secret_product_uuid",
                "discount": "20.0"
            }
        }
    }
}
```

**Comment by rafaelsetragni** [comment]
But you raised a important point. I didnt said anything about the required types on documentation.
Ill do it soon as possible to anyone else face the same problem.

Thank you!

**Comment by aaqibism** [comment]
I was having the same problem receiving messages sent from both the Firebase Cloud Messaging dashboard and through Firebase admin SDK. What I found for the dashboard was that you needed to add within 'Custom Data' the content key without any quotes and then for the value the JSON data again without any quotes anywhere. The value looked something like this:
`{id:100, channelKey: basic_channel, title: Test, body: Hello, notificationLayout: Default}`

For the admin SDK, JSON.stringify solved all the same issues. Here's an example written in TypeScript for creating a payload for sending. The additional data within notification and android is not really needed for displaying the message but I just kept it for compatibility reasons.
```
function createPayload(message: string, author: string, topic: string) {
  return {
    notification: {
      title: message,
      body: `Sent from ${author}`,
    },
    data: {
      content: JSON.stringify({
        id: 100,
        channelKey: "basic_channel",
        title: message,
        body: `Sent from ${author}`,
        notificationLayout: "Default",
      }),
      actionButtons: JSON.stringify([
        {
          key: "REPLY",
          label: "Reply",
          autoCancel: true,
          buttonType: "InputField",
        },
        { key: "ARCHIVE", label: "Archive", autoCancel: true },
      ]),
    },
    android: {
      notification: {
        channel_id: "2",
        click_action: "FLUTTER_NOTIFICATION_CLICK",
      },
      priority: "high",
    },
    webpush: {
      headers: {
        Urgency: "high",
      },
    },
    topic: topic,
  } as admin.messaging.Message;
}
```
I hope that helps anyone with the same issues.

**Comment by rafaelsetragni** [comment]
Exactely! I need and i will make the parser inside the plugin more torelable to different types than the expected ones.

Thank you so much aaqibism for your tip! I have absolute sure that your advices will be useful to many others!
