### ISSUE TITLE
Set soundSource to default phone ringtone

### ISSUE THREAD

**Issue by blackbusters** [rafaelsetragni/awesome_notifications#102]
Hello, thanks for this wonderful plugin.

Is there any way to set notification sound to default phone ringtone sound? For example with whatsapp, when call notification appear it plays my phone ringtone instead of notification sound.

Also is it possible to set color for icon or label in Action Button? 

Thanks in advance..

**Comment by rafaelsetragni** [comment]
> Is there any way to set notification sound to default phone ringtone sound? For example with whatsapp, when call notification appear it plays my phone ringtone instead of notification sound.

Yes! Thanks to your question ive made a new feature to set what default sound should be played: ringtone, notification or alarm sound. It will be available on next release.

> Also is it possible to set color for icon or label in Action Button?

Yes, but is only possible to define a single color for everything. Is not possible to define a button with one color and the icon with another one.

**Comment by blackbusters** [comment]
This is very good news to me! really excited for the next release..

Thank you very much and keep up the good work.

**Comment by rafaelsetragni** [comment]
New version released. Check to see if the problem is resolved.

**Comment by blackbusters** [comment]
Alright will try it soon, thanks and really appreciate your hard work !
