### ISSUE TITLE
Background Code

### ISSUE THREAD

**Issue by Samson11** [rafaelsetragni/awesome_notifications#103]
Hi is it possible for me to run some background code when i recieve a push notification via Firebase when the flutter app is terminated or in background?.
If so can you please add that functionality.

Thanks in advance

**Comment by rafaelsetragni** [comment]
Please, take a look at this topic:
[https://github.com/rafaelsetragni/awesome_notifications/issues/97](https://github.com/rafaelsetragni/awesome_notifications/issues/97)
