### ISSUE TITLE
Any fix to the iOS mediaPath issue?

### ISSUE THREAD

**Issue by ralmarri12** [rafaelsetragni/awesome_notifications#104]
I had a to make a release today, and I got this error during the build.

<img width="277" alt="image" src="https://user-images.githubusercontent.com/3468326/106581071-7edc7480-6553-11eb-8d20-20d67469be0c.png">

<img width="866" alt="image" src="https://user-images.githubusercontent.com/3468326/106581097-8734af80-6553-11eb-967f-268a4ca82284.png">

I have read issue #84 but seems like a solution is merged, but I'm still facing the issue. Knowing that I have latest version which is 0.0.5+5
`awesome_notifications: ^0.0.5+5`

so any quick fix that I can do to build? 

Thank you,

**Comment by ralmarri12** [comment]
For anyone facing the problem, I made a quick fix that help me make my first build, which is 

in the line
`
if(
    BitmapUtails.getMediaSourceType(icon) != MediaSource.Resource
)
`

make it like
`
if(
    BitmapUtails.getMediaSourceType(mediaPath: icon) != MediaSource.Resource
)
`

**Comment by bbence84** [comment]
@ralmarri12 : sorry, maybe basic question. But do you just go ahead and edit the file in the flutter package cache or how do you do  a local patch for cocoapods code? Thanks!

**Comment by ralmarri12** [comment]
Hi @bbence84 , in fact I edit the code from the package itself. Which is a bad practice, all my team mate had to do the same edit in order to run the code correctly, but what I see, that was my only solution.

yeah , sorry for late reply

**Comment by rafaelsetragni** [comment]
The fix is already on master branch and will be available for everyone on next release.

**Comment by Tuxilero** [comment]
@rafaelsetragni I am so happy to hear that! Any idea when we can expect a new version to come out? This is quite critical bug for us, as we are not able to use CI to build the APP, and have to change it manually each time we pub get dependencies.

**Comment by vishwajit76** [comment]
> The fix is already on master branch and will be available for everyone on next release.

master branch have null safety

**Comment by rafaelsetragni** [comment]
New version released. Check to see if the problem is resolved.
