### ISSUE TITLE
show notification on lock screen?

### ISSUE THREAD

**Issue by benyamin218118** [rafaelsetragni/awesome_notifications#105]
hi
thanks for this good package!

i need to show my notification on lock screen and turn the screen on
i think i should do this in java : 
  ` .setVisibility(NotificationCompat.VISIBILITY_PUBLIC)`
what should i do here in awesome_notifications for that?

**Comment by benyamin218118** [comment]
i can set the visibility using : 
 `   defaultPrivacy: NotificationPrivacy.Public`
in the channel properties.
but when the screen is off and i create a notification , notification sound is playing , but screen is not going to turn on , and i need this.
is there any solution about how to do this?

**Comment by rafaelsetragni** [comment]
You did it right. Can you debug your project to figure out why this configuration was not applied?

The source code's moment that this configuration is handle is this one:
https://github.com/rafaelsetragni/awesome_notifications/blob/a556245ca98e23c0592374f33f37a752d6f3df2f/android/src/main/java/me/carda/awesome_notifications/notifications/NotificationBuilder.java#L313

**Comment by benyamin218118** [comment]
i did this to solve my problem with wakeLock.acquire(timeout);
https://github.com/babaeeieKhodemoon/awesome_notifications/commit/fb2be7a49923d1a2bed79ccaa2bb372acfa311e5#diff-5502af789d9356c835aa42fd06f4dbbe2a6cc3f569f1ab01f783ad5daff8e213.
using this the lock screen turns on, but the notification icon is just a little icon , if you want to see the contents, you should click on it(second problem!).
but i will comment that line you sayd and i will try it again.
tnx

**Comment by benyamin218118** [comment]
hi.
i commented that line
https://github.com/rafaelsetragni/awesome_notifications/blob/a556245ca98e23c0592374f33f37a752d6f3df2f/android/src/main/java/me/carda/awesome_notifications/Definitions.java#L159
but still a little icon is there and you should click on it to see the contents.
![notifIcon](https://user-images.githubusercontent.com/43001019/107110691-3c6eac80-685f-11eb-80b8-42bb52951423.jpg)

**Comment by rafaelsetragni** [comment]
Test it in another android versions. Maybe just show a icon is a default behaviour from your android version.

**Comment by benyamin218118** [comment]
ok tnx i will test it on another phone with another android version.
and maybe it is because of my settings!? i will check it and let you know

**Comment by benyamin218118** [comment]
hi. 
i have tested that on samsung s10+ and it is still so ...

**Comment by rafaelsetragni** [comment]
I´ve fixed it. this fix will be available on next release. Also check your android security and privacy configurations. Some of then could change the way that your notifications are displayed.

**Comment by benyamin218118** [comment]
ok tnx,closing the issue and waiting for good news!

**Comment by Thioby** [comment]
> I´ve fixed it. this fix will be available on next release. Also check your android security and privacy configurations. Some of then could change the way that your notifications are displayed.

Is it fixed in latest version?

**Comment by rafaelsetragni** [comment]
Yes, and you can check it right now.
