### ISSUE TITLE
Avoid messaging notification

### ISSUE THREAD

**Issue by xmavara** [rafaelsetragni/awesome_notifications#107]
Hello,
I use both awesome_notifications and firebase_messaging 8.0 and everything is okay except background message.
My code is :
```
FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async { 
  await Firebase.initializeApp();
  AwesomeNotifications().createNotification(
      content: NotificationContent(
          id: 10,
          channelKey: 'basic_channel',
          title: message.notification.title,
          body: message.notification.body));
}
```

When my app is in background or closed two notification is shown.
I want to show only AwesomeNotifications notif.
Is there any way to prevent second notification?
thanks

**Comment by rafaelsetragni** [comment]
Please, take a look at your voting topic.

**Comment by scalz** [comment]
Hi,
just in case someone gets here while searching how to display only awesome notification without showing the fcm notification.
When you send a fcm notification, you just need to use 'data' key, and remove 'notification' key in json.
