### ISSUE TITLE
No vibration when I installed the example on github.

### ISSUE THREAD

**Issue by anonyran** [rafaelsetragni/awesome_notifications#109]
I use lenovo a7000 with android 6.0 and I borrowed from my friend an oppo, and there was no vibration when I installed the example on github. I have tried all buttons in the vibration pattern.

**Comment by Artem-Sobolev** [comment]
I'm using Xiaomi Note 3 for debugging and I have the same problem;
There is just no vibration at all and it doesn't matter what option I write in code;

**Comment by rafaelsetragni** [comment]
Certify to use the last version and try to debug de native code on Android Studio, using the option to `Attatch to the running process`

**Comment by rafaelsetragni** [comment]
I gonna close this issue for now, since there is no more activity in 6 months. But you can reopen it, in case you judge necessary.
