### ISSUE TITLE
Language dependent channel name and description?

### ISSUE THREAD

**Issue by bbence84** [rafaelsetragni/awesome_notifications#112]
This might be a basic question, but how do you provide a translatable text for the channel name and description? I am using EasyLocalization, but that is initialized insided the runApp call, whereas AwesomeNotifications is initialized outside of the runApp call. Can I maybe move the AwesomeNotifications initilization to another widget inside the runApp widget tree?
Thanks!

**Comment by rafaelsetragni** [comment]
You can update the channel name and description at any time. When your user change your languague, update the channel saving it with the translated text.
