### ISSUE TITLE
Support for flutter latest stable version (1.22.6) - due to flutter_driver

### ISSUE THREAD

**Issue by matanshukry** [rafaelsetragni/awesome_notifications#113]
Trying to use the latest stable version of flutter together with the latest version of this plugin (`0.0.5+5` as of right now), results in this error:
`Because every version of flutter_driver from sdk depends on platform 3.0.0-nullsafety.2 and every version of awesome_notifications depends on platform ^2.2.0, flutter_driver from sdk is incompatible with awesome_notifications.`

I looked at issues like #61 and #49 , where you seem to suggest one should Change the notification on the local copy.
However while I can do that for my local copy (although a bit more complex since the upgrade is for platform from 2.2.0 to 3.0.0-nullsafety.2), I can't do it for my deployment process.

**Comment by rafaelsetragni** [comment]
Source merged successfully! Thank you so much!
