### ISSUE TITLE
Not getting custom sound in release build

### ISSUE THREAD

**Issue by kcs-rahuljoshi** [rafaelsetragni/awesome_notifications#118]
Not getting custom sound in release build

**Comment by rafaelsetragni** [comment]
Custom sound will not be available in next releases. Instead, will be available a option to force a channel update, allowing to update all the parameters from the channel, with the downside to close all current notifications for that channel.

This feature will be available on next release.

**Comment by kcs-rahuljoshi** [comment]
In how much time you need release next version

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by kcs-rahuljoshi** [comment]
Hello, RafaelSetragni any update regarding the plugin. please let us known in how many days you are upload the next release version.

**Comment by rafaelsetragni** [comment]
Also, certify to use the tag "res_" before your resources, to avoid obfuscation from java minification process.

**Comment by rafaelsetragni** [comment]
New version released. Check to see if the problem is resolved.

**Comment by kcs-rahuljoshi** [comment]
Ok will check thanks for update.

[cid:image002.png@01D6B206.7594C400]

**Comment by kcs-rahuljoshi** [comment]
Hello Rafaelsetragni ,
                Issue is resolved I have checked in release build working fine.

[cid:image002.png@01D6B206.7594C400]

From: Rahul Joshi<mailto:rahul.joshi@kcsitglobal.com>
Sent: Monday, March 8, 2021 6:52 AM
To: rafaelsetragni/awesome_notifications<mailto:reply@reply.github.com>; rafaelsetragni/awesome_notifications<mailto:awesome_notifications@noreply.github.com>
Cc: Author<mailto:author@noreply.github.com>
Subject: RE: [rafaelsetragni/awesome_notifications] Not getting custom sound in release build (#118)

Ok will check thanks for update.

[cid:image002.png@01D6B206.7594C400]
