### ISSUE TITLE
Tapping on action button doesn't bring app to foreground

### ISSUE THREAD

**Issue by jglatre** [rafaelsetragni/awesome_notifications#12]
I've set up some `NotificationActionButton`s with button type `KeepOnTop` and I'm receiving tap events correctly, but when the app is minimized tapping on a button doesn't bring app to foreground, however tapping outside the buttons, on the background panel does the expected effect. Is this an intended behavior or a bug?

**Comment by jglatre** [comment]
Yes, this is the case: the app is doing geofencing, so when the user enters some predefined areas (regardless of being in the foreground or not) the app must register him in that area, but as the register action needs to be accepted by the user, those little buttons are really useful, I just present a notification carrying a confirmation, something like: "You just have entered area X, do you want to be registered? Yes/No", if user taps Yes the app should open a page with information about that area (hence the need of going to foreground), if he taps No current behaviour may be OK.

BTW, I'm using `KeepOnTop` because when I use `Default` the `actionStream` produces no events. Another bug or am I missing something?

**Comment by rafaelsetragni** [comment]
Default actions should always wake up the application. Maybe you are missing something.

But, while im doing the iOS code wright now, i finded a option to notifications triggered by geolocation. In other words, the notification is triggered not by time, but when the users arive in some place.

That feature may be useful for your application?

**Comment by rafaelsetragni** [comment]
Actualy, it is possible to do notifications based on geofence for Android, but it envolves to require to the app users permissions that could be invasive for some kind of other applications.

So, since this plugin is built for many applications, i will not be able to do notifications fully based on geofence on this pluggin, even its being technicaly possible to do. Sorry.

But anyway, lets get back to your "wake up action problem" to fix it.

**Comment by jglatre** [comment]
Obviously I don't expect your plugin to handle all kind of notification sources, like geofencing, and I'm also happy with my current geofencing algorithm, no need to change it.

So at this moment my geofencing is working nicelly with your plugin, showing up at the right moment with the right data, the only issue is with action events (that as you already have seen are essential for my use case). It boils down to:

-   if I use Default I don't get events (maybe I should investigate and try more).

-  if I use KeepOnTop I get events but I can't bring the app to foreground.

**Comment by rafaelsetragni** [comment]
I guess i got whats going on!
The default event is lost only when you pretend to wakeup your app?

While i built the streams, i did it choosing the broadcast type, wich does not wait until the first subscription to fire the listeners.
In other words, the default action arives too fast between the pluggin initialization and the first listener.

Try to change your plugin local files, updating the file "lib/src/awesome_notifications_core.dart":

```Java
  /// STREAM CREATION METHODS *********************************************

  // Streams are created so that app can respond to notification-related events since the plugin is initialised in the `main` function
  final StreamController<String> _tokenStreamController =
      StreamController<String>();

  final StreamController<ReceivedNotification>
      // ignore: close_sinks
      _createdSubject =
      StreamController<ReceivedNotification>();

  final StreamController<ReceivedNotification>
      // ignore: close_sinks
      _displayedSubject =
      StreamController<ReceivedNotification>();

  final StreamController<ReceivedAction>
      // ignore: close_sinks
      _actionSubject = StreamController<ReceivedAction>();

  final StreamController<ReceivedAction>
      // ignore: close_sinks
      _dismissedSubject =
      StreamController<ReceivedAction>();

  /// STREAM METHODS *********************************************
```

I hope it helps you. Keep me in touch.

**Comment by jglatre** [comment]
> The default event is lost only when you pretend to wakeup your app?

Events are never received in `Default` mode, in fact when in `KeepOnTop` mode I see the line "Action received" in the logs, but in the other mode that line never shows up.

I think the problem comes from a lower level, not dart code, because I've put a breakpoint at the beginning of `_handleMethod` an it's never invoked in `Default` mode.

I've tried your patch and I get the same behaviour (in both modes). BTW, I think you shouldn't drop that `broadcast` because then client app won't be able to subscribe more than once to the same stream. Maybe you should consider using rx_dart instead of raw dart streams, as it gives you more control over stream behavior.

**Comment by rafaelsetragni** [comment]
One user report similar problem in the past [here](https://github.com/rafaelsetragni/awesome_notifications/issues/6) , but i couldnt reproduce his error. He says he fix it include the code bellow inside his `Application.kt`:

```Kotlin
override fun registerWith(registry: PluginRegistry) {
AwesomeNotificationsPlugin.registerWith(registry?.registrarFor("me.carda.awesome_notifications"))
///FirebaseCloudMessagingPluginRegistrant.registerWith(registry)
}
```
