### ISSUE TITLE
Customize and send notification through FCM console

### ISSUE THREAD

**Issue by dhruv048** [rafaelsetragni/awesome_notifications#120]
Hi, first of all thanks for the awesome package with tons of options to customise the notification.
i was using fcm console to send notification currently and i want to use fcm console with this package too.
but i am stuck i a case that how can i customise and send notification from fcm console.
the reason i want to use fcm console is that i can send the notification to each and every user using my app with out retrieving the token of individual one.
Can you please spare your time and help me with my confusion.
Thankyou

**Comment by rafaelsetragni** [comment]
Your app need to send the user's token id to your server. After that, on your backend you create a reference of the token id to each user and call the firebase server to send the notification.

Remembe, the token id is created associated with the os user and app instaled. So, the token id can be changed for each new instalation, but also for a couple time after, with no reason. So, you need to keep tracking it on every app startup and send the new one to your backend.

**Comment by dhruv048** [comment]
Ohhkayyy so there is no way i can send the notification from the FCM. 
Anyways thanks for your information, thanks

**Comment by rafaelsetragni** [comment]
Of course you can. You only need to send the package as the same structure as showed on our readme file.

I do recommend you to use the firebase backend methods instead fcm. FCM is for tests and simple use. That is the limitation that you need to overpasses to get a more robust solution.
