### ISSUE TITLE
Grouping is not working

### ISSUE THREAD

**Issue by razmik-gharibyan** [rafaelsetragni/awesome_notifications#121]
So i am sending this json request by Postman 
{
 "to" : "my device token",
"mutable_content" : true,
"content_available": true,
"data" : {
        "content": {
            "id": 100,
            "channelKey": "basic_channel",
            "title": "Huston!\nThe eagle has landed!",
            "body": "A small step for a man, but a giant leap to Flutter's community!",
            "notificationLayout": "Default",
            "largeIcon": "https://media.fstatic.com/kdNpUx4VBicwDuRBnhBrNmVsaKU=/full-fit-in/290x478/media/artists/avatar/2013/08/neil-i-armstrong_a39978.jpeg",
            "bigPicture": "https://www.dw.com/image/49519617_303.jpg",
            "showWhen": true,
            "autoCancel": true,
            "privacy": "Private",
            "groupKey": "thiskey"
        },
        "actionButtons": [
            {
                "key": "REPLY",
                "label": "Reply",
                "autoCancel": true,
                "buttonType":  "InputField"
            },
            {
                "key": "MARK_AS_READ",
                "label": "Mark as read",
                "autoCancel": true
            },
            {
                "key": "SNOOZE",
                "label": "Snooze for 1 hour",
                "autoCancel": true
            }
        ]
    }
}

And in my code i have also added groupKey for NotificationChannel (same as groupKey in json request above) also using these parameters 

setAsGroupSummary: true,
groupAlertBehavior: GroupAlertBehavior.Children,
groupKey: "thiskey" 

And i am sending this json to same device by changing only id and logically it should group them together if there are more then 1 message in tray within same channel id, but it doesn't. I have tried putting NotificationLayout to Inbox , but it didn't helped too.

I am using Xiaomi device.

**Comment by rafaelsetragni** [comment]
The group functionality is working on local notifications as expected?

And to certify if the json package forma is correct, you can call the "toMap" method, to transform the notification package on a json one.

**Comment by razmik-gharibyan** [comment]
> Is the group functionality working on local notifications as expected?
> 
> And to certify if the json package forma is correct, you can call the "toMap" method, to transform the notification package on a json one.
Doesnt package automatically create notification by Notification.Builder ? So that is basically a local notification or am i wrong?
Json is correct, the only thing i am not sure about is sending grouKey parameter but as my logic tells me it's necessary so that client side can indentify group key.

**Comment by rafaelsetragni** [comment]
Yes, you are correct in parts. But the methods called are different on begining.

So, do the test, creating an couple of local notifications with the same group key and different ids to check if its working as expected.

**Comment by razmik-gharibyan** [comment]
If you mean AwesomeNotifications().createNotification() method for creating local notifications then it don't have groupKey param to set to.

**Comment by rafaelsetragni** [comment]
You need to set the group key inside your channel's configuration

**Comment by razmik-gharibyan** [comment]
Indeed problem was with unistalling and installing again. So i assume that everytime some configuration changes happen on channel i should re-install. But still i see that GroupBehavior.Children is not grouping 2 messages into each other within 1 notification, but just making visual borders around all app related notifications which is not how it suppost to be. Correct me if am wrong.

**Comment by ashishbeck** [comment]
Hello, I tried exactly everything from this thread but can't seem to group the notifications no matter what. Can you explain from scratch how it is achieved?

**Comment by razmik-gharibyan** [comment]
Problem is still there, grouping is not working, i have tried creating them with AwesomeNoficiations.createNotification() but group behavior isn't there. Any suggestions?
This is my channel 
```
AwesomeNotifications().initialize(
    // set the icon to null if you want to use the default app icon
      null,
      [
        NotificationChannel(
            channelKey: 'basic_channel',
            channelName: 'Basic notifications',
            channelDescription: 'Notification channel for basic tests',
            defaultColor: Color(0xFF9D50DD),
            ledColor: Colors.white,
            setAsGroupSummary: true,
            groupAlertBehavior: GroupAlertBehavior.Children,
            groupKey: "thiskey"
          //channelShowBadge: true
        )
      ]
  );
```
 And this is notification

```
AwesomeNotifications().createNotification(
        content: NotificationContent(
            id: id,
            channelKey: "basic_channel",
            title: "Huston! The eagle has landed!",
            body: "A small step for a man, but a giant leap to Flutter's community!",
            notificationLayout: NotificationLayout.Default,
            largeIcon: "https://avidabloga.files.wordpress.com/2012/08/emmemc3b3riadeneilarmstrong3.jpg",
            bigPicture: "https://www.dw.com/image/49519617_303.jpg",
            showWhen: true,
            autoCancel: true,
            payload: {
              "secret": "Awesome Notifications Rocks!"
            }
        ),
      actionButtons: [
        NotificationActionButton(
          key: "REPLY",
          label: "Reply",
          autoCancel: true,
          buttonType: ActionButtonType.InputField
        )
      ]
    );
```

**Comment by ashishbeck** [comment]
Yeah it doesn't work me as well. What exactly is the groupKey parameter in the channel configuration supposed to do? It has to be provided via a notification for it to work , right?
Neither the createNotifications() method nor the HTTPS request has any parameter to provide that.

**Comment by razmik-gharibyan** [comment]
GroupKey on android is supposted to group a few notifications that has same grouKey under 1 notification with same grouKey.
So for example if you create multiple notifications with same channel id, same groupKey but different id, they still would not be grouped under 1 notification, because you have to explicitly create one more notification for grouping those previous notifications, with same groupKey, without title and body and by specifying groupSummary true and groupingBehavior. I have looked at NotificationBuilder.java file under this plugin and did not find a code that will explicitly add one more notification for grouping.

**Comment by rafaelsetragni** [comment]
In fact, there is a issue while the group key was sent to native code. The group key sent was always null. I gonna release a new version soon with this fix.
Thank you so much for your report.

**Comment by rafaelsetragni** [comment]
Also, i've removed the option "setAsGroupSummary", because i automatized it. Also, ive included an extra option called "groupSort", that sorts the notification based in time on ascending or descending order.

This feature will be available in next release.

**Comment by razmik-gharibyan** [comment]
I will wait for it. Is there some documentation of what fcm content should look like with all available options. For example  "displayOnForeground": false .There is nowhere written that we can have this, i found out about it from other issue.
I know it's not related to this topic but that would've help alot.

**Comment by rafaelsetragni** [comment]
New version released. Check to see if the problem is resolved.

**Comment by razmik-gharibyan** [comment]
Ok i will give it a try, and comment result here

**Comment by nietsmmar** [comment]
I can't get grouping to work. Has anyone else been successful and could share some insight? Thank you!

**Comment by rafaelsetragni** [comment]
This is a grouped notification for Android:

![image](https://user-images.githubusercontent.com/40064496/112047070-8cfa4a80-8b2b-11eb-9fb5-209b66f18d60.png)


And this is a grouped notification for iOS:

![image](https://user-images.githubusercontent.com/40064496/112047423-08f49280-8b2c-11eb-9640-a8b007e105f5.png)


Is that what you wanna to do?

**Comment by nietsmmar** [comment]
Yes, I'd like to send three notifications with the same groupId that will get grouped like in your screenshots. Really cool would be the `ActionButton` of every notification would be still visible in case this is possible somehow.

I can't figure out how to do this. I added the same `groupKey` in the NotificationChannel when calling `initialize` but they won't get grouped. Is there some example code somewhere?

**Comment by rafaelsetragni** [comment]
On Android maybe is necessary to reinstall the app or do an `forceUpdate` , because once setted, the channel only is able to change his name and title.

Action button does not apperars at any mobile platform on group summary, only for individual notifications.

**Comment by nietsmmar** [comment]
> On Android maybe is necessary to reinstall the app or do an `forceUpdate` , because once setted, the channel is only able to change his name and title.

Thanks! this did the trick.
