### ISSUE TITLE
iOS action buttons are not showing

### ISSUE THREAD

**Issue by razmik-gharibyan** [rafaelsetragni/awesome_notifications#122]
I am using this scheme for generating local notification with action button. Everything is working except buttons. Buttons are not showing. I have done all steps via README instructions. One more note, from readme it is not clear that we need to set Bitcode Enable to NO from AwesomeContenct and AwesomeService Build Settings too. 

```
AwesomeNotifications().createNotification(
        content: NotificationContent(
            id: id,
            channelKey: "basic_channel",
            title: "Huston! The eagle has landed!",
            body: "A small step for a man, but a giant leap to Flutter's community!",
            notificationLayout: NotificationLayout.Default,
            largeIcon: "https://avidabloga.files.wordpress.com/2012/08/emmemc3b3riadeneilarmstrong3.jpg",
            bigPicture: "https://www.dw.com/image/49519617_303.jpg",
            showWhen: true,
            autoCancel: true,
            payload: {
              "secret": "Awesome Notifications Rocks!"
            }
        ),
      actionButtons: [
        NotificationActionButton(
          key: "REPLY",
          label: "Reply",
          autoCancel: true,
          buttonType: ActionButtonType.InputField
        )
      ]
    );
```

**Comment by rafaelsetragni** [comment]
Try to run the example app inside the plugin to check if the action buttons will still not be displayed.

**Comment by razmik-gharibyan** [comment]
Example app does not work because there are problems with NotificationContent.swift file, with mediaPath and +icon+ , after fixing them manually and re-running app i get this error which i have no idea how to fix.

 ld: warning: Could not find or use auto-linked framework 'Flutter'
    Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_FlutterStandardTypedData", referenced from:
          objc-class-ref in awesome_notifications(SwiftAwesomeNotificationsPlugin.o)
      "_OBJC_CLASS_$_FlutterError", referenced from:
          objc-class-ref in awesome_notifications(SwiftAwesomeNotificationsPlugin.o)
      "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
          objc-class-ref in awesome_notifications(SwiftAwesomeNotificationsPlugin.o)
    ld: symbol(s) not found for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    ld: warning: Could not find or use auto-linked framework 'Flutter'
    Undefined symbols for architecture arm64:
      "_OBJC_CLASS_$_FlutterStandardTypedData", referenced from:
          objc-class-ref in awesome_notifications(SwiftAwesomeNotificationsPlugin.o)
      "_OBJC_CLASS_$_FlutterError", referenced from:
          objc-class-ref in awesome_notifications(SwiftAwesomeNotificationsPlugin.o)
      "_OBJC_CLASS_$_FlutterMethodChannel", referenced from:
          objc-class-ref in awesome_notifications(SwiftAwesomeNotificationsPlugin.o)

**Comment by rafaelsetragni** [comment]
That happens because your ios folder was created on a older flutter version and now it will not work on new one. You unfortunally need to do the following steps:

    Update your Cocoa pod instalation with sudo gem install cocoapods
    Update your Flutter directory with flutter upgrade
    Save every modification inside your iOS folder and delete it
    Recreate the iOS folder using the command flutter create .
    Clean your project with flutter clean
    Redo all the steps for iOS inside from iOS Extra Configuration's Readme topic

Yes, is pretty bad. But that happens offen while were working with iOS products because they are Apple and do Apple things. They constantely keep the effort to make the "non native developers" lives worst, every day.

**Comment by supidupicoder** [comment]
Hello, after compiling the sample app, the Notification Action buttons do not seem to work.
Using an iPhone 5s
The notification is displaying, tapping on it brings you to a new activity, but no "quick action buttons" are displayed.
