### ISSUE TITLE
Specify amount of time the notification stays on screen and customization

### ISSUE THREAD

**Issue by rekonvald** [rafaelsetragni/awesome_notifications#123]
Hi!
Thank you for wonderful plugin!
Is it possible to style it so it would look as if calling notification(haven't found custom buttons  layout and icons for them) 

Thank you

**Comment by rekonvald** [comment]
Can we also specify amount of time the notification stays on screen? 

BTW, I use firebase, can I use this plugin simultaneously with yours, because after adding this plugin(and adding custom configs as was mentioned in readme) I have a lot of issues when I build for ios, such as Firebase-iOS 11.0.debug.xcconfig" is a member of multiple groups ("Support Files" and "Support Files") etc

**Comment by rafaelsetragni** [comment]
I gonna remove the push support for this plugin, wich should resolve a lot of your iOS problems. 
Will be there a last version, with some fixes before the 0.0.6 version, that will not have the push support anymore.

**Comment by nsumithradeveloper** [comment]
> Hi!
> Thank you for wonderful plugin!
> Is it possible to style it so it would look as if calling notification(haven't found custom buttons layout and icons for them)
> 
> Thank you

Yes. That would be great to create incoming call like notification like whatsapp
