### ISSUE TITLE
Replace substitution behavior of same id notification with appending at most 4 previous body

### ISSUE THREAD

**Issue by ashishbeck** [rafaelsetragni/awesome_notifications#124]
Taken from #65 
> if you think this substitution behaviour is not the correct one we still can change this, this plugin is not in final release.
> i've been thinking about it and now i starting to think than the replacement behaviour is not the correct one.

I would like to support this idea because it will help create notification trees like that of whatsapp. What you could do is add the new notification body to the previous one for at most 4 messages. I'm not sure how difficult it would be to achieve this but I hope you succeed.
Cheers.

**Comment by rafaelsetragni** [comment]
But the notifications with the same id always update the last one, doesnt?

**Comment by ashishbeck** [comment]
Yes it does. But then it replaces the previous notification and the user doesn't see the previous one when 2 notifications arrive one after another.

Current system-
Notification 1 is created and displayed. Notification 2 with the same id is created which replaces the notif 1 which the user might not have seen and is lost.

Proposed system-
Notification 1 is created and displayed. Notif 1 is not dismissed and notification 2 with the same id is created. The message from notif 1 is stored and joined to the message from the new notif 2 with a newline. Notification 3 with the same id is created and joined to the previous message body with a newline.
This is to emulate how whatsapp and telegram handles notifications

**Comment by rafaelsetragni** [comment]
What you want to do is group your notifications. This can be easily achieved with groupKey and groupSort, and the id must necessarily be different.

GroupKey and GroupSort will be available on next release, today.

**Comment by rafaelsetragni** [comment]
New version released. Check to see if the problem is resolved.

**Comment by rafaelsetragni** [comment]
You need to concatenate the text messages and update te notification with the same ID. What i saw on WhatsApp was a single notification updated for a person 2 person chat and group notifications for groups.

**Comment by ashishbeck** [comment]
Yeah I was just thinking of handling it from the app side. I guess that would be a good solution. Thanks for the quick update. You can close this issue.
