### ISSUE TITLE
issue with iOS debug

### ISSUE THREAD

**Issue by Filpin011** [rafaelsetragni/awesome_notifications#13]
hi, I'm trying to implement your package but when I try to debug, vs code give me this output
<img width="971" alt="Schermata 2020-10-16 alle 14 21 56" src="https://user-images.githubusercontent.com/64793842/96122555-f37e9b00-0ef1-11eb-8356-8586075b082e.png">
pls help me :(

**Comment by Filpin011** [comment]
I checked and the line of code talk about firebase, but I don't use it anywhere, how is possible he is talking about it?

**Comment by rafaelsetragni** [comment]
The iOS plugin is under construction, so you kind find some issues like this for a while.
This function check if the "GoogleService-Info.plist" file exists and, if don't, does not initalizes the firebase service.

Its strange this function does not return a least a empty string. Maybe the XCode tricked me to think that this file does not existed in my tests. I will send a update soon to fix this problem.

But, you can do it right now, to not wait until the next release. Just replace on your local files the method enableFirebase by the code below:

```swift
    private func enableFirebase(_ application: UIApplication){
        guard let firebaseConfigPath = Bundle.main.path(forResource: "GoogleService-Info", ofType: "plist") else {
            return
        }
        let fileManager = FileManager.default
        
        if fileManager.fileExists(atPath: firebaseConfigPath) {
            FirebaseApp.configure()
        }
    }
```

**Comment by Filpin011** [comment]
tnx, I only want to use local storage for save notification, then with this I can do?

**Comment by rafaelsetragni** [comment]
You can capture the notification listening **createStream**, extract the content using `toMap()` method, serialize it into a string and store it on local storage with the [shared_preferences](https://pub.dev/packages/shared_preferences) Flutter plugin.

But, were you able to start your iOS app with the fix above? ill insert this fix in next update if so

**Comment by Filpin011** [comment]
i'm trying

**Comment by Filpin011** [comment]
> i'm trying

it dont work, new project, modified plugin with ur code ah it say this: `Running pod install...
Xcode build done.                                            6,7s
Failed to build iOS app
Exited (sigterm)
Could not build the application for the simulator.
Error launching application on iPhone 12 mini.
`

my dependencies: `dependencies:
  awesome_notifications:
    path: ./awesome_notifications-0.0.3+3
  flutter:
    sdk: flutter

`

<img width="818" alt="Schermata 2020-10-16 alle 16 03 29" src="https://user-images.githubusercontent.com/64793842/96268267-23e53880-0fc9-11eb-8ce5-c027d8de4da8.png">

I hope this help u

**Comment by rafaelsetragni** [comment]
You did everything right. XCode is really complicated. Check if your `Signing & Capabilities` are setted for your team and check `Automatically manage signing` to ensure a basic debug running.

If you get any more details about this error, please send me.

**Comment by Filpin011** [comment]
<img width="1245" alt="Schermata 2020-10-16 alle 16 55 44" src="https://user-images.githubusercontent.com/64793842/96274164-80982180-0fd0-11eb-9dfa-e1f4a9b92650.png">


i find a lot of import error in the package when I use It locally, what I have to do, maybe is this to block my debug?

**Comment by rafaelsetragni** [comment]
You need to keep the Awesome Notifications  project folder outside your project xClock, because if you do not, android will not recognize it as a separated packadge. Thats why you are gettin those reference erros.

Clone my project on github and put it beside your project folder, but not inside it. After that just do the reference to the path in your pubspec.yaml

**Comment by Filpin011** [comment]
I tried to do with android device, but when i create a notification, it doesn't display, why?

**Comment by rafaelsetragni** [comment]
The only explanation that i have (without more informations) is your channel command never arives to the native layer.

Debug you Flutter app using Android Studio and put a break line as soon as possible. After that, attatch the Android Studio to your running process using the Native attach option as bellow:

![image](https://user-images.githubusercontent.com/40064496/96462980-9a1db100-11fc-11eb-9dd7-2c6a967c1a9a.png)
1. Flutter debug attatch
2. Android native debug attatch

This way youll be able to debug native and flutter source code at same time and discovery whats goin on with your notifications.

**Comment by Filpin011** [comment]
this is my main: `void main() {
  AwesomeNotifications().initialize('resource://drawable/app_icon', [
    NotificationChannel(
        channelKey: 'basic_channel',
        channelName: 'Basic notifications',
        channelDescription: 'Notification channel for basic tests',
        defaultColor: Color(0xFF9D50DD),
        ledColor: Colors.white),
    NotificationChannel(
        icon: 'resource://drawable/app_icon',
        channelKey: 'schedule',
        channelName: 'Scheduled Notifications',
        channelDescription: 'Notifications with schedule time',
        defaultColor: Color(0xFF9D50DD),
        ledColor: Colors.white),
  ]);
  runApp(MyApp());
}`

and this is where the notification is called: `      floatingActionButton: FloatingActionButton(
        onPressed: () {
          showBasicNotification();
        },
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

Future<void> showBasicNotification() async {
  await AwesomeNotifications().createNotification(
      content: NotificationContent(
          id: 0,
          channelKey: 'basic_channel',
          title: 'Simple Notification',
          body: 'Simple body'));
}`

dependecies:   awesome_notifications: any

**Comment by rafaelsetragni** [comment]
Try to use an id greater than 2

**Comment by Filpin011** [comment]
i dont find how to setup config menu, in ur example I dont find a config menu

**Comment by rafaelsetragni** [comment]
[How to enable push notifications](https://support.scruff.com/hc/en-us/articles/202625304-Disable-or-enable-push-notifications-Android-)

**Comment by Filpin011** [comment]
I'm able to show notification, but when I schedule 1 notification after 1 second or 5, it doesn't display, all permission are allowed

**Comment by rafaelsetragni** [comment]
Im writing new functions to check if notifications are allowed and to request the user to conceed his consent. They will be available on the next release.
