### ISSUE TITLE
Notification scheduling every X days

### ISSUE THREAD

**Issue by sylvainvillet** [rafaelsetragni/awesome_notifications#130]
Hi,

I'm writing an app where the user can create reminders for medications, and some medications must be taken every 2 or 3 days for example. I've checked the crontab synthax but it doesn't seam possible to do that, you can have some strange intervals at the end of the month depending how many days there is in the current month.

Thanks for your work and let me know if it could be possible for you to add this feature!

**Comment by rafaelsetragni** [comment]
Im working on it right now. This will soon be possible. I'll keep you posted here.

**Comment by rafaelsetragni** [comment]
Try to use the new Calendar and Crontab schedules on version 0.6.14
