### ISSUE TITLE
iOS can't get Firebase App Token

### ISSUE THREAD

**Issue by Kimsoer** [rafaelsetragni/awesome_notifications#133]
I get token null while using on iOS and work well with android
 AwesomeNotifications().firebaseAppToken.then((value) {
      print("Token value=> $value");
    }).catchError((onError) {
      print("error token=> $onError");
    });

**Comment by rafaelsetragni** [comment]
You need to make sure that your Firebase configuration is correct according to the characteristics of your application, such as bundle name, etc. Otherwise, it will not work and no valid token will be generated.

**Comment by Kimsoer** [comment]
I don't understand if the firebase configuration is not correct. why it don't execute in catchError.
