### ISSUE TITLE
Scheduled notification not triggering on same day.

### ISSUE THREAD

**Issue by marklester** [rafaelsetragni/awesome_notifications#134]
```dart  
var nschedule = NotificationSchedule(
      initialDateTime: DateTime.now(),
      allowWhileIdle: true,
      crontabSchedule: cronExp
  );

  var x = await AwesomeNotifications().createNotification(
      content: NotificationContent(
          id: id,
          channelKey: channelKey,
          title: 'Title:',
          body: 'Description ',
      ),
    schedule: nschedule
  );
  developer.log("schedule result $x",name: "app");
  var nextDate =  await AwesomeNotifications().getNextDate(nschedule);
```
given initial date of `2021-03-11 10:45:19` and
cron of: `0 46 10 ? * THU *`
the next date is `2021-03-18 10:46:00.000Z`
should next date be `2021-03-11 10:46:00.000Z` ?

**Comment by rafaelsetragni** [comment]
No, the next valid day should be at least thuesday again. 2021-03-22 10:46:00.000Z

And you dont need to specify `initialDate` with `now()` time. `initialDate` is not an required field.
And `now()` date must be explicity set to use UTC timestamp.

`DateTime.now().toUtc()`

**Comment by marklester** [comment]
ok thanks for the help.
My solution for same day was create one off scheduled notification if the event didn't happen yet on the same day. Also discovered the utc trick after digging through examples, closed tickets, and docs.
