### ISSUE TITLE
iOS: actionStream error with Scheduled Notification on app killed

### ISSUE THREAD

**Issue by Arcrueid** [rafaelsetragni/awesome_notifications#136]
Hello,

I have a problem on iOS, when creating a Scheduled Notification and closing the app.

When the notification appears and clicks, no data reaches the corresponding stream "AwesomeNotifications().actionStream" in this case it only reaches "AwesomeNotifications().displayedStream" with "displayedLifeCycle": "AppKilled".

I don't know if I'm doing something wrong but it works perfect on android.

**Comment by rafaelsetragni** [comment]
Try to debug it using XCode directly. Because it should work.
Also, try to create a local notification and check if it works fine for all streams.

Dismissed stream on iOS not works all times, due to iOS limitations.

**Comment by Arcrueid** [comment]
The only error I see in the console is:

Action (null) can't be executed because it has no runner

**Comment by rafaelsetragni** [comment]
Can you build a simple project with this issue and share it with me?

**Comment by adrianvintu** [comment]
I got the "AppKilled" error when I ran  ```AwesomeNotifications().initialize``` twice.

**Comment by MaheshKumarM-SCE** [comment]
hi @Arcrueid I am facing the same issue - https://github.com/rafaelsetragni/awesome_notifications/issues/164 and I am trying to debug. can you please help me

**Comment by rafaelsetragni** [comment]
Open the example project in xcode to be able to debug and capture the plugin's errors inside pod's folder.

To start to debug after clicking on notification, start to listen the application by your application id.

**Comment by pedrohsampaioo** [comment]
is there solution?

**Comment by rafaelsetragni** [comment]
The solution @pedrohsampaioo:

> Open the example project in xcode to be able to debug and capture the plugin's errors inside pod's folder.
> 
> To start to debug after clicking on notification, start to listen the application by your application id.

Help us given more information and coding as well.

**Comment by pedrohsampaioo** [comment]
@rafaelsetragni I saw the logs using `flutter logs` and now it's working 👁️ I received the correct ReceivedAction:

```bash
flutter: {
  "actionDate": "2022-01-26 18:51:21",
  "actionLifeCycle": "AppKilled",
  "autoCancel": true,
  "backgroundColor": null,
  "bigPicture": null,
  "body": "The ‘Testing timer’ from the Quelites needs your attention.",
  "buttonKeyInput": "",
  "buttonKeyPressed": "",
  "channelKey": "creme-cooking-timer-channel-id",
  "color": null,
  "createdDate": "2022-01-26 18:49:09",
  "createdLifeCycle": "Foreground",
  "createdSource": "Local",
  "customSound": null,
  "dismissedDate": null,
  "dismissedLifeCycle": null,
  "displayedDate": "2022-01-26 18:51:21",
  "displayedLifeCycle": "AppKilled",
  "icon": null,
  "id": 117336058,
  "largeIcon": null,
  "payload": {
    "recipeKey": "2ljV77Il55s7iTR8vUiN0K",
    "thumbnailUrl": "https://image.mux.com/bCHs5qDOR3kbXommE00nodvJJgIdY6zqERt7TvAqfx00c/thumbnail.jpg?token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJ0Iiwia2lkIjoibjAwN3hBRVEwMVdXZGZoeGh6RkxGWmdvODZLVlJrb1U0WExEUk5oZ0ttWnFrIiwic3ViIjoiYkNIczVxRE9SM2tiWG9tbUUwMG5vZHZKSmdJZFk2enF<…>
flutter: {
flutter:   "actionDate": "2022-01-26 18:51:21",
flutter:   "actionLifeCycle": "AppKilled",
flutter:   "autoCancel": true,
flutter:   "backgroundColor": null,
flutter:   "bigPicture": null,
flutter:   "body": "The ‘Testing timer’ needs your attention.",
flutter:   "buttonKeyInput": "",
flutter:   "buttonKeyPressed": "",
flutter:   "channelKey": "timer-channel-id",
flutter:   "color": null,
flutter:   "createdDate": "2022-01-26 18:49:09",
flutter:   "createdLifeCycle": "Foreground",
flutter:   "createdSource": "Local",
flutter:   "customSound": null,
flutter:   "dismissedDate": null,
flutter:   "dismissedLifeCycle": null,
flutter:   "displayedDate": "2022-01-26 18:51:21",
flutter:   "displayedLifeCycle": "AppKilled",
flutter:   "icon": null,
flutter:   "id": 117336058,
flutter:   "largeIcon": null,
flutter:   "payload": {
flutter:     ...,
flutter:   },
flutter:   "privacy": "Private",
flutter:   "showWhen": true,
flutter:   "summary": null,
flutter:   "title": "Timer is up! ⏰"
flutter: }
```

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
