### ISSUE TITLE
IOS profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port

### ISSUE THREAD

**Issue by Kimsoer** [rafaelsetragni/awesome_notifications#137]
Dear sir. I have one issue . please help  it.  
I got this error message, while I push notification with iOS while android work fine

profiler_metrics_ios.mm(184)] Error retrieving thread information: (ipc/send) invalid destination port

**Comment by rafaelsetragni** [comment]
Try to check the solutions in this topic:

[Getting "Error retrieving thread information: (ipc/send) invalid destination port" in the logs on Apple Silicon M1#71395](https://github.com/flutter/flutter/issues/71395)

**Comment by Kimsoer** [comment]
I am not M1 apple

**Comment by rafaelsetragni** [comment]
Can you create a simple project with this issue and share it with me?
