### ISSUE TITLE
Warning: Parameters can't override default values, this method overrides 'DataSource.fetchData' where 'headers' has a different value.

### ISSUE THREAD

**Issue by brightseagit** [rafaelsetragni/awesome_notifications#138]
Hello, thanks for providing this awesome plugin. 

**Issue:-**
I tried to use the example app of  awesome_notifications which can be found here https://github.com/rafaelsetragni/awesome_notifications/tree/master/example but I've received the following Warning in the dart analysis:-
```
Parameters can't override default values, this method overrides 'DataSource.fetchData' where 'headers' has a different value.
```
The warning is visible in `fetchData` argument `headers` at `awesome_notifications/example/lib/datasources/common/http_datasource.dart `

And I don't know what it means and found no previous issues filed with reference to it.  So I'm looking forward to knowing the means of this warning, why it's occurring, and how I can fix it.

Thank you.

**Comment by rafaelsetragni** [comment]
This example is outdated. Im finishing the new version to update it latter. Please, use the example app inside the pluggin files to do your tests.

**Comment by brightseagit** [comment]
Hey, thanks for responding I did use try to use the example app in the latest plugin 0.0.5+8 from pub.dev as you recommended but the warning was still there.

But I think you misunderstood the issue. This is what I was talking about:-
![Screenshot 2021-03-20 011507](https://user-images.githubusercontent.com/72334435/111834523-ba6faa00-8919-11eb-9b8d-8f79c1c70819.png)

Finally, I did manage to remove the warning by replacing this in datasouce file :-
```
abstract class DataSource {
  @protected
  Future<Response> fetchData({String directory, Map<String, String> parameters, Map<String, String> headers = const {}});
}
```

With this (removed const {} assigned to headers):-
```
abstract class DataSource {
  @protected
  Future<Response> fetchData({String directory, Map<String, String> parameters, Map<String, String> headers});
}
```

But I don't know if doing that has any bad effects.

**Comment by rafaelsetragni** [comment]
Yes, you are right.

Remove the const default value from abstract `DataSource` class and put it inside `HttpDataSource` class. 

in `datasource.dart` file:
```dart
abstract class DataSource {
  @protected
  Future<Response> fetchData({String directory, Map<String, String> parameters, Map<String, String> headers});
}

```

in `http_datasource.dart` file:
```dart
class HttpDataSource extends DataSource {

   /// ... other contents

  @override
  Future<Response> fetchData(
      {String directory = '',
      Map<String, String> parameters,
      Map<String, String> headers = const {}, // =
      String body,
      int timeoutInMilliseconds = 5000}) async {

     /// ... other contents

  }
}

```

This class depends of a default value, it cannot be null. With null safety will be more easy to protect the methods and this will not be more necessary anymore.

Thank you so much for this tip!

**Comment by brightseagit** [comment]
Hey, thanks for responding and clarifying the doubt. Now I clearly understand the reson for the warning. So, I think it is safe to close this issue now.

Thank you very much for the response and this awesome plugin 👍.
