### ISSUE TITLE
Oppo device when my app is not in background than i am not getting notification 

### ISSUE THREAD

**Issue by kcs-rahuljoshi** [rafaelsetragni/awesome_notifications#139]
Oppo device when my app is not in the background then I am not getting push notification else app is open than push notification getting successfully

**Comment by rafaelsetragni** [comment]
Sorry, i couldnt understand your problem. While the app is not in background, it only can be terminated / killed or in foreground. Are notifications not shown only when the app is in the background?

**Comment by kcs-rahuljoshi** [comment]
getting notification only when the app is in background or foreground but when the app is not in background or foreground than not getting notification this is a issue

**Comment by rafaelsetragni** [comment]
To receive a notification while the app is killed or you do a scheduled notification or a push notification. What are you trying to do and what platform are you using?

**Comment by kcs-rahuljoshi** [comment]
not receive a push notification while the app is killed. and we have used android platform

**Comment by rafaelsetragni** [comment]
This can be a issue with your firebase project configuration or the `google-services.json` file was placed in the wrong place, inside your flutter project. Please, check the firebase documentation to verifi if this conditions was accomplished.

**Comment by kcs-rahuljoshi** [comment]
but the same scenario I am checking in other device working fine only issue is getting in oppo device

**Comment by rafaelsetragni** [comment]
What is an oppo device?

**Comment by kcs-rahuljoshi** [comment]
I am getting this issue in all oppo device
