### ISSUE TITLE
App stops working only by importing this library

### ISSUE THREAD

**Issue by lucaslobasso** [rafaelsetragni/awesome_notifications#141]
Only by importing this library into my project, even without referencing it, it stops working as soon as it builds.

This is the console:
`/System  ( 7083): ClassLoader referenced unknown path: /system/priv-app/PrebuiltGmsCore/lib/x86
V/NativeCrypto( 7083): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 284 native methods...
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.org.conscrypt.Java7ExtendedSSLSession>
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.org.conscrypt.Java7ExtendedSSLSession>
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.org.conscrypt.Java8ExtendedSSLSession>
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<com.google.android.gms.org.conscrypt.Java8ExtendedSSLSession>
I/ProviderInstaller( 7083): Installed default security provider GmsCore_OpenSSL
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.Supplier>
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.Supplier>
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<io.grpc.internal.GrpcUtil$4>
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<io.grpc.internal.GrpcUtil$4>
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.Predicate>
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.Predicate>
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.CharMatcher>
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.CharMatcher>
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.CharMatcher>
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.CharMatcher>
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.CharMatcher>
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.CharMatcher>
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.CharMatcher>
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.CharMatcher>
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.CharMatcher>
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.CharMatcher>
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.CharMatcher>
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.CharMatcher>
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.CharMatcher>
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.CharMatcher>
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.CharMatcher>
I/art     ( 7083): Rejecting re-init on previously-failed class java.lang.Class<com.google.common.base.CharMatcher>
D/TransportRuntime.SQLiteEventStore( 7083): Storing event with priority=HIGHEST, name=FIREBASE_CRASHLYTICS_REPORT for destination cct
D/TransportRuntime.JobInfoScheduler( 7083): Upload for context TransportContext(cct, HIGHEST, MSRodHRwczovL2NyYXNobHl0aWNzcmVwb3J0cy1wYS5nb29nbGVhcGlzLmNvbS92MS9maXJlbG9nL2xlZ2FjeS9iYXRjaGxvZ1xBSXphU3lCcnBTWVQ0RkZMMDlyZUhKaTZIOUZZZGVpU25VVE92Mk0=) is already scheduled. Returning...
E/AndroidRuntime( 7083): FATAL EXCEPTION: AsyncTask #5
E/AndroidRuntime( 7083): Process: com.spacegrey.greenit, PID: 7083
E/AndroidRuntime( 7083): java.lang.NoClassDefFoundError: com.google.common.base.CharMatcher
E/AndroidRuntime( 7083):        at com.google.common.base.Splitter.on(Splitter.java:127)
E/AndroidRuntime( 7083):        at io.grpc.internal.GrpcUtil.<clinit>(GrpcUtil.java:197)
E/AndroidRuntime( 7083):        at io.grpc.internal.AbstractManagedChannelImplBuilder.<clinit>(AbstractManagedChannelImplBuilder.java:90)
E/AndroidRuntime( 7083):        at io.grpc.okhttp.OkHttpChannelProvider.builderForTarget(OkHttpChannelProvider.java:46)
E/AndroidRuntime( 7083):        at io.grpc.okhttp.OkHttpChannelProvider.builderForTarget(OkHttpChannelProvider.java:26)
E/AndroidRuntime( 7083):        at io.grpc.ManagedChannelBuilder.forTarget(ManagedChannelBuilder.java:76)
E/AndroidRuntime( 7083):        at com.google.firebase.firestore.remote.GrpcCallProvider.initChannel(GrpcCallProvider.java:113)
E/AndroidRuntime( 7083):        at com.google.firebase.firestore.remote.GrpcCallProvider.lambda$initChannelTask$6(GrpcCallProvider.java:256)
E/AndroidRuntime( 7083):        at com.google.firebase.firestore.remote.GrpcCallProvider$$Lambda$5.call(GrpcCallProvider.java)
E/AndroidRuntime( 7083):        at com.google.android.gms.tasks.zzv.run(Unknown Source)
E/AndroidRuntime( 7083):        at com.google.firebase.firestore.util.ThrottledForwardingExecutor.lambda$execute$0(ThrottledForwardingExecutor.java:54)
E/AndroidRuntime( 7083):        at com.google.firebase.firestore.util.ThrottledForwardingExecutor$$Lambda$1.run(ThrottledForwardingExecutor.java)
E/AndroidRuntime( 7083):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/AndroidRuntime( 7083):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/AndroidRuntime( 7083):        at java.lang.Thread.run(Thread.java:818)
E/Surface ( 7083): getSlotFromBufferLocked: unknown buffer: 0x9ed069c0
E/libEGL  ( 7083): call to OpenGL ES API with no current context (logged once per thread)
W/art     ( 7083): Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[39,tid=7121,Native,Thread*=0xae686600,peer=0x1306d100,"1.ui"]
D/EGL_emulation( 7083): eglMakeCurrent: 0xaa9fe220: ver 3 0 (tinfo 0x9c4b19a0)
E/Surface ( 7083): getSlotFromBufferLocked: unknown buffer: 0x97e596e0
W/Firestore( 7083): (22.0.1) [OnlineStateTracker]: Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds
W/Firestore( 7083): 
W/Firestore( 7083): This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
W/FlutterJNI( 7083): Tried to send a platform message response, but FlutterJNI was detached from native C++. Could not send. Response ID: 7
I/Process ( 7083): Sending signal. PID: 7083 SIG: 9
Lost connection to device.`

This is my pubspec.yaml:

> environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.2
  firebase_storage: ^8.0.1
  firebase_crashlytics: ^1.0.0
  cloud_firestore: ^1.0.3
  google_sign_in: ^5.0.1
  awesome_notifications: ^0.0.5+8
  flutter_email_sender: ^5.0.0
  image_picker: ^0.7.3
  share: ^2.0.1
  flutter_bloc: ^7.0.0-nullsafety.5
  equatable: ^2.0.0
  get_it: ^6.0.0
  uuid: ^3.0.2
  flushbar: ^1.10.4
  bubble_bottom_bar: ^1.2.0
  table_calendar: ^3.0.0-nullsafety.1
  package_info: ^2.0.0
  cupertino_icons: ^1.0.2

And this is my main (even though, as I said, if I omit every refence to this library the error still shows and the app stops working):

> void main() async {
  await startup();
  runApp(App());
}
Future startup() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  await _configureNotifications();
  await _configureCrashlytics();
}
Future _configureNotifications() async {
  AwesomeNotifications().initialize(
    null,
    [
      NotificationChannel(
        channelKey: 'basic_channel',
        channelName: 'Basic notifications',
        channelDescription: 'Notification channel for basic tests',
        defaultColor: Color(0xFF9D50DD),
        ledColor: Colors.white,
      ),
    ],
  );
}

Am I doing something wrong? Did I miss any configuration?
Thanks in advance.

(I edited it trying to fix the code markup, couldnt, hope its understandable)

**Comment by FedericoJoseLucia** [comment]
I am experiencing the same error. Currently found no solution. 
Ive been unable to use the library. Help would be appreciated.

**Comment by nietsmmar** [comment]
What flutter version are you using? I found this https://github.com/FirebaseExtended/flutterfire/issues/2570

**Comment by Mamun361054** [comment]
facing the same issue , where is this library developer

**Comment by rafaelsetragni** [comment]
Im here

**Comment by lorenzorheinicke** [comment]
We had the same issues as described in our project. The app crash was only on Android 6 (SDK =< 23) and older devices in our case.

The fix for us was to force the Google Guava dependency to use a specific version in the `app/build.gradle` file.
`implementation ("com.google.guava:guava:30.1-android") { setForce(true) }`

The app does not crash anymore and push notifications are working. We are using Firebase messaging with `version 0.0.6`

**Comment by rafaelsetragni** [comment]
> The fix for us was to force the Google Guava dependency to use a specific version in the `app/build.gradle` file.
> `implementation ("com.google.guava:guava:30.1-android") { setForce(true) }`

Thank you so much for this tip! Do you wanna send for us a fork of this change or can we put it for your?

**Comment by lorenzorheinicke** [comment]
@rafaelsetragni The original fix was added to my own project's `app/builld.gradle` file. but I tested the change above in the (awesome_notification) package's gradle file and it works.

Also, using `implementation "com.google.guava:guava:30.1-android"` in the gradle file of the (awesome_notification) package works on Android 6.

**Comment by saadBinZahoor** [comment]
> implementation ("com.google.guava:guava:30.1-android") { setForce(true) }

This line solved the issue. Thank you for this solution.
