### ISSUE TITLE
createdStream semantics

### ISSUE THREAD

**Issue by marklester** [rafaelsetragni/awesome_notifications#142]
Not sure if this is a bug or not.
The `createdStream.listen` looks to be called on scheduling a notification and when the notification is created

If this is intended it would be nice to separate those into scheduledStream and createdStream or something like that or a property that makes it easy to tell the difference.

Another note(which probably should be it's own ticket) Is there plans to be able to add dynamic content to cron schedule? e.g. when cron triggers calculate some value

Thanks!

**Comment by rafaelsetragni** [comment]
The streams are designed to be simple as that. Otherwise i gonna need to create a create, display, dismiss and action from scheduled and non-scheduled notifications.

But don´t worry. You can differentiate from each other using the createdSource, displayedSource fields.
