### ISSUE TITLE
Invalid JSON content on iOS

### ISSUE THREAD

**Issue by efraespada** [rafaelsetragni/awesome_notifications#149]
Hi, I'm using v `0.0.6+3`. The README.md says this notification body should be used:

```json
{
    "to" : "[YOUR APP TOKEN]",
    "mutable_content" : true,
    "data" : {
        "content": {
            "id": 100,
            "channelKey": "big_picture",
            "title": "Huston!\nThe eagle has landed!",
            "body": "A small step for a man, but a giant leap to Flutter's community!",
            "notificationLayout": "BigPicture",
            "largeIcon": "https://media.fstatic.com/kdNpUx4VBicwDuRBnhBrNmVsaKU=/full-fit-in/290x478/media/artists/avatar/2013/08/neil-i-armstrong_a39978.jpeg",
            "bigPicture": "https://www.dw.com/image/49519617_303.jpg",
            "showWhen": true,
            "autoCancel": true,
            "privacy": "Private"
        },
        "actionButtons": [
            {
                "key": "REPLY",
                "label": "Reply",
                "autoCancel": true,
                "buttonType":  "InputField"
            },
            {
                "key": "ARCHIVE",
                "label": "Archive",
                "autoCancel": true
            }
        ],
        "schedule": {
            "hour": "10",
            "minute": "0",
            "second": "0",
            "allowWhileIdle": true,
            "repeat": true
        }
    }
}
```
[testing with your POSTMAN collection]

When sending the notification body to an Android token everything works fine:
```json
{
    "multicast_id": 4113328644686548617,
    "success": 1,
    "failure": 0,
    "canonical_ids": 0,
    "results": [
        {
            "message_id": "0:1619766377347587%3174dbdcf9fd7ecd"
        }
    ]
}
```

But when sending the notification body to an iOS token, the request returns me this error:
```json
{
    "multicast_id": 1538360321705904628,
    "success": 0,
    "failure": 1,
    "canonical_ids": 0,
    "results": [
        {
            "error": "InvalidParameters: Invalid notification payload"
        }
    ]
}
```
I have to include this to avoid this error:
```json
{
   "to": "[IOS_TOKEN]",
   "notification": {
      "title": " "
    },
    ...
}
```
But when adding this, I'm getting this log on the iOS device:
```
"receiveNotification: notification discarted"
```

What can I do?

**Comment by efraespada** [comment]
I'm testing some changes in `SwiftAwesomeNotificationsPlugin`, specifically:
```swift
 @available(iOS 10.0, *)
 private func receiveNotification(content:UNNotificationContent, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void){
     let jsonData:String? = content.userInfo[Definitions.NOTIFICATION_JSON] as? String
        
     guard let pushNotification:PushNotification = NotificationBuilder.jsonToPushNotification(jsonData: jsonData)
     else {
        Log.d("receiveNotification","notification discarted")
        completionHandler([])
        return
     }
}
```
To:
```swift
 @available(iOS 10.0, *)
 private func receiveNotification(content:UNNotificationContent, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void){
     let jsonData:String? = JsonUtils.toJson([
         "content": JsonUtils.fromJson(content.userInfo["content"] as? String),
         "actionButtons": JsonUtils.fromJson(content.userInfo["actionButtons"] as? String),
         "schedule": JsonUtils.fromJson(content.userInfo["schedule"] as? String)
     ])
     guard let pushNotification:PushNotification = NotificationBuilder.jsonToPushNotification(jsonData: jsonData)
     else {
        Log.d("receiveNotification","notification discarted")
        completionHandler([])
        return
     }
}
```

This avoids the `"receiveNotification: notification discarted"`, and logs:

```
flutter: Notification displayed
flutter: Notification displayed: Huston!
The eagle has landed!
```

But I still having the JSON format problem, which forces me to add:
```json
{
    "notification": {
      "title": " "
    }
}
```

And shows only an empty notification.

**Comment by rafaelsetragni** [comment]
I working on it, but im facing the problem that `FirebaseMessaging.onBackgroundMessage` is never called when the app is in background (release mode) or closed/killed.

**Comment by efraespada** [comment]
I could fix it by adding the `content_available` and removing `notification`:

```json
{
    "to" : "[TOKEN]",
    "mutable_content" : true,
    "content_available": true,
    "data" : {
        "content": {
            "id": 100,
            "channelKey": "group_messages",
            "title": "Huston!\nThe eagle has landed!",
            "body": "A small step for a man, but a giant leap to Flutter's community!",
            "notificationLayout": "BigPicture",
            "largeIcon": "https://media.fstatic.com/kdNpUx4VBicwDuRBnhBrNmVsaKU=/full-fit-in/290x478/media/artists/avatar/2013/08/neil-i-armstrong_a39978.jpeg",
            "bigPicture": "https://www.dw.com/image/49519617_303.jpg",
            "showWhen": true,
            "autoCancel": true,
            "privacy": "Private"
        },
        "actionButtons": [
            {
                "key": "REPLY",
                "label": "Reply",
                "autoCancel": true,
                "buttonType":  "InputField"
            },
            {
                "key": "ARCHIVE",
                "label": "Archive",
                "autoCancel": true
            }
        ]
    }
}
```

But when the application is killed, nothing happens. Could be possible because of this?

[https://firebase.flutter.dev/docs/messaging/usage#low-priority-messages](https://firebase.flutter.dev/docs/messaging/usage#low-priority-messages)

**Comment by rafaelsetragni** [comment]
Your notifications arrived by the `onBackgroundMessage` method when your application is killed? I couldn't make the example app receive background push notifications for iOS using `firebase_messaging`

**Comment by efraespada** [comment]
I receive the notifications:

- When the app is open: `FirebaseMessaging.onMessage`
- When the app is in the background: `FirebaseMessaging.onBackgroundMessage`
- When the app is killed: 
        . in debug: Nothing more happens, but in this scenario, if I kill the app, it can't be opened again. It could be related.
        . in release: Not tested yet. Maybe it could work.

I'm gone test it from Testflight.

**Comment by rafaelsetragni** [comment]
For me, in release mode, is completely random when the `FirebaseMessaging.onBackgroundMessage` works or not.

![image](https://user-images.githubusercontent.com/40064496/116742115-4f5fcb80-a9cd-11eb-899a-62ecf45c243e.png)

This is the application log extracted directly from iOS System. I dont know how to solve it, and i cant release a new version until i figure out whats goin on.

**Comment by rafaelsetragni** [comment]
Yes, and it stills the same. I thinking about to quit and reactivate the push natively and let a option to the dev to use the native awesome push notification or the firebase one.

**Comment by efraespada** [comment]
I voted to keep the native system but it is true that implement/configure additional targets (as the `NotificationServiceExtension`) is more complicated than using `FirebaseMessaging.onBackgroundMessage`.

I've opened this #150 PR with all the changes. In release (from a Testflight installation) works as with prior versions with the native system even if the app is killed.

**Comment by rafaelsetragni** [comment]
Merge completed. I also made some changes before doing this.

**Comment by efraespada** [comment]
Perfect, thanks!
