### ISSUE TITLE
KeepOnTop notification button action is not fired when app is killed

### ISSUE THREAD

**Issue by gooldeer** [rafaelsetragni/awesome_notifications#15]
I am trying to develop an application which will be able to perform a REST API call when user clicked on scheduled notification button, without bringing an app to foreground. 

So I am showing a scheduled notification with KeepOnTop action button. When app is in foreground or in background action from click on this button is received. But when app is killed - no action is received. Is there a way to achieve this behavior?

**Comment by rafaelsetragni** [comment]
Keep on top actions are actions uses broadcast streamings, wich do not wake up your app. They are planned to use to controll background and foreground functions, as i show on example application with the media player function.

**Comment by gooldeer** [comment]
I see. So there is no way to link actions to notification buttons when app is killed?

I was thinking about combing background_fetch (https://pub.dev/packages/background_fetch) and getting all intended actions on each periodic task. Do you think it is possible?

**Comment by rafaelsetragni** [comment]
Honestly, i dont know.
After i finish the next release ill give a review on this source part, and see what i can do. Ill keep this topic opened until there.

**Comment by Ali1Ammar** [comment]
is there any update

**Comment by Ali1Ammar** [comment]
i have same problem but i am using workmanger package 
i was debugging and i figure out that the problem in BroadcastSender.java SendBroadcastKeepOnTopAction function 
i re write this 
```java
   if(success){
                Log.d(TAG, "success Sent created to broadcast");
            } else {
                  Log.d(TAG, "success not created to broadcast");
            }
```
when app is killed success became false and else statements printed and any log inside onBroadcastKeepOnTopActionNotification didnt  work
also catch didn't catch any error

**Comment by Ali1Ammar** [comment]
also i found that sendBroadcast  checks for available receivers and returns false if none found
i thinks flutter didnt initialise here because the enter point of our code here is KeepOnTopActionReceiver

**Comment by Ali1Ammar** [comment]
i read  [here](https://stackoverflow.com/questions/64052156/how-do-you-use-receiver-broadcastreceiver-in-a-flutter-plugin) that Receiver should be register inside the main `<appliction>` tage that have` android:name="io.flutter.app.FlutterApplication"`
so i delete `.notifications.broadcastReceivers.KeepOnTopActionReceiver `from the plugin and add this to my app
`<receiver android:name="me.carda.awesome_notifications.notifications.broadcastReceivers.KeepOnTopActionReceiver"/>`

now success return true and `onBroadcastKeepOnTopActionNotification` called but flutter still didnt recive any things

**Comment by gooldeer** [comment]
@Ali1Ammar Yes. Flutter won't start when broadcast is received unfortunately. You will need to add something like background_fetch to periodically wake up flutter and receive all pending notifications over there. For this you need to cache those actions in shared preferences for example.

Check my fork where I implemented such caching https://github.com/gooldeer/awesome_notifications

**Comment by rafaelsetragni** [comment]
And it worked fine for iOS?

**Comment by scalz** [comment]
Hello,

Does someone have a solution without using periodic wakeups (as background fetch is limited to 15mn)?

For example, when app is killed, when clicking on an action button+KeepOnTop, being able to immediately execute an action (like perform a REST api call). A special thread with a callback which would get killed after a timeout (configurable?), only for action buttons ?? probably not very neat and completely overheas, no idea if this is really doable..

@gooldeer  have you found a workaround for such non-scheduled case ? Or maybe I didn't get what you meant by caching+periodically check in flutter

For the moment, I'm not using KeeOnTop, and use actionStream to do the job, but that's  exactly the same.

btw @rafaelsetragni   thank you very much for your latest release, I'm testing your work on Android, and soon with iOS. I'm really excited, this is an awesome package ^^

**Comment by rafaelsetragni** [comment]
> Does someone have a solution without using periodic wakeups (as background fetch is limited to 15mn)?

It would be great if it was only 15 minutes. Its at least 15 min , if Apple and their crazy algorithms decides that yes for your app. In other words, you dont have sure about when, never. Could be 15 min, or 1 hour or even more. Who knows?

Apple doesnt care about your app in background. No ones are capable to make your app work as good as it does in Android, but for iOS. All background tasks are limited and they never run when you need. And they will kill your process if they decided to do so, without think twice.

Is Apple being Apple.

If you need to do a background processing, think about that. Do as fast as you can and never trust about when they will happen.

**Comment by scalz** [comment]
ahah so true ^^

oki. I'll try to find a workaround. there must be a way to achieve this for my usecase eg. home automation server sending a notification with actions to my phone, android of course :)

thx for your quick reply

**Comment by scalz** [comment]
@rafaelsetragni 
My quite ugly workaround (only for test purpose) .. :sweat_smile:
![Capture](https://user-images.githubusercontent.com/12609100/116229077-5cbf5080-a756-11eb-96ae-57bb65b402dc.PNG)
