### ISSUE TITLE
Questions about Schedule object

### ISSUE THREAD

**Issue by kimseongyong-nbt** [rafaelsetragni/awesome_notifications#153]
I tried to show notification every saturday.

To test repeating notification, I scheduled notification like this(targeting time is : '2021-05-01 23:30:30+09:00')
```dart
AwesomeNotifications().createNotification(
  content: NotificationContent(
      id: 1,
      channelKey: defaultChannelKey,
      title: 'title',
      body: 'body'
  ),
  schedule: NotificationCalendar(
    weekday: 6,
    hour: 23,
    minute: 30,
    second: 30,
    repeats: true
  )
);
```
and it's not worked.

so i kept trying with different parameters, and i found exact parameters that work correctly
```dart
  schedule: NotificationCalendar(
    weekday: 7,
    hour: 14,
    minute: 30,
    second: 30,
    repeats: true
  )
```
i wonder,
1. those parameters are calculated as UTC+0, so i had to change hour from 23 to 14 (here is UTC+9). i hope there's a setting for timezone.
2. if i pass weekday: 0 it throws error. and saturday is 7, not 6. is this intended?

ps. how about changing the parameter 'weekday' to 'dayOfWeek'?

**Comment by rafaelsetragni** [comment]
> 1. those parameters are calculated as UTC+0, so i had to change hour from 23 to 14 (here is UTC+9). i hope there's a setting for timezone.

It is a good pratice to use UTC+0 in storages and for internal procedures. Time zones are political and very complex to deal. Take a look at this video to see where the rabbit hole ends:

[The Problem with Time & Timezones - Computerphile](https://www.youtube.com/watch?v=-5wpm-gesOY)

To easily translate your local time into utc, or vice versa, use this in dart:

```dart
print(DateTime().toUtc());
print(DateTime().toLocal());
```

> 2. if i pass weekday: 0 it throws error. and saturday is 7, not 6. is this intended?
> ps. how about changing the parameter 'weekday' to 'dayOfWeek'?

I only copied the method names from NSCalendar and Calendar, from Swift and Java libraries, respectively. Those date values usually starts from 1. But ill check if that name is better to understand and put it in the next release, if necessary.

[NSCalendar Weekday](https://developer.apple.com/documentation/foundation/nscalendar/unit/1416394-weekday)

**Comment by jja08111** [comment]
I have same issue about weekday.

Flutter dateTime has weekday that start 1 for monday. But this plugin weekday is not. 

You can see a [document here](https://api.dart.dev/stable/2.12.4/dart-core/DateTime/weekday.html).

**Comment by rafaelsetragni** [comment]
For both java and swift, the day 1 is sunday. Notifications work based on those 2 languages and will be scheduled on OS following that rule.

I gonna need to force you guys to not use dart DateTime helpers, changing the model objects to demand by code the correct use of those values.

**Comment by jja08111** [comment]
> For both java and swift, the day 1 is sunday. Notifications work based on those 2 languages and will be scheduled on OS following that rule.
> 
> I gonna need to force you guys to not use dart DateTime helpers, changing the model objects to demand by code the correct use of those values.
> 
> Or i gonna need to convert those values on native level

In my opinion, it would be better to receive input from the user according to the dart and convert it in or before passing it to the native.

**Comment by rafaelsetragni** [comment]
I gonna need to change it in native for each platform, because the notification could arive from a push notification with the same issue.

**Comment by rafaelsetragni** [comment]
New version released with monday = 1. Please check it for me if the problem was solved.

**Comment by jja08111** [comment]
It works fine on Android. Thanks for your awesome plugin!

**Comment by kimseongyong-nbt** [comment]
It works good! Thanks a lot!
