### ISSUE TITLE
NotificationContent payload switches type

### ISSUE THREAD

**Issue by adrianvintu** [rafaelsetragni/awesome_notifications#154]
When creating a notification we use
```
AwesomeNotifications().createNotification(
 content: NotificationContent(
```
where the constructor is
```
NotificationContent(
Map<String, String>? payload,
```

When running through scheduled notifications
```
activeSchedules = await AwesomeNotifications().listScheduledNotifications();
```
schedule.content.payload is  ```Map<String, dynamic>? payload```

In other words:
NotificationContent defines ```Map<String, String>? payload,```
BaseNotificationContent defines ```Map<String, dynamic>? payload;```

Can you please set both payloads to ```Map<String, String>```?

Thank you for your... AWESOME work!

**Comment by rafaelsetragni** [comment]
Consider it done

**Comment by adrianvintu** [comment]
@rafaelsetragni thank you very much!
