### ISSUE TITLE
Log too verbose

### ISSUE THREAD

**Issue by adrianvintu** [rafaelsetragni/awesome_notifications#155]
When setting up a notification two messages dirty up the log
```
I/flutter ( 6874): Notification created
D/NotificationScheduler( 6874): Scheduled created
I/flutter ( 6874): Notification created
D/NotificationScheduler( 6874): Scheduled created
I/flutter ( 6874): Notification created
D/NotificationScheduler( 6874): Scheduled created
I/flutter ( 6874): Notification created
D/NotificationScheduler( 6874): Scheduled created
I/flutter ( 6874): Notification created
```

Can you make it so no message appears?

**Comment by rafaelsetragni** [comment]
Sure! Its removed for next release.

**Comment by adrianvintu** [comment]
@rafaelsetragni thank you very much!

**Comment by adrianvintu** [comment]
Can you also remove the cancelled notifications verbosity?

D/AwesomeNotificationsPlugin( 6442): Notification cancelled
D/NotificationScheduler( 6442): Scheduled created

**Comment by rafaelsetragni** [comment]
Gunny, i did it yesterday. Thanks!

Ive also create the `dismissNotification` method, to clear the notification from tray withou cancel any active schedule. I will soon release this new version.

**Comment by adrianvintu** [comment]
Thank you very much!
