### ISSUE TITLE
Can createNotification check if channelKey exists?

### ISSUE THREAD

**Issue by adrianvintu** [rafaelsetragni/awesome_notifications#156]
```AwesomeNotifications().initialize(``` uses a list of NotificationChannel.

Can the method
```
AwesomeNotifications().createNotification(
      content: NotificationContent(
        id: id,
        channelKey: channelKey,
````
check if the channelKey is actually in the list of NotificationChannel provied to ```AwesomeNotifications().initialize(```?

If the channel is not in the list, can it throw an exception, or at least a warning?

**Reasoning**

I was working on settings and testing properties to  ```  static NotificationChannel channelWithSound = NotificationChannel(channelKey: 'channelWithSoundKey',```
but in the code I was actually creating notification on another channel:
```
AwesomeNotifications().createNotification(
      content: NotificationContent(
        id: id,
        channelKey: 'basic_channel',
````

Thank you, and keep up the... AWESOME work!

**Comment by rafaelsetragni** [comment]
![image](https://user-images.githubusercontent.com/40064496/116931769-cf896980-ac37-11eb-8b40-6574f4f7a71a.png)
Isn't that showing to you? What platform are you using?

**Comment by adrianvintu** [comment]
@rafaelsetragni I tried to reproduce it using your example and i got
``` me.carda.awesome_notifications.notifications.exceptions.PushNotificationException: The notification channel 'basic_channel2' do not exist or is disabled```

So, I guess the is code for this. Maybe I did not notice the warning in the log?!

Thank you for your support, you can close this ticket.

**Comment by rafaelsetragni** [comment]
Yes. You need to remember that the notification channel still existing while the app keeps installed on the user device. So, once defined, the channel keeps existing, even if you erase the channel config into your dart code and rebuild the app.

**Comment by adrianvintu** [comment]
Thank you, I will keep it in mind!

**Comment by AlaaMarawi** [comment]
can you tell me how to catch this exception and other channel exceptions ? I am trying to enable the user to get test notification and see what is wrong when exception occurs
