### ISSUE TITLE
[iOS] Notification Calendar is not working based on UTC.

### ISSUE THREAD

**Issue by MaheshKumarM-SCE** [rafaelsetragni/awesome_notifications#161]
I have to say this... I really want to thank for the Awesome notifications. And Its so cool to see the feature-rich notifications working out perfectly and displayed in my notification panel. Its been more than two weeks since I known and I absolutely want to try all the features.

[Android] - Notification Calendar is working based on UTC. 

[IOS]  - Notification Calendar is working based on device time. 
             Also, Notification is working only after granting all permissions - allow notifications, badges.
             
 code snippet: 
 notificationSchedule: NotificationCalendar(
   weekday: _today.toUtc().weekday,
     allowWhileIdle: true,
     hour: _today.toUtc().hour,
     minute: _today.toUtc().minute,
     second: 0,
     repeats: true),

**Comment by MaheshKumarM-SCE** [comment]
![Image from iOS (1)](https://user-images.githubusercontent.com/16473581/117182874-8599b280-adf4-11eb-9b6f-71eeb5e70b99.png)

**Comment by rafaelsetragni** [comment]
I gonna check it today if the schedules based on calendar are scheduling in different timezones. Thank you.

**Comment by rafaelsetragni** [comment]
Im writing the 0.0.7 version with time zones option for schedule notifications. Wait just a little bit and ill warn you here when it goes live.

**Comment by rafaelsetragni** [comment]
The timezone is now available. Please take a look.
