### ISSUE TITLE
Custom notification sound on IOS & Android.

### ISSUE THREAD

**Issue by JobMoll** [rafaelsetragni/awesome_notifications#162]
Hey!

I am struggling with the soundSource on IOS & Android. Could someone write a short tutorial on how to do this correctly?
For Android I put the sound file in the raw folder
For IOS I imported it directly under Runner with "copy items if needed", "create folder references" and "add to targets".

What should my soundSource: path be like?
Now i am using this "resource://raw/res_swiq_alarm_notification_sound" but on IOS it just plays the default notification sound.

Any help is appreciated!

Regards, Job

**Comment by rafaelsetragni** [comment]
You dont need to create the respective folders for ios. You only need to copy the file into Runner folder using XCode (do not copy the file with finder's copy and paste).

You can check how everything works with the example project inside this plugin directory.
