### ISSUE TITLE
[iOS] actionStream error with Scheduled Notification on closing the app

### ISSUE THREAD

**Issue by MaheshKumarM-SCE** [rafaelsetragni/awesome_notifications#164]
Hello,
I have encountered this today on iOS, when creating a Scheduled Notification and closing the app.
When the notification appears and clicks, no data reaches the corresponding stream "AwesomeNotifications().actionStream" in this case it only reaches "AwesomeNotifications().displayedStream" with "displayedLifeCycle": "AppKilled".

I don't know if I'm doing something wrong but it works perfect on android.

I checked this related issue - https://github.com/rafaelsetragni/awesome_notifications/issues/136

**Comment by rafaelsetragni** [comment]
Can you build a simple project with this issue and share it with me?

**Comment by MaheshKumarM-SCE** [comment]
Yes sure. I just created my new project - [link](https://github.com/MaheshKumarM-SCE/reminderApp) for learning. I hope this helps.

**Comment by rafaelsetragni** [comment]
Im taking a look at your project right now. But why did you call `AwesomeNotifications().initialize` in `main.dart` and also in `home_page.dart`? And why with different parameters? Ive also notice that you called `AwesomeNotifications().cancelAllSchedules()`, why?

**Comment by rafaelsetragni** [comment]
Ive post a pull request with the first fixes. Take a look at:
[Pull Request](https://github.com/MaheshKumarM-SCE/reminderApp/pull/1)

Im also building a new version with time zones. Will be more easy to you guys creating the schedules.

**Comment by MaheshKumarM-SCE** [comment]
Yes after I posted and I had gone through the project and found the `AwesomeNotifications().cancelAllSchedules()` in the `main.dart` which is my mistake and should have removed - `resource://drawable/res_app_icon` too. 


Thanks friend. After the pull request - first fixes, I will again go through and improve the project.

**Comment by MaheshKumarM-SCE** [comment]
FOR IOS
**Scenario 1** - Works fine
- Notification with action buttons appears when app is in background or foreground state for scheduled date and time.
- When clicking on it, navigated to correct page.

**Scenario 2**
- But when app is in terminated state, I get the notifications for scheduled date and time but the buttons are not present. But notification navigation works when tapping on it.

**Scenario 3**
-when notification is triggered manually by changing device time in phone settings and while app is in terminated state. Clicking on the notification or on the button will only open the app but not navigate to the page. 

I have attached the video for reference - [link](https://drive.google.com/file/d/10qIy5Mv8qtfskiN-i1FDdb6792MHBdlH/view?usp=sharing)

**Comment by rafaelsetragni** [comment]
I tested it right now and i coudnt reproduce your error. Ive also recorded a vídeo.

[video screen recorded](https://drive.google.com/file/d/16DFTu_3Loz3bSn6P8VN0PZhlpVlXLvWc/view?usp=drivesdk)

**Comment by MaheshKumarM-SCE** [comment]
yes I just now saw the recorded video and tried the same. I scheduled the notification for the next minute. Its working fine even if the app is terminated.

but in the following scenarios, it was not working as expected. 
1. When I scheduled the notification at least after 4 minutes from the current time,  notification comes along with the button even if the app is terminated. But after tapping the notification or the button, app is opened and doesn't take me to the correct page.

2. When I scheduled the notification with at least 1 day interval from the current time,  I get the notification without the buttons  when the app is terminated. 
- After tapping on the notification, app is opened and navigated to the correct page.

3. When I scheduled the notification with at least 1 day interval from the current time and manually change the device time,  I get the notification with the buttons  when the app is terminated. 
- After tapping on the notification, app is opened and doesn't take me to the correct page.

**Comment by rafaelsetragni** [comment]
I cannot reproduce the error yet and i truly dont know how the notification after a day does not came with buttons, because this is managed by iOS.

Try to verify if there is something in logs in `XCode -> Window -> Devices and Simulators`

**Comment by MaheshKumarM-SCE** [comment]
I guess may this is something related to iOS version. my device is currently iOS 14.5.1.  Can you please your iOS version?

**Comment by rafaelsetragni** [comment]
Mine is 14.5.1 and all the scenarios worked for me.

**Comment by MaheshKumarM-SCE** [comment]
wow same 14.5.1 version just like mine.. then version is not the issue here.. 

Can you reproduce the following steps and send me recorded video to make sure we follow same steps.

- Schedule the notification at least after 4 minutes from the current time, 
- close the application to make sure the app is not in foreground or background.
- when the notification comes along with the button, tap the notification or the button and check whether it navigates to the correct page.
