### ISSUE TITLE
Support for *not* data-only notifications

### ISSUE THREAD

**Issue by Minituff** [rafaelsetragni/awesome_notifications#165]
## Background
Using this plugin has been a great experience. I was quickly able to get notifications up and looking very good on both IOS and Android. Adding things such as action buttons and input fields was easy.

The issue I am having is that I would like to be able to wrap incoming Firebase FCM notifications which contain the `notification` field in AwesomeNotifcations. I understand from your docs you say that you must use a data only message.

### From the Docs [here](https://github.com/rafaelsetragni/awesome_notifications#how-to-send-push-notifications-using-firebase-cloud-messaging-fcm)
> How to send Push Notifications using Firebase Cloud Messaging (FCM)
> To send a notification using Awesome Notifications and FCM Services, you need to send a POST request to the address https://fcm.googleapis.com/fcm/send. Due to limitations on Android and iOS, you should send a empty notification field and use only the data field to send your data, as bellow:
> 
> OBS: actionButtons and schedule are optional
> OBS 2: you should not implement any native code to use FCM with Awesome Notifications. All of then was already implemented inside the plugin.
> OBS 3: data only messages are classed as "low priority". Devices can throttle and ignore these messages if your application is in the background, terminated, or a variety of other conditions such as low battery or currently high CPU usage. To help improve delivery, you can bump the priority of messages. Note; this does still not guarantee delivery. More info here

## The Problem
Using a data only message will perfectly create the notification on both Android and IOS. The issue is `OBS 3`. My testing on IOS has shown that data only messages hardly come through unless my app was the last app used and is not closed from the "app switcher". IOS data-only notifications also don't come through if I am using another app (that's not mine). This is a deal breaker for a chat application, which would be useless without reliable notifications.

I can solve this issue by having the `notification` field not be empty--when I do this the notification comes in fine, regardless if the app is active or running in the background. The problem with this method is that the notification is created by the Firebase SDK and AweosmeNotifications so the device will show two notifications (one Awesome and one without Awesomeness).

**What I am looking for is** a way to stop the default firebase messaging notification from showing up or for AwesomeNotifications to take them over completely. The end goal I am looking for here is to have my chat application reliably get notifications (which seems like I can't use data-only messages), but also still present the user with all the awesomeness that AwesomeNotifications has like Action Buttons and Input Fields

How would I implement something like this? Is this possible?
Thanks

### A sample notification sent from Firebase cloud functions using the Nodejs SDK:
I tried to follow the guide [here](https://firebase.flutter.dev/docs/messaging/usage/#low-priority-messages) for setting up data-only notifications with the *highest* chance of going through. This works pretty well on Android, but not for IOS. The code snippet below shows how I am able to get reliable notifications except they are created twice. If I switch to a data-only notifcation, then I will comment out the `notification` field an uncomment all the other fields
```javascript
// The data Map is omitted
const msgData = {
  id: `${data.fcmID}`,
  title: `${data.senderName}`,
  body: `${data.text}`,
  type: 'chat_message',
  sender: `${data.sender}`,
  receiver: `${data.receiver}`,
  senderName: `${data.senderName}`,
}

const msg: admin.messaging.Message = {
  token: token,
  data: msgData,
  notification: {
      title: `${data.senderName}`,
      body: `${data.text}`,
  },
  android: {
      // priority: "high", // Required for background/quit data-only messages on Android
  },
  apns: {
      payload: {
          aps: {
              // contentAvailable: true, // Required for background/quit data-only messages on iOS
              // DATA only messsages cant have contentAvailable
          },
      },
      //  headers: {
      //     "apns-push-type": "background",
      //     "apns-priority": "5", // Must be `5` when `contentAvailable` is set to true. 
      //     "apns-topic": "com.my.app", // bundle identifier
      // },
  },
 }
```
### My main.dart file
```dart
import 'package:flutter/services.dart';
import 'package:flutter/material.dart';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:awesome_notifications/awesome_notifications.dart';
import 'package:myapp/models/notification_msg.dart';

// Declared as global, outside of any class
Future<void> _fcmBackgroundHandler(RemoteMessage message) async {
  print("Handling an incoming background message!");

  // If you're going to use other Firebase services in the background, such as Firestore,
  // make sure you call `initializeApp` before using other Firebase services.
  await Firebase.initializeApp();

  // A custom model for notifications I created
  NotificationMsg notificationMsg = NotificationMsg.fromAwesomeFCM(message);

  // Use this method to automatically convert the push data, in case you gonna use our data standard
  AwesomeNotifications().createNotificationFromJsonData(notificationMsg.toAwesomeNotifications());
}

initializeApp() async {
  AwesomeNotifications().initialize(
    // 'resource://drawable/res_app_icon',  // set the icon to null if you want to use the default app icon
    null, // this makes you use your default icon, if you haven't one
    [
      NotificationChannel(
        channelKey: 'high_importance_channel',
        channelName: 'High Importance Notifications',
        channelDescription: 'This channel is used for important notifications.',
        defaultColor: Colors.blueAccent,
        ledColor: Colors.white,
        enableLights: true,
        enableVibration: true,
        playSound: true,
        groupKey: 'chat_message',
        importance: NotificationImportance.Max,
        groupAlertBehavior: GroupAlertBehavior.All,
      )
    ],
  );

  // Initialize firebase
  await Firebase.initializeApp();

  // Set the background messaging handler early on, as a named top-level function
  FirebaseMessaging.onBackgroundMessage(_fcmBackgroundHandler);

  // Update the iOS foreground notification presentation options to allow heads up notifications.
  await FirebaseMessaging.instance.setForegroundNotificationPresentationOptions(
    alert: true,
    badge: true,
    sound: true,
  );
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await initializeApp();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  static final FirebaseAnalytics analytics = FirebaseAnalytics();
  static final FirebaseAnalyticsObserver observer = FirebaseAnalyticsObserver(analytics: analytics);
  static final FirebaseMessaging fcm = FirebaseMessaging.instance;
  static final FirebaseStorage storage = FirebaseStorage.instance;

  @override
  Widget build(BuildContext context) {
    print("MyApp build()");
    return NotificationHandler();
  }
}
```

**Comment by Minituff** [comment]
Update: I submitted a feature request to the FlutterFire team here https://github.com/FirebaseExtended/flutterfire/discussions/6113

**Comment by rafaelsetragni** [comment]
This issue will be solved soon with the companion plugin for awesome_notifications. I gonna close this issue since there is no more activity on it.

**Comment by Minituff** [comment]
@rafaelsetragni How has the work been going on the Companion Plugin? I can't seem to find a link to it. 
I would love support for more than just `data-only` messages.

**Comment by rafaelsetragni** [comment]
I already created the project on pub.dev and started to work on it. I was trying to discover how everything should works and when i took a look two forks was done from the repository with a total uncertain architecture.

Because of that ive put the project on GitHub private until i have a more stable project.

But, right now, im migrating the plugin to work with isolates and ive found a strong necessity to build unit test cases, because the project is too advanced to me test everything with smoke test on example app. The project starts to demand test cases.

So, this project is being done on branch version-0-7-0 and im writhing the test cases for every class. Ive found some very detailed bugs with Android conversion values and json transformations that could be the reason for some issues with channels not being found in release mode.

If you want to help, you can do the same for iOS, because as im not have a mac to work with, the iOS is always a bottleneck for my development.

**Comment by felixgabler** [comment]
Hi, I'm having the same problems and before I migrate to something like One Signal I was wondering what the current progress of the companion project is?
Do you still need help with the test cases? Perhaps I can help with those to speed things up.
