### ISSUE TITLE
Round Image at Notification's Large-Icon

### ISSUE THREAD

**Issue by Kimonnn** [rafaelsetragni/awesome_notifications#166]
Hello,

I really love this package but I found myself struggling with the Large Icon because I am unable to make it round. I found out that you would normally do this by using an Bitmap ( https://stackoverflow.com/questions/28280615/make-notification-large-icon-round ).

Is there already an way to this?

Thank you in forward 🥇

**Comment by rafaelsetragni** [comment]
I'm thinking of creating a special awesome_notifications plugin or package to implement natively 'firebase_messaging', but using awesome_notifications content. But I don't know how to make that kind of relationship between two plugins yet.

**Comment by rafaelsetragni** [comment]
This plugin will be availabe soon with awesome_notifications 0.7.0

**Comment by misterneo** [comment]
Hello @rafaelsetragni, 

I hope this feature will be available soon, I'm currently working on an app that would really benefit from this addition, so far I have been able to alter the source code so I can somehow make it work, but it would be awesome to have it within the package. Thank you and good luck.

![1](https://user-images.githubusercontent.com/25622326/147800627-ed8e4b8f-c301-45be-8827-b28ca111fd8b.PNG)
![2](https://user-images.githubusercontent.com/25622326/147800628-c81e841d-1e28-4863-9cb0-deb8b4d7ad9a.PNG)
![3](https://user-images.githubusercontent.com/25622326/147800629-64ec2bff-4676-4b23-aa64-319de8a151fa.jpg)

**Comment by adnan-haider007** [comment]
is there another way that we pass a string url in large icon parameter and display it , bcz i try to implement it it give me largeicon is invalid error even notification layout big piture is set
