### ISSUE TITLE
how to schedule a notification and repeat it every day

### ISSUE THREAD

**Issue by Mohammad-Adam** [rafaelsetragni/awesome_notifications#168]
Thanks for your awesome package;

I used cron before but now I don't know where it is!
my question is: How to schedule a notification at 11:15 pm GMT+2 and repeat it every day?

**Comment by rafaelsetragni** [comment]
Sorry, i had to remove it because i was obligated to downgrade to leveling Android to the poor iOS capabilities. But you can still do it with:

```Dart
 NotificationCalendar.fromDate(date: scheduleDateTime));
```

or

```Dart
 NotificationCalendar(
    hour:11, minute:15, second:0, millisecond:0, repeats: true
  );
```

Im creating a new version with time zones. For a while, you'll can only do it with UTC. This new version will be released sooner.

**Comment by Mohammad-Adam** [comment]
thank you @rafaelsetragni , I'll give it a try

**Comment by xennygrimmato** [comment]
@rafaelsetragni Would it be useful to add an expiry time if `repeats` is true, similar to CronTab?

**Comment by rafaelsetragni** [comment]
Its not possible due iOS limitations.
