### ISSUE TITLE
Invalid notification (no valid small icon)

### ISSUE THREAD

**Issue by lequyhien98** [rafaelsetragni/awesome_notifications#169]
`Future<void> initAwesomeNotifications(AwesomeNotifications awesomeNotifications) async {
  await awesomeNotifications.initialize(
      null,
      [
        NotificationChannel(
            channelKey: 'basic_channel',
            channelName: 'Basic notifications',
            channelDescription: 'Notification channel for basic tests',
            defaultColor: Colors.blueAccent,
            ledColor: Colors.white
        )
      ]
  );
}`
this my issue help me plaese.

**Comment by rafaelsetragni** [comment]
Please, reinstall your app. Maybe you already sent a command with the icon settled and now the plugin is still searching for it.

**Comment by pinguluk** [comment]
```
    AwesomeNotifications().initialize(
      // set the icon to null if you want to use the default app icon
      'resource://drawable/res_app_icon',
      [
      ...
```

You'll have to put your icon in the **drawable** folder and rename it to **res_app_icon** (or change the line with your image name)
