### ISSUE TITLE
Issue creating Xcode Archive

### ISSUE THREAD

**Issue by aaqibism** [rafaelsetragni/awesome_notifications#17]
Just wanted to let you in on an issue with latest commit in master. When I click archive in Xcode I can't build the project because of an error in these two variable definitions in Definitions.swift:
```
Definitions.NOTIFICATION_DEFAULT_COLOR: 0xFF000000,
Definitions.NOTIFICATION_LED_COLOR: 0xFFFFFFFF,
```
The specific error is that it can't store those values in an int saying that these values will overflow. What's weird is that I can still build fine through VSCode or terminal. I changed both of them to 0x00000000 for the time-being. Of course I realize you're still hard at work finishing the iOS plugin so issues like these are not uncommon but I just wanted to let you know if you weren't aware. Nice work man!

**Comment by rafaelsetragni** [comment]
What device are you running this plugin?

**Comment by rafaelsetragni** [comment]
I got the issue!

Just remove the transparency information from the color and youll sould be ready to go.

```Swift
        Definitions.NOTIFICATION_DEFAULT_COLOR: 0x000000,
        Definitions.NOTIFICATION_LED_COLOR: 0xFFFFFF,
```

You want to create a fork to publish this fix to  and add your name to the project or i do it by myself on the next update? Ill really would appreciate to include your name to the project. Its up to you.

**Comment by aaqibism** [comment]
I may fork it only because then I can stay up to date with your changes later.
