### ISSUE TITLE
IOS app not working with firebase - (example app)

### ISSUE THREAD

**Issue by bhanuka96** [rafaelsetragni/awesome_notifications#172]
I tried to send a message via [API](https://fcm.googleapis.com/fcm/send). The android app is working. The IOS app is not working. I tried the example app. 

```
{
    "to" : "",
    "mutable_content" : true,
    "content_available": true,
    "priority": "high",
    "data" : {
        "content": {
            "id": 100,
            "channelKey": "big_picture",
            "title": "Huston!\nThe eagle has landed!",
            "body": "A small step for a man, but a giant leap to Flutter's community!",
            "showWhen": true,
            "autoCancel": true,
            "privacy": "Private"
        },
        "actionButtons": [
            {
                "key": "REPLY",
                "label": "Reply",
                "autoCancel": true,
                "buttonType":  "InputField"
            },
            {
                "key": "ARCHIVE",
                "label": "Archive",
                "autoCancel": true
            }
        ]
    }
}
```

**Comment by bhanuka96** [comment]
@rafaelsetragni Is IOS app working with fcm?

**Comment by rafaelsetragni** [comment]
Yes, but now you need to implemet it by yourself. Ive put the method createNewNotificationFromJson to help you to translate de json data into Notification object.

On example app this was already done with firebase_messaging, but of course there is no Google project files in it. You need to create a new project on firebase console and import those files by yourself.

**Comment by bhanuka96** [comment]
> Yes, but now you need to implemet it by yourself. Ive put the method createNewNotificationFromJson to help you to translate de json data into Notification object.
> 
> On example app this was already done with firebase_messaging, but of course there is no Google project files in it. You need to create a new project on firebase console and import those files by yourself.

@rafaelsetragni I added the google project to both android and ios directories. I got the notification on android but not getting on the ios app using api. I got fcm token for both android and ios.

**Comment by bhanuka96** [comment]
@rafaelsetragni can you check it using API in the example app?

**Comment by rafaelsetragni** [comment]
Yes. I did it. And its working right now. To copy the files on iOS you need to use XCode to copy the files, not finder, and you need to put ir inside runner's folder.

**Comment by bhanuka96** [comment]
@rafaelsetragni yes I use xcode

**Comment by rafaelsetragni** [comment]
Please, debug it for us

**Comment by bhanuka96** [comment]
> Yes. I did it. And its working right now. To copy the files on iOS you need to use XCode to copy the files, not finder, and you need to put ir inside runner's folder.

okay I will remove all pods and re-try. btw are you running on origin/master branch?

**Comment by rafaelsetragni** [comment]
Yes. Ive tested it from master. If you can build an example app with this issue, ill trully can help you with this issue, otherwise i can only speculate whats going on fron here.

**Comment by bhanuka96** [comment]
@rafaelsetragni call this function. you will get #170

```
await AwesomeNotifications().createNotification(
        content: NotificationContent(
            id: id,
            channelKey: 'basic_channel',
            title: 'title',
            body: 'body',
            )
    );
```

**Comment by bhanuka96** [comment]
And another issue I found when running ios.

`.../awesome_notifications/example/ios/Runner/res_morph_power_rangers.aiff: No such file or directory (in target 'Runner' from project 'Runner')`

I have to delete that file

**Comment by bhanuka96** [comment]
@rafaelsetragni log

```
2021-05-16 19:42:58.221968+0530 Runner[7019:1667934] Metal API Validation Enabled
2021-05-16 19:42:58.478278+0530 Runner[7019:1668105] flutter: Observatory listening on http://127.0.0.1:59664/MhlAJEJK8xs=/
2021-05-16 19:42:58.482088+0530 Runner[7019:1668093] 7.11.0 - [Firebase/Core][I-COR000005] No app has been configured yet.
2021-05-16 19:42:58.484939+0530 Runner[7019:1668093] 7.11.0 - [Firebase/Messaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at:
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
2021-05-16 19:42:59.133112+0530 Runner[7019:1667934] [VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with error -65555.
2021-05-16 19:42:59.133192+0530 Runner[7019:1667934] [VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
"AwesomeNotificationsPlugin: Awesome Notifications service initialized"
2021-05-16 19:43:00.090847+0530 Runner[7019:1668098] flutter: Firebase token: {token is here}
2021-05-16 19:43:13.407229+0530 Runner[7019:1668098] flutter: Requesting url "https://fcm.googleapis.com/fcm/send"...
2021-05-16 19:43:13.804910+0530 Runner[7019:1668098] flutter: POST (200) - Up:607 B Down:143 B /fcm/send
2021-05-16 19:43:13.806420+0530 Runner[7019:1668098] flutter: response is : {"multicast_id":8709891504454583007,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1621174393923772%1bf9b035cccfb49c"}]} , 200

```

**Comment by bhanuka96** [comment]
I added my sample app to here. can you check this? https://github.com/bhanuka96/notification.git

**Comment by rafaelsetragni** [comment]
> And another issue I found when running ios.
> 
> `.../awesome_notifications/example/ios/Runner/res_morph_power_rangers.aiff: No such file or directory (in target 'Runner' from project 'Runner')`
> 
> I have to delete that file

I've uploaded that file for you:

[.../awesome_notifications/example/ios/Runner/res_morph_power_rangers.aiff](https://github.com/rafaelsetragni/awesome_notifications/blob/master/example/ios/Runner/res_morph_power_rangers.aiff)

ill gonna upload a new version of this plugin with time zones for scheduled notifications. After that i'll gonna take a look at your project example.

**Comment by IkhwanSI13** [comment]
I didn't try the sample app but it's happened to me on my project. I've worked with FCM, and everything is working fine. I use flutter_local_notifications as well for notification customization, but that lib doesn't provide action buttons for iOS like this lib.
Exactly after I add `awesome_notifications: ^0.0.6+5` in `pubspecy.yaml` and disable flutter_local_notifications, my FCM isn't working like before. I still get the token from `FirebaseMessaging.instance.getToken()` but I didn't get any notification on any state (foreground, background, and terminated). The same condition happened after I set this lib too. Maybe I did something wrong?

My firebase lib:
`  
  firebase_core: ^1.1.0
  firebase_messaging: ^9.1.3
  firebase_crashlytics: ^2.0.2
`

Flutter doctor:
<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-US)
    • Flutter version 2.0.4 at /Users/Software/flutter
    • Framework revision b1395592de (6 weeks ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (3 available)
    • iPhone (mobile)  • ios            • iOS 12.5.1
    • macOS (desktop) • macos                                    • darwin-x64     • Mac OS X 10.15.7 19H524 darwin-x64
    • Chrome (web)    • chrome                                   • web-javascript • Google Chrome 90.0.4430.212
```
</details>

**Comment by bhanuka96** [comment]
Is there any solution for that? android is working fine my and example app. ios doesn't work.

**Comment by rafaelsetragni** [comment]
Guys, be patient. I haven't had time to check out what happened to you, but soon I will. I am just a person who is developing everything for free. Be patient.

**Comment by IkhwanSI13** [comment]
> Guys, be patient. I haven't had time to check out what happened to you, but soon I will. I am just a person who is developing everything for free. Be patient.

it's okay brother. I'm just informing my situation to let you know. I have very little experience with native iOS, so I can't help you at this point. Sorry

**Comment by JobMoll** [comment]
I ran into the same issue, maybe this data helps pinpointing the issue:

"All notifications scheduled was cancelled"
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file awesome_notifications/NotificationSenderAndScheduler.swift, line 114
* thread #22, queue = 'com.apple.usernotifications.UNUserNotificationServiceConnection.call-out', stop reason = Fatal error: Unexpectedly found nil while unwrapping an Optional value
    frame #0: 0x0000000197c00e08 libswiftCore.dylib`_swift_runtime_on_report
libswiftCore.dylib`_swift_runtime_on_report:
->  0x197c00e08 <+0>: ret
libswiftCore.dylib`_swift_reportToDebugger:
    0x197c00e0c <+0>: b      0x197c00e08               ; _swift_runtime_on_report
libswiftCore.dylib`_swift_shouldReportFatalErrorsToDebugger:
    0x197c00e10 <+0>: adrp   x8, 346589
    0x197c00e14 <+4>: ldrb   w0, [x8, #0x7c8]
Target 0: (Runner) stopped.
Lost connection to device.

Exactly the same as this one:
> @rafaelsetragni call this function. you will get #170
> 
> ```
> await AwesomeNotifications().createNotification(
>         content: NotificationContent(
>             id: id,
>             channelKey: 'basic_channel',
>             title: 'title',
>             body: 'body',
>             )
>     );
> ```
> 
> Error on this line
> 
> `let displayedDate = pushNotification!.content!.displayedDate!.toDate()!`

**Comment by bhanuka96** [comment]
> Guys, be patient. I haven't had time to check out what happened to you, but soon I will. I am just a person who is developing everything for free. Be patient.

@rafaelsetragni It's okay. You did a great job. This is the only package that supports advanced features like the inline reply, I saw on Flutter on the internet. Take your time. Can I know is it possible to fix this?

**Comment by rafaelsetragni** [comment]
> I added my sample app to here. can you check this? https://github.com/bhanuka96/notification.git

But that is the example app copied, i have this project. 

Btw, i had released a new version 0.0.6+6. Please, check for me if your issues persists with the new version.

**Comment by bhanuka96** [comment]
@rafaelsetragni sure, I will update you asap

**Comment by bhanuka96** [comment]
@rafaelsetragni I tested it. Unfortunately fcm is not working on IOS. please check https://drive.google.com/file/d/1EAVM4RRyXcIkqEsYl9qBoroUIDQa1oKx/view?usp=drivesdk

**Comment by rafaelsetragni** [comment]
Try to use Postman and follow the recomendations in Readme file

**Comment by bhanuka96** [comment]
@rafaelsetragni Tried. working only `active` mode. 

```
{
    "to" : "",
    "mutable_content" : true,
    "content_available": true,
    "priority": "high",
    "data" : {
        "content": {
            "id": 100,
            "channelKey": "big_picture",
            "title": "Huston!\nThe eagle has landed!",
            "body": "A small step for a man, but a giant leap to Flutter's community!",
            "showWhen": true,
            "autoCancel": true,
            "privacy": "Private"
        },
         "actionButtons": [
            {
                "key": "REPLY",
                "label": "Reply",
                "autoCancel": true,
                "buttonType":  "InputField"
            },
            {
                "key": "ARCHIVE",
                "label": "Archive",
                "autoCancel": true
            }
        ]
    }
}
```

active mode working
foreground mode not working

**log on xcode**
```
2021-05-18 12:13:55.654577+0530 Runner[10267:2090968] flutter: Handling a background message: 1621320235083865
2021-05-18 12:13:55.654784+0530 Runner[10267:2090968] flutter: message also contained a notification: null
```
background model not working

**Comment by rafaelsetragni** [comment]
What are you facing with background push notifications is the expected behavior for iOS (sadly, but expected). I hightly recommend you to read the documentation files in `awesome_notification` README and specially in [FlutterFire Overview](https://firebase.flutter.dev/docs/messaging/usage/#low-priority-messages).

I had also updated the example app. Please, take a look.

**Comment by JobMoll** [comment]
0.0.6+6 fixed this crash issue on my test devices!

> @rafaelsetragni call this function. you will get #170
> 
> ```
> await AwesomeNotifications().createNotification(
>         content: NotificationContent(
>             id: id,
>             channelKey: 'basic_channel',
>             title: 'title',
>             body: 'body',
>             )
>     );
> ```
> 
> Error on this line
> 
> `let displayedDate = pushNotification!.content!.displayedDate!.toDate()!`

**Comment by IkhwanSI13** [comment]
it's working in all states now. But I must add `content_available` to my request. I don't get it, why is this changing firebase habits?

The final request looks like this:
<pre><code>{
  "to": "token",
  "content_available": true,
  "data": {
    "body": {
      "title": "sample title",
      "message": "sample"
    }
  },
  "notification":{
      "title": "sample title",
      "body": "sample"
  }
}</code></pre>

**Comment by rafaelsetragni** [comment]
The `content_available` tag makes the target extension `UNNotificationServiceExtension` intercepts the incoming notification before it beeing delivered to system tray. Also, the mutable_content makes the target extension `UNNotificationContentExtension` beeing called when the user expands the notification in system tray.

But they also change the notification priority. Why? I have no idea!

**Comment by piyush2greedy** [comment]
@rafaelsetragni @bhanuka96 
I need to integrate the action button with notification. Is there any way of doing it. I need to launch app next week. Currently with firebase_messaging everything is working fine without action button.

If awesome notification is stable with action buttons than please let me know. I don't want to mess up with things already working.

**Comment by rafaelsetragni** [comment]
Every plugin under version 1.0.0 is not in stable state.

**Comment by piyush2greedy** [comment]
Thanks @rafaelsetragni . Will wait for the version 1.0.0
