### ISSUE TITLE
Compatibility  awesome_notification and workmanager

### ISSUE THREAD

**Issue by siiger** [rafaelsetragni/awesome_notifications#174]
I have some issue when i try to use awesome_notification with workmanager... 
"Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: awesome_notifications. Response ID: 0"
Is it possible to fix?
Code where i get this issue: 

```
void callbackDispatcher() {
  Workmanager().executeTask((task, inputData) async {
    switch (task) {
      case channelDelayedTask:
        await awesomeNotifications.createNotification(
            content: NotificationContent(
                id: idAwa,
                channelKey: channelAwareness,
                title: 'title',
                body: 'body',
                payload: {'uuid': 'user-profile-uuid1'}),);
         
      

        Workmanager().registerOneOffTask(
          tagAwaTask,
          channelDelayedTask,
          initialDelay: Duration(seconds: intervalDelay),
          existingWorkPolicy: ExistingWorkPolicy.append,
        );

        break;
      case Workmanager.iOSBackgroundTask:
        print("The iOS background fetch was triggered");

        break;
    }
```

**Comment by rafaelsetragni** [comment]
I dont know how `workmanager` plugin works. I believe you gonna need to initialize every alternative plugin by your own. Check it with the `workmanager` Git community of how to do it.

**Comment by siiger** [comment]
Solved it to use background_fetch with awesome_notifications...now i don't have this issue. 

Rafael, Thanks for the awesome package! Would be great if you will create in future method or something for replace notifications with different id..something like tag. it's reason why now i try to use awesome_notifications with background_fetch to solve this task.

**Comment by Abhis33** [comment]
Having the same problem - 
Works in iOS but not on android -

Error -
W/FlutterJNI(17550): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: awesome_notifications. Response ID: 0

Package Versions - 
awesome_notifications: ^0.0.6+9
workmanager: ^0.4.1

@rafaelsetragni
