### ISSUE TITLE
Notifications are Overriding.

### ISSUE THREAD

**Issue by madd-project** [rafaelsetragni/awesome_notifications#177]
I am in love with the plugin, and it's real Fast.
I am just on the crush on this, this plugin so easy to use than the _flutter_local_notifications_ Thanks to the Creators of this.

**My Question:**
How to make Notifications recurring, I have a reminder app, So the issue is when I am setting up the new remainder the notification of the old remainder is fleeing, and so on and so so.

How to make Remainder, with this plugin which will not remove the past remainder?

```
  AwesomeNotifications().initialize(
      // set the icon to null if you want to use the default app icon
      'resource://drawable/toodoleeicon',
      [
        NotificationChannel(
          // groupKey: "remainderNotf",
          channelKey: 'remainderNotific',
          channelName: 'Remainder_Notification',
          channelDescription:
              'Sends you notifications of the remainders you set',
          defaultColor: Color(0xff4785FF),
          ledColor: Colors.blue,
          importance: NotificationImportance.Max,
          defaultPrivacy: NotificationPrivacy.Public,
          //soundSource: "resource://raw/alert_simple.wav",
        ),
      ]);
  AwesomeNotifications().isNotificationAllowed().then((isAllowed) {
    if (!isAllowed) {
      // Insert here your friendly dialog box before call the request method
      // This is very important to not harm the user experience
      AwesomeNotifications().requestPermissionToSendNotifications();
    }
  });

  AwesomeNotifications().createNotification(
      content: NotificationContent(
          id: 10,
          channelKey: 'remainderNotific',
          title: "$name",
          body: "work is life"),
      actionButtons: [
        NotificationActionButton(
          key: 'COMPLETED',
          label: 'Do it',
          autoCancel: true,
          buttonType: ActionButtonType.Default,
        ),
      ],
      schedule: NotificationCalendar(
        hour: hour,
        minute: minute,
        allowWhileIdle: true,
        timeZone: AwesomeNotifications.localTimeZoneIdentifier,
      ));
}
```

and also, check how I am calling it, 

```
setRemainderMethod(
                      todo.todoRemainder,
                      todo.todoName,
                      totalTodoCount.value,
                      context);
```

**Comment by madd-project** [comment]
Thanks are just kinda being missing, because i am in love with the open-source from now, just for the human race people tend to give up everything to help human get the resources at freest, 

I am not just Thanking this, plugin but every plugin which thinks to give 100% to humans and their further generations by providing the best of services free of cost. 

Now, these are Extra-ordinary Humans.
LOVE you all, who believe in open source.
Thanks ```awesome_notifications``` i am so Lucky...

**Comment by rafaelsetragni** [comment]
For a while, you can use different IDs for each reminder. But you need to keep in mind that iOS has a limit of 64 notifications enabled with different ids at the same time. There is an option in the native code to change this replacement behavior, but I haven't had time to analyze how it works on Android and iOS to provide a transparent layer for developers to use.

Thank you for your consideration, and if you want to help the project with any changes, be welcome!

In case you wish to, i can give you a orientation of where in source code you need to change to acchieve those different behaviors. This way you  can do this improvement and put your name as this project contributor.

**Comment by madd-project** [comment]
It works, it was eating my small brain from yesterday...
So Glad I found ```awesome_notifications``` ..

I am not so Professional Flutter Programmer, But I can contribute to this open-source in many ways, 
as this plugin will be a perennial seller soon, i can help with Word of Mouth, ask other programmers to join, I can merge my app which I am working with this, and any other additional support with graphics, etc., etc. although, with my current skill of Flutter I can help, as much as I could.  

You are now my role model, @rafaelsetragni I can learn and do anything for you, as you really helped me a lot, 

I could write a whole book on the amazingness of your skills and the plugin but I know you are busy with the well being of people so I am concluding it will less word, 

I am always there in this comment, you will be loved more if you will needing some help from me...
