### ISSUE TITLE
Media Player Layout Notifications not working in android 11.

### ISSUE THREAD

**Issue by ChakshuSaraswat** [rafaelsetragni/awesome_notifications#179]
I tried making a music player app which can be controlled using notifications. The plugin is working fine till android 10 but in android 11 i cant see the notification for controlling media. The basic layout notifications are visible though.

**Comment by rafaelsetragni** [comment]
For the moment im not beeing able to run any Android 10+ Emulator on my machine. Im getting BSOD. Can you debug this project with Android Studio debugger attatched to see whats going on?

**Comment by rafaelsetragni** [comment]
You also need to check how media player has changed since Android 11:

[Android 11 changed notifications in a big way: Here’s what you should know](https://www.androidauthority.com/android-11-notification-changes-1127807/)

**Comment by rafaelsetragni** [comment]
Issue solved with exported function addeed in Manifest file.
