### ISSUE TITLE
MissingPluginException(No implementation found for method createNewNotification on channel awesome_notifications)

### ISSUE THREAD

**Issue by bayuramadeza** [rafaelsetragni/awesome_notifications#18]
Hi, I followed your instruction about how to use this package.
So, I added initialize channel in my main.dart
Then I call create notification from the app, it's work
But, when i call it from background, push notification, i got the error mesage
```
Unable to handle incoming background message.
I/flutter (20190): MissingPluginException(No implementation found for method createNewNotification on channel awesome_notifications)

````

What's wrong?

**Comment by rafaelsetragni** [comment]
How are you calling it from background? Paste here a code example

**Comment by bayuramadeza** [comment]
So I have my backgroundMessageHandler in main.dart
I have created channel basic_test in main.dart before runApp.

```
Future<dynamic> myBackgroundMessageHandler(Map<String, dynamic> message) async {
  if (message.containsKey('data')) {
    // Handle data message
    final dynamic data = message['data'];
    String title = data['nt']??data['title'];
    String body = data['nm']??data['body'];
    String imageUrl = data['wzrk_bp']??'';
    return title.isEmpty? null : showNotification(title, body, imageUrl);
  }
}
```

When onBackground triggered, i show notification by call showNotification() method above.
show_notifications.dart

```
class ShowNotifications{
//other method
showNotification(String title, String body, String image)async{
  await AwesomeNotifications().createNotification(
      content: NotificationContent(
          id: id,
          channelKey: 'basic_test',
          title: title',
          bigPicture:
              'https://i0.wp.com/www.jornadageek.com.br/wp-content/uploads/2018/06/Looney-tunes.png?resize=696%2C398&ssl=1',
          notificationLayout: NotificationLayout.BigPicture,
          payload: {'uuid': 'uuid-test'}));
}
}
```

Whenever I called showNotification from any screen, the notif is show. But, when onbackground notification triggered, the error happened.

```
Unable to handle incoming background message.
I/flutter (20190): MissingPluginException(No implementation found for method createNewNotification on channel awesome_notifications)
```

**Comment by rafaelsetragni** [comment]
It seems like the plugin is not beeing initialized by Flutter on your background fetch. So there is no native handle registred to receive your background call.

Can you share with me your project on github to me reproduce this error?

**Comment by bayuramadeza** [comment]
I created mini example of how I user the package in https://github.com/bayuramadeza/Awesome-Notification-FCM,
I think this package should have something like :
FirebaseMessagingPlugin.registerWith(registry?.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin")) to add in Application.kt to handle this error.

Nope, I didn't use background_fetch

**Comment by rafaelsetragni** [comment]
Im fixing your source. 

First, you SHOULD NOT USE firebase classes on your project directly. You should strictly follow the steps to [How to show Local Notifications](https://pub.dev/packages/awesome_notifications#how-to-show-local-notifications) and to use firebase messaging you should follow the steps to [Using Firebase Services (Optional)](https://pub.dev/packages/awesome_notifications#using-firebase-services-optional).

Do not do anything else than what is indicate on the documentation. All the firebase class to sendo FCM was already implemented, managed and installed inside the Awesome Notifications plugin. You dont need to do anything else.

**Comment by bayuramadeza** [comment]
Thanks!! It works now.
But, I still have some questions.
1. Can the notification show up like heads-up notification, like image below?
<img width="412" alt="Screen Shot 2020-10-27 at 13 56 45" src="https://user-images.githubusercontent.com/32892647/97267203-5a8a4100-185c-11eb-9019-64b118e2b60c.png">
2. Can the notification handle onMessage notification like FCM? So it doesn't need to show in background, instead it pop in app screen.?
3. The problem I got is the marketing tools use their own data to handle notification, the notification structure is {"data" ; {"title" : title, "body": body}}, So, i can't customize it like the the structure specified in [Awesome Structure](https://pub.dev/packages/awesome_notifications#how-to-send-push-notifications-using-firebase-cloud-messaging-fcm)

**Comment by rafaelsetragni** [comment]
1. Sure. You can manipulate the entire notification to show as exactly as this example, changing `title`, `body`, `showWhen`, activating `BigPicture` layout with `largeIcon` and, for last, including the two `actionButtons` "Reply" and "Archive". 

And also you can control if your notification will automatically shows on foreground or background, using the variables `displayOnForeground` and `displayOnBackground`. Its all up to you.

2. `onMessage` event is equivalent to `displayedStream` stream. You just need to listen this stream, as you do on `actionStream`. Youll always receive the event on `displayedStream`, even when your app is terminate. Sometimes the streams could not be delivered on exactly time when they happen, but they will be delivered as soon as possible to your Flutter app.

You can check all those combinations on our [Notification Life Cycle](https://github.com/rafaelsetragni/awesome_notifications#notification-life-cycle) and [Flutter Streams](https://github.com/rafaelsetragni/awesome_notifications#flutter-streams) topics.

Also, i do recommend you to watch this video about **Dart Streams**:

[![Dart Streams](https://img.youtube.com/vi/nQBpOIHE4eE/0.jpg)](https://www.youtube.com/watch?v=nQBpOIHE4eE)

**Comment by rafaelsetragni** [comment]
Can i put your example code on our README documentation? This will allow the others to use this example to learn how to use Awesome Notifications and Firebase Cloud Messaging more easly.

And, of course, I want to include your name as thanks for helping the community. Can i?

**Comment by bayuramadeza** [comment]
Okay, Thankyou so much for your explanation. I got it,
Sure, You can  put my example code in your README documentation. I'm pleasure to heard it

**Comment by jenniestrongbow** [comment]
@rafaelsetragni  
Hi you mentioned the displayOnBackground option. I did not see it in the documentation. How do I set it? Thanks
