### ISSUE TITLE
Notification constantly repeats itself, it fires again and again

### ISSUE THREAD

**Issue by eyubSalihOzdemir** [rafaelsetragni/awesome_notifications#180]
Hello guys, in my app, I get the `selectedHour` and the `selectedMinute` from user. With these, my goal is to trigger an alarm at the same time everyday for a daily reminder.

But for some reason, when the alarm triggers it just does not stop and repeatedly fires again and again. Does anyone have an idea about why this might happen?

I have this in the initState:
```
AwesomeNotifications().initialize(
  // set the icon to null if you want to use the default app icon
  null,
  [
    NotificationChannel(
        channelKey: 'scheduled',
        channelName: 'Basic notifications',
        channelDescription: 'Notification channel for basic tests',
        defaultColor: Color(0xFF9D50DD),
        ledColor: Colors.blue,
        onlyAlertOnce: true,
        playSound: true)
  ]
);
```

And this is my onPressed function:
```
onPressed: () async {
      String localTimeZone = await AwesomeNotifications()
          .getLocalTimeZoneIdentifier();
      await AwesomeNotifications().createNotification(
          content: NotificationContent(
            id: 1,
            title: 'testing',
            channelKey: 'scheduled',
            body: 'yabi dabi du.',
          ),
          schedule: NotificationCalendar(
              allowWhileIdle: true,
              hour: int.parse(selectedHour),
              minute: int.parse(selectedMinute),
              second: 0,
              millisecond: 0,
              timeZone: localTimeZone,
              repeats: true
          )
);
```

**Comment by rafaelsetragni** [comment]
What platform are you creating these schedules?

**Comment by eyubSalihOzdemir** [comment]
I only tried it on Android side. I've used different emulators for API 29 and 30, Android 10. I also tried it on my Xiaomi Redmi Note 8, also Android 10. Both debug and release mode apk's creates the same error.

Lİsten to this, I forgot about the app on my phone today. The notification was up there the whole day. When I noticed, I deleted the notification and boom, right there, a brand new notification. It just won't die 😄, that's kinda cool.

Also, I'm not familiar with GitHub but I tried my best for you, here's the repository that I tried to create:
https://github.com/eyubSalihOzdemir/flutter_error_sample

I hope you can understand what is wrong with my code.
Thank you.

**Comment by rafaelsetragni** [comment]
I couldnt reproduce your error. The schedules was correctly displayed and dont fire in loop, ever. I also implemented some features to help you to see whats going on and test faster.

Pull request:
https://github.com/eyubSalihOzdemir/flutter_error_sample/pull/1

**Comment by eyubSalihOzdemir** [comment]
My new tests on emulator were successful, no repeating notifications. So I thought maybe it was because my timze zone. I had saw on wiki earlier that 'Europe/Istanbul' zone was deprecated. I changed my time zone on my real phone and tried again, but no. Notifications are repeating.

Than I thought it could be because of my phone, Xiaomi creates problems all the time. I tried on a few other devices: Samsung, GM, Huawei, LG. But again, still repeating notificaions.

I could not solve this problem but I have a clue. On the emulator (not repeating notifs), when the notification fires, it creates another one and in the terminal it says: 
`D/NotificationCreator: Scheduled created`
Bu on my phone, this line repeats every second. I guess for some reason, it creates new notification every second.

I hope this can help you solve it. 
Thank you.

**Comment by rafaelsetragni** [comment]
Im a little confused if you are solving the problem or if it persists.

Try to debug the native code using Android Studio to see what's going on under the hood.

**Comment by madd-project** [comment]
try `repeat : false`

**Comment by madd-project** [comment]
Can you do one thing, try removing play sound.
just for the experiment. :hehe

**Comment by madd-project** [comment]
@eyubSalihOzdemir did you got the bestter solutiono?
