### ISSUE TITLE
IOS notification buttons are not shown if notification scheduled time is more than 5 minutes from current time and app is in terminated state.

### ISSUE THREAD

**Issue by flytosowmya** [rafaelsetragni/awesome_notifications#181]
Hi, can you please check this scenario because it was not working as expected when I checked. I found this in IOS only.

I scheduled the notification after 5 minutes from the current time, notification is shown along with the buttons even if the app is terminated. But after tapping the notification or the button (app is in terminated state), my app opened and didn't take me to the correct page. I added the code used to initialize and schedule the notification. This works fine if the notification is scheduled for less than 5 minutes.
 When I scheduled the notification for next day, I get the notification without the buttons when the app is terminated. After tapping on the notification, app is opened and navigated to the correct page.

AwesomeNotifications().initialize(
    null ,
    [
        NotificationChannel(
            channelKey: 'basic_channel',
            channelName: 'Basic notifications',
            channelDescription: 'Notification channel for basic tests',
             importance: NotificationImportance.High,
            defaultColor: Color(0xFF9D50DD),
            ledColor: Colors.white,
        )
    ]
);

AwesomeNotifications().createNotification(
  content: NotificationContent(
      id: 5,
      channelKey: 'basic_channel',
      title: 'Assignment reminder',
      body: 'Last due date is saturday',
   actionButtons: [
        NotificationActionButton(
            key: 'NOW',
            label: 'Okay',
            enabled: true,
            buttonType: ActionButtonType.Default),
        NotificationActionButton(
            key: 'LATER',
            label: 'will do it later,
            enabled: true,
            buttonType: ActionButtonType.Default)
      ]
)
);

**Comment by rafaelsetragni** [comment]
But nothing on your example is scheduling a notification.
Anyway. I repeat your notification with NotificationCalendar and everything works just fine.

Can you build a simple application with this error happening and share it with me here on GitHub?

**Comment by flytosowmya** [comment]
I checked in my iphone version iOS 14.5.1. Sure I have uploaded simple application here - https://github.com/flytosowmya/task_tracker.

**Comment by rafaelsetragni** [comment]
Just a simple question: Have you settled the time zone identifier by yourself or using the `getLocalTime Zone Identifier` method?

**Comment by flytosowmya** [comment]
Oh I use the `getLocalTimeZoneIdentifier` to set the timezone. I checked on my real device and my timezone is Asia/Kolkata.

**Comment by flytosowmya** [comment]
Hi I found out when I start using multiple packages in my project , the notification doesnt take me to the correct page.
when I used just 3 packages - awesome notifications, flutter toast, get in pubspec.yaml, notifications work absolutely fine in iOS.
And, after importing each package one by one upto 10 packges, I tapped on the notification and it worked fine.
So, I will try again to import each package one by one today and tomorrow, I will update you if it worked or if its a package issue.

`contacts_service: ^0.6.1
  permission_handler: ^7.1.0
  cupertino_icons: ^1.0.2
  flutter_widget_from_html: ^0.6.0
  camera: ^0.8.1
  carousel_slider: ^3.0.0
  fl_chart: ^0.35.0
  flutter_blue: ^0.8.0
  flutter_svg: ^0.22.0
  flutter_xlider: ^3.4.0
  get: ^4.1.0
  intl: ^0.17.0
  multi_image_picker: ^4.8.0
  path_provider: ^2.0.1
  rxdart: ^0.26.0
  #sleek_circular_slider: ^2.0.0
  url_launcher: ^6.0.3
  usb_serial: ^0.2.4
  #video_player: ^1.0.1
  build_runner: ^1.10.11
  json_serializable: ^3.5.1
  flutter_spinkit: ^5.0.0
  flutter_inappwebview: ^5.3.2
  dio: ^4.0.0
  vibration: ^1.7.3
  liquid_progress_indicator: ^0.3.2
  percent_indicator: ^3.0.1
  flutter_native_timezone: ^1.0.10
  device_info: ^2.0.0
  package_info: ^2.0.0
  location: ^4.1.1
  regexpattern: ^1.0.0
  shared_preferences: ^2.0.5
  uuid: ^3.0.4
  #firebase_ml_vision: ^0.9.10
  #tflite_flutter: ^0.5.0
  image: ^3.0.2
  connectivity: ^3.0.3
  #encrypted_shared_preferences: ^1.0.7
  #disk_space: ^0.0.3
  equatable: ^2.0.0
  #sqflite: ^1.3.2+3
  sqflite_sqlcipher: ^2.0.0
  app_settings: ^4.1.0
  #datetime_setting: ^1.0.0
  bluetooth_enable: ^0.1.1
  #battery_optimization: ^0.1.0
  google_maps_flutter: ^2.0.3
  google_place: ^0.4.0
  shimmer: ^2.0.0
  archive: ^3.1.2
  marquee: ^2.1.0
  string_validator: ^0.3.0
  timelines: ^0.1.0
  lottie: ^1.0.1
  math_expressions: ^2.1.0
  keyboard_actions: ^3.4.0
  font_awesome_flutter: ^9.0.0
  firebase_messaging: ^10.0.0
  firebase_core: ^1.2.0
  firebase_analytics: ^8.1.0
  image_picker: ^0.7.4
  feature_discovery: ^0.14.0
  screenshot: ^0.3.0
  flare_flutter: ^3.0.0
  maps_launcher: ^2.0.0
  smooth_page_indicator: ^0.2.3
  auto_size_text: ^2.1.0
  share: ^2.0.1
  #notification_permissions: ^0.5.0
  #flutter_app_badger: ^1.2.0
  assets_audio_player: ^3.0.3+3
  flutter_sticky_header: ^0.6.0`

**Comment by rafaelsetragni** [comment]
Dude, debug your application using Android Studio and XCode and you gonna discover in details whats going on. Will be a lot more easy and faster than do all the combinations necessary switching packages.

**Comment by flytosowmya** [comment]
I tried debugging and checked the console for messages. when I tried first time by importing each package and tapped on the notification, app is navigated to correct page

When I imported the multiple packages and scheduled the notification, I tapped the notification (app is in terminated state) and displayedStream is successful but actionStream is not working.

**Comment by rafaelsetragni** [comment]
I got what's going on.

You are taking time enough between the initialization and the action stream listen to capture the call. Because there is many things to do between these two events.

Try to modify the `AwesomeNotificationPlugin` streams to not work on broadcast and try again.

**Comment by flytosowmya** [comment]
oh ok I have first declared the notification plugins in the pubspec yaml.
also I have initialized the Awesome notification inside main method with async and await before run(MyApp()). can you help me change AwesomeNotificationPlugin to not work on broadcast. 
Also, everything works fine in Android. I found this issue only in iOS.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
