### ISSUE TITLE
Multi line body text

### ISSUE THREAD

**Issue by PaoloCirasa** [rafaelsetragni/awesome_notifications#186]
Hi, I can't understand how to set the body of notification as multi line text. I tried to name channelKey as 'big_text', but I don't know if it is the right solution.
I set body as:

body: '''
this is 
a multiline text'''

But the notification has always a one line text. How can I achieve that? 
Thank you very much!

**Comment by rafaelsetragni** [comment]
Try to change the layout and you can achieve this.
[Notification types, values and defaults - NotificationContent](https://github.com/rafaelsetragni/awesome_notifications#notificationcontent-content-in-push-data---required)

**Comment by PaoloCirasa** [comment]
Hi Rafael, thank you for your answer!
I made (I guess) the right correction, adding notificationLayout, but it still returns me a one line notification.
Can you please tell me what I am doing wrong?
Maybe am I writing multiline body in a wrong way?
(I'm new in android/dart/flutter)

Thank you very much!

This is my code:

```
import 'package:awesome_notifications/awesome_notifications.dart';

Future main() async {
    AwesomeNotifications().initialize(
      null, //default app icon
      [
        NotificationChannel(
            channelKey: 'big_text',
            channelName: 'Notification',
            channelDescription: 'Multi line notification',
            defaultColor: Color(0xFF9D50DD)
        )
      ]
  );

 AwesomeNotifications().createNotification(
      content: NotificationContent (
          id: 1,
          channelKey: 'big_text',
          notificationLayout: NotificationLayout.BigText,
          title: 'Ciao',
          body: '''Questa è 
          Una notifica
          Multilinea'''
         //also tried body: "Questa è\nUna notifica\nMultilinea" with no success :(
      )
  );

}
```

**Comment by rafaelsetragni** [comment]
Try to take a look on our example app. Its inside the folder example, inside the GitHub repository.

**Comment by PaoloCirasa** [comment]
Ah ok, what a shame! :-(
I wanted to append a kind of "nested list" in notification body, but it's impossible doing it without a "new line" element.
In the past I used node androidjs and I managed to do it calling directly from javascript this function:

app.notification.initBig("Title", ["line1", "line2", "line3"]);
app.notification.show(2);

this is the reference url:
https://android-js.github.io/docs/notification_api.html

Later I abandoned that framework because of lack of enviromental functions for Android.
But I know it's possible to do it in Android.

Thank you anyway!

**Comment by kakposoe** [comment]
For anyone looking into how to make multiline notifications, it can be done by using `<br>`. 

```dart
AwesomeNotifications().createNotification(
    content: NotificationContent(
        id: 10,
        channelKey: 'big_text',
        title: 'I have Duchenne Muscular Dystrophy (DMD)',
        body: 'This is a line<br>This is another line<br>This is a third line',
        notificationLayout: NotificationLayout.BigText
    )
);
```

I originally made the mistake of using `\n` to separate but after some research I realised my error.

**Note:** When the notification appears, it will concatenate the string into a single line until the notification expanded.

**Comment by kishangohel** [comment]
i have already acheive \n in content in native android
there must be issue within this package.

**Comment by rafaelsetragni** [comment]
> 
> 
> i have already acheive \n in content in native android
> there must be issue within this package.

This plugin is open source. Fell free to edit it and share with us your fix.
