### ISSUE TITLE
My build fails only on IOS after adding this package. 

### ISSUE THREAD

**Issue by mtkgeek** [rafaelsetragni/awesome_notifications#187]
My app runs smoothly on android but i keep getting this error whenever i try running it on an ios simulator.
`flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.0.6+7/ios/Classes
    /lib/extensions/StringExtension.swift:2:12: error: no such module 'CommonCrypto'
    import var CommonCrypto.CC_MD5_DIGEST_LENGTH`
The app works fine if i remove the awesome notifications packages but crashes with this error whenever i add it. I'm on an M1 Mac so i don't know if that may be a factor. Any help would be appreciated.

**Comment by rafaelsetragni** [comment]
Add this line into file `awesome_notifications.podspec`, in plugin's ios folder, and try to build your app again:

![image](https://user-images.githubusercontent.com/40064496/120863725-6449f480-c561-11eb-990e-0bea2e1ac503.png)

**Comment by mtkgeek** [comment]
Thanks for the quick response @rafaelsetragni. I did like you said but now i get this error 
`/ios/Pods/CommonCrypto/NSData+CommonCrypto.h:42:9: error:
    include of non-modular header inside framework module 'CommonCrypto.NSData_CommonCrypto':
    '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPh
    oneSimulator14.5.sdk/usr/include/CommonCrypto/CommonHMAC.h'
    #import <CommonCrypto/CommonHMAC.h>
            ^
    /Users/moses/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.0.6+7/ios/Classes
    /lib/extensions/StringExtension.swift:2:12: error: could not build Objective-C module`
    This is what the awesome notifications podspec looks like`
Pod::Spec.new do |s|
  s.name             = 'awesome_notifications'
  s.version          = '0.0.2'
  s.summary          = 'A complete solution to create Local Notifications and Push Notifications, throught Firebase or another services, using Flutter.'
  s.description      = <<-DESC
A complete solution to create Local Notifications and Push Notifications, throught Firebase or another services, using Flutter.
                       DESC
  s.homepage         = 'https://github.com/rafaelsetragni/awesome_notifications'
  s.license          = { :file => '../LICENSE' }
  s.author           = { 'Rafael Setragni' => 'rafaelsetra@gmail.com' }
  s.source           = { :path => '.' }
  s.source_files = 'Classes/**/*'
  s.static_framework = true
  s.dependency 'Flutter'
  s.dependency 'CommonCrypto'
  #s.dependency 'Firebase'
  #s.dependency 'Firebase/Messaging'
  s.platform = :ios, '10.0'

  # Flutter.framework does not contain a i386 slice. Only x86_64 simulators are supported.
  s.pod_target_xcconfig = {
    'DEFINES_MODULE' => 'YES',
    'VALID_ARCHS[sdk=iphonesimulator*]' => 'x86_64',
    'ENABLE_BITCODE' => 'NO',
    'APPLICATION_EXTENSION_API_ONLY' => 'NO'
  }
  s.swift_version = '5.0'
  
end
`

**Comment by mtkgeek** [comment]
I'll also like to mention that this issue is only visible in versions >=0.0.6. Earlier versions don't bring this up.

**Comment by rafaelsetragni** [comment]
Im removing common cripto library reference and implementing it by my own, so in version 0.0.7 this problem will be solved.

Take a look at this mods:

New String Extension:
[ios/Classes/lib/extensions/StringExtension.swift](https://github.com/rafaelsetragni/awesome_notifications/blob/52accb4c1297e9461a467756c06705fe59566adc/ios/Classes/lib/extensions/StringExtension.swift)

New MD5 method:
[ios/Classes/lib/externalLibs/MD5.swift](https://github.com/rafaelsetragni/awesome_notifications/blob/52accb4c1297e9461a467756c06705fe59566adc/ios/Classes/lib/externalLibs/MD5.swift)

**Comment by mtkgeek** [comment]
So my options right now are to either wait for version 0.0.7 or copy the new StringExtension.swift file into my plugin folder locally?

**Comment by rafaelsetragni** [comment]
Exactly, or request your money back / refund.

**Comment by mtkgeek** [comment]
I figured using that commit as a ref in my pubspec would be a much better idea than editing locally i.e
`awesome_notifications: #^0.0.6+7
    git:
      url: https://github.com/rafaelsetragni/awesome_notifications.git
      ref: 52accb4`


`
New errors though
```
ios/Classes/lib/utils/JsonUtils.swift:31:46: error: value of optional type '[String : Any]??'
    not unwrapped; did you mean to use 'try!' or chain with '?'?
                let decodedData:[String:Any?]? = try? JSONSerialization.jsonObject(with: data,
                options: []) as? [String: Any]
                                                 ^~~~
                                                 try!
    /Users/user/flutter/.pub-cache/git/awesome_notifications-52accb4c1297e9461a467756c06705fe59566ad
    c/ios/Classes/lib/utils/JsonUtils.swift:44:22: error: value of optional type '[[String : Any]]??'
    must be unwrapped to a value of type '[[String : Any]]?'
                  return jsonArray
```

**Comment by rafaelsetragni** [comment]
There is another changes with this commit that are incompatible or not finished yet (Work In Progress)

**Comment by mtkgeek** [comment]
oh alright. Appreciate all you do all the same, looking forward to it.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
