### ISSUE TITLE
After Build Apk, Custom Sounds and Icons are not Visible?

### ISSUE THREAD

**Issue by madd-project** [rafaelsetragni/awesome_notifications#188]
Hey `awesomely awesome_notifications`,
I am Getting a Trouble, with the App, I search this issue in the repo itself in the issues tab so much, but I can't find any relevant ideas about it, 

I have Tried using `res_` in the drawable, in the icon name.
I had Tried also building app with `--no-shrink`
The app is Running Beautifully in Debug mode, but in Release, I can't able to make it up.

If in case, You need the Minimal Code, I can Provide it up.
Thanks a lot for the beauty of the package.
That is really helpful.

**Comment by madd-project** [comment]
Hey Admin, @rafaelsetragni Greetings, 
I am finding an Issue, 
I am So Sorry, I am troubling, because, I made a lot of Efforts and seen so much Stacks, and Closed Issues in Asesome Notifications but nothing Worked, But if you have a relevant answer of it, I would love it. Please.

> I have Tried using res_ in the drawable, in the icon name.
I had Tried also building an app with --no-shrink
The app is Running Beautifully in Debug mode, but in Release, I can't able to make it up.

**Comment by rafaelsetragni** [comment]
Sorry to not give an response before. Ill gona have time to check this only on Saturday now. Ill respond to you aa soon as i can.

**Comment by madd-project** [comment]
No Issues Most Talented🔋 ,
Ask yourself, As I asked for these Errors, there are many others who ask and tell you that they are regularly getting errors in using Custom Icons and sounds from the Package. Right?

I Got the Permanent Solution to the Problem.
Listen I have Searched the Whole Web, Listed and played with the Different Packages, around and observed that, 
They are supporting the use of these Two Lines, 
```
android:showWhenLocked="true"
            android:turnScreenOn="true">```

in the  ```android\app\src\main\AndroidManifest.XML`` file ..
You can Check out the most of the Notification packages Examples or README they are using these two lines in order to show up the notifications in the release,
without any errors.


I have created the Pull Request to Prompt up user ahead, before using the Package, they can first add up these lines so that you can focus on issues that matter the most, not those who are regularly coming up to you.

You can use it on your own.
It is a Social Proof that it works, and Even For me, As I had tried everything which was written in your package (README) but nothing was working, when I added these lines, BOOM.. 

Everything got So Good.
@rafaelsetragni  it's All About Customer Experience, So you have minimized the Errors and Issues, For this, I created the Pull, 
If it will work for you, Merge it. Right Away for your OpenSource Community. ❤️

**Comment by madd-project** [comment]
![cb36f118a4d8f5cd849a5552c463fd5a6b3124ab68bccbcd6a31962e118b9f96.0.png](https://user-images.githubusercontent.com/64954854/121461138-e9069980-c9cb-11eb-8f85-498c34669a91.png)

**Comment by mtkgeek** [comment]
This ironic because i'm not currently having this issue but adding this to my manifest file stops my notifications from working completely in release mode.
So maybe you wanna hold off on making this a requirement in the readme.

**Comment by madd-project** [comment]
> 
> 
> This is ironic because i'm not currently having this issue but adding
> 
> ```
> android:showWhenLocked="true"
> android:turnScreenOn="true"
> ```
> 
> to my manifest file stops my notifications from working completely in release mode.
> So maybe you wanna hold off on making this a requirement in the readme.

Hey Yo, @mtkgeek  
You have to do it like this,

```
 <application
        ...
</receiver>
        <activity
            ....
            ...
            .... 
            android:showWhenLocked="true"
            android:turnScreenOn="true">
          ...

```

**Comment by bbence84** [comment]
I also had the same issue, and finally managed to fix it by adding a keep.xml. I had the icon in a drawable resource folder and also the issue that the icon was blank in release mode. How to fix it:
1. Create a folder called "raw" under android/app/src/main/res
2. Create a keep.xml file and add the following content:

<?xml version="1.0" encoding="utf-8"?>
<resources xmlns:tools="http://schemas.android.com/tools"
    tools:keep="@drawable/*,@raw/slow_spring_board" />

Save it and rebuild.

Not sure if the AndroidManifest.XML change was also neccessary, I kept it there, but without the keep.xml, I still had the issue even after the AndroidManifest.XML change.
