### ISSUE TITLE
Can't Listen to FCM Token Changes

### ISSUE THREAD

**Issue by vimalk29** [rafaelsetragni/awesome_notifications#189]
I am currently using `awesome_notifications: ^0.0.6+7` and I couldn't find any `fcmTokenStream` inside the awesome notification package. Rather I saw that it's commented out for some reason. How am I supposed to get the tokens? I am able to use awesome notification locally but unable to use it with FCM.
I also tried to get the token by including the firebase_messaging package but it doesn't work either.
No push notifications are displayed inside my notification bar in any of the modes.

The documentation doesn't really have anything about working with FCM except one example which uses `awesome_notifications: ^0.0.5+1` and I don't want to use that, although when I tried using this in my flutter code just to check if it works correctly, fcmTokenStream was still not there even after I tied `flutter clean` and `flutter pub get`.

I might be missing something or maybe I am overlooking something.

**Comment by rafaelsetragni** [comment]
In versions between 0.0.6 and 0.0.7, the push notification was completely delegate to `firebase_messaging` plugin. But sooner i gonna release the 0.0.7 version with a separated plugin, called `awesome_notifications_fcm`. to re-enable all the push features with all local awesome capabilites.
