### ISSUE TITLE
PlatformException getFirebaseToken could not fetch instanceID, types and labels must be unique

### ISSUE THREAD

**Issue by Cybernetics354** [rafaelsetragni/awesome_notifications#19]
I'm trying to use awesome notification on my app, when on debug mode it's work well, but when on release mode there's an error caught. i'm using awesome_notifications: ^0.0.3+3.

```
PlatformException(getFirebaseToken could not fetch instanceID, types and labels must be unique,
java.lang.IllegalArgumentException: types and labels must be unique
    at i.a.a.d.b.a(Unknown Source:35)
    at i.a.a.d.b.a(Unknown Source:4)
    at i.a.a.f.i.a(Unknown Source:28)
    at i.a.a.f.i.a(Unknown Source:0)
```
and here's my initialize code.

```dart
 try {
      bool status = await awesomeNotifications.initialize('resource://drawable/app_icon',
        [
          NotificationChannel(
            channelKey: "local_notification",
            channelName: "Local Notification",
            channelDescription: "Channel for showing local notification",
            defaultColor: mainColor.themeColor,
            ledColor: mainColor.backgroundColor
          )
        ]
      );

      if(status == true) {
        awesomeNotifications.actionStream.listen((ReceivedNotification receivedNotification) {
          print(receivedNotification.body);
        });
      }
    } catch (e) {
      ErrorHandleProduct().errorHandle(e, ErrorHandleProductType.basic, callback: () async {
        await Future.delayed(Duration(seconds: 2));
        initialize();
      });
    }
```

is there any clue why this error happen? or there's some extra configuration for release. looking forward for the solution

**Edit**
i have solve the issue right now, im using `minifyEnable true` on my release gradle configuration, so i can't initialize awesome notification if `minifyEnable` is true, i'm curious why this package won't work if `minifyEnable` is true. or there's a way to use it but with extra configurations?

**Comment by rafaelsetragni** [comment]
What is minifyEnabled?

**Comment by Cybernetics354** [comment]
thanks for the answer, according to issue that you've mentioned. flutter tool now has `minifyEnabled` by default using R8 instead of proguard, and i've using proguard for `minifyEnabled` yesterday and get me that error. and that's my fault because i don't research much farther about that. but why the other packages works well with that configuration? my issue has been solved, and you don't need to answer this if you don't want to, this is just my curiosity. but I would be very grateful if you answer the reason.

i'm always use `flutter run --release` to test on release mode with my physical device. and of course to release my app on stores i prefer app bundle instead of splited-abi apks.

**Comment by rafaelsetragni** [comment]
Maybe is a undesired result of run the compiling with minifyEnable twice, one of your part and the another from Flutter. And depending of what is beeing used on each plugin, the error occurs or not.

Its only what i beleive whats going on. I did not inspected this deeply.

**Comment by rafaelsetragni** [comment]
I discovered whats goin on and how to fix this error:

[awesome_notifications only works in debug mode, in release mode the notification doesn't appear at all
#29](https://github.com/rafaelsetragni/awesome_notifications/issues/29)
