### ISSUE TITLE
How to Make Daily Notifications?

### ISSUE THREAD

**Issue by madd-project** [rafaelsetragni/awesome_notifications#199]
```  
AwesomeNotifications().createNotification(
      content: NotificationContent(
          id: 30,
          channelKey: 'streakNotific',
          title: "$name $emoji",
          body: "Save the Streak, its $hour:$minute"),
      schedule: NotificationInterval(
        // hour: 6,
        // minute: 30,
        interval: 86400,
        allowWhileIdle: true,
        repeats: true,
        timeZone: AwesomeNotifications.localTimeZoneIdentifier,
      ));
}
```

At a Specific Time I Want to Thow-up Notifications, let's say, 6:30, every day, How can I use this?
Guide me the best. as I am not seeing Potential in Interval.

Thanks, Advance. 
❤️

**Comment by rafaelsetragni** [comment]
Use `NotificationCalendar` instead

**Comment by madd-project** [comment]
@rafaelsetragni 💡 
will It Repeat & Flare-Up Daily, at the same time.

**Comment by madd-project** [comment]
![Yellow and Red Kiddie Lion Birthday Postcard](https://user-images.githubusercontent.com/64954854/121775137-689a9100-cba3-11eb-9758-61a6427d41ee.png)

### Thank You For Completing the 100 Issues Mark, 
@rafaelsetragni

**Comment by rafaelsetragni** [comment]
![image](https://user-images.githubusercontent.com/40064496/121783018-f5812280-cb82-11eb-9b9a-4b4b8d01dab7.png)
kkkk Thanks!

**Comment by kam-ox** [comment]
really, how to make notifications show up at a given time every day

**Comment by rafaelsetragni** [comment]
```Dart

AwesomeNotifications().createNotification(

      content: NotificationContent(

          id: 30,

          channelKey: 'streakNotific',
           title: "$name $emoji",

          body: "Save the Streak, its $hour:$minute"),

      schedule: NotificationCalendar(

        hour: 6,
 
        minute: 30,

        second: 0,

        allowWhileIdle: true,
 
        repeats: true,

        timeZone: AwesomeNotifications.localTimeZoneIdentifier,

    ));

}

```

**Comment by phamquoctrongnta** [comment]
@rafaelsetragni 
What about weekly and monthly?
Can I do it?
Thank you so much.

**Comment by phamquoctrongnta** [comment]
@rafaelsetragni 
How about `weekly` and `monthly`?
In my case, current is 2024/06/07 (GMT +7) , I want to set schedule to display notification on:
- 11:20 AM every Monday (start from 2024/06/10).
- 17:00 10th of every month (start from 2024/09/10).
How do I implement this?
