### ISSUE TITLE
[iOS] actionStream not working with Scheduled Notification when app is in terminated state.

### ISSUE THREAD

**Issue by MaheshKumarM-SCE** [rafaelsetragni/awesome_notifications#200]
Hi, I had scheduled and checked for notifications in iOS. And I found the issue in navigating to page after tapping on the notification.
In Android, this is working fine - my app opened and navigated to correct page. 

I scheduled the notification like more than 5 minutes from current time, notification is shown along with the buttons even if the app is foreground, background or terminated. After scheduling the notification, I closed my app and after I got the notification and after tapping the notification or the buttons , my app opened and didn't take me to the correct page. I tried to check and I found displayedStream is successful but actionStream is not working.

I added my code for Initialize and scheduling below.. Please comment if I'm missing or doing anything wrong.
 AwesomeNotifications().initialize(null, [
    NotificationChannel(
      channelKey: 'basic_channel',
      channelName: 'Basic notifications',
      channelDescription: 'Notification channel for basic tests',
      importance: NotificationImportance.High,
      defaultColor: Color(0xFF9D50DD),
      ledColor: Colors.white,
    )
  ]);

AwesomeNotifications().createNotification(      
content: NotificationContent(          
id: id,          
channelKey: 'basic_channel',          
title: 'Fitness Alert',          
body: '30-minute walk is good for health',          
payload: {'uuid': 'user-profile-uuid'}),      
schedule: NotificationCalendar(          
timeZone: await AwesomeNotifications().getLocalTimeZoneIdentifier(),          
hour: scheduleDateTime.hour,          
minute: scheduleDateTime.minute,          
second: 0,          
allowWhileIdle: true,          
repeats: true),      
actionButtons: [        
NotificationActionButton(            
key: 'NOW',            
label: 'Okay',            
enabled: true,            
buttonType: ActionButtonType.Default),        
NotificationActionButton(            
key: 'LATER',            
label: 'will do it later',            
enabled: true,            
buttonType: ActionButtonType.Default)     
 ]);

**Comment by rafaelsetragni** [comment]
Can i ask you something? Are you creating a scheduled notification for more than 5 minutes and after that going to system settings and changing it manually on the system settings, to not really wait for 5 minutes?

And how are you doing these tests? With a real phone? What platform? And what is your current time zone?

**Comment by MaheshKumarM-SCE** [comment]
Yes sure.. ask me anything.. 

I created the scheduled Notification for more than 5 minutes and I checked by both a) waiting for the scheduled time  
and b) Changing the Device time to not really wait for 5 minutes. I checked in real device - iphone 11. For Android, 

After scheduling the notification, I closed the App, swiped the app from App Switcher. After receiving the notification, I tapped and checked - displayStream is working fine but actionStream is not working. so that app is not navigated to the corresponding page.  

I checked and there was no error messages in the log.

**Comment by JobMoll** [comment]
> Yes sure.. ask me anything..
> 
> I created the scheduled Notification for more than 5 minutes and I checked by both a) waiting for the scheduled time
> and b) Changing the Device time to not really wait for 5 minutes. I checked in real device - iphone 11. For Android, everything is working fine.
> 
> After scheduling the notification, I closed the App, swiped the app from App Switcher. After receiving the notification, I tapped and checked - displayStream is working fine but actionStream is not working. so that app is not navigated to the corresponding page.
> 
> I checked and there was no error messages in the log.

Hey,

Did you find a solution for this? I am having the exact same issue...

**Comment by red-star25** [comment]
Same issue

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
