### ISSUE TITLE
Inconsistent information about supported platforms

### ISSUE THREAD

**Issue by j-vasil** [rafaelsetragni/awesome_notifications#201]
On the [pub.dev page](https://pub.dev/packages/awesome_notifications) for this package, the compatibility information right below the publish date is

`FLUTTER | ANDROID IOS`

But the 1st and 6th bullets under Features are

> - Create Local Notifications on Android, iOS and **Web** using Flutter
> - Include **Web** support

I'm hoping that the Feature description is correct.  If so, I suggest fixing the "platform" section so that users that are working on a web app don't pass this package by without examining it (as I almost did!).

**Comment by rafaelsetragni** [comment]
This plug-in is still in development and will support web platform soon. For now we are finishing Android and iOS. And there is a banner on beginning warning about it.

And every plugin under version 1.0.0 is considered in development stage.

The web support is not so far from being supported. There is source codes already implemented, but not finished. Currently im finishing Android and iOS first to finally enable web support.

Case you wish to, you are welcome to implement it. This is a open source project and every help is welcome.
