### ISSUE TITLE
💡 What Technologies `awesome_notifications` use for Scheduling and showing the Notifications even the app is Killed?

### ISSUE THREAD

**Issue by madd-project** [rafaelsetragni/awesome_notifications#202]
Actually, I had a,
**Question**
That how The `awesome_notifications` senses the app is killed and even the app is killed in the background it Shows up the notification, I am really astonished by the work.

If You could Explain. That would be fun, nope Really Fun

**Comment by rafaelsetragni** [comment]
The app lifecycle is captured taking in note some simple concepts from Object-oriented programming and the application lifecycle observers from Android and iOS.

A static class always starts loading at the same time than the main application. So a put a private static object to store that value, wich starts with `AppKilled` state. After that, for each platform, i've implemented an respective lifecycle observer, that updates the lifecycle variable as soon the application reaches a state that i can considerer in `foreground` or `background` state.

So, if the app just receive a remote notification or creates a new one from some schedule, it never reachs that lifecycle points to became `foreground` or `background`, and the notification registers will receive `AppKilled` State. If the app already started, it will pass through the point considered `foreground` or `background`, and the next notifications will receive these respective values.

**Comment by madd-project** [comment]
Maybe, The Notification System is also Dependent upon some packages, for picking and playing up with the background and foreground, like I have seen the package is using cron, 

But It was really astonishing to me that how cron can Communicate with background, foreground, and even when the app is killed or stabbed 🔪 by the user.

**Comment by madd-project** [comment]
Do you know? 
I was just confused for `NotificationCalender`, I was going deeper into the concepts but not able to get that thing, 
except for understanding on my own, I decided to ask the creator of it.

Actually, I asked that because maybe there is something that I may be doing wrong, (absolutely wrong) maybe I should not close the app, or kill it or minimize it, I am saying it because, 

`NotificationCalender` just does not works, if I need to schedule daily repeating notifications, mm.. 
Like this, 

```
    NotificationChannel(
        // groupKey: "remainderNotf",
        channelKey: 'streakNotific',
        channelName: 'Streak Notifications',
        channelDescription:
            'Reminds you to check the streaks, so you never break them.',
        defaultColor: Color(0xffFBFB0E),
        ledColor: Color(0xffFBFB0E),
        importance: NotificationImportance.Max,
        defaultPrivacy: NotificationPrivacy.Public,
        soundSource: "resource://raw/res_alert_simple",
      ),

setStreakRemainderMethod(time, name, emoji, id, context) {
  int hour = int.parse(time.first);
  print(hour);

  int minute = int.parse(time.last);
  print(minute);

  AwesomeNotifications().isNotificationAllowed().then((isAllowed) {
    if (!isAllowed) {
      // Insert here your friendly dialog box before call the request method
      // This is very important to not harm the user experience
      AwesomeNotifications().requestPermissionToSendNotifications();
    }
  });

  AwesomeNotifications().createNotification(
      content: NotificationContent(
          id: id,
          channelKey: 'streakNotific',
          title: emoji == "null" ? "$name" : "$name $emoji",
          body: "Save the Streak, its $hour:$minute"),
      schedule: NotificationCalendar(
        hour: hour,
        minute: minute,
        // interval: 86400,
        //allowWhileIdle: true,

        timeZone: AwesomeNotifications.rootNativePath,
      ));


``` 

I had elaborated on the issue, but It was resolved, recently by you in #199 then It just stops automatically and not gives an output when i change the dates in my Phone. This is serious..

**Comment by rafaelsetragni** [comment]
What you meaning with "is not working"? "Is not working" could be many things.

And on iOS the notifications schedules are totally managed by iOS.

**Comment by madd-project** [comment]
"Is not Working" yeps, actually, I had not tried the thing in IOS yet.
But in Android it "is not working"
