### ISSUE TITLE
Pause repeating Notification on condition

### ISSUE THREAD

**Issue by roland-burke** [rafaelsetragni/awesome_notifications#205]
Hello,
first of all, i really like this package and i think it's very useful👍 
I have a use case where i want to repeateadly show a notification but based on a condition. For example every 60 minutes, but if it's between 10 pm and 8am don't show any notifications because they shouldn't bother you at night.

Is this possible? If yes could you please tell me how

best regards

**Comment by madd-project** [comment]
Can you show some code? @roland-burke . 

plus, Love you

**Comment by roland-burke** [comment]
In this method i check, wether the current time is outside a time range (e.g. when you are sleeping) but obviously it doesn't affect the execution of the timer. So i would really like to pause or do a check every time the timer executes.

```
static void updateNotification() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    await AwesomeNotifications().cancelAllSchedules();
    bool isReminderActive = prefs.getBool('reminder') ?? false;

    if (!isReminderActive) {
      log('ReminderNotification: turned off');
      return;
    }
    String localTimeZone =
        await AwesomeNotifications().getLocalTimeZoneIdentifier();

    int interval = prefs.getInt('interval') ?? 60;
    int startTimeHours = prefs.getInt('startTimeHours') ?? 20;
    int startTimeMinutes = prefs.getInt('startTimeMinutes') ?? 0;
    int endTimeHours = prefs.getInt('endTimeHours') ?? 8;
    int endTimeMinutes = prefs.getInt('endTimeMinutes') ?? 0;
    int cupSize = prefs.getInt('size') ?? 300;

    if (isCurrentTimeOfDayOutsideTimes(
        TimeOfDay.now(),
        TimeOfDay(hour: startTimeHours, minute: startTimeMinutes),
        TimeOfDay(hour: endTimeHours, minute: endTimeMinutes))) {
      AwesomeNotifications().createNotification(
          content: NotificationContent(
              id: 10,
              channelKey: 'basic_channel',
              title: 'Stay Hydrated!',
              body: 'notification.body'.tr(),
              payload: {'cupSize': '$cupSize'},),
          schedule: NotificationInterval(
              interval: interval, timeZone: localTimeZone, repeats: true, ));
      log('ReminderNotification: scheduled');
    }
  }
```

**Comment by madd-project** [comment]
One thing you can do is, 
In single-channel create the multiple contents that will ring, or ask users to when they want to sip water. (like 8 times a day or 20 times) (then ask when they all must ring) and set the remainder accordingly.
I hope it is understandable.



like One content will ring up in 5:00, 7:00 and 12:00, etc, 
Because what you are doing is a=only helped by `NotificationSchedule` where it takes an hour and minute when the notification will ring, 

You can dynamically set each hour interval (programmatically).
If this sounds good?
If not please let me know more

**Comment by roland-burke** [comment]
Thank you so much for this solution, i guess this should work now :)
In the UI the user can set 2 times and an interval and now in the code i calculate the moments when to set each schedule.
I have a submission due on 27.06 and this was one of the last things not working ! 👍 

```
TimeOfDay startTimeRemind = TimeOfDay(hour: endTimeSleepHours, minute: endTimeSleepMinutes);
    TimeOfDay endTimeRemind = TimeOfDay(hour: startTimeSleepHours, minute: startTimeSleepMinutes);
    TimeOfDay currentTime = startTimeRemind;

    List<TimeOfDay> reminderTimes = [];

    double numberOfReminds = getTimeOfDayRange(startTimeRemind, endTimeRemind) / (interval / 60);

    for (var i = 0; i <= numberOfReminds; i++) {
      reminderTimes.add(currentTime);
      currentTime.plusMinutes(interval);
    }

    reminderTimes.forEach((time) {
      AwesomeNotifications().createNotification(
          content: NotificationContent(
              id: 10,
              channelKey: 'basic_channel',
              title: 'Stay Hydrated!',
              body: 'notification.body'.tr(),
              payload: {'cupSize': '$cupSize'},),
          schedule: 
              NotificationCalendar(hour: time.hour, minute: time.minute, second: 0, millisecond: 0, timeZone: localTimeZone, repeats: true));
          log('ReminderNotification: scheduled');
    });
```

**Comment by madd-project** [comment]
Hey @roland-burke, :hehe: 
I just got some errors in understanding the Question a bit, Could you explain me that ^_^; 

That just got off, 
Thanks, This was the first help I am doing in, And loving it. 🥼

**Comment by roland-burke** [comment]
There was no question ^^ i just explained, how i designed the ui.

Your solution was perfekt 👍🏼

**Comment by madd-project** [comment]
Thanks alot. ❤️

**Comment by roland-burke** [comment]
Thank you :) here is the link to the App: https://github.com/roland-burke/Aquapido

**Comment by madd-project** [comment]
Did you got the APK?

**Comment by roland-burke** [comment]
Yes @madd-project , i created a release with the apk:
https://github.com/roland-burke/Aquapido/releases/tag/1.0.0
Here you go :)

**Comment by rafaelsetragni** [comment]
I gonna close this issue for now, since there is no more activity in 6 months. But you can reopen it, in case you judge necessary.
