### ISSUE TITLE
iOS: Image and action buttons not showing

### ISSUE THREAD

**Issue by imSanjaySoni** [rafaelsetragni/awesome_notifications#215]
iOS notification layout not showing image and action button. always poping default basic layout (only with title and body text), even after changing the layout type to   ```      notificationLayout: NotificationLayout.BigPicture ``` 
for Android no issue working as expected.

```json

{
    "content": {
      "id": 1291,
      "channelKey": "big_picture",
      "title": "Huston!\nThe eagle has landed!",
      "body":
          "A small step for a man, but a giant leap to Flutter's community!",
      "notificationLayout": "BigPicture",
      "largeIcon":
          "https://media.fstatic.com/kdNpUx4VBicwDuRBnhBrNmVsaKU=/full-fit-in/290x478/media/artists/avatar/2013/08/neil-i-armstrong_a39978.jpeg",
      "bigPicture": "https://www.dw.com/image/49519617_303.jpg",
      "showWhen": true,
      "autoCancel": true,
      "payload": {"type": "orders", "order_id": "259258"},
      "actionButtons": [
        {
          "key": "REPLY",
          "label": "Reply",
          "autoCancel": true,
          "buttonType": "InputField"
        },
        {"key": "ARCHIVE", "label": "Archive", "autoCancel": true}
      ],
    }
}

```

**Comment by samirasalah** [comment]
Any solution ?

**Comment by rafaelsetragni** [comment]
Guys, there is a simple example of how to do in the readme file, a complete video tutorial and a full example app in our repository. You need to expend a little time on it to learn how to use.

**Comment by rafaelsetragni** [comment]
> for me action buttons works on android, on ios only on banner notification but on notification window no button available...

This is how notifications are displayed on iOS.

**Comment by chris-jones-sq** [comment]
.Same issue. Action buttons show on Android but not iOS (I'm on 15.5).

> > for me action buttons works on android, on ios only on banner notification but on notification window no button available...
> 
> This is how notifications are displayed on iOS.

On iOS actions should show when you press and hold the notification. They aren't showing. Fine on Android.

**Comment by RulyAnggriawan** [comment]
similar issue.
bigPicture work fine on android but not with ios :(
it is not showing the picture

**Comment by rafaelsetragni** [comment]
Folks, when you say "it's not working", "it's working", "works fine" or any other variation, it doesn't bring any useful information about the problem you're having. It's not working it could be anything. Can you send me some print screens or detail a little more?

In addition, there is a complete example app in the github repository, showing how to implement each type of notification available.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!

**Comment by samirasalah** [comment]
This isn't a problém, in ios the button not displayed in notification, the
button displayed when you still click in notification (Just put your
fingers in notification 5 second)
