### ISSUE TITLE
How to set a function on action button

### ISSUE THREAD

**Issue by benyaminbeyzaie** [rafaelsetragni/awesome_notifications#223]
I show a notification with two action button on flutter app but I can't set any function to this button here is my code:
```
AwesomeNotifications().createNotification(
        content: NotificationContent(
          id: message.hashCode,
          channelKey: 'basic_channel',
          title: 'Simple Notification',
          body: 'Simple body',
          autoCancel: false,
        ),
        actionButtons: [
          NotificationActionButton(key: '0', label: 'Accept'),
          NotificationActionButton(key: '1', label: 'Reject')
        ]);
```
How can I call a function after user clicks on each button? Thanks!

**Comment by benyaminbeyzaie** [comment]
Ok I found the solution when app is open we can create a stream over the action events like that:
```
    AwesomeNotifications().actionStream.listen((event) {
      print('Recieved a event!');
      print(event.toMap().toString());
      // Do something
    });
```
but how can we handle actions when app is terminated and we show a notification by background message handler?

**Comment by jja08111** [comment]
It is next feature to run code when app is closed. (I really want this feature)
> - Add an option to choose if a notification action should bring the app to foreground or not.

**Comment by samerkh** [comment]
> Ok I found the solution when app is open we can create a stream over the action events like that:
> 
> ```
>     AwesomeNotifications().actionStream.listen((event) {
>       print('Recieved a event!');
>       print(event.toMap().toString());
>       // Do something
>     });
> ```
> 
> but how can we handle actions when app is terminated and we show a notification by background message handler?
if you are using remote notifications like fcm maybe you can call the listen in handleBackgroundMessage function

**Comment by baimamboukar** [comment]
> I show a notification with two action button on flutter app but I can't set any function to this button here is my code:
> 
> ```
> AwesomeNotifications().createNotification(
>         content: NotificationContent(
>           id: message.hashCode,
>           channelKey: 'basic_channel',
>           title: 'Simple Notification',
>           body: 'Simple body',
>           autoCancel: false,
>         ),
>         actionButtons: [
>           NotificationActionButton(key: '0', label: 'Accept'),
>           NotificationActionButton(key: '1', label: 'Reject')
>         ]);
> ```
> 
> How can I call a function after user clicks on each button? Thanks!

This method worked for me. It is pretty easy. Just call listen to **OnActionNotificationMethod**.
Add this when your app starts. NB: Make sure you have initialized your notif channel
   /// Use this method to detect when the user taps on a notification or action button
    AwesomeNotifications().setListeners(
        onActionNotificationMethod:    ReceivedAction receivedAction) async {

    // action code goes here
  }   );

**Comment by SaadAkram200** [comment]
Try this
 
  AwesomeNotifications().setListeners(
    onActionReceivedMethod: (receivedAction) async {
      if (receivedAction.buttonKeyPressed == 'accept') {
        print("call accepted");
       
      } else if (receivedAction.buttonKeyPressed == 'reject') {
        print("call rejected");
      }
    },
  );
