### ISSUE TITLE
Bad state: Stream has already been listened to.

### ISSUE THREAD

**Issue by MobileAppDevKtn** [rafaelsetragni/awesome_notifications#23]
Issue: I am calling notification in xyz.dart page I have made initialization correctly though when the notification displayed and when I clicked on it does not open the desired page but instead of any button click on the page it listening to that time and I am getting this issue.

> Bad state: Stream has already been listened to.

log:

`════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following StateError was thrown, building Builder:
Bad state: Stream has already been listened to.

The relevant error-causing widget was: 
  MaterialApp file:///D:/code/xyz/lib/main.dart:60:12
When the exception was thrown, this was the stack: 
#3      _xyzState.initState (package:xyz.dart:136:47)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
...     Normal element mounting (132 frames)
#137    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
...`

**Comment by rafaelsetragni** [comment]
This is not a error. Streams could be only listened for a single class.

There is another Setream type, called broadcast streams, which allows you to listen the same stream multiple times, but you could loose a notification stream, if the notification arives too fast after the initialization process.

[About Dart Streams (YouTube)](https://youtu.be/nQBpOIHE4eE)


You can create a new class, which reads the Awesome Stream as displayedStream and actionStream, and replicates the incoming data in an another Broadcast Stream. So your entire project will be able to listen the same stream, multiple times.

**Comment by MaheshPeri19** [comment]
> This is not a error. Streams can only be heard by a single object.
> 
> There is another Stream type, called broadcast streams, which allows you to listen the same stream multiple times. But be careful, because you can lose a notification stream, if the notification arives first than the first listener.
> 
> [About Dart Streams (YouTube)](https://youtu.be/nQBpOIHE4eE)
> 
> You can create a new class, which reads the Awesome Stream as displayedStream and actionStream, and replicates the incoming data in an another Broadcast Stream. So your entire project will be able to listen the same stream, multiple times.

I am having same issue. Can you please give us example code to solve this problem ?

**Comment by MaheshPeri19** [comment]
> This is not a error. Streams can only be heard by a single object.
> 
> There is another Stream type, called broadcast streams, which allows you to listen the same stream multiple times. But be careful, because you can lose a notification stream, if the notification arives first than the first listener.
> 
> [About Dart Streams (YouTube)](https://youtu.be/nQBpOIHE4eE)
> 
> You can create a new class, which reads the Awesome Stream as displayedStream and actionStream, and replicates the incoming data in an another Broadcast Stream. So your entire project will be able to listen the same stream, multiple times.

I am having the same issue. Can you please give some example code to solve this problem ?

I tried with below code, but action button callback is not working.

```
 AwesomeNotifications().actionStream.asBroadcastStream(
        onListen: (subscription) => subscription.onData((data) {
              print("data/asbroadcast =============== $data");
              processDefaultActionReceived(data);
            }));
```

**Comment by josaphatcampos** [comment]
> > This is not a error. Streams can only be heard by a single object.
> > There is another Stream type, called broadcast streams, which allows you to listen the same stream multiple times. But be careful, because you can lose a notification stream, if the notification arives first than the first listener.
> > [About Dart Streams (YouTube)](https://youtu.be/nQBpOIHE4eE)
> > You can create a new class, which reads the Awesome Stream as displayedStream and actionStream, and replicates the incoming data in an another Broadcast Stream. So your entire project will be able to listen the same stream, multiple times.
> 
> I am having the same issue. Can you please give some example code to solve this problem ?
> 
> I tried with below code, but action button callback is not working.
> 
> ```
>  AwesomeNotifications().actionStream.asBroadcastStream(
>         onListen: (subscription) => subscription.onData((data) {
>               print("data/asbroadcast =============== $data");
>               processDefaultActionReceived(data);
>             }));
> ```
> 
> Anyone please help me on this. i was stuck at this.

This works for me:

`try{
      AwesomeNotifications().actionStream.listen((receivedNotification) {
        Navigator.of(context).pushNamed(AppRoutes.OPERATIONADMIN,
            arguments: {'notifications': receivedNotification});
      });
    }catch(e){ //do something }`

**Comment by josaphatcampos** [comment]
> > This is not a error. Streams can only be heard by a single object.
> > There is another Stream type, called broadcast streams, which allows you to listen the same stream multiple times. But be careful, because you can lose a notification stream, if the notification arives first than the first listener.
> > [About Dart Streams (YouTube)](https://youtu.be/nQBpOIHE4eE)
> > You can create a new class, which reads the Awesome Stream as displayedStream and actionStream, and replicates the incoming data in an another Broadcast Stream. So your entire project will be able to listen the same stream, multiple times.
> 
> I am having the same issue. Can you please give some example code to solve this problem ?
> 
> I tried with below code, but action button callback is not working.
> 
> ```
>  AwesomeNotifications().actionStream.asBroadcastStream(
>         onListen: (subscription) => subscription.onData((data) {
>               print("data/asbroadcast =============== $data");
>               processDefaultActionReceived(data);
>             }));
> ```
> 
> Anyone please help me on this. i was stuck at this.

`try{

      AwesomeNotifications().actionStream.listen((receivedNotification) {

        Navigator.of(context).pushNamed(AppRoutes.OPERATIONADMIN,
            arguments: {'notifications': receivedNotification});

      });

    }catch(e){ //do something }`

**Comment by marcos-bah** [comment]
Use inside of Statefull at initState.
Its works for me.

```
@override
  void initState() {
    super.initState();
   AwesomeNotifications().actionStream.listen((receivedNotification) {
      print(receivedNotification);
      Navigator.of(context).pushNamed("/classpage");
 });
}
```

**Comment by Williano** [comment]
@josaphatcampos Thank you very much for this wonderful, easy to use and less code package.

This your answer fixed my problem

try{
      AwesomeNotifications().actionStream.listen((receivedNotification) {

        Navigator.of(context).pushNamed(AppRoutes.OPERATIONADMIN,
            arguments: {'notifications': receivedNotification});

      });

    }catch(e){ print(e); }

**Comment by ffaridi1** [comment]
I have an App where user can switch from receiving Push Notifications from 1 source to another (and drop the first source). I know it is not possible to simulteneously listen to 2 streams, but is it possible to cancel or unsubscribe from 1 stream and start the listen on another stream ? That will really help me. Thanks

**Comment by rafaelsetragni** [comment]
Yes, its possible. You need to keep a subscription reference from listen return method. With that subscription reference, you can call the method cancel() to unsubscribe your listen method.

But i designed this stream to be listen just once in the entire application. You can start to listen the stream as soon your app starts and do all the redirections from it. I recommend you to just subscribe once, but as i dont know the necessities from your app, ill let to you decide it.
