### ISSUE TITLE
IOS startup exception

### ISSUE THREAD

**Issue by xiejibiao** [rafaelsetragni/awesome_notifications#232]
After adding this plug-in, IOS can't start normally. I don't know if it conflicts with other plug-ins. How can I solve it.

awesome_notifications: ^0.0.5+5

`
flutter doctor:

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.3 20E232 darwin-x64, locale zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] IntelliJ IDEA Ultimate Edition (version 2021.1.2)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.58.2)
[✓] Connected device (1 available)
    ! Error: iPhone is busy: Copying cache files from device. Xcode will continue when iPhone is finished. (code -10)

! Doctor found issues in 2 categories.
`

Launching lib/main_dev.dart on iPhone in debug mode...
lib/main_dev.dart:1
Automatically signing iOS for device deployment using specified development team in Xcode project: 44LQ6V9CTS
CocoaPods' output:
↳
      Preparing
    Analyzing dependencies
    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
    Finding Podfile changes
      A awesome_notifications
      - Flutter
      - connectivity
      - flutter_webview_plugin
      - fluwx
      - h5pay
      - install_apk_plugin
      - jpush_flutter
      - package_info
      - path_provider
      - permission_handler
      - qrcode
      - shared_preferences
      - url_launcher
      - video_player
      - wakelock
      - webview_flutter
    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Fetching podspec for `awesome_notifications` from `.symlinks/plugins/awesome_notifications/ios`
    -> Fetching podspec for `connectivity` from `.symlinks/plugins/connectivity/ios`
    -> Fetching podspec for `flutter_webview_plugin` from `.symlinks/plugins/flutter_webview_plugin/ios`
    -> Fetching podspec for `fluwx` from `.symlinks/plugins/fluwx/ios`
    -> Fetching podspec for `h5pay` from `.symlinks/plugins/h5pay/ios`
    -> Fetching podspec for `install_apk_plugin` from `.symlinks/plugins/install_apk_plugin/ios`
    -> Fetching podspec for `jpush_flutter` from `.symlinks/plugins/jpush_flutter/ios`
    -> Fetching podspec for `permission_handler` from `.symlinks/plugins/permission_handler/ios`
    -> Fetching podspec for `qrcode` from `.symlinks/plugins/qrcode/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
    -> Fetching podspec for `video_player` from `.symlinks/plugins/video_player/ios`
    -> Fetching podspec for `wakelock` from `.symlinks/plugins/wakelock/ios`
    -> Fetching podspec for `webview_flutter` from `.symlinks/plugins/webview_flutter/ios`
    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists! Returning local because checking is only perfomed in repo update
    [!] CocoaPods could not find compatible versions for pod "awesome_notifications":
      In Podfile:
        awesome_notifications (from `.symlinks/plugins/awesome_notifications/ios`)
    Specs satisfying the `awesome_notifications (from `.symlinks/plugins/awesome_notifications/ios`)` dependency were found, but they required a higher minimum deployment target.
    /Users/xiejibiao/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:328:in `raise_error_unless_state'
    /Users/xiejibiao/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:310:in `block in unwind_for_conflict'
<internal:kernel>:90:in `tap'
    /Users/xiejibiao/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:308:in `unwind_for_conflict'
    /Users/xiejibiao/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
    /Users/xiejibiao/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Users/xiejibiao/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Users/xiejibiao/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Users/xiejibiao/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:94:in `resolve'
    /Users/xiejibiao/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1074:in `block in resolve_dependencies'
    /Users/xiejibiao/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/xiejibiao/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
    /Users/xiejibiao/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
    /Users/xiejibiao/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
    /Users/xiejibiao/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
    /Users/xiejibiao/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
    /Users/xiejibiao/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
    /Users/xiejibiao/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
    /Users/xiejibiao/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
    /Users/xiejibiao/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Users/xiejibiao/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
    /Users/xiejibiao/.rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
    /Users/xiejibiao/.rvm/rubies/ruby-3.0.0/bin/pod:23:in `load'
    /Users/xiejibiao/.rvm/rubies/ruby-3.0.0/bin/pod:23:in `<main>'
    /Users/xiejibiao/.rvm/rubies/ruby-3.0.0/bin/ruby_executable_hooks:22:in `eval'
    /Users/xiejibiao/.rvm/rubies/ruby-3.0.0/bin/ruby_executable_hooks:22:in `<main>'
Exception: Error running pod install

**Comment by xiejibiao** [comment]
I try to upgrade the flutter SDK to 2.2.3, and then create a new project. I find that the problem still exists. I suspect it's a plug-in problem

**Comment by Letalus** [comment]
Does the example app work on your side with the correct configuration for iOS?

**Comment by AmbujaAK** [comment]
I am getting the same issue for ios.

**Comment by xiejibiao** [comment]
> I am getting the same issue for ios.

Brother, I haven't found a solution yet. If you find a solution, remember to remind me. Thank you very much

**Comment by JoeyTeng** [comment]
@xiejibiao @Letalus @AmbujaAK 

I think the issue is we need to bump up the minimum OS version, which should be > 10.0 as specified in `ios/.symlinks/plugins/awesome_notifications/iOS/awesome_notifications.podspec` line 18: `s.platform = :ios, '10.0'`

I'm not sure which step(s) is(are) unnecessary, but I did all of them so I just list them below for your reference.

## Using Xcode

1. Go to `Pods` (not `Runner` > `Pods`), select `PROJECT` > `Pods`, change `Deployment Target` to `10.0`.
2.  Go to `Runner` > `Flutter` > `AppFrameworkInfo.plist`, change `MinimumOSVersion` to `10.0`

## Use Editor

1. `ios/Podfile` change to

```
platform :ios, '10.0'
```

2. `ios/Flutter/AppFrameworkInfo.plist` change to 

```
	<key>MinimumOSVersion</key>
	<string>10.0</string>
```

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!

**Comment by rameshboyee-sayukth** [comment]
I am getting same issue.
