### ISSUE TITLE
How to tell if the app has been opened via notification ?

### ISSUE THREAD

**Issue by Sauvikk** [rafaelsetragni/awesome_notifications#238]
Basically, I want my app to be able to tell when it's opened normally and when it's opened via clicking a notification.

I know I can listen to the stream `AwesomeNotifications().actionStream`

So, would the below code be a proper way to handle this scenario or is there a better approach

```
AwesomeNotifications()
        .actionStream
        .timeout(const Duration(milliseconds: 100), onTimeout: (_) {
      // app didn't open through notification
    }).listen((event) {
      // app opened through notification
      _handleNotification(event);
    });
```

**Comment by rafaelsetragni** [comment]
```Dart
if(event.actionLifeCycle == NotificationLifeCycle.AppKilled){
      // The app was bring to foreground by an notification action
}
```

**Comment by Sauvikk** [comment]
Is there any way to find out before if the app was opened via notification before I start listening to the stream.

This is probably a unusual use case but I am trying to achieve something as follows:
If the app was opened through a notification, listen for the notification event and handle the notification first... then perform some tasks.
If the app was opened normally, perform the tasks and then start listening for notifications.

```
if (appOpenedViaNotification) {
      AwesomeNotifications().actionStream.listen((event) async {
        await _handleNotification(event);
        if (tasksNotPerformed) {
          performTask1();
          performTask2();
        }
      }
    } else {
      performTask1();
      performTask2();
      // start listening for notifications
      AwesomeNotifications().actionStream.listen((event) {
          _handleNotification(event);
      }
    }
```

**Comment by rafaelsetragni** [comment]
> 
> 
> Is there any way to find out if the app was opened via notification before I start listening to the stream.
> 
> This is probably a unusual use case but I am trying to achieve something as follows:
> If the app was opened through a notification, listen for the notification event and handle the notification first... then perform some tasks.
> If the app was opened normally, perform the tasks and then start listening for notifications.
> 
> ```
> if (appOpenedViaNotification) {
>       AwesomeNotifications().actionStream.listen((event) async {
>         await _handleNotification(event);
>         if (tasksNotPerformed) {
>           performTask1();
>           performTask2();
>         }
>       }
>     } else {
>       performTask1();
>       performTask2();
>       // start listening for notifications
>       AwesomeNotifications().actionStream.listen((event) {
>           _handleNotification(event);
>       }
>     }
> ```

```Dart
bool appOpenedViaNotification = false;
AwesomeNotifications().actionStream.listen((event) async {
    if(event.actionLifeCycle == NotificationLifeCycle.AppKilled){
         appOpenedViaNotification = true;
    }
   if (appOpenedViaNotification) {
        await _handleNotification(event);
        if (tasksNotPerformed) {
          performTask1();
          performTask2();
        }
      }
    } else {
      performTask1();
      performTask2();
    }
  }
```

**Comment by Sauvikk** [comment]
```
bool appOpenedViaNotification = false;
AwesomeNotifications().actionStream.listen((event) async {
   
   // As far as I understand, this portion of the code will never be executed until a notification is tapped
   //  so it won't be execute when the app is opened normally

    if(event.actionLifeCycle == NotificationLifeCycle.AppKilled){
         appOpenedViaNotification = true;
    }
   if (appOpenedViaNotification) {
        await _handleNotification(event);
        if (tasksNotPerformed) {
          performTask1();
          performTask2();
        }
    } else {
        performTask1();
        performTask2();
    }
  }

```

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
