### ISSUE TITLE
tag missing in code

### ISSUE THREAD

**Issue by puzzled17** [rafaelsetragni/awesome_notifications#252]
First of all it is a very good plugin,
but at https://pub.dev/packages/awesome_notifications/versions , versions are listed as 0.0.6+10 and 0.0.6+9 etc .

I could not find a way to go to 0.0.6+9

git log 
shows following

commit e0304592f4e470ea96a85b29b19c1c7242957f56 (HEAD -> master, origin/master, origin/HEAD)
Merge: 1cccfd3 1612925
Author: rafaelsetragni <40064496+rafaelsetragni@users.noreply.github.com>
Date:   Sat Jul 24 15:38:02 2021 -0300

    Merge pull request #235 from jja08111/master

    Fix `showWhen` typo in Definitions.java

commit 161292562c186aadbc0c471262d86c7a6bbb4e68
Author: Minseong Kim <57604817+jja08111@users.noreply.github.com>
Date:   Sun Jul 25 02:47:06 2021 +0900

    Fix typo in Definitions.java

commit 1cccfd38be49dce893685f329384f941826ec18e
Author: rafaelsetragni <rafaelsetra@gmail.com>
Date:   Sat Jul 24 10:42:07 2021 -0300

    Release of version 0.0.6+10

commit 9b70f8f42c0ef52d9b596f84a5956540c3b1da31
Merge: fa7277e c986153
Author: rafaelsetragni <40064496+rafaelsetragni@users.noreply.github.com>
Date:   Thu Jul 22 11:01:19 2021 -0300

    Merge pull request #220 from EPNW/master

    Added Android foreground service functionallity

commit fa7277e27fdf4377a9585edee60dcd22061c551b
Merge: 888c957 49390e1
Author: rafaelsetragni <40064496+rafaelsetragni@users.noreply.github.com>
Date:   Tue Jul 20 14:07:42 2021 -0300

    Merge pull request #233 from alcrus/master

    Guava '-android' should be used to avoid conflicts with other packages.

**Comment by rafaelsetragni** [comment]
commit https://github.com/rafaelsetragni/awesome_notifications/commit/888c957f306bd0234c5a808f872ed03569464762
Author: rafaelsetragni <40064496+rafaelsetragni@users.noreply.github.com>

    Release of version 0.0.6+9

**Comment by puzzled17** [comment]
Thanks, 0.0.6+9 is listed as on June 8th 2021, and 888c957 was committed on July 20. Thanks any way.
