### ISSUE TITLE
Initialize defaultIcon example using flutter asset?

### ISSUE THREAD

**Issue by AdamBridges** [rafaelsetragni/awesome_notifications#259]
Hello,

I am having a difficult time while trying to use my image assets from my assets directory under my project (Project -> Assets - > Images -> Icon) and am hoping someone can clarify with an example if this is a new issue or simply my misunderstanding. Here's what's being called:

```
Future<void> init() async {
    await AwesomeNotifications().initialize(
        'asset://images/logo_192x192',
        [
          NotificationChannel(
              channelKey: _dailyReminderKey,
              channelName: await AppLocalizations.delegate
                  .load(Locale("en"))
                  .then((value) => value.nc_checkin_reminder_name),
              channelDescription: await AppLocalizations.delegate
                  .load(Locale("en"))
                  .then((value) => value.nc_checkin_reminder_desc),
            importance: NotificationImportance.Max,
            defaultColor: Color(0x275DAD)
          ),
      ],
      debug: true
    );
  }
```

**pubspec.yaml**
```
flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/
```

**Resulting Error**
```
E/flutter ( 5344): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: 'package:awesome_notifications/src/awesome_notifications_core.dart': Failed assertion: line 169 pos 13: 'BitmapUtils().getMediaSource(defaultIcon!) == MediaSource.Resource': is not true.
```

Note that I've tried the following variations:
'assets://images/logo_192x192',
'asset://assets/images/logo_192x192',
'asset://images/logo_192x192.png',
'assets://images/logo_192x192.png',
'asset://assets/images/logo_192x192.png',
'assets://assets/images/logo_192x192',

So any insight would be greatly appreciated. Thanks!

**Comment by rafaelsetragni** [comment]
Unfortunately, it is impossible to use any other media type for icons and sounds than native resources. This is because the android and iOS native notification's methods only accept native references.

**Comment by AdamBridges** [comment]
I was already following the documentation you linked and thought I could based on this:

> Images can be defined using 4 prefix types:
> 
> **Asset: images access through Flutter asset method. Example: asset://path/to/image-asset.png**
> Network: images access through internet connection. Example: http(s)://url.com/to/image-asset.png
> File: images access through files stored on device. Example: file://path/to/image-asset.png
> Resource: images access through drawable native resources. On Android, those files are stored inside [project]/android/app/src/main/drawabe folder. Example: resource://drawable/res_image-asset.png
>
> OBS: Unfortunately, icons and sounds can be only resource media types.

However, I see now what the OBS disclaimer means now and this is just my misunderstanding. Sorry about that and thanks for clarifying. :)
