### ISSUE TITLE
Notification not working in release mode.

### ISSUE THREAD

**Issue by EngAlaa22** [rafaelsetragni/awesome_notifications#271]
the plugin keeps crashing in release mode throwing this exception:

PlatformException(createNewNotification, The notification channel 'key1' do not exist or is disabled, h.a.a.e.f.a: The notification channel 'ke
y1' do not exist or is disabled
I/flutter (15352):      at h.a.a.a.j(:4)
I/flutter (15352):      at h.a.a.a.z(:19)
I/flutter (15352):      at e.a.d.a.w.a(Unknown Source:17)
I/flutter (15352):      at io.flutter.embedding.engine.l.g.e(Unknown Source:25)
I/flutter (15352):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
I/flutter (15352):      at android.os.MessageQueue.nativePollOnce(Native Method)
I/flutter (15352):      at android.os.MessageQueue.next(MessageQueue.java:336)
I/flutter (15352):      at android.os.Looper.loop(Looper.java:174)
I/flutter (15352):      at android.app.ActivityThread.main(ActivityThread.java:7697)
I/flutter (15352):      at java.lang.reflect.Method.invoke(Native Method)
I/flutter (15352):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
I/flutter (15352):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/flutter (15352): , null)

**Comment by rafaelsetragni** [comment]
Try to uninstall the App from the device and reinstall it.

**Comment by EngAlaa22** [comment]
I've tried this for many times, still throwing same exception. any other suggestions?

**Comment by rafaelsetragni** [comment]
When you say crashing, you mean that the app suddely closes for no reason?

> 
> PlatformException(createNewNotification, The notification channel 'key1' do not exist or is disabled, h.a.a.e.f.a: The notification channel 'ke
> y1' do not exist or is disabled
> I/flutter (15352): at h.a.a.a.j(:4)
> I/flutter (15352): at h.a.a.a.z(:19)

This means you are trying to use a channel that is disabled or does not exist. Have you used the removeChannel method in any part of your application?

I'm available now if you want to have a quick meeting to fix this. Im very interesting to know what is going on.

**Comment by EngAlaa22** [comment]
thanks for replies, nope the app is working although when the notification is meant to be showed, it throws that exception.  you are saying now that maybe i'm using a channel that is disabled or doesn't exist? so how should i know? I mean, in the code i just give the channel parameters a name and a key to use them later on, should I be doing something at first? am i missing something?

**Comment by rafaelsetragni** [comment]
Im coming back in 30 min. We can make a meeting call to inspect what's going on with your app. I will help you on it.

**Comment by PoeMcMoe** [comment]
Experiencing same problem

**Comment by sanjayvramani** [comment]
Yes , it solved the issue. Thank you for your support.

**Comment by sanjayvramani** [comment]
reinstalled flutter and check it.

**Comment by Mohsin0344** [comment]
minifyEnable false
shrinkResources false
It worked for me
