### ISSUE TITLE
Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present

### ISSUE THREAD

**Issue by Orbi360** [rafaelsetragni/awesome_notifications#277]
Now Android 12 is out and plugin doesn't have support for it and doesn't build as it doesn't have directive exported in manifest. Need to add it so plugin will build.
```
build\app\outputs\flutter-apk\app.apk: Failure [INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl347578671.tmp/base.apk (at Binary XML file line #321): me.carda.awesome_notifications.notifications.broadcastReceivers.RefreshNotificationBootReceiver: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present]
Error launching application on sdk gphone64 x86 64.
```

**Comment by rafaelsetragni** [comment]
I dont have any way to test Android 10+ versions on simulator because im getting BSOD on my machine. But ill try to fix it following this error message that you send to me.

**Comment by JSBmanD** [comment]
@rafaelsetragni I've fixed that by editing manifest. I think we need some confirmations from other people that everything works well.
