### ISSUE TITLE
Multiline Body?

### ISSUE THREAD

**Issue by tomassasovsky** [rafaelsetragni/awesome_notifications#281]
I am currently using this package, but I see the body is just one line, no matter what i do.
Is there any way of changing this so that i can display a multiline (text) body?

**Comment by rafaelsetragni** [comment]
Try to use HTML tags in your notification body and title.

**Comment by AhemadAbbasVagh** [comment]
I can see it's working for all the android devices but not working in the samsung devices. So any solution for that?
