### ISSUE TITLE
work in debug, not in release

### ISSUE THREAD

**Issue by g0coders** [rafaelsetragni/awesome_notifications#283]
when the debug notification appears, but when I build the apk and I test the notification doesn't appear

**Comment by g0coders** [comment]
done i'm add in app/build.gradle in buildTypes :

 buildTypes {
        release {
            shrinkResources false
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

and then run flutter build apk --no-sound-null-safety --no-shrink --release

**Comment by rafaelsetragni** [comment]
> 
> 
> done i'm add in app/build.gradle in buildTypes :
> 
> buildTypes {
> release {
> shrinkResources false
> minifyEnabled false
> signingConfig signingConfigs.release
> }
> }
> 
> and then run flutter build apk --no-sound-null-safety --no-shrink --release

**No!** This is dangerous because expose your App to **reverse engenering**.

You need to protect the resource files (image and audio) that you use on notifications with the tag `res_` before the file name, as specified on the README page.
