### ISSUE TITLE
App discarding/deleting all scheduled notifications once it is terminated.

### ISSUE THREAD

**Issue by arpit24sahu** [rafaelsetragni/awesome_notifications#285]
When I schedule a notification, it is working fine when app is in foreground, or when app is in background.
But when I tried to test if it works when app is terminated, it did not. 
On further debugging, I found that the app is discarding all the scheduled notifications once it is terminating. So when I reopen the app, I see no scheduled notification there.
I have re-checked and cross-verified all the configuration steps. 
This problem occurred with Local Notifications. I am not using FCM in my project.

**Comment by arpit24sahu** [comment]
Can there be something I am missing which is making the Scheduled Notifications disappear on App termination?
(I am sure I am not calling the function to cancel Scheduled Notifications anywhere).
Can the package flutter_local_notification be interferring with the package awesome_notifications?

**Comment by rafaelsetragni** [comment]
I gonna check whats happening. But just for curiosity, why do you use flutter_local_notifications combined with awesome_notifications? There is some feature missing on awesome?

**Comment by arpit24sahu** [comment]
Hi, Sorry for the late response.
I was trying various ways to implement scheduled notifications, so I implemented flutter_local_notifications first, and then implemented awesome_notifications. Although, now I have removed flutter_local_notifications, but still I am not able to retain scheduled notifications once the app is terminated.
For now, I have only checked the issue in Android Platform. Can't verify it for iOS.
Can you think of some thing that might me causing this issue?

Thanks.

**Comment by rafaelsetragni** [comment]
Lets schedule an hour to talk about your implementation and discovery whats going on. On the new README, on github, there is a Discord chat available to talk. If you have some time, go at there and we discuss about it.

**Comment by arpit24sahu** [comment]
Hi, 
I am sorry, I can't find a reference to your Discord account on your README.
So I have attached my code and a demo of the issue I am facing.

In the video, I have created 3 buttons.
- "Permissions" button asks for permission if there isn't. I have ensured that the app has permission to display notification.
- "Make Scheduled Notification" button creates a Scheduled Notification for a distant future.
- "Scheduled Notif" button lists the scheduled notifications.

As displayed in the video, the Scheduled Notifications are retained when the app is minimized, but they are deleted once the app is terminated.

In the code, I haven't made any other changes regarding awesome_notifications package, apart from adding the package in pubspec.yaml file, and making the changes in main.dart file. 

Please help me through this.

Thanks

[AwesomeNotifMainDotDart.txt](https://github.com/rafaelsetragni/awesome_notifications/files/7269734/AwesomeNotifMainDotDart.txt

https://user-images.githubusercontent.com/66864322/135677343-6c7cb602-f240-43d5-9887-4f9730d24564.mp4

)

**Comment by rafaelsetragni** [comment]
Have this issue solved with 0.0.6+11 version @itsdani121 ?

**Comment by rafaelsetragni** [comment]
I've added Crontab schedules on version 0.6.14, but unfortunately only for Android. Maybe it can solve your problem.

**Comment by ffaridi1** [comment]
I am also facing exact same issue with version 0.6.19 . I used AlarmManager to delay the firing of notification based on alarm delay. If the App runs in foreground and even background I get the notification , but as soon as I terminate the App, I don't get any notification. Please help. Thanks

**Comment by itsdani121** [comment]
The issue is when app destroy the backend app remove from cache so alarm
manager did not get app context

**Comment by rafaelsetragni** [comment]
> I am also facing exact same issue with version 0.6.19 . I used AlarmManager to delay the firing of notification based on alarm delay. If the App runs in foreground and even background I get the notification , but as soon as I terminate the App, I don't get any notification. Please help. Thanks

I think that your use of Alarm Manager is unnecessary, since the notification can be scheduled using the schedule parameter.

**Comment by itsdani121** [comment]
after the schedule when the app is destroyed you can't do anything but
the response does not work.

**Comment by rafaelsetragni** [comment]
> Hi, I am sorry, I can't find a reference to your Discord account on your README. So I have attached my code and a demo of the issue I am facing.
> 
> In the video, I have created 3 buttons.
> 
>     * "Permissions" button asks for permission if there isn't. I have ensured that the app has permission to display notification.
> 
>     * "Make Scheduled Notification" button creates a Scheduled Notification for a distant future.
> 
>     * "Scheduled Notif" button lists the scheduled notifications.
> 
> 
> As displayed in the video, the Scheduled Notifications are retained when the app is minimized, but they are deleted once the app is terminated.
> 
> In the code, I haven't made any other changes regarding awesome_notifications package, apart from adding the package in pubspec.yaml file, and making the changes in main.dart file.
> 
> Please help me through this.
> 
> Thanks
> 
> [AwesomeNotifMainDotDart.txt](https://github.com/rafaelsetragni/awesome_notifications/files/7269734/AwesomeNotifMainDotDart.txt
> awesomeNotifScreenRecord.1.mp4
> 
> )

Dani, I tested the version 0.6.19 with this example and it scheduled perfectly.
I've shared this example on github so you can clone and test it yourself:

https://github.com/rafaelsetragni/issue_285

**Comment by itsdani121** [comment]
Thanks, I'll take a look.

**Comment by itsdani121** [comment]
I saw your code but the issue is data came from API even app close or
destroyed data came from API or SQLite then show notification suppose a
list of string of time came from API which i save in SQLite then i get data
from SQLite and match time with current data time if matched
notification triggered otherwise not etc time =['10:11', '11:15'], etc. so
at 11 time app destroyed but when 11:15 came time-matched notification
called

**Comment by rafaelsetragni** [comment]
If i understood what you said, you can try to use Android Notification CronTab to create a list of schedules.

**Comment by itsdani121** [comment]
can you explain little bit about this

**Comment by rafaelsetragni** [comment]
Take a look at: https://github.com/rafaelsetragni/awesome_notifications#notificationandroidcrontab-only-for-androidschedule-in-push-data---optional

**Comment by itsdani121** [comment]
Thanks, I'll take a look.

**Comment by ffaridi1** [comment]
> > I am also facing exact same issue with version 0.6.19 . I used AlarmManager to delay the firing of notification based on alarm delay. If the App runs in foreground and even background I get the notification , but as soon as I terminate the App, I don't get any notification. Please help. Thanks
> 
> I think that your use of AlarmManager is unnecessary to delay the notifications, since the notification can be scheduled using the schedule parameter.

Here is my usecase :

- My server maintaiins a list of Alarm times , these times can change anytime from server side
- App needs to sync with server every hour and based on refreshed times , it needs to reschedule notifications for whole day.

Thats why I need AlarmManager to sync periodically with the server. 
I would love to just use Notification schedules but I don't think there is such a functionality in Awesome Notifications which just invoke a Stream without showing a visual notification.

BTW. My issue has been fixed after I did 2 things:
1- Added a category: NotificationCategory.Service field in the NotificationContent
2- Removed the use of Isolate messaging and directly issue the Notification in the Alarm callback

Hope this will help someone here , and I will appreciate if you let me know about the 'true silent' notification feature I asked above?

**Comment by rafaelsetragni** [comment]
> Thats why I need AlarmManager to sync periodically with the server. I would love to just use Notification schedules but I don't think there is such a functionality in Awesome Notifications which just invoke a Stream without showing a visual notification.

![image](https://user-images.githubusercontent.com/40064496/145411391-ea9ad93b-f5eb-4cae-9422-81a97004a34c.png)
As you can see, if title and body is null or empty, the notification is condiered silent and is not displayed on status bar.

> 1- Added a category: NotificationCategory.Service field in the NotificationContent

Is already on live:
https://github.com/rafaelsetragni/awesome_notifications#notifications-category

**Comment by ffaridi1** [comment]
> > Thats why I need AlarmManager to sync periodically with the server. I would love to just use Notification schedules but I don't think there is such a functionality in Awesome Notifications which just invoke a Stream without showing a visual notification.
> 
> ![image](https://user-images.githubusercontent.com/40064496/145411391-ea9ad93b-f5eb-4cae-9422-81a97004a34c.png)
> 
> As you can see, if title and body is null or empty, the notification is condiered silent and is not displayed on status bar. Maybe if i implement a `displayOnTerminated` property, and remove the condition of ending if title and body is empty, it could help you.

Yes, this will help. I tried to make title and body empty but as mentioned in the flow, it only fired the notification once and ended. Not like Alaarm Manager where I get a repeated trigger. 
The biggest advantage of this silent notification method as compared to AlarmManager will be that I can use it as is on iOS devices, as AlarmManager doesnot work on iOS.

**Comment by rafaelsetragni** [comment]
In fact, Ive forgot about iOS. Once the application is terminated, i totally lost control over it. So, this way is impossible to implement displayOnTerminated.

The IOS team has always made some pretty bad decisions about offering the libraries to the developers. They think, with their arrogance, that they've figured out every possible way to create new apps, choosing when things happen or not, and ended up with a very limited and poor library , resulting in apps with fewer features.

**Comment by ffaridi1** [comment]
For Android, my flow works as expected even when the App is terminated 
1- Set an alarm for 1 hour using AlarmManager
2- When Alarm fires, sync the times with the server
3- Use new times to schedule the Notifications
This way even when the App is terminated I can get reminders through Awesome Notifications

For iOS I have written a Cloud function to send data only FCM Push Notifications every hour, with the hope that even if the App is terminated, they will swake the App, and the App will sync times with server and schedule Notifications.
Unfortumately, its just hit or miss, if the OS puts the App to "Depp Sleep" no matter what I push from server, App never wakes up and from that point, App gets out of sync with the server.

**Comment by itsdani121** [comment]
how time sync from server when app is terminated?

**Comment by ffaridi1** [comment]
> In fact, Ive forgot about iOS. Once the application is terminated, i totally lost control over it. So, this way is impossible to implement displayOnTerminated.
> 
> The IOS team has always made some pretty bad decisions about offering the libraries to the developers. They think, with their arrogance, that they've figured out every possible way to create new apps, choosing when things happen or not, and ended up with a very limited and poor library , resulting in apps with fewer features.

Can you remove the condition of ending if title and body are empty ? This will most likely solve my issue

**Comment by rafaelsetragni** [comment]
> > In fact, Ive forgot about iOS. Once the application is terminated, i totally lost control over it. So, this way is impossible to implement displayOnTerminated.
> > The IOS team has always made some pretty bad decisions about offering the libraries to the developers. They think, with their arrogance, that they've figured out every possible way to create new apps, choosing when things happen or not, and ended up with a very limited and poor library , resulting in apps with fewer features.
> 
> Can you remove the condition of ending if title and body are empty ? This will most likely solve my issue

So, this way is impossible to implement displayOnTerminated.
Yep, unfortunately it's impossible.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
