### ISSUE TITLE
Starting Foreground service from notification

### ISSUE THREAD

**Issue by prajwal27** [rafaelsetragni/awesome_notifications#288]
I need to create a custom notification, which starts the foreground service. However, by following this [link](https://github.com/rafaelsetragni/awesome_notifications#android-foreground-services), the notification is not customizable and doesn't open the app on tap.

**Comment by rafaelsetragni** [comment]
Sorry, but i couldn't reproduce your error.
I did a small test here and i was able to personalize the notification and bring the app to foreground with the tap.

![image](https://user-images.githubusercontent.com/40064496/134018994-820369fd-7f41-4734-9ad9-13194e0c5990.png)

Can you share with us here on GitHub a small example with this issue?

**Comment by prajwal27** [comment]
How do I make sure only certain notifications start the foreground service and not all? The document on starting foreground service from notification isn't that clear.

**Comment by rafaelsetragni** [comment]
All notifications created with `startForeground` is related to a foreground service.
All notifications created with `createNotification` is not related to a foreground service.

**Comment by prajwal27** [comment]
Do we need any external package for `startForeground` method?

**Comment by rafaelsetragni** [comment]
No. You just need to import the dart file:

```Dart
import 'package:awesome_notifications/android_foreground_service.dart';
```

And to call:


```Dart
    AndroidForegroundService.startForeground(
        content: NotificationContent(
          id: 42,
          body: 'Service is running!',
          title: 'Android Foreground Service',
          channelKey: 'simple_channel',
          bigPicture: 'asset://assets/images/android-bg-worker.jpg',
          notificationLayout: NotificationLayout.BigPicture,
        ),
        actionButtons: [
          NotificationActionButton(
              key: 'SHOW_SERVICE_DETAILS',
              label: 'Show details'
          )
        ]
    );
```

**Comment by prajwal27** [comment]
@rafaelsetragni  after I start the foreground, it says `MyApp isn't responsing` and it terminates. Any reason?

**Comment by rafaelsetragni** [comment]
Can you send me your LogCat?

**Comment by prajwal27** [comment]
![image](https://user-images.githubusercontent.com/31249460/134108318-bcfa9588-b05a-4969-98ce-958458bb95b5.png)

**Comment by prajwal27** [comment]
@rafaelsetragni  Yeah, it worked. I don't what the issue was, 
I removed all these properties from the channel and it worked.
```
importance: an.NotificationImportance.High,
locked: true,
playSound: false,
defaultPrivacy: an.NotificationPrivacy.Public
```

Also, I have another issue, I need to show notification and tap on a button from the lock screen. This notification is part of a audio call (hope you get the idea). So, Should I create a new issue for that?

**Comment by prajwal27** [comment]
I was using Xiaomi Redmi Note 5 Pro, the android version is 9 (Pie).
