### ISSUE TITLE
awesome_notifications only works in debug mode, in release mode the notification doesn't appear at all

### ISSUE THREAD

**Issue by naufalw** [rafaelsetragni/awesome_notifications#29]
Good Day, Sir.
I'm confused what happened to my application in release mode. For permissions, I've checked by printing the isAllowed variable that contains a boolean information for the permission (copy pasted from the example) , and the result is true. but still, there is no notification at all. But in debug mode, the notifications appear

**Comment by workflow2** [comment]
Wow I was going to write about the same identical issue!!! same here in debug works perfectly but in release nothing. I have tried cron and normal notifications... nothing to do.

**Comment by rafaelsetragni** [comment]
In what platform are you running? Android or iOS? And which OS version?
Here i tested with debug and release mode for both platforms.

**Comment by naufalw** [comment]
> In what platform are you running? Android or iOS? And which OS version?
> Here i tested with debug and release mode for both platforms. The notifications are allowed in configuration page?
> 
> Try to get the log messages using "LogCat" on Android Studio:
> https://developer.android.com/studio/command-line/logcat?hl=pt-br

Hello, thanks for your answer sir.
Im Using Android 10, and 11 
none of them are working

Here is my logcat in debug mode 
[Debug Mode Emulator.txt](https://github.com/rafaelsetragni/awesome_notifications/files/5504144/Debug.Mode.Emulator.txt)

in release mode (emulator)
[Release Mode Emulator.txt](https://github.com/rafaelsetragni/awesome_notifications/files/5504145/Release.Mode.Emulator.txt)

in release mode (Physical Device (Android 10))
[Release Mode Physical Device.txt](https://github.com/rafaelsetragni/awesome_notifications/files/5504146/Release.Mode.Physical.Device.txt)

my vscode debug console log
https://pastebin.com/sbdXDF6b

**Comment by rafaelsetragni** [comment]
Your app calls `BestClock` and the notifications that do not shows are the scheduled notifications? There is a lot of NTP exceptions throwed by the AlarmManager.

Send me here your `CreateNotification` calling source code.

**Comment by workflow2** [comment]
> Your app calls `BestClock` and the notifications that do not shows are the scheduled notifications? There is a lot of NTP exceptions throwed by the AlarmManager.
> 
> Send me here your `CreateNotification` calling source code.
> 
> **Edited**:
> I guess i got whats goin on. There is a firebase misconfiguration file.
> 
> `11-07 07:50:55.613 4517 4557 E flutter : [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(getFirebaseToken could not fetch instanceID, types and labels must be unique, java.lang.IllegalArgumentException: types and labels must be unique 11-07 07:50:55.613 4517 4557 E flutter : at h.a.a.d.b.a(Unknown Source:35) 11-07 07:50:55.613 4517 4557 E flutter : at h.a.a.d.b.a(Unknown Source:4) 11-07 07:50:55.613 4517 4557 E flutter : at h.a.a.f.i.a(Unknown Source:28) 11-07 07:50:55.613 4517 4557 E flutter : at h.a.a.f.i.a(Unknown Source:0) 11-07 07:50:55.613 4517 4557 E flutter : at h.a.a.e.g.g.a(Unknown Source:8) 11-07 07:50:55.613 4517 4557 E flutter : at h.a.a.e.g.c.a(Unknown Source:4) 11-07 07:50:55.613 4517 4557 E flutter : at h.a.a.a.b(Unknown Source:11) 11-07 07:50:55.613 4517 4557 E flutter : at h.a.a.a.a(Unknown Source:0) 11-07 07:50:55.613 4517 4557 E flutter : at h.a.a.a.j(Unknown Source:24) 11-07 07:50:55.613 4517 4557 E flutter : at h.a.a.a.a(Unknown Source:273) 11-07 07:50:55.613 4517 4557 E flutter : at e.a.c.a.i$a.a(Unknown Source:17) 11-07 07:50:55.613 4517 4557 E flutter : at io.flutter.embedding.engine.e.b.a(Unknown Source:57) 11-07 07:50:55.613 4517 4557 E flutter : at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4) 11-07 07:50:55.613 4517 4557 E flutter : at android.os.MessageQueue.nativePollOnce(Native Method) 11-07 07:50:55.613 4517 4557 E flutter : at android.os.MessageQueue.next(MessageQueue.java:336) 11-07 07:50:55.613 4517 4557 E flutter : at android.os.Looper.loop(Looper.java:181) 11-07 07:50:55.613 4517 4557 E flutter : at android.app.ActivityThread.main(ActivityThread.java:7519) 11-07 07:50:55.613 4517 4557 E flutter : at java.lang.reflect.Method.invoke(Native Method) 11-07 07:50:55.613 4517 4557 E flutter : at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 11-07 07:50:55.613 4517 4557 E flutter : at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995) 11-07 07:50:55.613 4517 4557 E flutter : , null) 11-07 07:50:55.613 4517 4557 E flutter : #0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582) 11-07 07:50:55.613 4517 4557 E flutter : #1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159) 11-07 07:50:55.613 4517 4557 E flutter : <asynchronous suspension> 11-07 07:50:55.613 4517 4557 E flutter : #2 AwesomeNotifications.initialize (package:awesome_notifications/src/awesome_notifications_core.dart:145)`
> 
> ...and after that, while you're trying to send a notification:
> 
> `PlatformException(Notifications are disabled, null, null, null)`
> 
> This exception is throwed when you trying to send a notification in a disable channel or if all the notifications are disabled.

Me i'm not using firebase at all... Can I use logcat with VS code?

**Comment by rafaelsetragni** [comment]
I dont know. Im using Android Studio for everything.

**Comment by workflow2** [comment]
I have updated and tried `flutter run --release` in this way the application works fine with notifications, but when i build the apk with `flutter build apk` it does not work... maybe i have to add some flags?

**Comment by rafaelsetragni** [comment]
In that case, I recommend that you send me your LogCat for analysis.

**Comment by rafaelsetragni** [comment]
Is your APK file signed?

**Comment by naufalw** [comment]
> WOW! I discovered the error!
> 
> The error "types and labels must be unique" is throwed inside the Google Json helper class called `RuntimeTypeAdapterFactory`. 
> when you try to declare two subtypes with the same name.
> 
> BUT if you don't provide a name, the `registerSubtype` method will automatically produce a name based on another Java common method called `type.getSimpleName()`.
> 
> The problem is when you build your app using compressing mode, which changes a lot your source to reduce the final APK size, including change your classes names by the standard "h.a.a.e.i.b", "h.a.a.e.i.c", "h.a.a.e.i.f.b", etc.
> 
> The simple name of the class  "h.a.a.e.i.f.b" is "b" and the simple name of the class "h.a.a.e.i.b" is also "b". So, is very easy to encounter two classes with the same name and the error occurs.
> 
> I gonna put this fix in the next release.

    Wow, nice sir!! I will really look forward to the update, sir. Because in my opinion, this is the simplest and easiest notification plugin for beginners. Goodluck :)

**Comment by workflow2** [comment]
Good! let me know when you'll release the new version! thanks!

**Comment by naufalw** [comment]
Nice....

**Comment by rafaelsetragni** [comment]
Maybe ill need to find another solution to store objects into data with json. And this could take some time to do.
But you guys can use this alternative for a while:

`flutter build apk --no-shrink`
`flutter install`

**Comment by rafaelsetragni** [comment]
Version 0.0.5 finally released!

But you gonna need to protect your native resources against minification inserting the prefix "res_" in your image or sound file names. You can see more about it [here in the README file](https://github.com/rafaelsetragni/awesome_notifications#media-source-types).

Also i simplified the iOS installation. Please, update it if you pretend to use iOS too.

Call me here if you continue with issues on this new version.

**Comment by naufalw** [comment]
> Version 0.0.5 finally released!
> 
> But you gonna need to protect your native resources against minification inserting the prefix "res_" in your image or sound file names. You can see more about it [here in the README file](https://github.com/rafaelsetragni/awesome_notifications#media-source-types).
> 
> Also i simplified the iOS installation. Please, update it if you pretend to use iOS too.
> 
> Call me here if you continue with issues on this new version.

Umm i sorry sir, i didn't understand. Is the res_ prefix used in every file in the res folder (android/app/src/main/res)?

**Comment by rafaelsetragni** [comment]
Yes. This is the only way to access native resource files with minification enabled. And minification and obfuscation are extremely important to protect your application from reverse engineering.

The other solution is to call flutter `build apk --no-shrink` or include the `shrinkResources false` statement within your Build.gradle file. But both "solutions" seriously undermine the security of your application.

**Comment by naufalw** [comment]
> Yes. This is the only way to access native resource files remotely with minification enabled. And minification and obfuscation are extremely important to protect your application from reverse engineering.
> 
> The other solution is to call flutter `build apk --no-shrink` or include the `shrinkResources false` statement within your Build.gradle file. But both "solutions" seriously undermine the security of your application.
> 
> But dont worry, its very simple. You just need to include the tag "res_" before the file names and the minification process will protect these assets from being obfuscated.

Okay sir, i now understood. And one more thing sir 😅, how can i disable the default toast notification?.

How about you @workflow2 ? Is your problem resolved now? If it does, i think i will close this issue😅

**Comment by workflow2** [comment]
> > Yes. This is the only way to access native resource files remotely with minification enabled. And minification and obfuscation are extremely important to protect your application from reverse engineering.
> > The other solution is to call flutter `build apk --no-shrink` or include the `shrinkResources false` statement within your Build.gradle file. But both "solutions" seriously undermine the security of your application.
> > But dont worry, its very simple. You just need to include the tag "res_" before the file names and the minification process will protect these assets from being obfuscated.
> 
> Okay sir, now i understood. And one more thing sir sweat_smile, how can i disable the default toast notification?.
> 
> How about you @workflow2 ? Is your problem resolved now? If it does, i think i will close this issuegrin

Thank you for asking, yes it works fine :smile:

**Comment by rafaelsetragni** [comment]
The toast notification was only used on example app, inside the listening streams.

For you to build your own application, youll only find small debug messages to visualy confirm the events. And they are not displayed in release modes.

I didnt built any option to disable these debug prints. Do you wanna disable then?

**Comment by naufalw** [comment]
> The toast notification was only used on example app, inside the listening streams.
> 
> For you to build your own application, youll only find small debug messages to visualy confirm the events. And they are not displayed in release modes.
> 
> I didnt built any option to disable these debug prints. Do you wanna disable then?

hmmm but in my app it still shows the toast confirmation sir, even in release mode.
i dont have any listener configured. should i ?

`AwesomeNotifications().createNotification(
      schedule: NotificationSchedule(
        crontabSchedule: waktu,
        allowWhileIdle: true,
      ),
      content: NotificationContent(
          id: Random().nextInt(200),
          channelKey: 'progress_channel',
          title: 'Subject Reminder',
          body: 'WARNING : $mapel in 10 minutes'))`

`AwesomeNotifications().initialize(
    'resource://drawable/app_logo',
    [
      NotificationChannel(
        channelKey: 'progress_channel',
        channelName: 'progress notifications',
        channelDescription: 'Notification channel for basic tests',
        defaultColor: Color(0xFF9D50DD),
        ledColor: Colors.white,
        enableVibration: true,
        playSound: true,
        vibrationPattern: mediumVibrationPattern,
        importance: NotificationImportance.High,
      ),
    ],
  );`

`AwesomeNotifications().displayedStream.listen((receivedNotification) {});`

Yes of course sir, i think it is more cleaner to disable them in my app

**Comment by rafaelsetragni** [comment]
This is odd, because i only used toast messages in the example app.
But there is no problem to take it off. There is no correlation between toast messages and the notification plugin.

**Comment by naufalw** [comment]
> This is odd, because i only used toast messages in the example app.
> But there is no problem to take it off. There is no correlation between toast messages and the notification plugin.

woops im sorry sir, i just realized that it was my fault  :)

**Comment by workflow2** [comment]
Thank you @rafaelsetragni for you work :+1:

**Comment by madd-project** [comment]
Hey i was Also Having some Trouble, with this, but the ntifications are now working great, I just took a look at the Example Folder, `main.dart` as a reference, there i saw, the Inititalisation should take place in main()..

So Check if you could, Use it in main()... 
Just Check Example file of the repo by @rafaelsetragni 's amazing and opensource package.. 

Love to the Package.. Thanks

**Comment by Vish88781** [comment]
Well for that you have to create a JSON file through firebase and I don't think your problem is related to that,  One piece of advice copy the example code of awesome notification then try to go with release mode. For unique Id exception, you should pass random int " int id =  Random().nextInt(2147483647);"

**Comment by gsshakil** [comment]
> Well for that you have to create a JSON file through firebase and I don't think your problem is related to that, One piece of advice copy the example code of awesome notification then try to go with release mode. For unique Id exception, you should pass random int " int id = Random().nextInt(2147483647);"

in example code of awesome notification id is set like this:

`id: -1, // -1 is replaced by a random number`

**Comment by gsshakil** [comment]
After solving the unique id issue, scheduled notification is working but not performing always. Some notification don't shows up but when app opens they appear at once. 

How to confirm that scheduled notification will perform on exact time and also show an Icon on status bar while background tasks/scheduled notifications is running, like in Clock app clock icon always show on status bar while alarm is schedule?

**Comment by gsshakil** [comment]
![Screenshot_2022-12-09-03-02-16-202_com miui home](https://user-images.githubusercontent.com/3165380/206569117-3e97637e-6c72-4c23-b603-82ad890588cf.jpg)
How to show this type of non-dismissible notification which has the action buttons to open app and refresh location along with a timer which displays remaining time of an upcoming event?

**Comment by dimi1985** [comment]
put @pragma('vm:entry-point') on top of import in main and also @pragma('vm:entry-point') in backrounf service if you have any
works like charm in production mode after this.
