### ISSUE TITLE
Notification not working in release mode

### ISSUE THREAD

**Issue by kcs-rahuljoshi** [rafaelsetragni/awesome_notifications#291]
Notification not working in release mode and in debug mode when the app is in the foreground than not working else working.

**Comment by rafaelsetragni** [comment]
Take a look at:

[https://github.com/rafaelsetragni/awesome_notifications/pull/196](https://github.com/rafaelsetragni/awesome_notifications/pull/196)
[https://github.com/rafaelsetragni/awesome_notifications#media-source-types](https://github.com/rafaelsetragni/awesome_notifications#media-source-types)
