### ISSUE TITLE
On background notification appear twice

### ISSUE THREAD

**Issue by JeanChristopheMobizel** [rafaelsetragni/awesome_notifications#292]
When app is in foreground notification works well (appear once with the good assets).

In background notification appear twice, one with the good assets, the other with default. Do you have an idea on why this is happening?

![notif](https://user-images.githubusercontent.com/44803127/134937637-1a0f779b-1a49-46f9-9c4d-3d7555e7840c.png)

**Comment by JeanChristopheMobizel** [comment]
> Are you using firebase_messaging?
> If yes, probably because firebase_messaging are creating its own notification in concurrency with awesome_notifications.
> 
> Im developing a new companion plugin to handle all firebase_messaging features pefectly integrated with awesome_notifications. And you can check the progress on our development branchs.



> Are you using firebase_messaging?
> If yes, probably because firebase_messaging are creating its own notification in concurrency with awesome_notifications.
> 
> Im developing a new companion plugin to handle all firebase_messaging features pefectly integrated with awesome_notifications. And you can check the progress on our development branchs.

Yes I'm using firebase messaging. Do you have any temporary fix?

Thank you very much.

**Comment by rafaelsetragni** [comment]
Ive tried by many ways to integrate perfectly firebase_messaging to achieve a more complex notification throught push notifications, with awesome_notifications and even other plugins, but its not possible to do it with flutter, and specialy make it works with the expected trustbility.

The plugin firebase_messaging decides by itself to create or not the notification when the application is in background (and even if your events will be track or not on analytics), and there is nothing that you can do about it using the official plugin.

Thats why im creating the companion plugin. To give the developers all the resources available to create push notifications, as i did on local notification with awesome_notification.

And its not possible to change it with what we have now. Belive me, i tried everything to make firebase_messaging works differently,  but is impossible. Or you use it the way it is or.... or you use it the way it is.

Or you wait for the new companion plugin and do whatever you want to. Finally.

**Comment by JeanChristopheMobizel** [comment]
Thank you for your answers

**Comment by JeanChristopheMobizel** [comment]
I found a small workaround by sending a data message (only) with title and body in the payload.

**Comment by rafaelsetragni** [comment]
> I found a small workaround by sending a data message (only) with title and body in the payload.

Unfortunately it will fail on iOS because of their background processing policies, and data only messages are delivered with low priority.

**Comment by scalz** [comment]
as a temporary workaround, you could maybe use the Eraser plugin, and delete the unwanted notification, right after awesome notification plugin processed it.

**Comment by surveshoeb** [comment]
@JeanChristopheMobizel try this and let me know this work's or not

```
{
    "to": "token",
    "notification": {
        "body": null, //This should be null
        "title": null, //This should be null
        "clickAction": "FLUTTER_NOTIFICATION_CLICK"
    },
    "data": {
        "body": "Set your notification body",
        "title": "Set your notification title",
    },
    "android": {
        "priority": "high"
    },
    "apns": {
        "payload": {
            "aps": {
                "contentAvailable": true
            }
        },
        "headers": {
            "apns-push-type": "background",
            "apns-priority": "5",
            "apns-topic": "your package"
        }
    }
}
```

**Comment by tuemaytinh1981** [comment]
> Are you using firebase_messaging? If yes, probably because firebase_messaging are creating its own notification in concurrency with awesome_notifications.
> 
> Im developing a new companion plugin to handle all firebase_messaging features pefectly integrated with awesome_notifications. And you can check the progress on our development branchs.

I look on the firebase message library:
[https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/example/lib/main.dart](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging/example/lib/main.dart)
Looks like there is a solution to override the default notification:

flutterLocalNotificationsPlugin = FlutterLocalNotificationsPlugin();

    /// Create an Android Notification Channel.
    ///
    /// We use this channel in the `AndroidManifest.xml` file to override the
    /// default FCM channel to enable heads up notifications.
    await flutterLocalNotificationsPlugin
        .resolvePlatformSpecificImplementation<
            AndroidFlutterLocalNotificationsPlugin>()
        ?.createNotificationChannel(channel);

You avoid the situation when the application in the background sends the notification twice.

**Comment by scalz** [comment]
Thx for your reply, I appreciate it.
> 
> 
> I've tried everything but the only way to do it correctly is through native code. Its more resource efficient and an more robust solution. That's why i quit to integrate this plugin with `firebase_messaging` and start to do my own message plugin, to perfectly integrate `awesome_notifications`.

Sounds really interesting, can't wait to try ^^

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
