### ISSUE TITLE
[IOS] After long press on the notification and the app freeze then crash in a few second

### ISSUE THREAD

**Issue by ralphvmo** [rafaelsetragni/awesome_notifications#299]
App is in the foreground, I got heads-up notification after that I long press on it and click on close icon to back to app. Then the app becomes freeze and can not  be used any more. A few second later, it crashes. @rafaelsetragni  Please help me. 
I print a text in listener of actionStream and I realize that it loops and print a lots. Can you help me fix it ?

**Comment by ralphvmo** [comment]
here is crash text from firebase crashlytics
Crashed: com.apple.main-thread
0  libsystem_malloc.dylib         0xebb2 nanov2_allocate_from_block + 17
1  libsystem_malloc.dylib         0xdfb7 nanov2_allocate + 130
2  libsystem_malloc.dylib         0xdee4 nanov2_malloc + 55
3  libsystem_malloc.dylib         0x129d0 _malloc_zone_malloc + 114
4  libicucore.A.dylib             0xafca5 ures_getNextResource + 690
5  libicucore.A.dylib             0x36fe ures_getByIndex + 238
6  libicucore.A.dylib             0x31ba ucurr_forLocale + 404
7  libicucore.A.dylib             0x148bce icu::number::impl::CurrencySymbols::getPluralName(icu::StandardPlural::Form, UErrorCode&) const + 220
8  libicucore.A.dylib             0x1519f1 icu::number::IntegerWidth::operator==(icu::number::IntegerWidth const&) const + 7105
9  libicucore.A.dylib             0x152535 icu::number::IntegerWidth::operator==(icu::number::IntegerWidth const&) const + 9989
10 libicucore.A.dylib             0x106fd6 icu::DecimalFormat::touch(UErrorCode&) + 142
11 libicucore.A.dylib             0x1085e6 icu::DecimalFormat::DecimalFormat(icu::DecimalFormat const&) + 200
12 libicucore.A.dylib             0x108a57 icu::DecimalFormat::clone() const + 49
13 libicucore.A.dylib             0x15f624 icu::NumberFormat::createInstance(icu::Locale const&, UNumberFormatStyle, UErrorCode&) + 96
14 libicucore.A.dylib             0xc304 icu::SimpleDateFormat::initialize(icu::Locale const&, UErrorCode&) + 432
15 libicucore.A.dylib             0xce47 icu::SimpleDateFormat::SimpleDateFormat(icu::Locale const&, UErrorCode&) + 359
16 libicucore.A.dylib             0x6e45 icu::DateFormat::create(icu::DateFormat::EStyle, icu::DateFormat::EStyle, icu::Locale const&) + 223
17 libicucore.A.dylib             0x6c57 udat_open + 393
18 CoreFoundation                 0x10341f __cficu_udat_open + 48
19 CoreFoundation                 0x37bb9 __ResetUDateFormat + 470
20 CoreFoundation                 0x37607 __CreateCFDateFormatter + 320
21 Foundation                     0x3df7b -[NSDateFormatter _regenerateFormatter] + 259
22 Foundation                     0x3ebdf -[NSDateFormatter stringForObjectValue:] + 135
23 Runner                         0xd8020 specialized static DateUtils.dateToString(_:timeZone:) + 37 (DateUtils.swift:37)
24 Runner                         0xe5265 specialized static NotificationBuilder.buildNotificationActionFromJson(jsonData:actionKey:userText:) + 1029 (<compiler-generated>:1029)
25 Runner                         0x104ebf SwiftAwesomeNotificationsPlugin.receiveAction(jsonData:actionKey:userText:) + 447 (SwiftAwesomeNotificationsPlugin.swift:447)
26 Runner                         0x109c3e specialized SwiftAwesomeNotificationsPlugin.userNotificationCenter(_:didReceive:withCompletionHandler:) + 670 (<compiler-generated>:670)
27 Runner                         0x103180 @objc SwiftAwesomeNotificationsPlugin.userNotificationCenter(_:didReceive:withCompletionHandler:) + 96
28 FirebaseMessaging              0x1706c FCMSwizzleDidReceiveNotificationResponseWithHandler + 599
29 Flutter                        0x1d16b -[FlutterPluginAppLifeCycleDelegate userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:] + 299
30 Runner                         0x109dd6 specialized SwiftAwesomeNotificationsPlugin.userNotificationCenter(_:didReceive:withCompletionHandler:) + 1078 (<compiler-generated>:1078)
31 Runner                         0x103180 @objc SwiftAwesomeNotificationsPlugin.userNotificationCenter(_:didReceive:withCompletionHandler:) + 96
32 FirebaseMessaging              0x1706c FCMSwizzleDidReceiveNotificationResponseWithHandler + 599
33 UIKitCore                      0xc11b3b -[FlutterPluginAppLifeCycleDelegate userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:] + 299
34 UIKitCore                      0x4e311 $s21awesome_notifications31SwiftAwesomeNotificationsPluginC22userNotificationCenter_10didReceive21withCompletionHandlerySo06UNUserhI0C_So22UNNotificationResponseCyyctF13$sIeyB_Ieg_TRIeyB_Tf1nncn_nTf4nnng_n + 1078
35 UIKitCore                      0x4f398 $s21awesome_notifications31SwiftAwesomeNotificationsPluginC22userNotificationCenter_10didReceive21withCompletionHandlerySo06UNUserhI0C_So22UNNotificationResponseCyyctFToTm + 96
36 UIKitCore                      0x6e4e8b FCMSwizzleDidReceiveNotificationResponseWithHandler + 599
37 FrontBoardServices             0x88c7 -[FlutterPluginAppLifeCycleDelegate userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:] + 299
38 FrontBoardServices             0x32149 $s21awesome_notifications31SwiftAwesomeNotificationsPluginC22userNotificationCenter_10didReceive21withCompletionHandlerySo06UNUserhI0C_So22UNNotificationResponseCyyctF13$sIeyB_Ieg_TRIeyB_Tf1nncn_nTf4nnng_n + 1078
39 FrontBoardServices             0x15ad5 $s21awesome_notifications31SwiftAwesomeNotificationsPluginC22userNotificationCenter_10didReceive21withCompletionHandlerySo06UNUserhI0C_So22UNNotificationResponseCyyctFToTm + 96
40 FrontBoardServices             0x32091 FCMSwizzleDidReceiveNotificationResponseWithHandler + 599
41 libdispatch.dylib              0x3508 -[FlutterPluginAppLifeCycleDelegate userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:] + 299
42 libdispatch.dylib              0x6052 $s21awesome_notifications31SwiftAwesomeNotificationsPluginC22userNotificationCenter_10didReceive21withCompletionHandlerySo06UNUserhI0C_So22UNNotificationResponseCyyctF13$sIeyB_Ieg_TRIeyB_Tf1nncn_nTf4nnng_n + 1078
43 FrontBoardServices             0x567a5 $s21awesome_notifications31SwiftAwesomeNotificationsPluginC22userNotificationCenter_10didReceive21withCompletionHandlerySo06UNUserhI0C_So22UNNotificationResponseCyyctFToTm + 96
44 FrontBoardServices             0x5648b FCMSwizzleDidReceiveNotificationResponseWithHandler + 599
45 FrontBoardServices             0x56950 -[FlutterPluginAppLifeCycleDelegate userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:] + 299
46 CoreFoundation                 0x8038a $s21awesome_notifications31SwiftAwesomeNotificationsPluginC22userNotificationCenter_10didReceive21withCompletionHandlerySo06UNUserhI0C_So22UNNotificationResponseCyyctF13$sIeyB_Ieg_TRIeyB_Tf1nncn_nTf4nnng_n + 1078
47 CoreFoundation                 0x80282 $s21awesome_notifications31SwiftAwesomeNotificationsPluginC22userNotificationCenter_10didReceive21withCompletionHandlerySo06UNUserhI0C_So22UNNotificationResponseCyyctFToTm + 96
48 CoreFoundation                 0x7f764 FCMSwizzleDidReceiveNotificationResponseWithHandler + 599
49 CoreFoundation                 0x79f2f -[FlutterPluginAppLifeCycleDelegate userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:] + 299
50 CoreFoundation                 0x796d6 $s21awesome_notifications31SwiftAwesomeNotificationsPluginC22userNotificationCenter_10didReceive21withCompletionHandlerySo06UNUserhI0C_So22UNNotificationResponseCyyctF13$sIeyB_Ieg_TRIeyB_Tf1nncn_nTf4nnng_n + 1078
51 GraphicsServices               0x3db3 $s21awesome_notifications31SwiftAwesomeNotificationsPluginC22userNotificationCenter_10didReceive21withCompletionHandlerySo06UNUserhI0C_So22UNNotificationResponseCyyctFToTm + 96
52 UIKitCore                      0xbf7cf7 FCMSwizzleDidReceiveNotificationResponseWithHandler + 599
53 UIKitCore                      0xbfcba8 -[FlutterPluginAppLifeCycleDelegate userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:] + 299
54 Runner                         0x817b main + 6 (AppDelegate.swift:6)
55 libdyld.dylib                  0x13e9 $s21awesome_notifications31SwiftAwesomeNotificationsPluginC22userNotificationCenter_10didReceive21withCompletionHandlerySo06UNUserhI0C_So22UNNotificationResponseCyyctFToTm + 96

**Comment by ralphvmo** [comment]
<img width="898" alt="Screen Shot 2021-10-13 at 19 22 59" src="https://user-images.githubusercontent.com/85177958/137131594-a441c9ab-3c93-43d0-af5a-85b3b9ed7619.png">

**Comment by JoGuribye** [comment]
I have the same problem, is there any solutions for this?
