### ISSUE TITLE
Existing NotificationChannel does not update on initialize or setChannel

### ISSUE THREAD

**Issue by Quijx** [rafaelsetragni/awesome_notifications#3]
When calling `AwesomeNotifications().initialize('blah', [existingChannel])` or `AwesomeNotifications().setChannel(existingChannel)`  on a `NotificationChannel` `existingChannel` that has a `channelKey` for which a `NotificationChannel` has been created before, the channel is not updated. However the documentation says, they should update existing channels.

Creating a new channel using both methods, as well as `removeChannel` do work though.

**Comment by rafaelsetragni** [comment]
Once a notification channel was created, the user has the ultimate control over it on the settings. As the developer, you can only change the channel's title and description or drop it.

If you want to recreate the channel, you have to use a different id or drop before the existing one.

**Comment by Quijx** [comment]
I actually only tried change the title and description and that didn't work.
Also I read the following here: https://developer.android.com/reference/android/app/NotificationManager#deleteNotificationChannel(java.lang.String)
> If you create a new channel with this same id, the deleted channel will be un-deleted with all of the same settings it had before it was deleted.

I don't know much about native android development, but could that mean, that the user settings are also preserved? So maybe in that case the channel could be fake-changed by internally removing and recreating it?

**Comment by rafaelsetragni** [comment]
I will test it for your soon. Im finishing the iOS code right now. After that (4-5 days) i promisse you i will check it out.

**Comment by rafaelsetragni** [comment]
Sorry for take so long to fix your problem. The iOS was pretty harder than i thought.
The channel update was fixed since version 0.0.4 and i create a exclusive test on example application for it.
