### ISSUE TITLE
awesome with fcm

### ISSUE THREAD

**Issue by gbbest15** [rafaelsetragni/awesome_notifications#301]
i am lost at some point, 
what should use to reply this:
this is working on fcm fine but i am trying to switch from fcm because of the reply like whatsApp
 1. FirebaseMessaging.onMessage.listen
 2. FirebaseMessaging.onMessageOpenedApp.listen
 3.  FirebaseMessaging.instance
        .getInitialMessage()
        .then((RemoteMessage message) {
   
    });
for awesome notification....

**Comment by cedvdb** [comment]
> But yes, they forgot to send some analytic data. And they already implemented the functions to send. I believe they implemented but forgot to use it.

That really sounds like an issue that should be filed in their repository

https://github.com/FirebaseExtended/flutterfire/issues
