### ISSUE TITLE
MediaButtonReceiver@exported value=(false)

### ISSUE THREAD

**Issue by Zelfapp** [rafaelsetragni/awesome_notifications#320]
Targeting SDK 31 (Android 12) with `awesome_notifications: ^0.6.14` I'm getting this error during run build.

> /home/nate/AndroidStudioProjects/wakie_up/android/app/src/debug/AndroidManifest.xml:65:13-37 
Error: Attribute receiver#androidx.media.session.MediaButtonReceiver@exported value=(false) from [:awesome_notifications] AndroidManifest.xml:65:13-37 is also present at [com.github.canardoux:flutter_sound_core:8.4.2] AndroidManifest.xml:18:13-36 value=(true).

I don't know if this `MediaButtonReceiver@exported` error is something you can resolve in awesome_notifications or an issue with [flutter_sound who also released an update for android:exported recently](https://flutter-sound.canardoux.xyz/changelog.html).

Again, I don't fully understand the `exported true` requirements for Android 12, but I suspect if you update awesome_notifications `Attribute receiver#androidx.media.session.MediaButtonReceiver@exported value=(false)` from `false` to `true` that this conflict would be resolved.

[Android 12 component exporting info](https://developer.android.com/about/versions/12/behavior-changes-12#exported).

**Comment by rafaelsetragni** [comment]
Yes, it seems like a conflict between both packages.
I gonna check if there is an implication in change from my part the export property to true.

**Comment by rafaelsetragni** [comment]
Try to go at this file and erase entirely the MediaButton receiver:

File location:

![image](https://user-images.githubusercontent.com/40064496/139819270-cee38112-4d6b-4471-9b05-9c1f0f1d35f9.png)

Lines to erase:

```xml
        <receiver
            android:name="androidx.media.session.MediaButtonReceiver"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MEDIA_BUTTON" />
            </intent-filter>
        </receiver>
```

**Comment by Zelfapp** [comment]
@rafaelsetragni removing these `receiver` lines for the MEDIA_BUTTON allowed me to upgrade both awesome_notifications and flutter_sound. Is that the fix or you just wanted me to provide feedback?

**Comment by rafaelsetragni** [comment]
Is that the fix. Thank you so much for your feedback!
I gonna release it today in 0.6.16.

**Comment by rafaelsetragni** [comment]
Version 0.6.16 released! Check if this solved your issue.

**Comment by Zelfapp** [comment]
awesome_notifications: ^0.6.16 resolves this issue. Thanks @rafaelsetragni.
