### ISSUE TITLE
Clic on Action Button doesn't dismiss the notification

### ISSUE THREAD

**Issue by scalz** [rafaelsetragni/awesome_notifications#321]
Hello,

I am testing your latest update (0.6.14), and when clicking on an action button, it doesn't dismiss the notification, and it recreates one, like a loop.
Is it how it should now work, and we have to dismiss it manually in code ? 

I tested to manually dismiss it in my app, in actionStream, but it doesn't always dismiss it, I'm trying to understand why.

I also tested your example, I just clicked on "Show notification with buttons" without dismissing it in code, and it's same behaviour, the notification always reappears. clicking on the button "Cancel notification" is working though.

Thank you for your help and your work :)

**Comment by rafaelsetragni** [comment]
Yes, you are right. There is a bug on the receiving process. I gonna send a fix for this today. Thank you so much for your help!

**Comment by rafaelsetragni** [comment]
Version 0.6.15 released! Please check for me if the problem is solved.

**Comment by scalz** [comment]
I just checked. And it's working well.

Thx you're too fast :)
