### ISSUE TITLE
defaultPrivacy: NotificationPrivacy.Public doesn't wake up the app when on lock screen.

### ISSUE THREAD

**Issue by ShruAlekha** [rafaelsetragni/awesome_notifications#322]
I am trying to implement alarm feature. So when the phone is on lock screen, I would like the scheduled alarm to wake up the app and show the notification that the user can tap. I saw a  similar question in the issues and the status said it's resolved. However, using the example app and adding the defaultPrivacy: NotificationPrivacy.Public with  NotificationImportance.High just shows the little icon and doesn't really wake up the screen that user can tap on. What am I missing here? Please help

**Comment by rafaelsetragni** [comment]
try to add this permission into your AndroidManifest.xml file:

```xml
<uses-permission android:name="android.permission.WAKE_LOCK" />
```

**Comment by ShruAlekha** [comment]
I downloaded the example app and edited the code which has the NotificationImportance.High. I added the above line to the Manifest.xml however, the behavior doesn't change. Still a little icon that shows up with screen lit. Adding the line above didn't make any difference.

**Comment by rafaelsetragni** [comment]
Im studding a different way to make this wake screen happen. I already achieve it locally, but I need to ensure if this is the correct way to do. Soon i will share with you a github branch to test if it is working as youre expecting.

**Comment by ShruAlekha** [comment]
Sounds good. Thanks

**Comment by rafaelsetragni** [comment]
Add this into your `pusbpec.yaml`:
```yaml
# awesome_notifications: ^0.6.16
awesome_notifications:
     git:
       url: https://github.com/rafaelsetragni/awesome_notifications.git
       ref: b44486c
```

**Comment by ShruAlekha** [comment]
Thanks so much. I will give it a try and let you know.

**Comment by rafaelsetragni** [comment]
I've updated with the final iOS source. Please, update your `pubspec.yaml`:

```yaml
# awesome_notifications: ^0.6.16
awesome_notifications:
     git:
       url: https://github.com/rafaelsetragni/awesome_notifications.git
       ref: 2010b2e
```

**Comment by ShruAlekha** [comment]
Thank you very much for the swift response and the branch. Really appreciate it! I have tested the branch and it definitely shows the notification and wakes up the lock screen, however it doesn't allow me to click on the notification until I open the lock. (Please see screenshot 1)
I am looking for either one of these since it is an alarm clock I am trying to implement. 
1. Either the notification overrides the lock screen and allows the user to click a button. 
2. Or redirects the user to a full screen Intent instead of the small notification. 
Please see screenshot 2 of the alarm clock notification on lock screen. This app is the one that comes bundled with OS
![Screenshot_2](https://user-images.githubusercontent.com/36599535/140441145-6760e25f-c49c-4cc2-aa43-2ff0edc3ec5a.png)
![Screenshot_1](https://user-images.githubusercontent.com/36599535/140441147-8a1c37ca-a35b-4571-b4ff-472e92f4bff5.png)
.

**Comment by ShruAlekha** [comment]
@rafaelsetragni is this even possible? I was thinking if there was a flag to set stating a full screen intent is needed, then if the app needs wake up screen (i.e the phone is in lock screen) then the notification can directly navigate to the action received screen instead of the small notification pop up. Not sure if that is a possible behavior.

**Comment by rafaelsetragni** [comment]
This full screen is not a notification, it is an activity created by the app.

And secondly, the fact that you need to unlock the screen to access the app makes sense, because it might otherwise be a security breach to be able to bypass the lock screen without being granted through notifications. Do you agree?

**Comment by ShruAlekha** [comment]
Well, the alarm doesn't unlock the screen. Its just that screen that overrides the lock screen. I agree if it unlocked the phone it would be a security breach but it doesn't. You can try the android alarm app. However, I guess even with the above feature from your package, I think it is still okay if the notification sound would last until the user clicks.  I am yet to try the custom sound.  
Also, the full screen feature is available in the flutter_local_notifications package. Just in case if you want to take a look?

**Comment by t1ooo** [comment]
Same issue. Adding this code to NotificationBuilder.java fix problem for me (Android only solution).

```java
builder.setFullScreenIntent(pendingIntent, true);
```

**Comment by rafaelsetragni** [comment]
You need to add the respective permission into manifest and, since 11 android version, explicity request the user consent.

**Comment by ShruAlekha** [comment]
@t1ooo thanks. @rafaelsetragni  shall we submit a PR request by making these changes ?

**Comment by rafaelsetragni** [comment]
Im already doing it, ive tried to implement the request, but this i couldnt. If you wanna help me to implement the permission request for full intent and schedule exact alarms, ill apreciate very very much.

**Comment by ShruAlekha** [comment]
Sure I can take a look at the permissions. Want me to comment or a PR? Wouldn't the schedule exact alarms that is already in code not work for full screen intents?

**Comment by rafaelsetragni** [comment]
Im still working on it, but you can check my progress [here](https://github.com/rafaelsetragni/awesome_notifications/tree/workmanager-migration)

**Comment by ShruAlekha** [comment]
@rafaelsetragni I was able to get the full screen intent to work with lock screen on android. There is one small issue though. 
1. Schedule alarm - stay on app - lock screen - alarm wakes up the lock screen, makes sound and I am ale to click on the notification. The phone is locked so no security breach, but I can just use this screen from the example app. 
2. Schedule alarm - navigate away from app - lock screen - alarm wakes up lock the screen and shows the full screen however **doesn't make the sound**. This is the issue I am still trying to figure out. 
However, I don't have Ios so haven't been able to try anything on it.

**Comment by rafaelsetragni** [comment]
To play sound on silent mode you need to use critical alerts for iOS and Do not Disturbe mode for Android. Ive tried to implement it, but without success yet.

**Comment by ShruAlekha** [comment]
This is not on silent mode. Just that when I navigate out of the app after setting the alarm and lock screen, it doesn't make noise. Shows full screen intent. I guess somehow this full screen intent introduced a bug.

**Comment by ShruAlekha** [comment]
@rafaelsetragni With the changes I made in the link above, everything is working as expected now on android. I was able to test using the example app you provided - "Schedule notification with local time zone" button.  If you would like me to send a PR, I can make the full screen as a variable that user can set. 
It's all on loud mode. I haven't tried the silent mode yet.

**Comment by rafaelsetragni** [comment]
Send me your pr to the workmanager branch here and ill merge them

**Comment by rafaelsetragni** [comment]
Yes. Now i saw your branch and these changes are already present on workmanager branch, but also the request permission is present, because on Android 11+ the full screen intent needs the explicity user conscent to work.

**Comment by ShruAlekha** [comment]
Yes I didn't add explicit permissions since I was trying whether it will work. I also haven't made full screen intent a variable that can be configured. I forked from the wakeup branch. Let me fork workmanager branch and see if I can help with it in that case.

**Comment by ShruAlekha** [comment]
I forked the workmanager branch and made a minor change. The full screen intent is working as expected. I have submitted a PR. @rafaelsetragni

**Comment by rafaelsetragni** [comment]
I did some improvements in code and in the readme file. Now th only thing "missing" is the request permission method. I mean "missing" because i did everything recommended by official Android documentation, but im still not getting any request prompting on screen.

**Comment by ShruAlekha** [comment]
@rafaelsetragni I have been trying this as well and it isn't showing up. I tried using a plugin called permission handler, it works well but it doesn't have permissions for wake lock, alarm or full screen. Please check [here](https://github.com/ShruAlekha/awesome_notifications/blob/workmanager-migration-permissions/example/lib/main.dart)

**Comment by rafaelsetragni** [comment]
For another permissions its working on my code as well. I changed the alert code to read storage and it pops up the request dialog as expected.

**Comment by ShruAlekha** [comment]
So what permission pop up are we missing?

**Comment by rafaelsetragni** [comment]
Yes! I did commit on the branch right now to share with you the current code that im working with.

https://github.com/rafaelsetragni/awesome_notifications/tree/workmanager-migration

**Comment by ShruAlekha** [comment]
Thanks. I was going to ask for that. Let me try and will let you know if I get something working.

**Comment by ShruAlekha** [comment]
When I switch the Read_STORAGE to SCHEDULE_EXTERNAL_ALARM, the Android 12 by default adds the permission. 
![image](https://user-images.githubusercontent.com/36599535/141665708-3b509251-e4bc-49dd-96b9-12439676237f.png)

**Comment by rafaelsetragni** [comment]
Yes, me too. But take a look at the alarm page. Ive put a shortlink button on the example app.

**Comment by ShruAlekha** [comment]
@rafaelsetragni Strange enough, the button is greyed out with everything in there as per the Android 12 spec. However, all alarms work as expected which means the permissions are there. I am not sure if this a bug with the emulator but unfortunately I don't have a device with Android 12 on it.

**Comment by rafaelsetragni** [comment]
Yes. Same with me. Im thinking in release this new version and fix something if necessary later.

**Comment by ShruAlekha** [comment]
Makes sense to me.

**Comment by rafaelsetragni** [comment]
Sorry, but i will take a little more time to release, because now i got how to sintetize the whole idea about permissions and channels in a single and simple approach. It will be way more easy to understand and to use.

**Comment by DevKhalyd** [comment]
Hello Guys. I've been reading your thread because I'm loooking for something like that: https://developer.android.com/training/notify-user/time-sensitive#kotlin . I can assume that you are working on it. Please let me know If I can help with something. Thanks. :D

**Comment by ShruAlekha** [comment]
@DevKhalyd The full screen intent is working as expected now, @rafaelsetragni is working on cleaning up the permissions after which he will merge the branch to master. You can use 
url: https://github.com/rafaelsetragni/awesome_notifications.git  ref: cfa29f5 to see the changes.

**Comment by Albertbol** [comment]
Hey, 
I guess it's related, I have Android 12 on a real device and notifications are not working. On IOS real device and android simulator it works perfectly.
I get this error:
```
D/FLTFireMsgReceiver(23285): broadcast received for message
W/System.err(23285): java.lang.IllegalArgumentException: com.shopamoji.app: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
W/System.err(23285): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
W/System.err(23285): 	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
W/System.err(23285): 	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
W/System.err(23285): 	at android.app.PendingIntent.getActivity(PendingIntent.java:444)
W/System.err(23285): 	at android.app.PendingIntent.getActivity(PendingIntent.java:408)
W/System.err(23285): 	at me.carda.awesome_notifications.notifications.NotificationBuilder.createNotification(NotificationBuilder.java:133)
W/System.err(23285): 	at me.carda.awesome_notifications.notifications.NotificationBuilder.createNotification(NotificationBuilder.java:103)
W/System.err(23285): 	at me.carda.awesome_notifications.notifications.NotificationSender.showNotification(NotificationSender.java:210)
W/System.err(23285): 	at me.carda.awesome_notifications.notifications.NotificationSender.doInBackground(NotificationSender.java:130)
W/System.err(23285): 	at me.carda.awesome_notifications.notifications.NotificationSender.doInBackground(NotificationSender.java:34)
W/System.err(23285): 	at android.os.AsyncTask$3.call(AsyncTask.java:394)
W/System.err(23285): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(23285): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
W/System.err(23285): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(23285): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(23285): 	at java.lang.Thread.run(Thread.java:920)
```
I tried to import:

> url: https://github.com/rafaelsetragni/awesome_notifications.git ref: cfa29f5 to see the changes.
But I get the same error.
Flutter 2.5.3, android manifest: minSdkVersion 23, targetSdkVersion 31

Thanks in advance,

**Comment by rafaelsetragni** [comment]
Version 0.6.18 released! 

Now notifications have categories and permissions are fully implemented, with permissions to increase schedule precision and features to wake up screen, and a lot more!

Please take a look and check for me if your issue is solved.

[0.6.18]

    Added Channel's Group feature for Android
    Added notification's category feature for Android
    Added fullScreenIntent permission and content option to allow to show notifications in full screen mode.
    Added PreciseAlarms permission and sheculde option to allow to show scheduled notifications with more precision.
    Added showPage methods to provide shortcuts to channel permissions page and alarm permission page.
    Added shouldShowRationale method for android to check if the requested permissions require user intervention to be enable.
    Added request permissions methods to demand the users permissions considered dangerous by the system.
    Permission's request methods refactored to enable a more modular and scalable evolution to comport future permissions for Android
    Documentation has been improved with the new permissions methods, channel's group, notification categories, fullScreenIntent and PreciseAlarms permissions

**Comment by Albertbol** [comment]
Hey , thanks for release.
But i am getting this error now:
```
/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.6.18/android/src/main/java/me/carda/awesome_notifications/AwesomeNotificationsPlugin.java:926: error: method references are not supported in -source 7
                    result::success);
                            ^
  (use -source 8 or higher to enable method references)
/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.6.18/android/src/main/java/me/carda/awesome_notifications/notifications/managers/PermissionManager.java:482: error: lambda expressions are not supported in -source 7
            activityQueue.add(() -> permissionCompletionHandler.handle(new ArrayList<>()));
                                 ^
  (use -source 8 or higher to enable lambda expressions)
2 errors

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':awesome_notifications:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 23s
Exception: Gradle task assembleDebug failed with exit code 1
```
Trying to figure out how to bump Java version. This did not help in app/build.gradle:
```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

**Comment by rafaelsetragni** [comment]
I made right now a mod to be compatible with Java 7. Please, put this into your `pusbpec.yaml`:

```yaml
# awesome_notifications: ^0.6.18
awesome_notifications:
     git:
       url: https://github.com/rafaelsetragni/awesome_notifications.git
       ref: d139ffb
```

Tell me if its solve your problem.

**Comment by rafaelsetragni** [comment]
I just released the version 0.6.18+1 with this fix. Use it instead and tell me if its working now.

**Comment by Albertbol** [comment]
Nice, thanks 👍!
Almost there, couple of fixes only left:
```
lib/main.dart:1
/flutter/.pub-cache/git/awesome_notifications-33cd87dd275d296f6463e9fbd747774f1cdb6dc6/android/src/main/java/me/carda/awesome_notifications/AwesomeNotificationsPlugin.java:930: error: local variable result is accessed from within inner class; needs to be declared final
                            result.success(missingPermissions);
                            ^
```
 **All occurrences  (930,940,951,962,1034)**

```
/flutter/.pub-cache/git/awesome_notifications-33cd87dd275d296f6463e9fbd747774f1cdb6dc6/android/src/main/java/me/carda/awesome_notifications/notifications/managers/PermissionManager.java:240: error: incompatible types: ArrayList<Object> cannot be converted to List<String>
                        new ArrayList<>(),
                        ^
```
**All occurrences  (240,485,488,496,499,507,510,518,521)**

**Comment by rafaelsetragni** [comment]
Try again now:

```yaml
# awesome_notifications: ^0.6.18
awesome_notifications:
     git:
       url: https://github.com/rafaelsetragni/awesome_notifications.git
       ref: 61f4d57
```

keep me in touch if you found any more issues.

**Comment by DevKhalyd** [comment]
@rafaelsetragni  I've added the snippet in my code and now a I got this error:

> awesome_notifications\notifications\managers\PermissionManager.java:342: error: local variable permissionCompletionHandler is accessed from within inner class; needs to be declared final
                    refreshReturnedPermissions(context, channelKey, permissions, permissionCompletionHandler);

I ran flutter clean and I've added the permission in the manifest

> uses-permission android:name="android.permission.USE_FULL_SCREEN_INTENT"

**Comment by rafaelsetragni** [comment]
`uses-permission android:name="android.permission.USE_FULL_SCREEN_INTENT"` you need to add by yourself on your manifest app file, because not all projects will need this permission.

Its sad that my compiler was automatically upgraded and i'm not being able to see these errors. Thank you so much for your support!

Now try again (again):
```yaml
# awesome_notifications: ^0.6.18+1
awesome_notifications:
     git:
       url: https://github.com/rafaelsetragni/awesome_notifications.git
       ref: a8930a1
```

**Comment by rafaelsetragni** [comment]
Now i understood what is going on. You will inevitably need to update your app to Android 12, and that's a good thing, otherwise the app won't be available from the version 12 Google Store without these changes. This is required for this plugin because Android 12 insert new important features for notifications and schedules.

You need to set your targetSdk to 31, minTargetSdk to 23 and add the tag android:exported=true in the activity to your AndroidManifest.xml file. I'm updating the documentation with instructions of how to do it.

**Comment by DevKhalyd** [comment]
It's something rare this issue, because I ran your example in my device with Android 11 and works fine. But when I implement the library in my own projects stop works. It contains the same specifications that you said. I'll research further to find the problem. Thanks for your help.

**Comment by rafaelsetragni** [comment]
Now i put every completion handler property as final and added into documentation how to upgrade successfully to Android 12. Please, try again:

```yaml
# awesome_notifications: ^0.6.18+1
awesome_notifications:
     git:
       url: https://github.com/rafaelsetragni/awesome_notifications.git
       ref: fca5362
```

**Comment by Albertbol** [comment]
Hey, 
Thanks for your fast actions.
I had `andoird:exported="true"` flag before and with your last commit `fca5362`, I have been able to build.
Great job 🎉

**Comment by krispykalsi** [comment]
If it's any help now, these properties were also required for it to work for me (works on API Level 28).

```
<activity
    ...
    android:showWhenLocked="true"
    android:turnScreenOn="true">
```

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
