### ISSUE TITLE
Could iOS use custom push icon?

### ISSUE THREAD

**Issue by zhouxinle** [rafaelsetragni/awesome_notifications#324]
I am using this amazing widget to do ios local notification. I wonder that could we use custom push icon?

It seems ios only can use its default app icon?

**Comment by zhouxinle** [comment]
@rafaelsetragni

**Comment by rafaelsetragni** [comment]
Yes, iOS only supports the default app icon.

**Comment by adrianvintu** [comment]
Could you please put this in the documentation on pub.dev? It took me a while to find this answer. Thank you!
