### ISSUE TITLE
Once a notification is created, it never goes away

### ISSUE THREAD

**Issue by Zelfapp** [rafaelsetragni/awesome_notifications#325]
Using `awesome_notifications: ^0.6.16`

When a firebase message is received in the foreground, I am creating an awesome notification. When the user taps the notification, my main screen's `initState` routes the payload to the appropriate screen. This works no problems. Also, in `dispose` on the main screen I am calling `AwesomeNotifications().actionSink.close();`

If I Navigator.pushNamed, back to the main screen from the screen I was initiallly routed to, Awesome Notifications is still getting event.payload from my main screen's `initState` method and then routes back to the screen I'm trying to navigate away from. Creating an unbreakable navigation loop.

How do I fully kill an Awesome Notification since `actionSink.close()` does not appear to be working? I'm also cancelling the notification id, but that has no effect either.

You can see in my `print()` logs how AwesomeNotifications().actionStream.listen() on my main screen `initState` keeps routing over and over when I try to go back to the main screen. **The event.payload never goes away and the event createdDate is always the same.**

I've also tried to use `AwesomeNotifications().dismissAllNotifications()`, but nothing works to dismiss this event.

```
...initState first routing
awesome notification listener called
event.createdDate: 2021-11-05 17:49:01
routing awesome notification
try to cancel awesome notification id
canceled awesome notification id: 1
Routing _appRoute: notifications_screen

trying to go back to main screen
awesome notification listener called
event.createdDate: 2021-11-05 17:49:01
routing awesome notification
try to cancel awesome notification id
canceled awesome notification id: 1
Routing _appRoute: notifications_screen

trying to go back to main screen
awesome notification listener called
event.createdDate: 2021-11-05 17:49:01
routing awesome notification
try to cancel awesome notification id
canceled awesome notification id: 1
Routing _appRoute: notifications_screen
```

My solution for dealing with AwesomeNotifications never releasing an event is in the following code. I'm having to use RiverPod to keep track of the `event.createdDate` in a StateProvider. If that date has already been routed then it is ignore, but this is pretty hacky. What am I missing here?

```flutter
final notificationEventCreatedStateProvider = StateProvider<List>((ref) => []);

AwesomeNotifications().actionStream.listen((event) {
  /// Check if this event has already been routed
  final List notificationEventCreated =
      context.read(notificationEventCreatedStateProvider).state;
  final String? createdDate = event.createdDate;
  bool eventRouted = false;
  if (createdDate != null) {
    eventRouted = notificationEventCreated.contains(createdDate);
  }

  if (event.payload != null &&
      event.payload?['appRoute'] != null &&
      !eventRouted) {
    /// Store the createdAt event date
    if (createdDate != null) {
      print('storing createdAt: $createdDate');
      context
          .read(notificationEventCreatedStateProvider)
          .state
          .add(createdDate);
    }

    print('routing awesome notification');
    print('event.id: ${event.id}');
    print('event.createdDate: ${event.createdDate}');
    print('event.title: ${event.title}');
    _setAppRoute(event.payload?['appRoute']);
    _navigateToRoute(
      context: context,
      payload: event.payload,
    );
  } else {
    print('No routing occurred.');
  }
});
```

**Comment by rafaelsetragni** [comment]
These notification streams was designed to only be listen once. You need to declare it globaly and redirect to the respective page or action when a new notification action arives.

If you initialize a listener on every new page, many things could happen, including to pages still existing in the stack widget and listen the same notification action twice.

**Comment by IliaKhuzhakhmetovRoonyx** [comment]
I have same problems(

My code in `main.dart`
```
runZonedGuarded<Future<void>>(() async {
    FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterError;

    await AwesomeNotifications().initialize(
        null,
        [
          CustomNotifications.bedTimeChannel,
          CustomNotifications.wakeUpChannel,
        ],
        debug: true);

    AwesomeNotifications().actionStream.listen((action) {
      debugPrint('recived');
    });

    runApp(const Initialization());
  }, (error, stack) {
    FirebaseCrashlytics.instance.recordError(error, stack);
  });
```

After I opened the notification, the application goes into an infinite loop, and finally crashes due to lack of space in the stack (

![image](https://user-images.githubusercontent.com/62252276/140783077-60a4e756-4c52-4023-85bf-37338fb40795.png)

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
