### ISSUE TITLE
Why validate with assertions?

### ISSUE THREAD

**Issue by t1ooo** [rafaelsetragni/awesome_notifications#326]
For example, https://github.com/rafaelsetragni/awesome_notifications/blob/04e066b01c0771d1c51daf5e7568dd014e232d55/lib/src/models/notification_calendar.dart#L155-L177

Assertions don't work in release build. 
Why not use exceptions instead?

**Comment by rafaelsetragni** [comment]
I saw many official Flutter classes that use asserts to validate parameters. But i don't see any problem in change that. This change will be available at next release.
