### ISSUE TITLE
getNotificationAppLaunchDetails ??

### ISSUE THREAD

**Issue by mzl1988** [rafaelsetragni/awesome_notifications#327]
local notifications 
How to getNotificationAppLaunchDetails

**Comment by rafaelsetragni** [comment]
There is no two different methods to handle notification when it arives from launch or not. ActionStream receives both and you can diferentiate when with the actionLifeCycle property. If the property is setted to AppKilled, that measn that the action was took when the app was terminated/killed.

**Comment by mzl1988** [comment]
Resolved, thank you
