### ISSUE TITLE
Why android local notification not shows float on the top screen of the phone?

### ISSUE THREAD

**Issue by zhouxinle** [rafaelsetragni/awesome_notifications#332]
I have open the "allow Floating notification" in the system setting. But when the notification comes. I only hear the notification sound which I set, I did not see the floating notification on the top screen. When I drag down the status bar, I can see the notification. is there any params to set in the codes to show the floating notification?
@rafaelsetragni

**Comment by rafaelsetragni** [comment]
Set the priority to max
