### ISSUE TITLE
Unable to handle notifications on iOS when the app is on screen

### ISSUE THREAD

**Issue by rish07** [rafaelsetragni/awesome_notifications#333]
When I send a notification through the Firebase console to test the notifications on iOS it prints the following in the console:
![image](https://user-images.githubusercontent.com/49035175/141243746-753fb0c3-f19e-41dc-a8ee-97e6cfd0a2a9.png)

Here's my handling of the notification service which is working fine on android.

```
import 'dart:math' as math;

import 'package:awesome_notifications/awesome_notifications.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:page_transition/page_transition.dart';
import 'package:persistent_bottom_nav_bar/persistent-tab-view.dart';
import 'package:spike_app/bloc/auth_bloc.dart';
import 'package:spike_app/bloc/incident_bloc.dart';
import 'package:spike_app/bloc/user_bloc.dart';
import 'package:spike_app/helpers/user_helper.dart';
import 'package:spike_app/main.dart';
import 'package:spike_app/screens/home_screen.dart';
import 'package:spike_app/screens/incident_screen.dart';

import 'app_color_helper.dart';
import 'app_utils.dart';

class NotificationHelper {
  static IncidentBloc bloc = IncidentBloc();
  static UserBloc userBloc = UserBloc();
  static Future init(BuildContext context) async {
    AwesomeNotifications().initialize("resource://drawable/launcher_icon", [
      NotificationChannel(
          importance: NotificationImportance.High,
          playSound: true,
          channelKey: 'basic_channel',
          channelName: 'Basic notifications',
          channelDescription: 'Notification channel for basic tests',
          defaultColor: AppColorHelper.blue,
          ledColor: AppColorHelper.white)
    ]);

    AwesomeNotifications().isNotificationAllowed().then((isAllowed) {
      if (!isAllowed) {
        AwesomeNotifications().requestPermissionToSendNotifications();
      }
    });

    AwesomeNotifications().actionStream.listen((ReceivedAction action) async {
      if (action.buttonKeyPressed == 'Acknowledge') {
        print("Acknowledge");
        await bloc.ackSingleIncident(context,
            counterId: int.parse(action.payload?['counterId'] ?? "0"));
      } else if (action.buttonKeyPressed == 'Resolve') {
        print("Resolve");
        await bloc.resSingleIncident(context,
            counterId: int.parse(action.payload?['counterId'] ?? "0"));
      }

      if ((action.payload?['type'] == "incident" ||
              action.payload?['type'] == "incidentAssign") &&
          action.payload?['counterId'] != null) {
        try {
          pushNewScreen(
            navigatorKey.currentContext!,
            screen: IncidentScreen(
              counterId: int.parse(action.payload?['counterId'] ?? "0"),
              index: 0,
            ),
            pageTransitionAnimation: PageTransitionAnimation.fade,
            withNavBar: false,
          );
        } catch (e) {
          print(e.toString());
        }
      } else if (action.payload?['type'] == "oncall") {
        Navigator.push(
          navigatorKey.currentContext!,
          PageTransition(
              child: HomeScreen(
                initialIndex: 2,
              ),
              type: PageTransitionType.fade),
        );
      } else if (action.payload?['type'] == "orgRemove") {
        AuthBloc().signOut(navigatorKey.currentContext!);
      }
    });

    initializeFirebaseService(context);
    AppUtils.log("Notification", "Successfully initialized");
  }

  static Future<void> initializeFirebaseService(BuildContext context) async {
    FirebaseMessaging messaging = FirebaseMessaging.instance;
    messaging.getToken().then((value) {
      AppUtils.log("FCM token", value);

      UserHelper.fcmToken = value!;
      User? user = FirebaseAuth.instance.currentUser;
      userBloc.setUserFCM(context, fcm: value, email: user?.email ?? "");
    });
    messaging.subscribeToTopic("general");
    AppUtils.log("FCM", "Subscribed to general");

    FirebaseMessaging.onMessage.listen((RemoteMessage event) {
      print("message received");

      buildNotification(event);
    });
  }

  static void buildNotification(RemoteMessage event) {
    if (event.data['type'] == "incident") {
      AwesomeNotifications().createNotification(
        actionButtons: [
          NotificationActionButton(
            key: 'Acknowledge',
            label: 'Acknowledge',
          ),
          NotificationActionButton(
            key: 'Resolve',
            label: 'Resolve',
          ),
        ],
        content: NotificationContent(
          payload: {
            "type": event.data['type'],
            "counterId": event.data['counterId'] ?? ""
          },
          id: math.Random().nextInt(10000),
          channelKey: 'basic_channel',
          title: event.data['title'],
          body: event.data['body'],
        ),
      );
    } else {
      AwesomeNotifications().createNotification(
        content: NotificationContent(
          payload: {
            "type": event.data['type'],
            "counterId": event.data['counterId'] ?? ""
          },
          id: math.Random().nextInt(10000),
          channelKey: 'basic_channel',
          title: event.data['title'],
          body: event.data['body'],
        ),
      );
    }
  }

  static Future dispose() async {
    try {
      AwesomeNotifications().actionSink.close();
      AwesomeNotifications().createdSink.close();
      await AwesomeNotifications().dispose();
    } catch (e) {
      print(e.toString());
    }
  }
}

```

Please help

**Comment by minhnhatvdl** [comment]
I have the same problem here. Anyone has a solution ?

**Comment by rafaelsetragni** [comment]
Have you guys used another plugin and made some changes in the iOS app source code?

**Comment by minhnhatvdl** [comment]
Yeah i use firebase_messaging (10.0.9) for a configuration of push notification.
Even if i don't use the lib awesome_notifications (just let it in pubspec.yaml), i have this problem.
"Was going to present a notification, but no plugin wanted ti handle it."

**Comment by vivekdk** [comment]
I have the same issue on iOS. Works all good on Android

**Comment by proczak1** [comment]
Any update on this? After removing code from AppDelegate (from local notifications setup) still does show : "was going..."

**Comment by jinxiking** [comment]
I have the same problem here. Anyone has a solution ?

**Comment by rafaelsetragni** [comment]
Please, if you did a modification on your iOS swift / objective-C source code, please remove it. These changes can create a loop in the receiving process because its handle twice or even more depending of what changes you did.

**Comment by shrutika-tatkare-apptware** [comment]
I am also facing same issue. do you find any solution

**Comment by duraibabu-14** [comment]
I am Facing the same Issue In my app as well. I am migrating from flutter local notification to this package. so I removed these block of code from appDelegate,


```
 if #available(iOS 10.0, *) {
   UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
   }

```

 Now background message is working fine But foreground says **"Was going to present a notification, but no plugin wanted to handle."** Could you tell me how To fix it 
 
 This is my **AppDelegate.swift** file.

```
import UIKit
import Flutter
import flutter_downloader
@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
    override func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        GeneratedPluginRegistrant.register(with: self)
        FlutterDownloaderPlugin.setPluginRegistrantCallback(registerPlugins)
        // if #available(iOS 10.0, *) {
        //     UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
        // }
        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }
}
private func registerPlugins(registry: FlutterPluginRegistry) {
    if (!registry.hasPlugin("FlutterDownloaderPlugin")) {
        FlutterDownloaderPlugin.register(with: registry.registrar(forPlugin: "FlutterDownloaderPlugin")!)
    }
}
```

**Comment by iamrohitsuthar** [comment]
Any update on this?

When I used only the firebase messaging library, I am getting notifications and callbacks in code but in the same project if I add awesome notifications then firebase messaging stops working. 

The default firebase notification appears from the notification payload when the app is running in the background but in case of foreground messages not getting callbacks in ```onMessage``` of FirebaseMessaging.
Whenever I send the message from console it prints 
`was going to present a notification, but no plugin wanted to handle it`

I haven't added any native code. Just added ```firebase_messaging``` and ```awesome_notifications``` libraries in my project.

**Flutter version:** 2.5.3
**Firebase messaging:** 11.2.0
**Awesome notifications:** 0.6.18+2

**Comment by yassinsameh** [comment]
Hi @rafaelsetragni , Happy holidays, wanted to say that the Issue still remains, once awesome_notifications is removed 0.6.19 onMessage works correctly.

**Comment by Luppakorva** [comment]
Facing this issue as well just as described by others. 

Solution would indeed be great if possible?

**Comment by Aastha-dev** [comment]
Hi, I am sending data in notification like shown below and receiving it properly when app is in background.  But when app goes to foreground I am not able to receive any notification. Actually main issue is that none of the listener gets triggered of FirebaseMessaging. 

Above issue happens only in IOS devices while in Android everything works fine using this library.

firebase_messaging: 11.1.0
awesome_notifications: 0.0.6+12

```
   data = {
        'registration_ids': tokens,
        "notification": {
         body: "",
          title: "",
        },
        'apns': {
          'headers': {'apns-priority': "5"},
          'payload': {
            'aps': {
               body: "",
               title: "",
              'channel': '1000',
              'isUpdateNotification': 'update'
            }
          }
        }
      };
```

**Comment by iamrohitsuthar** [comment]
> Any update on this, please?
> 
> When I used only the firebase messaging library, I am getting notifications and callbacks in code but in the same project if I add awesome notifications then firebase messaging stops working.
> 
> The default firebase notification appears from the notification payload when the app is running in the background but in case of foreground messages not getting callbacks in `onMessage` of FirebaseMessaging. Whenever I send the message from console it prints `was going to present a notification, but no plugin wanted to handle it`
> 
> I haven't added any native code. Just added `firebase_messaging` and `awesome_notifications` libraries in my project.
> 
> **Flutter version:** 2.5.3 **Firebase messaging:** 11.2.0 **Awesome notifications:** 0.6.18+2

**Update:**
```
{
  "message": {
    "token": "...",
    "notification": {
      "body": "notification message body",
      "title": "notification message title"
    },
    "data": {
        // custom data
        // here you can add your title and body
    },
    "apns": {
      "headers": {
        "apns-push-type": "background",
        "apns-priority": "5"
      },
      "payload": {
        "aps": {
          "content-available": 1
        }
      }
    }
  }
}
```
With this payload, everything is working fine as expected.
For testing the above payload through postman, refer to this link -> https://stackoverflow.com/questions/50399170/what-bearer-token-should-i-be-using-for-firebase-cloud-messaging-testing

@rafaelsetragni Thanks for creating such an amazing package

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
