### ISSUE TITLE
On iOS receivedAction is not received from actionStream listener

### ISSUE THREAD

**Issue by matszafraniec** [rafaelsetragni/awesome_notifications#334]
Hello,

I faced issue that actionStream listener is not being invoked when push notification is selected (app in foreground), so I can't read payload and prepare navigation from notification. Only iOS is affected.

Here is my initialisation code:
```
Future<void> init() async {
    await AwesomeNotifications().initialize(
      null,
      [
        NotificationChannel(
          channelKey: 'local_channel',
          channelName: 'Local notifications',
          channelDescription:
              // ignore: lines_longer_than_80_chars
              'Notification channel responsible of showing local notifications',
          defaultColor: AppTheme.colorAquaMarineBright,
          ledColor: Colors.white,
        )
      ],
    );

     // Handle navigation for notifications opened on foreground
    AwesomeNotifications().actionStream.listen(
      (actionReceived) {
            **// Here is issue. ActionReceived is not received here on iOS**
            print('actionReceived');
      },
    );
  }
```

Here is piece of code responsible for presenting notification (notification is delivered from Pushwoosh service) - this part is working fine. Notification appears properly in notification center:
```
Future<void> presentNotification({
    required String title,
    required String body,
    Map<String, String>? payload,
  }) async {
    notificationId++;

    await AwesomeNotifications().createNotification(
      content: NotificationContent(
        id: notificationId,
        channelKey: 'local_channel',
        title: title,
        body: body,
        payload: payload,
      ),
    );
  }
```

Can you support on this?

Flutter version: 2.5.3
iOS version: 15.1
Xcode version: 13.1

package version: 0.6.17

**Comment by IliaKhuzhakhmetovRoonyx** [comment]
Same problem

**Comment by colunira** [comment]
I have this problem as well

**Comment by rafaelsetragni** [comment]
try to take a look at:
https://github.com/rafaelsetragni/awesome_notifications/issues/331#event-5611660545

**Comment by matszafraniec** [comment]
@rafaelsetragni In my code I don't have this dependency in AppDelegate.switft:

`if #available(iOS 10.0, *) {
UNUserNotificationCenter.current().delegate = self as? UNUserNotificationCenterDelegate
}`

So this is not the solution for this case. And app isn't crashing.

**Comment by rafaelsetragni** [comment]
Did you made any modification on the original swift/Objective C source code, oriented by another plugin, such as flutter_local_notifications? Please, if yes, remove this changes and try again.

**Comment by matszafraniec** [comment]
There is no dependency to flutter_local_notifications anywhere as it wasn't implemented in my project in the past.

**Comment by rafaelsetragni** [comment]
Can you share with us on github a small example app with this issue? I couldn't reproduce this error.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
