### ISSUE TITLE
Can i delete a particular notification, before the scheduled time ?

### ISSUE THREAD

**Issue by Angurajdin** [rafaelsetragni/awesome_notifications#336]
I have created a channel name as key1 and I used the same channel for all of my notifications.
How can I delete a particular notification, before the scheduled time, Once it was created ?

Thanks in advance,

**Comment by rafaelsetragni** [comment]
You can delete a notification by its ID, channel key or group key, at any time.

Dismiss methods will only clear the status bar. Cancel Schedule methods will only cancel the schedule, without clear the status bar. And, for last, Cancel methods will dismiss and cancel the respective schedule at same time.

**Comment by Angurajdin** [comment]
thank you @rafaelsetragni
