### ISSUE TITLE
Android-Why float window shows flutter default icon when receive local notification.

### ISSUE THREAD

**Issue by zhouxinle** [rafaelsetragni/awesome_notifications#337]
<img width="438" alt="1" src="https://user-images.githubusercontent.com/4567999/141665072-52388090-fa48-4c49-a668-9de5ecc36d03.png">

please see the pic above.

I copy awaresome android example's drawable and mipmap to my own project.  so The icon pic is same with awaresome android example. I have installed  awaresome android example in my phone, it show correctly. But my own application float window shows flutter default icon when receive local notification.(In addtion, the icon of the application show correctly on desktop)

What have I missed some setting? 

@rafaelsetragni  Thank you.

**Comment by rafaelsetragni** [comment]
There is a video tutorial wich explains with fine details how to add the custom app icons for both platforms. I strongly recommend you to take a look.

**Comment by zhouxinle** [comment]
> There is a video tutorial in the README file wich explains with fine details how to add the custom app icons for both platforms. I strongly recommend you to take a look.

Could give me the link directly, I did not find it in README, Thank you very much.

**Comment by rafaelsetragni** [comment]
https://github.com/rafaelsetragni/awesome_notifications#video-tutorial
