### ISSUE TITLE
Required minimum iOS version 10

### ISSUE THREAD

**Issue by deliqs** [rafaelsetragni/awesome_notifications#338]
I'd love to use this library, but using iOS version 10.0 conflicts with my database library (objectbox). Is there any way I can workaround the required the minimum iOS version 10 and set it to 11.0 (which is the minimum for objectbox)?

**Comment by rafaelsetragni** [comment]
But the versions are leveled to the higher value. If you set your main project as minimum 11, it will be compatible with awesome notifications, which is minimum 10.

**Comment by deliqs** [comment]
Alright, then something else must be broken on iOS for me. I assumed this was the reason because targeting sdk 31 for Android did break the library as well (I saw that you'll fix this in the next release) and had the exact same.

The issue I have is that the notifications work perfectly on Simulator, but not on real iOS devices. I had the same issue for Android, but fixed that by targeting sdk 30.
