### ISSUE TITLE
Tried to send a platform message to Flutter

### ISSUE THREAD

**Issue by niypoo** [rafaelsetragni/awesome_notifications#340]
I'm facing warning message in console after run app in release mode
```
W/FlutterJNI(13182): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: awesome_notifications. Response ID: 0
```

I'm using   awesome_notifications: ^0.6.17 with flutter Flutter 2.5.3 • channel stable 

<img width="831" alt="Screen Shot 2021-11-18 at 2 27 00 AM" src="https://user-images.githubusercontent.com/13227239/142310959-8e443c38-2fc3-4696-bec2-246f3fe7eb43.png">

**Comment by Bes79** [comment]
Same issue

**Comment by naramwork** [comment]
same

**Comment by phamdanh** [comment]
> I'm facing warning message in console after run app in release mode
> 
> ```
> W/FlutterJNI(13182): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: awesome_notifications. Response ID: 0
> ```
> 
> I'm using awesome_notifications: ^0.6.17 with flutter Flutter 2.5.3 • channel stable
> 
> <img alt="Screen Shot 2021-11-18 at 2 27 00 AM" width="831" src="https://user-images.githubusercontent.com/13227239/142310959-8e443c38-2fc3-4696-bec2-246f3fe7eb43.png">

have you solved it yet?
