### ISSUE TITLE
minSdk version to at least 23

### ISSUE THREAD

**Issue by hatemragab** [rafaelsetragni/awesome_notifications#343]
my app supports android version API 19 how to config this plugin with my app?

**Comment by rafaelsetragni** [comment]
You just need to follow these steps:
https://github.com/rafaelsetragni/awesome_notifications#initial-requirements

**Comment by hatemragab** [comment]
> You just need to follow these steps: https://github.com/rafaelsetragni/awesome_notifications#initial-requirements

No this steps say i must use api level 23 i need 19 as min

**Comment by rafaelsetragni** [comment]
Im working right now to achieve min 21, but i'm afraid i will not be able to support such so old devices alone.

**Comment by hatemragab** [comment]
https://pub.dev/packages/flutter_local_notifications supports min 19

**Comment by rafaelsetragni** [comment]
Good for him.

**Comment by rafaelsetragni** [comment]
If you think it is essential for your business to extend support to Android 4.4, please feel free to modify the plugin.
This is the magic of open source.

![](https://c.tenor.com/bxHQ4KcM8eMAAAAC/magic-meme.gif)

https://gs.statcounter.com/android-version-market-share/mobile-tablet/worldwide/

**Comment by hatemragab** [comment]
I don't have time to edit thanks ☺️
