### ISSUE TITLE
I/flutter (11367): PlatformException(createNewNotification, Notification channel 'medopedia' does not exist., h.a.a.k.f.a: Notification channel 'medopedia' does not exist.

### ISSUE THREAD

**Issue by shivdvaio** [rafaelsetragni/awesome_notifications#345]
i  have already created channel name with medopedia but this error is showing only in release mode and using awesome_notifications: ^0.6.18+2

**Comment by rafaelsetragni** [comment]
Try to reinstall your app on device.

**Comment by shivdvaio** [comment]
i have already done 10 times

**Comment by rafaelsetragni** [comment]
And thats happening on all your devices? Try to use it in another emulator.

**Comment by shivdvaio** [comment]
i have already tested more than 3 device

**Comment by shivdvaio** [comment]
I/flutter (10821): PlatformException(createNewNotification, Notification channel 'medopedia' does not exist., h.a.a.k.f.a: Notification channel 'medopedia' does not exist.
I/flutter (10821):      at h.a.a.k.i.g.i(:5)
I/flutter (10821):      at h.a.a.k.i.k.i(Unknown Source:4)
I/flutter (10821):      at h.a.a.k.c.e(Unknown Source:10)
I/flutter (10821):      at h.a.a.f.h(:2)
I/flutter (10821):      at h.a.a.f.onMethodCall(:29)
I/flutter (10821):      at e.a.d.a.w.a(Unknown Source:17)
I/flutter (10821):      at io.flutter.embedding.engine.n.g.e(Unknown Source:17)
I/flutter (10821):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
I/flutter (10821):      at android.os.MessageQueue.nativePollOnce(Native Method)
I/flutter (10821):      at android.os.MessageQueue.next(MessageQueue.java:335)
I/flutter (10821):      at android.os.Looper.loop(Looper.java:206)
I/flutter (10821):      at android.app.ActivityThread.main(ActivityThread.java:8595)
I/flutter (10821):      at java.lang.reflect.Method.invoke(Native Method)
I/flutter (10821):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)

**Comment by rafaelsetragni** [comment]
You need to discovery in your project files what class is getting called "h.a.a.k.i.g.i"

**Comment by shivdvaio** [comment]
i have nothing   like h.a.a.k.i.g.i" in my project.

**Comment by shivdvaio** [comment]
![Screenshot 2021-11-26 at 7 06 50 PM](https://user-images.githubusercontent.com/57656560/143589194-bfcb3419-5fae-4575-a753-2537c82f9c38.png)

**Comment by shivdvaio** [comment]
and also i have tried many version of awesome notifications.

**Comment by rafaelsetragni** [comment]
I know. When you compile for release mode, all your class names are changed to this type of names to avoid reverse engineering and the correspondence is written within your project's local files. Search your entire machine and you'll find it.

**Comment by shivdvaio** [comment]
<img width="1440" alt="Screenshot 2021-11-26 at 7 15 25 PM" src="https://user-images.githubusercontent.com/57656560/143590242-2790b3a3-cb6f-43d8-b88b-54b4a5c0dbc0.png">
![Screenshot 2021-11-26 at 7 15 25 PM (2)](https://user-images.githubusercontent.com/57656560/143590266-09ea363d-2802-4d64-ac63-8e107fa2d9c8.png)

**Comment by rafaelsetragni** [comment]
https://meet.google.com/saa-sfvj-ijr

**Comment by rafaelsetragni** [comment]
One idea I've had here is to try running the sample app in launch mode on this Samsung device to see if it's generating the same error.

**Comment by shivdvaio** [comment]
yes try

**Comment by shivdvaio** [comment]
![Screenshot 2021-11-27 at 10 45 13 AM](https://user-images.githubusercontent.com/57656560/143669001-42a816a7-99bb-43b5-8210-1830eee018b0.png)

**Comment by rafaelsetragni** [comment]
So, is something related to your device and notification channels. Check for me if in the settings there is some special condition activated related to notifications or power / battery.

**Comment by ShruAlekha** [comment]
I had this error too, but it was because I had not initialized the channel before creating it. It does make sense to take a look whether the initialization has been done properly in the project.

**Comment by rafaelsetragni** [comment]
But, if he executed the example app and this error happened on the example app, there is nothing about coding. Is something related or to device configs or with your developing settings, such deploy keys, etc.

**Comment by ShruAlekha** [comment]
True. But I didn't realize this error showed up on example app for him.

**Comment by shivdvaio** [comment]
> I had this error too, but it was because I had not initialized the channel before creating it. It does make sense to take a look whether the initialization has been done properly in the project.
![Screenshot 2021-11-28 at 8 53 48 PM](https://user-images.githubusercontent.com/57656560/143774345-670834d4-dc0b-4f73-a7f7-f2150087c3be.png) see channel is already created.

**Comment by shivdvaio** [comment]
> But, if he executed the example app and this error happened on the example app, there is nothing about coding. Is something related or to device configs or with your developing settings, such deploy keys, etc.

i have tested with 5 devices already.

**Comment by shivdvaio** [comment]
> True. But I didn't realize this error showed up on example app for him.

yes in example app i didnt face any error with my device.

**Comment by shivdvaio** [comment]
but  in my project in debug mode every notification is working but in release mode this error i am facing.

**Comment by ShruAlekha** [comment]
So example app is working, debug mode is working. Release mode both android and ios?

**Comment by shivdvaio** [comment]
> So example app is working, debug mode is working. Release mode both android and ios?

yes correct

**Comment by shivdvaio** [comment]
![Screenshot 2021-11-28 at 9 04 40 PM](https://user-images.githubusercontent.com/57656560/143774865-b98d925d-1526-4240-a6d6-ca569cccf72e.png)

**Comment by ShruAlekha** [comment]
Which version Android and Ios?

**Comment by shivdvaio** [comment]
> Which version Android and Ios?

android 11

**Comment by shivdvaio** [comment]
![Screenshot 2021-11-28 at 9 05 50 PM](https://user-images.githubusercontent.com/57656560/143774967-871b0972-e566-4387-8b18-c6c1b8e1fb51.png)

**Comment by shivdvaio** [comment]
> So, is something related to your device and notification channels. Check for me if in the settings there is some special condition activated related to notifications or power / battery.
> 
> Important: Save your files in your repository and create a local copy before try these changes:
> 
> And you can try to change your SHA 1 release key as well: https://stackoverflow.com/questions/65488046/fcm-notifications-not-working-in-release-app
> 
> And clean your gradle files too: [invertase/react-native-firebase#2839](https://github.com/invertase/react-native-firebase/issues/2839)
> 
> Just one more question: Only the scheduled notifications did not work or none of them worked at all?

none of them is working in release mode.

**Comment by ShruAlekha** [comment]
https://github.com/rafaelsetragni/awesome_notifications/issues/271  - See this. It was solved by reinstalling flutter.

**Comment by shivdvaio** [comment]
> #271 - See this. It was solved by reinstalling flutter.

ok checking

**Comment by shivdvaio** [comment]
![Screenshot 2021-11-28 at 9 34 38 PM](https://user-images.githubusercontent.com/57656560/143776018-4ed850ae-7539-489d-b982-8639734c61b2.png)
same error after upgrading flutter

**Comment by shivdvaio** [comment]
![Screenshot 2021-11-28 at 9 39 53 PM](https://user-images.githubusercontent.com/57656560/143776287-70ef49ad-c6b2-4b70-8255-91d482f6f493.png)

**Comment by rafaelsetragni** [comment]
Ive teached you how to edit your souce code, clone the project and do almost anything with the app. Change the error message, print the channel result, channel key, etc. Create your own debug and im sure youll will find whats goin on pretty fast. And unfortunatelly, only you have the source code and the conditions to do it.

**Comment by ShruAlekha** [comment]
I just tested my code with Android 11 release mode on LG and motorola devices. I was able toget it to work without any issues. It's not even the example app. It's my own application which uses awesome notifications. @shivdvaio @rafaelsetragni

**Comment by rafaelsetragni** [comment]
I'm really curious to discover what's going on! Keep me in touch in case you need some help.

**Comment by ShruAlekha** [comment]
@shivdvaio If you have your code on GitHub I can take a look.

**Comment by mahdimoaz** [comment]
it happens when these parameters are true
 minifyEnabled true
 shrinkResources true

**Comment by marcelodev9** [comment]
I'm also having the same problem when in the release version of the application.

"PlatformException(createNewNotification, Notification channel 'scheduled' does not exist., i.a.a.k.f.a: Notification channel 'scheduled' does not exist."

Fixed it when I put the minifyEnabled properties and shrinkResources to false, but on some devices when opening the app there is only a white screen.

**Comment by rafaelsetragni** [comment]
Can you guys confirm to me if you only are facing this issue with Android 8 or greater or on Android 7.1 or older?

**Comment by rafaelsetragni** [comment]
Can you test it on an older Android device to see if the problem persists?

**Comment by marcelodev9** [comment]
@rafaelsetragni  I haven't tested it with older devices yet.
However, can you tell me why I need to set the minifyEnabled and shrinkResources properties to false for the alarms to work on release? Eventually when the app goes to stores, I won't be able to set them that way.
As for gradle, I tested it with the latest versions from 7.x.x and nothing changed.

**Comment by rafaelsetragni** [comment]
Minify changes the class and variables names to shorter versions and optimize lines of code to increase performance and the shrink compress the media and even the source code to reduce size and avoid reverse engineering. This options are enable by default on Flutter for release apps.

But did you changed on awesome_notifications source code or in your project? I guess we need to change it inside awesome project.
And you can try the version 3.6.4 as well.

**Comment by kushaln007** [comment]
@shivdvaio hello pls tell me about your error....
where did you find this error (in console or any other place).
and have you solved this error????
if you solved this error then pls tell me about it.

**Comment by shatil-zz** [comment]
I was facing same issue and solved by adding this proguard rules. I think main problem was gson serializable when building in release mode and I added proguard rules from [gson github proguard config](https://github.com/google/gson/blob/master/examples/android-proguard-example/proguard.cfg)

`-keepattributes SourceFile,LineNumberTable
-keep class me.carda.** { *; }

#Keep all public and protected class
-keep public class * {
      public protected *;
}
# Keep class members
-keepclassmembernames class * {
    java.lang.Class class$(java.lang.String);
    java.lang.Class class$(java.lang.String, boolean);
}

# Keep class members and native method
-keepclasseswithmembernames,includedescriptorclasses class * {
    native <methods>;
}

# Keep ENUM
-keepclassmembers,allowoptimization enum * {
    public static **[] values(); public static ** valueOf(java.lang.String);
}

# Keep Serializable classes and members
-keepclassmembers class * implements java.io.Serializable {
    static final long serialVersionUID;
    private static final java.io.ObjectStreamField[] serialPersistentFields;
    private void writeObject(java.io.ObjectOutputStream);
    private void readObject(java.io.ObjectInputStream);
    java.lang.Object writeReplace();
    java.lang.Object readResolve();
}


##---------------Begin: proguard configuration for Gson  ----------
# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.
-keepattributes Signature
-keepattributes InnerClasses

# For using GSON @Expose annotation
-keepattributes *Annotation*

# Gson specific classes
-dontwarn sun.misc.**
#-keep class com.google.gson.stream.** { *; }

# Application classes that will be serialized/deserialized over Gson
-keep class com.google.gson.examples.android.model.** { <fields>; }

# Prevent proguard from stripping interface information from TypeAdapter, TypeAdapterFactory,
# JsonSerializer, JsonDeserializer instances (so they can be used in @JsonAdapter)
-keep class * extends com.google.gson.TypeAdapter
-keep class * implements com.google.gson.TypeAdapterFactory
-keep class * implements com.google.gson.JsonSerializer
-keep class * implements com.google.gson.JsonDeserializer

# Prevent R8 from leaving Data object members always null
-keepclassmembers,allowobfuscation class * {
  @com.google.gson.annotations.SerializedName <fields>;
}

# Retain generic signatures of TypeToken and its subclasses with R8 version 3.0 and higher.
-keep,allowobfuscation,allowshrinking class com.google.gson.reflect.TypeToken
-keep,allowobfuscation,allowshrinking class * extends com.google.gson.reflect.TypeToken
`

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
