### ISSUE TITLE
he minCompileSdk (31) specified in a dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)

### ISSUE THREAD

**Issue by ibrahim-demirci** [rafaelsetragni/awesome_notifications#346]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Multiple task action failures occurred:
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.core:core:1.7.0.
        AAR metadata file: /Users/ibrahimdemirci/.gradle/caches/transforms-2/files-2.1/54ad79ea09a5ca853a674e0ee902f4fc/core-1.7.0/META-INF/com/android/build/gradle/aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.lifecycle:lifecycle-viewmodel-savedstate:2.4.0.
        AAR metadata file: /Users/ibrahimdemirci/.gradle/caches/transforms-2/files-2.1/e9a934f71e58886ce3641b88b2c04aa9/jetified-lifecycle-viewmodel-savedstate-2.4.0/META-INF/com/android/build/gradle/aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.lifecycle:lifecycle-viewmodel:2.4.0.
        AAR metadata file: /Users/ibrahimdemirci/.gradle/caches/transforms-2/files-2.1/ed1b3be0c44c913c83405fcb79e30cc9/lifecycle-viewmodel-2.4.0/META-INF/com/android/build/gradle/aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
        is greater than this module's compileSdkVersion (android-30).
        Dependency: androidx.lifecycle:lifecycle-service:2.4.0.
        AAR metadata file: /Users/ibrahimdemirci/.gradle/caches/transforms-2/files-2.1/17f644781cca6c50446bf515866fe88e/jetified-lifecycle-service-2.4.0/META-INF/com/android/build/gradle/aar-metadata.properties.
   > A failure occurred while executing com.android.build.gradle.internal.tasks.CheckAarMetadataWorkAction
      > The minCompileSdk (31) specified in a
        dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)

I got this error when I try run without debug.

**Comment by rafaelsetragni** [comment]
> The minCompileSdk (31) specified in a
dependency's AAR metadata (META-INF/com/android/build/gradle/aar-metadata.properties)
is greater than this module's compileSdkVersion (android-30)

Take a look at:
https://pub.dev/packages/awesome_notifications#initial-requirements

**Comment by ibrahim-demirci** [comment]
Thanks, I missed it 👍🏼
