### ISSUE TITLE
notification is not  static while downloading (progress value change)

### ISSUE THREAD

**Issue by Su-desh** [rafaelsetragni/awesome_notifications#347]
```Dart

Future<void> testingDownloadNotfication(
      {required String title,
      required String url,
      required String downloadFolder}) async {
    int uniqueId = createUniqueID(AwesomeNotifications.maxID);
    String downloadMessage = 'Downloading 0 %   ';
    var dir = extStorageDir;
    var getResponse = await dio.get('$url',
        options: Options(
          responseType: ResponseType.bytes,
          followRedirects: false,
        ), onReceiveProgress: (actualbytes, totalbytes) async {
      var percentage = actualbytes / totalbytes * 100;
      if (percentage < 100) {
        downloadMessage = ' Downloading ... ${percentage.floor()} %';
        print('completion percentage $percentage');
        await notifications.createNotification(
          content: NotificationContent(
            icon: 'resource://mipmap/download_logo',
            id: uniqueId,
            channelKey: 'progress_channel',
            title: 'File Downloading...',
            body: downloadMessage,
            progress: percentage.toInt(),
            notificationLayout: NotificationLayout.ProgressBar,
            locked: false,
          ),
        );
      } else {
        downloadMessage = 'Successfully Downloaded .';
        await notifications.createNotification(
          content: NotificationContent(
              icon: 'resource://mipmap/download_logo',
              id: uniqueId,
              channelKey: 'progress_channel',
              title: 'File Downloaded',
              body: '$downloadMessage ${dir!.path}/$downloadFolder/$title.pdf',
              notificationLayout: NotificationLayout.Default,
              locked: false,
              ),
        );
      }
    });
    var filePath = '${dir!.path}/$downloadFolder/$title.pdf';
    File file = await File(filePath).create(recursive: true);
    var raf = file.openSync(mode: FileMode.write);
    // getResponse.data is List<int> type
    raf.writeFromSync(getResponse.data);
    await raf.close();
  }

```

@rafaelsetragni 

this works fine but i want notification to be static , the each rebuild of notification should not be visible to user (currently user get to know this as the notification is building again and again ) . 

is there any better solution for the above code ????

**Comment by rafaelsetragni** [comment]
How the user knows about it?

**Comment by Su-desh** [comment]
it blinks again and again

**Comment by Su-desh** [comment]
@rafaelsetragni   
is there any way to update only the progress ( in above code)  ??

**Comment by rafaelsetragni** [comment]
When you send a notification with same ID it replaces the old one. You can set the property onlyAlertOnce to true to only play sound and vibrate on first time and set the autoDismissible to false.

And, for last, when the download finish you programmatically dismiss the notification.

**Comment by Su-desh** [comment]
Thank you . problem solved , but if possible a function to listen progress value instead of rebuilding notification will be better .

@rafaelsetragni 
and also can you tell the use of locked property ??

**Comment by rafaelsetragni** [comment]
It locks the notification on status bar, so the user will not be able to swipe it to dismiss.
Do such function to listen the progress value is impossible for notifications.

**Comment by Su-desh** [comment]
such function will help a lot , it will reduce the memory use because we will not be building notification again .

**Comment by Su-desh** [comment]
```Dart 
import 'dart:io';
import 'dart:math';
import 'package:awesome_notifications/awesome_notifications.dart';
import 'package:cbse/main.dart';
import 'package:dio/dio.dart';
import 'package:flutter/material.dart';

class ShowNotification {
  init() {
    notifications.initialize('resource://drawable/logo', [
      NotificationChannel(
        channelKey: 'progress_channel',
        channelName: 'progress notifications',
        channelDescription: 'channel for showing Progress Notification',
        defaultColor: Color(0xFF9D50DD),
        ledColor: Colors.white,
        playSound: false,
        enableLights: false,
        enableVibration: false,
        onlyAlertOnce: true,
        defaultPrivacy: NotificationPrivacy.Secret,
        importance: NotificationImportance.High,
      ),
    ]);
  }

  int createUniqueID(int maxValue) {
    Random random = new Random();
    return random.nextInt(maxValue);
  }

  Future<void> notficationForDownloadingFile(
      {required String title,
      required String url,
      required String downloadFolder}) async {
    int uniqueId = createUniqueID(AwesomeNotifications.maxID);
    String downloadMessage = 'Downloading 0 %';
    var dir = extStorageDir;
    var filePath = '${dir!.path}/$downloadFolder/$title.pdf';
    //initial notification when download is not started
    await notifications.createNotification(
        content: NotificationContent(
            icon: 'resource://mipmap/download_logo',
            id: uniqueId,
            channelKey: 'progress_channel',
            title: 'File Downloading...',
            body: downloadMessage,
            progress: null,
            notificationLayout: NotificationLayout.ProgressBar,
            locked: true,
            autoDismissible: false));

    var getResponse = await dio.get('$url',
        options: Options(
          responseType: ResponseType.bytes,
          followRedirects: false,
        ), onReceiveProgress: (actualbytes, totalbytes) async {
      var percentage = actualbytes / totalbytes * 100;
      if (percentage < 100) {
        downloadMessage = ' Downloading ... ${percentage.floor()} %';
        print('completion percentage $percentage');
        await notifications.createNotification(
          content: NotificationContent(
              icon: 'resource://mipmap/download_logo',
              id: uniqueId,
              channelKey: 'progress_channel',
              title: 'File Downloading...',
              body: downloadMessage,
              progress: percentage.toInt(),
              notificationLayout: NotificationLayout.ProgressBar,
              locked: true,
              autoDismissible: false),
        );
      } else {
        print(
            'File is Downloaded , now below notification should override with downloaded message');
        downloadMessage = 'Successfully Downloaded .';
        await notifications.createNotification(
          content: NotificationContent(
              icon: 'resource://mipmap/download_logo',
              id: uniqueId,
              channelKey: 'progress_channel',
              title: 'File Downloaded',
              body: '$downloadMessage $filePath',
              notificationLayout: NotificationLayout.Default,
              locked: false,
              autoDismissible: true),
        );
      }
    });

    File file = await File(filePath).create(recursive: true);
    print('File created ');
    var raf = file.openSync(mode: FileMode.write);
    // getResponse.data is List<int> type
    raf.writeFromSync(getResponse.data);
    print('Data Written');
    await raf.close();
  }
}
```
![Screenshot from 2021-12-01 16-32-10](https://user-images.githubusercontent.com/65455207/144223890-1311a6f2-c3fe-476f-9390-91687d9536c1.png
)



![Screenshot_2021-12-01-16-38-48-59_e8cb57a9cabfa7ea3050fc0a07895aa3](https://user-images.githubusercontent.com/65455207/144224261-133fe736-e41f-4e0f-a901-6c82190a8b03.jpg)



Hi @rafaelsetragni  in the debug console the else part of the code is executed but the in the notification the result is not shown , it should show that the file is downloaded . 


In the mobile screenshot , the download progress stopped at 78% this time, this value varies each time , but it never shows that the file is downloaded (else part of the above code) , it should show the notification with downloaded message  because the else part is executed successfully .

This is unexpected error , Can you tell the reason of this ?

**Comment by rafaelsetragni** [comment]
I guess youre updating your notifications too often. Do a async process to update the notification each time and update a public local variable with more precision. Remember, the user dont need to have such soo precise download updates.

**Comment by Su-desh** [comment]
delay in updating the notification is creating more problems , like the progress bar is still moving but the file is already downloaded and saved .

**Comment by Su-desh** [comment]
Through the else part of the code , i am not able to destroy the download notification as well . If you can tell a way to destroy notification with that id , according the above code , that will also be okay because i will show a different notification with another id , telling that the file is downloaded .

**Comment by rafaelsetragni** [comment]
No. You're not going to interfear in nothing on download process. You gonna create a parallel process to update your notifications on each 1 second, for example. If this parallel process encounters 100% of download concluded, it will shows a final notification and shutdown itself.

**Comment by rafaelsetragni** [comment]
> Through the else part of the code , i am not able to destroy the download notification as well . If you can tell a way to destroy notification with that id , according the above code , that will also be okay because i will show a different notification with another id , telling that the file is downloaded .

Dismiss the notification with method dismissNotification.

**Comment by Su-desh** [comment]
> Every problem that youre encontering to update or exclude some notification is because the operational system is defending itself from your app bombarding it with notifications and consumpting too much resources. It will pass to refuse your notifications after a while and its very understanding.

delay of few seconds in updating the notification is one solution , but i think the good solution will be adding a method in plugin to automatically update the progress without rebuilding the notification .

**Comment by rafaelsetragni** [comment]
You're not understanding, you're not going to delay nothing.

The download process and the notification update process will run in parallel and the only communication between then is the amount of download finished process. The download process will run as fast as possible and update the local public progress value as fast as possible.

The notification process will run stepped in 1 second (or even more) and update the notification ONLY when the value (rounded) has changed since the last update step. If it founds 100%, it will shows a final notifiation and shutdown itself.

> but i think the good solution will be adding a method in plugin to automatically update the progress without rebuilding the notification.

Such thing does not exist, and is a bad archtectural decision, since the notification process will gain to much responsabilities and increase a lot the coupling between the process.

You're facing a archtecural problem. The user do not need to have the UI updated so often and the download process must not be interrupted.

**Comment by Su-desh** [comment]
updating notification , after 1 second solved the problem . Thank you
