### ISSUE TITLE
schedule notification didn't show after app terminated

### ISSUE THREAD

**Issue by tp-coderbabu** [rafaelsetragni/awesome_notifications#349]
I created a specific scheduled time and successfully log printed on the terminal like - schedule is created but only show notification while the app is in foreground or background after terminated or close the app schedule notification didn't show.

 here is my code for schedule generation:

```
 NotificationService.getInstance.showScheduleNotification(
            notificationID: createUniqueId(),
            title:"title",
            body: "Awesome Notification",
            payload: payload,
            scheduleTime: DateTime(
                DateTime.now().year,
                DateTime.now().month,
                DateTime.now().day,
                DateTime.now().hour,
                DateTime.now().add(const Duration(minutes: 2)).minute));
```

here is the method:

```
  Future<bool> showScheduleNotification(
      {int notificationID,
      String title,
      String body,
      Map payload,
      DateTime scheduleTime}) async {
    await AwesomeNotifications().createNotification(
        content: NotificationContent(
            id: notificationID,
            channelKey: 'channelKey',
            title: title,
            body: body,
            locked: true,
            payload: payload,
            notificationLayout: NotificationLayout.Default),
        schedule: NotificationCalendar.fromDate(
            preciseAlarm: true, allowWhileIdle: true, date: scheduleTime)
    );
    return true;
  }
```
device: one plus 5 android version 10.
Any help would be appreciated.
Thank you.

**Comment by arpit24sahu** [comment]
I'm facing this same issue. 
Device: One Plus 8T

**Comment by mzl1988** [comment]
After testing Huawei many times, Xiaomi has the same problem

**Comment by mzl1988** [comment]
Scheduled Android notifications
Some Android OEMs have their own customised Android OS that can prevent applications from running in the background. Consequently, scheduled notifications may not work when the application is in the background on certain devices (e.g. by Xiaomi, Huawei). If you experience problems like this then this would be the reason why. As it's a restriction imposed by the OS, this is not something that can be resolved by the plugin. Some devices may have setting that lets users control which applications run in the background. The steps for these can vary but it is still up to the users of your application to do given it's a setting on the phone itself.

It has been reported that Samsung's implementation of Android has imposed a maximum of 500 alarms that can be scheduled via the Alarm Manager API and exceptions can occur when going over the limit.

[https://consumer.huawei.com/en/support/content/en-us00685514/](https://consumer.huawei.com/en/support/content/en-us00685514/)

The solution is as follows：
![FE021104BA3C3C91FEC04AAC6071E6FC](https://user-images.githubusercontent.com/11645762/145956978-56c6c85a-b7c7-47ff-8df0-f837c3916075.jpg)

**Comment by RobertHeim** [comment]
Also note that the debug bridge from android studio can be a problem on emulated devices. In case you experience this on an emulator try this out:

1. compile the app to the phone (start via IDE)
2. kill the app (which also removes the debug connection)
3. start the app again on the phone
4. schedule the notification
5. kill the app
6. should receive the scheduled notificaiton

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!

**Comment by 10ndavis** [comment]
> Also note that the debug bridge from android studio can be a problem on emulated devices. In case you experience this on an emulator try this out:
> 
> 1. compile the app to the phone (start via IDE)
> 2. kill the app (which also removes the debug connection)
> 3. start the app again on the phone
> 4. schedule the notification
> 5. kill the app
> 6. should receive the scheduled notification

It took me entirely too long to find this solution. Thank you!!
