### ISSUE TITLE
Notification Importance (show as pop-up)

### ISSUE THREAD

**Issue by hardik-weenggs** [rafaelsetragni/awesome_notifications#35]
- Notifications does't show as pop-up. I tried with **_NotificationImportance.Max_** and **_NotificationImportance.High_**  in **_Importance:_** but it doesn't work. it's also not working in this demo project. It worked in previous version "0.0.4+4".

- check attachment.

/////
Device: Samsung m30s
Version: Android 10 (Q)
/////

/// Attachment:

![device-2020-11-11-150125](https://user-images.githubusercontent.com/73572548/98795230-fd7fb500-242f-11eb-8596-f9f3f34183b7.png)

**Comment by rafaelsetragni** [comment]
I do not wrote anything to work with pop up notifications, but i agree is a good idea!
Ill study what i can do about it and i give you a return about it.

**Comment by hardik-weenggs** [comment]
But it was already working in the older version "0.0.4+4". if i pass **_NotificationImportance.High_** in **_Importance_** then it's enabled in older version. it's not working in latest version. please check once old version of library. ("0.0.4+4")

**Comment by hardik-weenggs** [comment]
any updates?

**Comment by hardik-weenggs** [comment]
Did you check this?
And when will you release new version?

**Comment by rafaelsetragni** [comment]
Today. I got some issues to update the firebase package for Android. They changed a lot of things.

**Comment by joankabello** [comment]
> But it was already working in the older version "0.0.4+4". if i pass **_NotificationImportance.High_** in **_Importance_** then it's enabled in older version. it's not working in latest version. please check once old version of library. ("0.0.4+4")

I tried with the old version and its not working with that too.

**Comment by hardik-weenggs** [comment]
add library like `awesome_notifications: '0.0.4+4'` in **pubspec.yaml**.
and uninstall app once.

**Comment by joankabello** [comment]
> add library like `awesome_notifications: '0.0.4+4'` in **pubspec.yaml**.
> and uninstall app once.
> 

I did it, on android 10, still doesn't work for me.

**Comment by rafaelsetragni** [comment]
I guess i found whats going on:

https://developer.android.com/guide/topics/ui/notifiers/notifications#importance

After Android 8, importance is defined only on channel. Ill include the channel config for it in next release.

**Comment by rafaelsetragni** [comment]
Importance levels fixed. Please test it for me.

Remember: The channel parameters can only be defined once. After that, you need to reinstal the app to modify it or erase the channel, wait for some time and recreate it.

**Comment by joankabello** [comment]
> Importance levels fixed. Please test it for me.
> 
> Remember: The channel parameters can only be defined once. After that, you need to reinstal the app to modify it or erase the channel, wait for some time and recreate it.

Great, it works now. Thanks!

**Comment by hardik-weenggs** [comment]
it works now.
Thanks

**Comment by Mahesh-Umg** [comment]
Really Awesome. It works fine.

In addition to this, i suggest to add afterTimeout. And also if any one is looking for custom incoming call, please add below code in NotificationBuilder.java file.

`NotificationCompat.Builder builder = new NotificationCompat.Builder(context, pushNotification.content.channelKey).setCategory(Notification.CATEGORY_CALL).setFullScreenIntent(pendingIntent,true).setTimeoutAfter(30000);`

And add below line in AndroidManifest.xml.

`<uses-permission android:name="android.permission.USE_FULL_SCREEN_INTENT" />
`
add soundSource parameter string in NotificationChannel for custom ringtone.

It should work like custom incoming call...

I hope it helps.

**Comment by MaheshPeri19** [comment]
Really Awesome. It works fine.

In addition to this, i suggest to add afterTimeout. And also if any one is looking for custom incoming call, please add below code in NotificationBuilder.java file.
NotificationCompat.Builder builder = new NotificationCompat.Builder(context, pushNotification.content.channelKey).setCategory(Notification.CATEGORY_CALL).setFullScreenIntent(pendingIntent,true).setTimeoutAfter(30000);
And add below line in AndroidManifest.xml.
<uses-permission android:name="android.permission.USE_FULL_SCREEN_INTENT" /> add soundSource parameter string in NotificationChannel for custom ringtone.
It should work like custom incoming call...
I hope it helps.

**Comment by efraespada** [comment]
@MaheshPeri19 
Really interesting! **What about iOS?**

Right now I'm showing a simple notification with the call information and playing a ringtone sound.

**Comment by MaheshPeri19** [comment]
@efraespada 
I have checked in iOS. But I didn't find anything like that. Need more research on iOS.

**Comment by efraespada** [comment]
@MaheshPeri19 

I found this: 
https://github.com/flutter-webrtc/callkeep

It would be super useful to integrate it with the **awesome_notifications** if it could prevent a notification to be displayed.

**Prevent ReceivedNotification from being displayed:** https://github.com/rafaelsetragni/awesome_notifications/issues/91

For example, in the case of Android, the logic could show a full-screen notification (as you propose).
In iOS we should detect the notification (with the call's information) and launch callkeep.

**Comment by MaheshPeri19** [comment]
@efraespada 

https://pub.dev/packages/callkeep
https://pub.dev/packages/flutter_callkeep

Yes. I know that callkeep and flutter_callkeep for incoming call functionality. Before using awesome notifications, i used callkeep.

In callkeep, we have to ask unnecessary permissions like phone account permissions and other permissions. Otherwise incoming call functionality will not work. 

In flutter_callkeep, answer and decline button action callbacks are not working. Our main focus is in Android. Thats why i left it.

My actual requirement is agora video calling just like skype or whatsapp. So i found awesome notifications is very useful and customized just like i suggested above.

**Comment by nsumithradeveloper** [comment]
> @MaheshPeri19
> Really interesting! **What about iOS?**
> 
> Right now I'm showing a simple notification with the call information and playing a ringtone sound.

Doing the same but the notification is getting back to status bar within few seconds

**Comment by rekonvald** [comment]
Hi!I am using  0.0.5+5 version, but there is no importance type Urgent: Makes a sound and appears as a heads-up notification.

**Comment by hardik-weenggs** [comment]
- 1st uninstall your app and install new one. add following line to your channel intialization. 
check **Example**

`importance: NotificationImportance.Max`

```
# Example

AwesomeNotifications().initialize(
        'resource://drawable/ic_launcher',
        [
          NotificationChannel(
              channelKey: ParamsArgus.CHANNEL_ID_BASIC,
              channelName: ParamsArgus.CHANNEL_NAME_BASIC,
              channelDescription: '',
              importance: NotificationImportance.Max,
              defaultPrivacy: NotificationPrivacy.Public,
              icon: 'resource://drawable/ic_launcher',
              soundSource: 'resource://raw/res_ringtone',
              enableLights: true,
              playSound: true,
              enableVibration: true),
```

**Comment by rekonvald** [comment]
Thank you

**Comment by thefdisk** [comment]
> Really Awesome. It works fine. In addition to this, i suggest to add afterTimeout.
> 
> And also if any one is looking for custom incoming call, please add below code in NotificationBuilder.java file.
> 
> `NotificationCompat.Builder builder = new NotificationCompat.Builder(context, pushNotification.content.channelKey).setCategory(Notification.CATEGORY_CALL).setFullScreenIntent(pendingIntent,true).setTimeoutAfter(30000);`

Where I can find this file?
