### ISSUE TITLE
schedule seems not work in FirebaseMessaging.onBackgroundMessage

### ISSUE THREAD

**Issue by WingCH** [rafaelsetragni/awesome_notifications#355]
I used the example and tried 

1. [How to send Push Notifications using Firebase Cloud Messaging plugin (FCM)](https://github.com/rafaelsetragni/awesome_notifications#how-to-send-push-notifications-using-firebase-cloud-messaging-plugin-fcm) and 
2. [Schedules](https://github.com/rafaelsetragni/awesome_notifications#schedules) 
3. https://github.com/rafaelsetragni/awesome_notifications/pull/354

The schedule function does not take effect in `FirebaseMessaging.onBackgroundMessage`, but `FirebaseMessaging.onMessage` can work normally.

OS: Android 11

**Comment by rafaelsetragni** [comment]
I've sent to you some changes in your master branch repository to fix it.
Please, take a look: https://github.com/rafaelsetragni/awesome_notifications/pull/354

**Comment by WingCH** [comment]
fixed in https://github.com/rafaelsetragni/awesome_notifications/pull/354
