### ISSUE TITLE
Action Button or Custom notification is not working in Release apk

### ISSUE THREAD

**Issue by Sagarsappic** [rafaelsetragni/awesome_notifications#356]
Hello 
i want to report a bug that when i work with action buttons in notification its working but in release apk it is showing only normal notification with title and body not  show anything giving channel error

 PlatformException(createNewNotification, Notification channel 'basic_channel' does not exists., f.a.a.e.f.a: Notification channel 'basic_channel' does not exists.

**Comment by rafaelsetragni** [comment]
Repeated topic: https://github.com/rafaelsetragni/awesome_notifications/issues/345
