### ISSUE TITLE
The plugin uses an insecure Random Number Generator.

### ISSUE THREAD

**Issue by tim-teacher** [rafaelsetragni/awesome_notifications#357]
The App uses an insecure Random Number Generator.
`awesome_notifications/notifications/NotificationSender.java:13`
It should be replaced with [SecureRandom](https://docs.oracle.com/javase/7/docs/api/java/security/SecureRandom.html).

**Comment by rafaelsetragni** [comment]
The point is not be secure, but to be unique at time. You can also use your own random IDs with dart, if you wish to.
