### ISSUE TITLE
MD5 is a weak hash known to have hash collisions.

### ISSUE THREAD

**Issue by tim-teacher** [rafaelsetragni/awesome_notifications#358]
MD5 is a weak hash known to have hash collisions.
`awesome_notifications/notifications/managers/SharedManager.java:28`
`awesome_notifications/notifications/managers/SharedManager.java:26`
`awesome_notifications/utils/StringUtils.java:24`

**Comment by rafaelsetragni** [comment]
Every hash function have collisions. But feel free to improve it.
