### ISSUE TITLE
Open app when tapping notification 

### ISSUE THREAD

**Issue by maimand** [rafaelsetragni/awesome_notifications#363]
Hi there,

This is a really great package. Thank you for your hard work.
I am using your package to show notification. I am struggling with the actionStream when open app from tapping the notification when app is killed. Because before navigating and do my logic, I have to authenticate the user and get some information. But as far as I know and have implemented, the action will fire immediately after the app is open, leading to my logic crashed because no authentication.

So is there any way for me to wait the app authenticate before navigating?

**Comment by maimand** [comment]
You can think of getIntitialMessage of Firebase messaging for easier understanding.
Thank you in advance.

**Comment by rafaelsetragni** [comment]
Notifications are indicated to just notify the user. I recommend you to do the comunication between the validation backend process and your app in REST and use the notifications to only notify the user about the action results. You can start this process with a silent background push or after a user action. Is not necessary to use a workmanager to do this and i do not recommend your process to rely on the silent background push delivery.

**Comment by maimand** [comment]
Thank you for your response.
My situation is like I have a new message notification from firebase messaging, I use background handler with awesome notification to handle the tapping action that open app and show the chat screen, but I want before showing chat screen, I do authentication. When i implement actionStream, when i tap notification, it show the chat screen immediately after the app open. I found a work around solution but not really good one.
Do you have any recommendation for this?

**Comment by rafaelsetragni** [comment]
This is something that your app can handle totally by its own. Store the action into a variable, do the login and redirect the user. And you can redirect the user to any place inside the actionStream.

I only think its a mistake to rely on a notification action as requirement to accomplish an use case. But, since i don't know all your business details, i can only recommend to you, as a generically suggestion, to not rely on notifications action to accomplish your process.

**Comment by maimand** [comment]
I got it.
Thank you for your time and effort. I really appreciate that.

Oh 1 more small question, is there any option to change the text format app name in notification from all uppercase to normal format on iOS device? Like in this case AWESOME NOTIFICATION will be Awesome Notification.
![image](https://user-images.githubusercontent.com/42661871/145922100-5a0f9275-fdd6-44e3-a7c0-58159acb4b90.png)

**Comment by rafaelsetragni** [comment]
No. iOS icons and app name are defined by OS and cannot be changed.

**Comment by maimand** [comment]
Thank you so much.
