### ISSUE TITLE
iOS - onMessageOpenedApp method not getting invoked while opening app from background notification created by firebase. 

### ISSUE THREAD

**Issue by MohamedRisaldarTA** [rafaelsetragni/awesome_notifications#365]
I have integrated firebase_messaging along with awesome_notifications plugin to customise notifications received while app is running.

and everything is working on Android well.
But on iOS, when i tap on a notification created by firebase_messaging while app is in background, the app just opens but not calling onMessageOpenedApp method of firebase.

But without awesome_notifications plugin, onMessageOpenedApp, getInitialMessage methods / listeners are getting invoked.
 Flutter : 2.5.3
 awesome_notifications: 0.6.19
 firebase_messaging : 11.2.4

I think the problem is in didFinishLaunchingWithOptions delegate ,because, the value for _originalNotificationCenterDelegate is null while invoking didReceive.

**Comment by Williano** [comment]
Facing the same problem. Any solutions yet?

**Comment by MohamedRisaldarTA** [comment]
> Facing the same problem. Any solutions yet?

Not yet!!!
Planning to fork this repo and to implement one temporary mechanism to get it working for now.

**Comment by Williano** [comment]
Please can you share the code with me once you are done because both firebase background, foreground and terminated doesn’t work for me on iOS

**Comment by Chinmay-KB** [comment]
I have been struggling with this issue for a week, until yesterday. Go through issue #132 to get an overview of the problem. Some have tried fixing it but none of the solutions worked for me. If you look closely the logs, on tapping the notification, a message is printed on the screen
```
Received an invalid notification content 
```
The only solution I could find is removing awesome_notifications and using flutter_local_notifications instead. I do not know why is that so, but it works with fcm_messaging on iOS, can confirm.
NOTE: Just commenting out all the code related to awesome notifications is not enough, you will have to remove the dependency as well.

**Comment by mtmfuture** [comment]
having same problem also

**Comment by alecisco** [comment]
having same problem.

**Comment by ebelevics** [comment]
Just removed awesome_notifications package and yes, on press is working now. Please fix firebase_messaging with this package

**Comment by alfalcon90** [comment]
If you're only using awesome_notifications to manage notifications on Android and don't need it for iOS you can fork this repo and remove iOS support like I did here: https://github.com/alfalcon90/awesome_notifications/commit/8e7270f44f65f7bf3ffaab0ad4a0d15478d53226

Then make sure any code using awesome_notifications is behind an `defaultTargetPlatform == TargetPlatform.android` if statement. This workaround seems to be working for me so far.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
