### ISSUE TITLE
android.os.NetworkOnMainThreadException when using the largeIcon property with a remote URL

### ISSUE THREAD

**Issue by GrupoDO** [rafaelsetragni/awesome_notifications#369]
I get this error when I use the largeIcon property with a remote URL:

[ +166 ms] W/System.err( 7718): android.os.NetworkOnMainThreadException
[        ] W/System.err( 7718): 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1565)
[        ] W/System.err( 7718): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
[        ] W/System.err( 7718): 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
[  +20 ms] W/System.err( 7718): 	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
[        ] W/System.err( 7718): 	at com.android.okhttp.Dns$1.lookup(Dns.java:41)
[        ] W/System.err( 7718): 	at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:178)
[        ] W/System.err( 7718): 	at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:144)
[  +48 ms] W/System.err( 7718): 	at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:86)
[        ] W/System.err( 7718): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:176)
[        ] W/System.err( 7718): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
[   +1 ms] W/System.err( 7718): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
[        ] W/System.err( 7718): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
[        ] W/System.err( 7718): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
[        ] W/System.err( 7718): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
[        ] W/System.err( 7718): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
[        ] W/System.err( 7718): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
[        ] W/System.err( 7718): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
[        ] W/System.err( 7718): 	at me.carda.awesome_notifications.utils.BitmapUtils.getBitmapFromUrl(BitmapUtils.java:173)
[        ] W/System.err( 7718): 	at me.carda.awesome_notifications.utils.BitmapUtils.getBitmapFromSource(BitmapUtils.java:44)
[   +1 ms] W/System.err( 7718): 	at me.carda.awesome_notifications.notifications.NotificationBuilder.setLargeIcon(NotificationBuilder.java:604)
[   +1 ms] W/System.err( 7718): 	at me.carda.awesome_notifications.notifications.NotificationBuilder.getNotificationBuilderFromModel(NotificationBuilder.java:411)
[        ] W/System.err( 7718): 	at me.carda.awesome_notifications.notifications.NotificationBuilder.createNotification(NotificationBuilder.java:110)
[        ] W/System.err( 7718): 	at me.carda.awesome_notifications.services.ForegroundService.onStartCommand(ForegroundService.java:50)
[        ] W/System.err( 7718): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4087)
[        ] W/System.err( 7718): 	at android.app.ActivityThread.access$1800(ActivityThread.java:219)
[        ] W/System.err( 7718): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1891)
[        ] W/System.err( 7718): 	at android.os.Handler.dispatchMessage(Handler.java:107)
[        ] W/System.err( 7718): 	at android.os.Looper.loop(Looper.java:214)
[        ] W/System.err( 7718): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
[        ] W/System.err( 7718): 	at java.lang.reflect.Method.invoke(Native Method)
[        ] W/System.err( 7718): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
[  +41 ms] W/System.err( 7718): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

According the Android Developers docs, this must be avoided.

Ref:
https://developer.android.com/reference/android/os/NetworkOnMainThreadException
https://developer.android.com/training/articles/perf-anr#Avoiding
https://stackoverflow.com/a/6343299

**Comment by rafaelsetragni** [comment]
Yes, its a bug. CreateNotification should run inside a thread, but instead was directly called by foreground service. This fix will done at next version 0.7.0

**Comment by frananleo** [comment]
How is going the fix?

**Comment by rafaelsetragni** [comment]
Ive blocked the network assets to be used on foreground services until i discover how to run the background service (or part of it) in background.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
