### ISSUE TITLE
Awesome notifications error prevents flutter web from launching

### ISSUE THREAD

**Issue by baimamboukar** [rafaelsetragni/awesome_notifications#377]
![awesome_notiff](https://user-images.githubusercontent.com/49169158/148090164-b69075c2-f99f-4b1d-8f99-a27c2b06c303.png)

I use Awesome Notifications for the Android version of the app. But when I try to launch the web app, This error form the awesome notifications package prevents my flutter web app to load.
Need solution.....

**Comment by imertgul** [comment]
Yeah same unfortunately.

**Comment by baimamboukar** [comment]
@imertgul you go the same error ?

**Comment by imertgul** [comment]
> @imertgul you go the same error ?

Yes same. Any suggestion to make it work?

**Comment by rafaelsetragni** [comment]
Thats happen because flutter web replicates every widget in a respective javascript script. What is happen in your case is that flutter generate two scripts with the same name. In awesome_notifications case, the AssertUtil class is used to validate map contents, but seems that another package that youre using also has a class with same name.

Im changing the util class names with prefix Awesome to avoid this kind of conflicts, as this name seems to often to be used. Will be available at version 0.6.20.

**Comment by imertgul** [comment]
Thanks for quick responce and update but not fixed :(.

@rafaelsetragni  Problem is not the name of class. There is type parameter for exterctValue method in assert_utils.dart as you see. But also third parameter of method is the same for javascript. I think it is unnececary. So maybe you can remove it.

![resim](https://user-images.githubusercontent.com/22999961/148731622-50a6e5d0-4643-4418-b4c8-2c058c05d85a.png)
![resim](https://user-images.githubusercontent.com/22999961/148731588-cd502d6d-726d-4b14-827b-db4a643d9686.png)

**Comment by imertgul** [comment]
> Thanks for quick responce and update but not fixed :(.
> 
> @rafaelsetragni Problem is not the name of class. There is type parameter for exterctValue method in assert_utils.dart as you see. But also third parameter of method is the same for javascript. I think it is unnececary. So maybe you can remove it.
> 

I removed the type parameter and it worked.

**Comment by baimamboukar** [comment]
@rafaelsetragni  Thanks for the quick response. I changed the version of Awesome_notifications and it worked

**Comment by baimamboukar** [comment]
@imertgul I'll to removed the parameter.

**Comment by rafaelsetragni** [comment]
I recommend you to run the test file called `extraction_values_test.dart` to certify if this change gonna impact the extraction method.

**Comment by imertgul** [comment]
Here is a test result after edit. Are you considering updating the parameter? Or maybe I can search for other alternatives.

By the way I think best practice is removing the third parameter, not the type parameter. But you are using third parameter thats why i tested with removing type param.

![resim](https://user-images.githubusercontent.com/22999961/148773893-1c5d0a4e-13c2-4db0-915d-82f39f5186b2.png)

**Comment by rafaelsetragni** [comment]
The problem is the type parameter is receiving dynamic, instead of the target type. Thats why ive also pass it as third parameter.

**Comment by imertgul** [comment]
> The problem is the type parameter is receiving dynamic, instead of the target type. Thats why ive also pass it as third parameter. I gonna release a new version with this small fix today.

Oh i see. I can imagine the problem you're having. I ll watch the next updates.

Thank you for the attention and package of course.
