### ISSUE TITLE
Schedule Notification

### ISSUE THREAD

**Issue by hardik-weenggs** [rafaelsetragni/awesome_notifications#38]
-  Schedule Notification does't work when _"autoCancel: false"_.

**Comment by rafaelsetragni** [comment]
Can you send me your notification creation code as an example?
And also send me what system are you running, which version and whats is your plugin version?

**Comment by hardik-weenggs** [comment]
- macOS Catalina (10.15.5)
- Samsung m30s
- Android 10 (Q)
- awesome_notifications: ^0.0.5+2



//////////////// **Example** ////////////////

AwesomeNotifications().initialize(
      'resource://drawable/ic_launcher',
      [
        NotificationChannel(
            channelKey: 'appointment_channel',
            channelName: 'Appointment Alert',
            channelDescription: '',
            importance: NotificationImportance.Max, // High, Max
            defaultPrivacy: NotificationPrivacy.Public,
            icon: 'resource://drawable/ic_launcher',
            enableLights: true,
            playSound: true,
            enableVibration: true,
            onlyAlertOnce: false,
            locked: true,
            ledOnMs: 1000,
            ledOffMs: 500,
            defaultColor: Colors.red,
            ledColor: Colors.blue,
            vibrationPattern: Int64List.fromList(
                List.generate(30, (index) => index % 2 == 0 ? 500 : 1000)
                    .toList())),
      ],
    );

////////////////

Future<void> showNotification () async {

    final scheduleDate = DateTime.now().add(Duration(minutes: 1));

    await AwesomeNotifications().createNotification(
      content: NotificationContent(
        id: 12,
        channelKey: 'appointment_channel',
        title: "*** Appointment Alert ***",
        body: "",
        autoCancel: false,
        locked: true,
        showWhen: true,
        color: appColor.red,
        ticker: 'ticker1',
        payload: {
          "data": "hiii",
        },
      ),
      actionButtons: [
        NotificationActionButton(
            buttonType: ActionButtonType.KeepOnTop,
            key: "CANCEL",
            label: "Cancel",
            autoCancel: true),
        NotificationActionButton(
            buttonType: ActionButtonType.Default,
            key: "OPEN",
            label: "Open",
            autoCancel: true)
      ],
      schedule: NotificationSchedule(
        allowWhileIdle: true,
        crontabSchedule: CronHelper.instance
            .atDate(scheduleDate.toUtc(), initialSecond: 0),
      ),
    );
  }

**Comment by rafaelsetragni** [comment]
I did not check what happened, but ill do as soon as possible.

**Comment by rafaelsetragni** [comment]
Sorry for take so long. I had fixed it, was a "copy and paste" mistake inside json conversion method.

https://github.com/rafaelsetragni/awesome_notifications/blob/b3e4da96f0302fef43f4c801d819dad044021332/android/src/main/java/me/carda/awesome_notifications/notifications/models/NotificationContentModel.java#L166

https://github.com/rafaelsetragni/awesome_notifications/blob/b3e4da96f0302fef43f4c801d819dad044021332/android/src/main/java/me/carda/awesome_notifications/notifications/models/NotificationContentModel.java#L169

This fix will be available on next release.
