### ISSUE TITLE
[Android][Enhancement] HTTPSUrlConnection instead of UrlConnection

### ISSUE THREAD

**Issue by frogman1189** [rafaelsetragni/awesome_notifications#392]
It would be useful to use `HttpsUrlConnection` instead of `UrlConnection` in the `getBitmapFromUrl` function call as it doesn't require you to add the `android:usesCleartextTraffic="true"` tag to your AndroidManifest and allows your app to be more secure

**Comment by rafaelsetragni** [comment]
URLConnection is an abstract class. The method `new URL(bitmapUri).openConnection()` returns `HttpsUrlConnection` or `HttpUrlConnection`, depending of what you sent as protocol prefix of your url. This way is totally up to the developer decides if the pretend to offer the images though http or https.

And its not necessary to use `android:usesCleartextTraffic="true"` for awesome_notifications.

**Comment by frogman1189** [comment]
Thanks.
I had tried it earlier with an https link (I believe as I don't remember changing it) and was getting the clear text error. Have just tried again and its working as expected. Sorry about wasting your time
