### ISSUE TITLE
fatal error: module 'awesome_notifications' not found

### ISSUE THREAD

**Issue by mcorbelli-zz** [rafaelsetragni/awesome_notifications#398]
I get this error when compiling from vscode

Flutter doctor:

[✓] Flutter (Channel stable, 2.8.1, on macOS 12.1 21C52 darwin-x64, locale it-IT)
    • Flutter version 2.8.1 at /Users/mattiacorbelli/fvm/versions/2.8.1
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (6 settimane fa), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mattiacorbelli/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.32.0

Error:

    /* com.apple.ibtool.document.warnings */
    /Users/mattiacorbelli/.pub-cache/hosted/pub.dartlang.org/flutter_inappwebview-5.3.2/ios/Storyboards/WebView.storyboard:global: warning: This file is set to build for a version older than the deployment target. Functionality may be limited. [9]
    /Users/mattiacorbelli/Documents/development/work_repos/coyzy/coyzy-app/ios/Runner/GeneratedPluginRegistrant.m:12:9: fatal error: module 'awesome_notifications' not found
    @import awesome_notifications;
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order

Could not build the precompiled application for the device.

**Comment by playfairdisplay** [comment]
Were you able to solve this issue? I'm facing it too on Mac M1.

**Comment by rafaelsetragni** [comment]
Im also using mac M1 and im not finding the same issue. Probably is something related to your local development environment. Try to use `flutter clean` or use another IDE.

**Comment by iKlsR** [comment]
Same issue, M1 mac, latest flutter etc. I tried cleaning, the project builds and runs fine, I only get this from inside xcode.

**Comment by willroyMyles** [comment]
anything on this?

**Comment by willroyMyles** [comment]
i deleted my ios folder
ran ```flutter upgarde```
ran ```flutter build ios``` which miracously worked!
then opened xcode and archived my project

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
