### ISSUE TITLE
Flutter iOS IPA build issue

### ISSUE THREAD

**Issue by ismailkhan885** [rafaelsetragni/awesome_notifications#399]
**first i create flavors using flutter_flavorizer after that i add**
**awesome_notification: 0.6.21**

`rror output from Xcode build:
↳
    objc[28030]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1f600ab90) and
    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103c902c8). One of the two will be used. Which one is undefined.
    objc[28030]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1f600abe0) and
    /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x103c90318). One of the two will be used. Which one is undefined.`
    ** ARCHIVE FAILED **

Xcode's output:
↳
    /Users/ismailkhan/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.6.21/ios/Classes/lib/utils/BitmapUtils.swift:163:11: warning: 'catch' block is
    unreachable because no errors are thrown in 'do' block
            } catch let error {
              ^
    /Users/ismailkhan/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.6.21/ios/Classes/lib/utils/BitmapUtils.swift:176:11: warning: 'catch' block is
    unreachable because no errors are thrown in 'do' block
            } catch let error {
              ^
    /Users/ismailkhan/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.6.21/ios/Classes/lib/externalLibs/SyncronizedArray.swift:100:42: warning: 'index(where:)'
    is deprecated: renamed to 'firstIndex(where:)'
            queue.sync { result = self.array.index(where: predicate) }
                                             ^
    /Users/ismailkhan/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.6.21/ios/Classes/lib/externalLibs/SyncronizedArray.swift:100:42: note: use
    'firstIndex(where:)' instead
            queue.sync { result = self.array.index(where: predicate) }
                                             ^~~~~
                                             firstIndex
    /Users/ismailkhan/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.6.21/ios/Classes/lib/externalLibs/SyncronizedArray.swift:239:42: warning: 'index(where:)'
    is deprecated: renamed to 'firstIndex(where:)'
                while let index = self.array.index(where: predicate) {
                                             ^
    /Users/ismailkhan/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.6.21/ios/Classes/lib/externalLibs/SyncronizedArray.swift:239:42: note: use
    'firstIndex(where:)' instead
                while let index = self.array.index(where: predicate) {
                                             ^~~~~
                                             firstIndex
    remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
    /Users/ismailkhan/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.6.21/ios/Classes/lib/utils/BitmapUtils.swift:163:11: warning: 'catch' block is
    unreachable because no errors are thrown in 'do' block
            } catch let error {
              ^
    /Users/ismailkhan/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.6.21/ios/Classes/lib/utils/BitmapUtils.swift:176:11: warning: 'catch' block is
    unreachable because no errors are thrown in 'do' block
            } catch let error {
              ^
    /Users/ismailkhan/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.6.21/ios/Classes/lib/externalLibs/SyncronizedArray.swift:100:42: warning: 'index(where:)'
    is deprecated: renamed to 'firstIndex(where:)'
            queue.sync { result = self.array.index(where: predicate) }

**Comment by capemsx** [comment]
I am experiencing the same issue!

**Comment by rafaelsetragni** [comment]
AMSupportURLConnectionDelegate? I don't know what class is this.

@capemsx  and @ismailkhan885 , can you recreate this issue, but now using the new template? There's some informations that i need to know from you to be capable to understand the problems that youre facing.

I gonna close this one and wait for the new one. Thanks!
