### ISSUE TITLE
iOS Multiple Custom Sounds - Only one custom sound is working

### ISSUE THREAD

**Issue by trqalothman** [rafaelsetragni/awesome_notifications#403]
Hello there,

I have setup my two channels, each with a different custom sound.  It is working fine on Android, however, on iOS first channel is working fine with the custom sound, second channel is only playing default notification sound of iOS.  Here is my setup:

```
AwesomeNotifications().initialize(
    'resource://drawable/res_notif_icon',
    [
      NotificationChannel(
        defaultColor: Colors.white,
        importance: NotificationImportance.Max,
        channelShowBadge: false,
        playSound: true,
        defaultPrivacy: NotificationPrivacy.Public,
        soundSource: 'resource://raw/res_software_interface_start',
        channelKey: 'names_channel',
        channelName: 'Names Channel',
        channelDescription:
            'Names Channel',
      ),
      NotificationChannel(
        defaultColor: Colors.white,
        importance: NotificationImportance.Max,
        channelShowBadge: false,
        playSound: true,
        defaultPrivacy: NotificationPrivacy.Public,
        soundSource: 'resource://raw/res_vintage_typewriter',
        channelKey: 'ads_channel',
        channelName: 'Ads_Channel',
        channelDescription: 'Ads Channel',
      ),
    ],
  );
```

Here is my PHP code to send the notification:

```
$fields = array(
      'to' => '/topics/adsTopic',
      'mutable_content' => true,
      'content_available' => true,
      'priority' => 'high',
      'data' => array(
        'content' => array(
          'channelKey' => 'ads_channel',
          'title' => 'Hello',
          'body' => 'My Name is ...',
          'notificationLayout' => 'BigPicture',
          'sound' => 'vintage_typewriter.caf',
          'showWhen' => true,
          // 'autoCancel' => true,
          // 'autoDismissible' => true,
          'privacy' => 'Public',
          'wakeUpScreen' => true,
          'largeIcon' => 'https://hackaday.com/wp-content/uploads/2017/01/zimmermann-telegram-featured.jpg',
          'bigPicture' => 'https://hackaday.com/wp-content/uploads/2017/01/zimmermann-telegram-featured.jpg',
        ),
      ),
    );
```

Here is how I call the package:

```
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  await AwesomeNotifications().createNotificationFromJsonData(message.data);
}

FirebaseMessaging.onBackgroundMessage(
            _firebaseMessagingBackgroundHandler);
        FirebaseMessaging.onMessage
            .listen((message) => _firebaseMessagingBackgroundHandler(message));
```

`Pubspec: awesome_notifications: ^0.6.19`

Flutter doctor:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 11.6.3 20G415 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)
```

Can anyone please help why it is working fine with the `names_channel` and not working on the second channel `ads_channel`.  Custom sound works fine with Android (both channels), on iOS custom sound only works with the first channel not the second :(

**Comment by trqalothman** [comment]
This is very weird, I have tried changing the sound file format from `caf` to `aiff` and always adding the files from xcode, and yet it is still not working.  Is it something from the package that prevents multiple sound files on iOS??

**Comment by trqalothman** [comment]
ok, it turns out that audio files in iOS must be named starting with `res_` and using the `aiff` file format :)  Hope this helps!

It is now working for the second audio file when using it as described above.

**Comment by mhdaslam790** [comment]
hey . can you help me with custom sound.i want to import sound from local storage 
and set it as custom sound

**Comment by apoleo88** [comment]
> ok, it turns out that audio files in iOS must be named starting with `res_` and using the `aiff` file format :) Hope this helps!
> 
> It is now working for the second audio file when using it as described above.

I had the same problem and I think the documentation should be a little clearer about that:
- The file need `res_` prefix.
- The file for android needs to be in `res/raw/` folder and in ios directly under Runner (as it is in the example)
- IOS does not support `.caf` file. It does support `.aiff`, but it does NOT work with `.aif`! It needs two `f`, even if they are the same thing, in fact, you can just manually add an extra `f`.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
