### ISSUE TITLE
0.7.0 async operations in listeners are not executed for SilentBackgroundAction

### ISSUE THREAD

**Issue by RobertHeim** [rafaelsetragni/awesome_notifications#416]
Async operations in the static event handlers are not executed for `SilentBackgroundAction`. For example:
```
class LocalNotificationListeners {
  static Future<void> onActionReceivedMethod(ReceivedAction receivedAction) async {
    print("start");
    final url = Uri.parse("http://google.com");
    final re = await http.get(url);
    print(re.body);
    print("done");
  }
}
```
While the `start` is printed, the `GET` request is never executed and the prints at the end are **not** printed either.

I think the reason might be, that flutter closes the spawned isolate after the method returns. I suggest that by default it uses a  `Future` that is `await`ed.

The workaround is to spawn another isolate from the event handler:

```
import 'dart:isolate';

class LocalNotificationListeners {
  static Future<void> onActionReceivedMethod(ReceivedAction receivedAction) async {
    Isolate.spawn(_handleReceivedAction, receivedAction);
  }

  static Future<void> _handleReceivedAction(ReceiveAction receivedAction) async {
    print("start");
    final uri = Uri.parse("http://google.com");
    final re = await http.get(uri);
    print(re.body);
    print("done");
  }
}
```

**Comment by rafaelsetragni** [comment]
Yes! You're totally right! Was an issue with long background process on awesome notifications beta.
I did a fixed version now. You just need to use the last reference available: 

`ref: "83443b7"`

**Comment by RobertHeim** [comment]
yes, the update solved it. Thanks.
