### ISSUE TITLE
Keep notification appears in the system tray for sometime ?

### ISSUE THREAD

**Issue by MaheshPeri19** [rafaelsetragni/awesome_notifications#42]
Hi,

Is it possible to keep notification in the system tray for atleast 30 seconds ?

I have checked this : https://github.com/rafaelsetragni/flutter_local_notifications

I am implementing video calling app and want action buttons in notification. I have checked other related packages callkeep. But it does require unnecessary permissions for telephone account and connection services, logs etc. Simply i want notification with answer and decline buttons with call back actions.   

rafaelsetragni/flutter_local_notifications project is perfect match for me. But problem is notification disappears after 2 seconds.

![Screenshot_20201124-010255](https://user-images.githubusercontent.com/58836654/100008096-ff178880-2df2-11eb-94ab-2ac1b767b1fb.jpg)

![Screenshot_20201121-201752](https://user-images.githubusercontent.com/58836654/100008562-9bda2600-2df3-11eb-9279-cd766e82a79c.jpg)

**Comment by swapnens** [comment]
+1

**Comment by rafaelsetragni** [comment]
Unfortunately not. The notification's duration in the tray (and also the duration of the song) is determined by the operating system. It is beyond our control in both platforms.

But you can configure your application to work with voip features. That way, you can activate your app with an incoming call to play and displays whatever you need. And if the user does not answer the call, you trigger a notification with all the details to alert him.

**Comment by MaheshPeri19** [comment]
Voip features means similar to Callkit in iOS and Connection service in Android ?

**Comment by rafaelsetragni** [comment]
Sincerely, I do not know. The only thing I know is that using the voip background features allows your application to be activated and perform extra background processing, but I don't know how to do it in details.

**Comment by MaheshPeri19** [comment]
Okay. Thank you. I will check it.

**Comment by MaheshPeri19** [comment]
@rafaelsetragni 

If you are android developer, Please help me this.

In your local notifications project sample, provided action buttons and call backs when click on those buttons. In below flutter call keep package, they have written displayCustomIncomingCall() method with answer and decline buttons, but no callbacks provided when click on answer or decline button.

Is it possible for you to add that code in your project, so that it looks like incoming call with answer and decline buttons ?

https://pub.dev/packages/flutter_callkeep
https://github.com/doneservices/flutter_callkeep

**Comment by rafaelsetragni** [comment]
But the action button has a callback method, fired on "actionStream" with the respective button key in it.

**Comment by MaheshPeri19** [comment]
Okay. I dont know android. I am from iOS background.
Is it possible to do that ?

**Comment by rafaelsetragni** [comment]
Yes,the action button brings the application to foreground and fires the actionStream event with the respective button key in it.

**Comment by MaheshPeri19** [comment]
Okay. Please. Not only me, but also so many are looking like this feature as callkeep and flutter_call_keep packages has some limitations.
