### ISSUE TITLE
Calling Notification in Background

### ISSUE THREAD

**Issue by MuhammadAliKust** [rafaelsetragni/awesome_notifications#423]
Thanks developer team for this awsome package. 

Im trying to implement calling in my app. In my scenerio im invoking CALL notification using fcm token. In foreground notification is working fine, it is ringing. 

But the problem is when the app is in background i did receive call notification but its not ringing just notification alert sound. And furthermore when i tap on reject button it is rejecting call but also sending me to the app. And no more notification when app killed.

I will highly thankfull if you help me in solving these issues. Thanks in advance

**Comment by rutvikbabariya** [comment]
Did you found anything?
