### ISSUE TITLE
bigPicture not showing after providing a http url image

### ISSUE THREAD

**Issue by Boanerges1996** [rafaelsetragni/awesome_notifications#427]
bigPicture not showing after providing a http url image, but notification shows

**Comment by rafaelsetragni** [comment]
Send me the url that are you trying to display.
Remembering that you meed to change the notification layout to display images.

**Comment by juarezfranco** [comment]
Set `notificationLayout: NotificationLayout.BigPicture,`

**Comment by Boanerges1996** [comment]
> Send me the url that are you trying to display. Remembering that you meed to change the notification layout to display images.

Working now
