### ISSUE TITLE
Notification is not showing when l exit the app

### ISSUE THREAD

**Issue by vicXvac** [rafaelsetragni/awesome_notifications#442]
Once l create the notification, everything works great, displaying, dismissing and so on, but when l schedule a notification and exit the app, it does not show until l open the app again

**Comment by vicXvac** [comment]
Eureka !!!!, its not an issue with the plugin, if you have turned on power saving mode which limits some apps from running in the background, notifications won't show, SOLUTION, make sure the app is allowed to run in the background on your device.

**Comment by novatov** [comment]
https://github.com/rafaelsetragni/awesome_notifications/issues/491
