### ISSUE TITLE
Notification Sound not working in iOS by using FCM.

### ISSUE THREAD

**Issue by MuhammadAliKust** [rafaelsetragni/awesome_notifications#443]
Hi, thanks for this awesome package. 

I have scenerio where i am receiving notification from web panel using FCM, 

```
FirebaseMessaging.onMessage.listen((RemoteMessage message) {
        print("Notification Called by using fcm onMessage");     
        RemoteNotification notification = message.notification!;
        AndroidNotification android = message.notification!.android!;
        if (notification.body!.contains(','))
          createNotification(
            title: 'Alert!',
            body: 'You have recieved an alert from admin!',
          );

        if (!notification.body!.contains(',')) if (notification != null &&
            android != null) {
          createNotification(
            title: notification.title.toString(),
            body: notification.body.toString(),
          );

        }
      });

```
 Where createNotification function is given as:
 
```
 Future<void> createNotification(
    {required String title, required String body}) async {
  await AwesomeNotifications().createNotification(
    content: NotificationContent(
        id: 1, channelKey: 'basic_channel', title: title, body: body),
  );
}
```

Its working fine in Android but when i try to invoke this notification from iOS i did receive notification, but no sound play on notification receive. Here is my code for awesome notification:

```
AwesomeNotifications().initialize(
    'resource://drawable/res_notification_app_icon',
    [
      NotificationChannel(
        channelKey: 'basic_channel',
        channelName: 'Basic Notifications',
        defaultColor: Colors.teal,
        importance: NotificationImportance.High,
        channelShowBadge: true,
        channelDescription: '',
      ),
    ],
  );
```

**Comment by samirasalah** [comment]
Hi, I have same prob, do you resole it ?

**Comment by MuhammadAliKust** [comment]
No still facing same issue

**Comment by rafaelsetragni** [comment]
Try to check out our example app in our GitHub repository. Is the folder called example. Try to run the example app and see if the notifications sound is not playing as well.

**Comment by MuhammadAliKust** [comment]
on calling notification locally it works fine even in my app but when i try to call same notification using fcm then no sound at all :(

**Comment by MuhammadAliKust** [comment]
Hi Im going to close this issue, basically there is no issue on notification end, rather missing sound attribute in fcm api,

![image](https://user-images.githubusercontent.com/55309828/161414919-ddf9ec02-0d0c-4f6e-90b1-fdf4bf34dd9e.png)

**Comment by samirasalah** [comment]
Hi everybody, my problem is that the notification in background is not
working when building release. I need help

**Comment by MuhammadAliKust** [comment]
Cannot say anything without diving into the code.
