### ISSUE TITLE
Scheduling not working

### ISSUE THREAD

**Issue by ModernChocolate** [rafaelsetragni/awesome_notifications#47]
I've scheduled a notification with NotificationSchedule but it is not shown. 
```dart
var fiveSecondsDelayed = DateTime.now().add(Duration(seconds: 5));
await AwesomeNotifications().createNotification(content: NotificationContent(id: 111, channelKey: "alarm", title: 'scheduled title', body: 'scheduled body'), schedule: NotificationSchedule(initialDateTime: fiveSecondsDelayed));```

**Comment by rafaelsetragni** [comment]
And what platform, plugin version and flutter version are you using?

**Comment by ModernChocolate** [comment]
By the way, I just replaced my scheduling by :
```dart
NotificationSchedule(preciseSchedules: [DateTime.now().add(Duration(seconds: 5)).toUtc()])
```
and it finally worked. But I don't understand why.

**Comment by rafaelsetragni** [comment]
The initial date is the most priority date component, it should have worked.
And what platform, plugin version and flutter version are you using?

**Comment by ModernChocolate** [comment]
Yes it should but visibly what was missing was the `.toUtc()`...

**Comment by ModernChocolate** [comment]
I'm using Android, using source (git) and Flutter 1.22.4

**Comment by rafaelsetragni** [comment]
> Yes it should but visibly what was missing was the .toUtc()...

Yes. All schedule dates work in the UTC time zone. For most internal systems to work, it is the most effective way to surround time zone madness. And I strongly recommend that you use it.

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/-5wpm-gesOY/0.jpg)](https://www.youtube.com/watch?v=-5wpm-gesOY)
The Problem with Time & Timezones - Computerphile (Youtube)

**Comment by ModernChocolate** [comment]
Ok ! Finally is there any way to remove the toast notification when getting a scheduled notification ? (it doesn't disappears in release mode)

**Comment by rafaelsetragni** [comment]
Yes. Of course! Comment this line.

**Comment by ModernChocolate** [comment]
Nice thank you !
