### ISSUE TITLE
NotificationChannel - soundSource not working [Android - iOS]

### ISSUE THREAD

**Issue by efraespada** [rafaelsetragni/awesome_notifications#48]
First of all thanks for this library 😀

I tried to use the `soundSource` param when defining the `NotificationChannel` but it doesn't work when the notification is displayed.

```dart
NotificationChannel(
      channelKey: 'channel_call',
      channelName: 'channel name',
      channelDescription: 'channel description',
      importance: NotificationImportance.Max,
      playSound: true,
      soundSource: 'asset://audio/ringtone.mp3',
);
```

**Comment by rafaelsetragni** [comment]
Not all file formats are accepted. And it depends on what platform you are running.

Please, check in the respective platform documentation what are the acceptable media types.

**Comment by efraespada** [comment]
😅 I was doing two mistakes:

**iOS**: In Xcode, I forget to include the `aiff` audio file in all the `Target Membership` options.
**Android**: The `channelKey` param can't contain _**channel**_.

```dart
NotificationChannel(
      channelKey: 'channel_call',
);
```
```dart
NotificationChannel(
      channelKey: 'call',
);
```

Consider include these details in the README.md file.
