### ISSUE TITLE
Error with extra step in 0.7.0-beta.2

### ISSUE THREAD

**Issue by TimeLord2010** [rafaelsetragni/awesome_notifications#480]
I'm trying to compile my app in IOS but I was having MissingImplementationException in AwesomeNotification.initialize.

I then noticed that this plugin as a beta version and in that, it requires a extra step for the IOS platform. However, I keep getting errors.

If I copy the following lines:

```swift
SwiftAwesomeNotificationsPlugin.setPluginRegistrantCallback { registry in          
    SwiftAwesomeNotificationsPlugin.register(
      with: registry.registrar(forPlugin: "io.flutter.plugins.awesomenotifications.AwesomeNotificationsPlugin")!)          
    FLTSharedPreferencesPlugin.register(
      with: registry.registrar(forPlugin: "io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin")!)
}
```

To AppDelegate.swift, the I get:
`.../ios/Runner/AppDelegate.swift:11:5: error: cannot find 'SwiftAwesomeNotificationsPlugin' in scope`

But according to the plugin guide: "And you can check how to correctly call each plugin opening the file GeneratedPluginRegistrant.m". And in my GeratedPluginRegistrant.m, I cannot find `SwiftAwesomeNotificationsPlugin`. But I do find `AwesomeNotificationsPlugin`.

So I rewrite the code to:

```swift
AwesomeNotificationsPlugin.setPluginRegistrantCallback { registry in          
    AwesomeNotificationsPlugin.register(
      with: registry.registrar(forPlugin: "io.flutter.plugins.awesomenotifications.AwesomeNotificationsPlugin")!)          
    FLTSharedPreferencesPlugin.register(
      with: registry.registrar(forPlugin: "io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin")!)
}
```

But I just get the same error, but updated: 
`.../ios/Runner/AppDelegate.swift:11:5: error: cannot find 'AwesomeNotificationsPlugin' in scope`

Am I missing an import?

**Comment by TimeLord2010** [comment]
Fix

```swift
import shared_preferences_ios
import flutter_background_service_ios
```

**Comment by Divish1032** [comment]
Does above fix solved your problem? @TimeLord2010

**Comment by TimeLord2010** [comment]
It did. But I had to make some changes after:

```swift
import UIKit
import Flutter
import awesome_notifications
import shared_preferences_ios
import flutter_background_service_ios

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    FlutterBackgroundServicePlugin.setPluginRegistrantCallback { registry in
        GeneratedPluginRegistrant.register(with: registry)
    }
    SwiftAwesomeNotificationsPlugin.setPluginRegistrantCallback { registry in          
      SwiftAwesomeNotificationsPlugin.register(
        with: registry.registrar(forPlugin: "io.flutter.plugins.awesomenotifications.AwesomeNotificationsPlugin")!)          
      FLTSharedPreferencesPlugin.register(
        with: registry.registrar(forPlugin: "io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin")!)
    }
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}

```

**Comment by nurhazbiy** [comment]
hi, suddenly out of nowhere, i can't build my apps on ios anymore, i suspect because of this step. here is the error logs

```


Swift Compiler Error (Xcode): Cannot find 'FLTSharedPreferencesPlugin' in scope
/Users/hazbiy/Data/Kerja/Freelance/Project/Risearrow/Flutter/ios/Runner/AppDelegate.swift:17:12


Encountered error while building for device.
```

I think it's because i remove shared preferences on my main package because i moved it on my secondary packages, and when i check on pubscpec.lock, i can't find any line stating that shared_preferences_ios is installed (meanwhile all other shared_preferences is installed, even for web and linux). does it mean i need to manually include it in my apps? i thought it would be included by the awesome notification package
