### ISSUE TITLE
The number of action buttons is limited to 3

### ISSUE THREAD

**Issue by GergelyH** [rafaelsetragni/awesome_notifications#483]
If I pass more than 3 action buttons to createNotification() only the first 3 shows up. How can I display more than 3 actions?

**Comment by rafaelsetragni** [comment]
This is a platform limitation. There's no way to display more buttons than 3.

**Comment by GergelyH** [comment]
![Screenshot_2022-04-30-17-49-02-898_com mi android globallauncher](https://user-images.githubusercontent.com/28755242/166112721-f970281c-d45e-4adb-abbe-4eed737d506a.jpg)
YouTube Vanced player has 4 actions, how could they get around the limitation?

**Comment by rafaelsetragni** [comment]
This is a media player notification. There's an example on how to implement it on our example app.

**Comment by GergelyH** [comment]
Got it, thank you!
