### ISSUE TITLE
intl version mismatch

### ISSUE THREAD

**Issue by Chris1234567899** [rafaelsetragni/awesome_notifications#49]
Trying to install it, I receive this error message: 
```
Running "flutter pub get" in myApp...
Because every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2 and every version of awesome_notifications depends on intl ^0.16.1, flutter_localizations from sdk is incompatible with awesome_notifications. 

So, because myApp depends on both awesome_notifications ^0.0.5+2 and flutter_localizations any from sdk, version solving failed.
pub get failed
```

Looks like a version mismatch. A dependency update should do it.

flutter version:
Flutter (Channel master, 1.24.0-8.0.pre.374, on Microsoft Windows [Version 10.0.18363.1198], locale de-DE)

**Comment by Chris1234567899** [comment]
A temporary fix might be putting:

```
dependency_overrides:
  intl: ^0.16.1
```
in the pubspec.yaml

Seems to work for now, but on the long run updating the package might be better.

**Comment by rafaelsetragni** [comment]
No, update the intl version inside awesome _notification. Always use the most updated plugin version.

Change it here:

https://github.com/rafaelsetragni/awesome_notifications/blob/b3e4da96f0302fef43f4c801d819dad044021332/pubspec.yaml#L16

I gonna update it in next release. Thanks for advice.

**Comment by rafaelsetragni** [comment]
Sorry, but your intl version 0.17.0-null safety.2 does not seem to be a master version, so it was not able to update it in next release.
But you can change it to your local files, without any problems.
