### ISSUE TITLE
The release version sometimes doesn't work on Android 10 or later.

### ISSUE THREAD

**Issue by Mehdigithubuser** [rafaelsetragni/awesome_notifications#490]
Hello everybody
I use the "createNotification" method with schedule property (at 11:00 every day). It works fine on Android 9 or lower, but in the release version of the app (.apk), it sometimes doesn't work only on Android 10 and higher, especially after the device reboots. (for example on an Android 11 device, A notification is received after ten days).

**tested solutions:**
1. using previous versions of the "awesome_notification" package (with and without the ^ symbol).
2. tried all 3 of [these](https://github.com/rafaelsetragni/awesome_notifications/issues/29#issuecomment-725412723).

**My expectation:**
get a notification every day at 11:00 on all Android versions.

**The outcome**:
Android 9 and lower: receive notifications properly every day even after the device reboots.
Android 10 and higher:
before rebooting the device:  The notification sometimes is received.
After rebooting the device: The notification won't be received.

**package version**:
awesome_notifications: ^0.6.21

**flutter doctor**:

[√] Flutter (Channel stable, 2.10.3, on Microsoft Windows [Version 10.0.22000.493], locale en-US)
    • Flutter version 2.10.3 at D:\Software\flutter_windows_2.8.0-stable_3\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7e9793dee1 (3 months ago), 2022-03-02 11:23:12 -0600
    • Engine revision bd539267b4
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at D:\Software\Android_sdk
    • Platform android-31, build-tools 32.0.0
    • ANDROID_SDK_ROOT = D:\Software\Android_sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[X] Chrome - develop for the web (Cannot find Chrome executable at .\Google\Chrome\Application\chrome.exe)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)

[√] VS Code, 64-bit edition (version 1.66.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.40.0

[√] Connected device (2 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.493]
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 101.0.1210.47

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 2 categories.

**code snippet**:

`AwesomeNotifications().initialize(

    null,

    [

      NotificationChannel(

        channelGroupKey: 'basic_channel_group',

        channelKey: 'basic_channel',

        channelName: 'Basic notifications',

        channelDescription: 'Notification channel for basic tests',

        // defaultColor: const Color(0xFF9D50DD),

        importance: NotificationImportance.High,

        channelShowBadge: true,

      )

    ],

  );`

`Future<void> scheduleNotification() async {

    String localTimeZone =

        await AwesomeNotifications().getLocalTimeZoneIdentifier();

    await AwesomeNotifications().createNotification(

        content: NotificationContent(

          id: 0,

          channelKey: 'basic_channel',

          title: 'Notification title',

          body: 'Notification body',

          notificationLayout: NotificationLayout.Default,

          // criticalAlert: true

        ),

        schedule: NotificationCalendar(

          allowWhileIdle: true,

          timeZone: localTimeZone,

          hour: 11,

          minute: 0,

          second: 0,

          repeats: true,

          preciseAlarm: false,

        ));
  }`

Also, I tried with preciseAlarm: true. But I didn't get any notification after the device rebooted.

I appreciate any help🙏

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
