### ISSUE TITLE
Firebase onMessage listener not working when awsome_notifications is installed

### ISSUE THREAD

**Issue by maximiliannocker** [rafaelsetragni/awesome_notifications#493]
Hi,

If I install awesome_notification then the Firebase onMessage listener in not working anymore. Also other firebase messaging listeners are not working too. Then If I remove the plugin it works again. I hope you can make a fix that works for firebase messaging

**Comment by nsivraj** [comment]
For me this seems to only happen on iOS. On Android it is working fine.

**Comment by maximiliannocker** [comment]
Yes it happens only on iOS

**Comment by gadgetreviews** [comment]
and what is solution for this? If I can not find a solution, I have to use another package.

**Comment by Glexium** [comment]
What version of firebase_messaging are you using?, it works up to firebase_messaging: ^10.0.9, maybe the problem is some change on firebase_messaging after that version.

**Comment by gadgetreviews** [comment]
> What version of firebase_messaging are you using?, it works up to firebase_messaging: ^10.0.9, maybe the problem is some change on firebase_messaging after that version.

11.4.0

**Comment by clockwork189** [comment]
I tried downgrading the plugin to 0.7.0-beta.2 and it works fine, however does not work with latest beta version of the plugin. I tried 0.7.0-beta.3+2 and 0.7.0-beta.3+1  with no luck either.

**Comment by duykhanhhs1** [comment]
It still happens only on iOS, any ideas?

**Comment by duykhanhhs1** [comment]
> I tried downgrading the plugin to 0.7.0-beta.2 and it works fine, however does not work with latest beta version of the plugin. I tried 0.7.0-beta.3+2 and 0.7.0-beta.3+1 with no luck either.

What version of firebase_messaging are you using?

**Comment by clockwork189** [comment]
At the time I was using firebase_messaging 11.4.0. I have tried with 11.4.1 and still the same issue.

**Comment by duykhanhhs1** [comment]
> At the time I was using firebase_messaging 11.4.0. I have tried with 11.4.1 and still the same issue.

I have tried with firebase_messaging 11.4.0 and awesome_notification 0.7.0-beta.2 but the same issue still happens. Maybe I have to use another package

**Comment by clockwork189** [comment]
I am not sure what ended up changing, if it was something with the other dependencies in my project or what, however the onMessage firebase function "magically" started working for me

**Comment by duykhanhhs1** [comment]
![image](https://user-images.githubusercontent.com/74110768/173268819-a6f409bc-4229-4e81-b84b-28dc06d63786.png)

@clockwork189

**Comment by lore-co** [comment]
So what do we do? Do we have to consider the lib unusable together with Firebase Messaging on iOS? Is this going to be fixed? Is this going to remain?

**Comment by Shams-Mahmoud** [comment]
any updates??

**Comment by eduardo-and** [comment]
Guys, this worked for me

using:
 firebase_messaging: 13.0.1
 awesome_notifications: 0.7.0-beta.6+1

https://github.com/firebase/flutterfire/issues/8065#issuecomment-1087062719

**Comment by eduardo-and** [comment]
Guys, this worked for me:
https://github.com/firebase/flutterfire/issues/8065#issuecomment-1087062719

 using versions:
-  firebase_messaging: 12.0.3
-  awesome_notifications: 0.6.21
or last versions

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
