### ISSUE TITLE
Assertion Error while initializing on iOS

### ISSUE THREAD

**Issue by aaqibism** [rafaelsetragni/awesome_notifications#5]
For some reason I am not able to initialize the plugin on iOS. I believe it's because I am incorrectly accessing the native assets. How do I correctly choose an xcasset for initializing the plugin? Is there any way to simply choose the app icon?

```
await AwesomeNotifications().initialize(
    Platform.isIOS ? 'AppIcon' : 'resource://drawable/notification',
    [
      NotificationChannel(
        channelKey: 'basic_channel',
        channelName: 'Basic notifications',
        channelDescription: 'Notification channel for basic tests',
        defaultColor: Colors.blueAccent,
        ledColor: Colors.blueAccent,
        channelShowBadge: true,
        importance: NotificationImportance.Max,
      ),
	],
);
```
![image](https://user-images.githubusercontent.com/42590291/93801253-90e9f600-fbf6-11ea-8bc1-88d27acfae08.png)

**Comment by rafaelsetragni** [comment]
The iOS version did not go to master version yet. Im doing it on a new branch that you could check it [here](https://github.com/rafaelsetragni/awesome_notifications/tree/Android-Code-Rewrite-to-Swift)

Im constantly updating this branch and i didnt finished yet, but you could check it, for curiosity.

On master one, the iOS code stills empty.
