### ISSUE TITLE
While running "flutter build apk" show error Task 'assembleAarRelease' not found in root project 'awesome_notifications'

### ISSUE THREAD

**Issue by woinbo** [rafaelsetragni/awesome_notifications#51]
In debug mode, the app and plugin run smoothly but while building release apk flutter gives error: 

* What went wrong:
Task 'assembleAarRelease' not found in root project 'awesome_notifications'.

**Comment by rafaelsetragni** [comment]
Try this one:
https://stackoverflow.com/questions/62357322/how-to-fix-this-error-task-assembleaarrelease-not-found-in-root-project-flutt

**Comment by woinbo** [comment]
@rafaelsetragni Thanks for the solution, it is working fine now.
