### ISSUE TITLE
NotificationLayout

### ISSUE THREAD

**Issue by hardik-weenggs** [rafaelsetragni/awesome_notifications#52]
**macOS Catalina (10.15.5)
Samsung m30s
Android 10 (Q)
awesome_notifications: ^0.0.5+2**

- i'm getting the following error when i used **_notificationLayout: NotificationLayout.BigText_**.  but when i passed more texts in `body` then it's working. why it's not working for small text?.    

**(not working)**
`body:  "Lorem ipsum dolor sit amet, consectetur".`

**(working)**
`body:  "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation."`

**_//////////////// ERROR_**

`W/System.err: java.lang.IndexOutOfBoundsException: getChars (0 ... 49) ends beyond length 11
W/System.err:     at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1325)
W/System.err:     at android.text.SpannableStringBuilder.getChars(SpannableStringBuilder.java:1205)
W/System.err:     at android.text.TextUtils.getChars(TextUtils.java:154)
W/System.err:     at android.text.SpannableStringBuilder.<init>(SpannableStringBuilder.java:68)
W/System.err:     at android.text.SpannableStringBuilder.subSequence(SpannableStringBuilder.java:1197)
W/System.err:     at me.carda.awesome_notifications.notifications.NotificationBuilder.setBigTextStyle(NotificationBuilder.java:586)
W/System.err:     at me.carda.awesome_notifications.notifications.NotificationBuilder.setLayout(NotificationBuilder.java:514)
W/System.err:     at me.carda.awesome_notifications.notifications.NotificationBuilder.getNotificationBuilderFromModel(NotificationBuilder.java:185)
W/System.err:     at me.carda.awesome_notifications.notifications.NotificationBuilder.createNotification(NotificationBuilder.java:83)
W/System.err:     at me.carda.awesome_notifications.notifications.NotificationSender.showNotification(NotificationSender.java:190)
W/System.err:     at me.carda.awesome_notifications.notifications.NotificationSender.doInBackground(NotificationSender.java:121)
W/System.err:     at me.carda.awesome_notifications.notifications.NotificationSender.doInBackground(NotificationSender.java:25)
W/System.err:     at android.os.AsyncTask$3.call(AsyncTask.java:378)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at java.lang.Thread.run(Thread.java:919)`

**_////////////////**

- When i use **_notificationLayout: NotificationLayout.BigText_**  `body` content is displayed 2 times. how can i remove it?
- check below images.

**- NotificationLayout.BigText**

![img_bigtext_notif](https://user-images.githubusercontent.com/73572548/100877481-d9634100-34ce-11eb-8567-77b4c159ab7f.png)

**- DEFAULT**
![img_default_notif](https://user-images.githubusercontent.com/73572548/100877689-25ae8100-34cf-11eb-8773-92e1e69ce388.png)

**Comment by rafaelsetragni** [comment]
Unfortunately, the layouts are still not fully working for iOS. I haven't finished AwesomeContentExtension yet, which will be responsible for creating these extra layouts for iOS.

The challange that i facing now is how to create these layouts only using swift, and not a storyboard. Or how to include the storyboard inside the plugin.

**Comment by hardik-weenggs** [comment]
- It is also not working on **Android 9** device. I have tested in '**Redmi Note 6 Pro**' device. 
- The error occurs when the length of the 'body' text is less than 50. it works fine if the length of the 'body' text is greater than 50. 

can you set dynamically if **notificationLayout** is `**_BigText_**` ?

`java.lang.IndexOutOfBoundsException: getChars (0 ... 49)`

**Comment by derBeukatt** [comment]
I provided a potential fix in https://github.com/rafaelsetragni/awesome_notifications/pull/55.

**Comment by rafaelsetragni** [comment]
Great!
I merged your fix into master. Soon i gonna release a new version with your fix as well. Thank you so much!

**Comment by hardik-weenggs** [comment]
i will check.
Thanks.
