### ISSUE TITLE
Question about ios behaviour 

### ISSUE THREAD

**Issue by ahmetakil** [rafaelsetragni/awesome_notifications#53]
Hi, Sorry for this issue but I have a quick question, 

I need to catch the notification payload and save it to the local storage even if the ios app is terminated
or
I need to catch the notification and show/update the badge on the launcher icon.

I've been trying to accomplish this using several different versions of fcm
Ios shows the notification but it seems like there is no way to actually handle it before the app opens. 

Can this plugin achieve this behavior?
Thanks.

**Comment by rafaelsetragni** [comment]
> I need to catch the notification payload and save it to the local storage even if the ios app is terminated

Yes. Even when the application is terminated/ killed, streams are stored locally. This storage is managed by the plugin, but will be delivered as soon as you initialize the plugin. That way, you can do whatever you want at this point.

> I need to catch the notification and show/update the badge on the launcher icon.

Yes. The badge indicator is updated automatically and instantly over any application lifecycle, you just need to create a channel with `channelShowBadge` set to True and send the notification using this channel. In addition, you can manually update the badge indicator at any time on iOS and Android using your flutter code.

And you don't need to use any other firebase messaging packages to get push notifications. Just follow the steps inside the README file and you are ready to go.

**Comment by ahmetakil** [comment]
Hi, thanks for the response so I implemented the plugin registered a Channel with the name 'badge_channel', and whenever the application is in the foreground or background the notifications work very well. 

I get the notifications and they automatically increment the badge. 

But whenever the application is terminated I only see the title of the notification object from the payload (not the data)
and it does not increment the badge 

I saw the ios extra configurations section in the readme is there something I need to implement from there?
Thanks.

**Comment by ahmetakil** [comment]
Also here is my payload: 

```
{
    "to":"<token>",
    "mutable_content" : true,
    "content_available": true,
    "notification": {
        "title": " "
    },
    "data" : {
        "content": {
            "id": 100,
            "channelKey": "badge_channel",
            "title": "Notification Title",
            "body": "Notification body"
        }
    }
}
```

**Comment by ahmetakil** [comment]
So I did implement the NotificationServiceExtension and NotificationContentExtension by following the steps in the readme file but unfortunately it still only shows the notification title does not update the badge and does not trigger the alarm sound

**Comment by rafaelsetragni** [comment]
I believe you are gettin the same dificult as this topic:

https://github.com/rafaelsetragni/awesome_notifications/issues/41

**Comment by ahmetakil** [comment]
Wow, it worked, 

I really don't know what to say, we have been working on this for almost 3 weeks. You sir saved us

Thank you very much
