### ISSUE TITLE
Playing sound when receiving notification worked in Development but not in Production

### ISSUE THREAD

**Issue by FatehP** [rafaelsetragni/awesome_notifications#530]
I'm Facing an issue when i Debug Project in Real Device, I'm Getting Notification With Custom Sound, But After making a Build Via Diwai, I'm Not Getting Custom Sound, It Play Default Sound with Notification.I'm Using Firebase. I have Added Custom Sound in Project and added in Bundle Resources as well. Please Have A look on My Code.

**My Code  In App Delegate**

      `class AppDelegate: UIResponder, UIApplicationDelegate,UNUserNotificationCenterDelegate, MessagingDelegate {

     var window: UIWindow?
    var audioPlayer : AVAudioPlayer?

       func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // Override point for customization after application launch.

        let content = UNMutableNotificationContent()
        content.sound = UNNotificationSound.default
        content.sound = UNNotificationSound(named:UNNotificationSoundName(rawValue: "Eigenintro.aiff"))

        FirebaseApp.configure()

        
        let audioSessionError: Error? = nil
        do {
            try AVAudioSession.sharedInstance().setCategory(.playback, options: .mixWithOthers)
            try AVAudioSession.sharedInstance().setActive(true)
        } catch let audioSessionError {
            print(audioSessionError.localizedDescription)
        }
       
        UIApplication.shared.beginReceivingRemoteControlEvents()

        if let audioSessionError = audioSessionError {
            print("[AppDelegate] audioSessionError: \(audioSessionError)")
        }

        if #available(iOS 10.0, *) {
            // For iOS 10 display notification (sent via APNS)
            UNUserNotificationCenter.current().delegate = self
            Messaging.messaging().isAutoInitEnabled = true

            let authOptions: UNAuthorizationOptions = [.alert, .badge, .sound]
            UNUserNotificationCenter.current().requestAuthorization(
                options: authOptions,
                completionHandler: { [self] _, _ in
                    Messaging.messaging().delegate = self

                }
            )
        } else {
            let settings: UIUserNotificationSettings =
            UIUserNotificationSettings(types: [.alert, .badge, .sound], categories: nil)
            application.registerUserNotificationSettings(settings)

        }
        
        
                    

        Messaging.messaging().token { token, error in
            if let error = error {
                print("Error fetching FCM registration token: \(error)")
            } else if let token = token {
                print("FCM registration token: \(token)")
            }
        }
        application.registerForRemoteNotifications()
        return true
    }

         func messaging(_ messaging: Messaging, didReceiveRegistrationToken fcmToken: String?) {
           print("Firebase registration token: \(String(describing: fcmToken))")
          self.sendDataToServer(token: fcmToken!)
          }

    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                willPresent notification: UNNotification,
                                withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions)
                                -> Void) {
        let userInfo = notification.request.content.userInfo
        
         defer {
            completionHandler([.badge,.sound, .alert])
            SoundPlayer.sharedInstance.playSound()
         }
        
        print(#function)
        print(userInfo)

    }

    func userNotificationCenter(_ center: UNUserNotificationCenter,
                                didReceive response: UNNotificationResponse,
                                withCompletionHandler completionHandler: @escaping () -> Void) {
        let userInfo = response.notification.request.content.userInfo

       

        print(#function)
        print(userInfo)
        completionHandler()
    }

           func application(_ application: UIApplication,
                 didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
    let token = deviceToken.hexString
    
    print("APNs Device Token: \(token)")
    #if DEVELOPMENT
    Messaging.messaging().apnsToken = deviceToken
    
    #else
    Messaging.messaging().setAPNSToken(deviceToken, type: .prod)
    #endif
    
    }

           func application(_ application: UIApplication,
                 didReceiveRemoteNotification userInfo: [AnyHashable : Any],
                 fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {

    print(#function)
    Messaging.messaging().appDidReceiveMessage(userInfo)
    
    if application.applicationState == .background {
     
           guard let soundURL = Bundle.main.url(forResource: "Eigenintro", withExtension: "aiff") else { return }
            //let soundUrl = URL(fileURLWithPath: path)
            do {
                audioPlayer = try AVAudioPlayer(contentsOf: soundURL)

                print("[AppDelegate] audioPlayer play call")
                audioPlayer!.play()
            } catch let audioPlayerError {
                print("[AppDelegate] audioPlayerError: \(audioPlayerError)")
            }
        completionHandler(UIBackgroundFetchResult.newData)
        

        
         } else {
        completionHandler(UIBackgroundFetchResult.noData)
         }
         }

        // foreground
           func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable: Any]) {
        print("didReceiveRemoteNotification: Received new push Notification")
        Messaging.messaging().appDidReceiveMessage(userInfo)
         print(#function)
        print("didReceiveRemoteNotification: Push notificationMessage is: \(userInfo)")
       }
       }`

     **Payload**

       `{
       "message": {
      "token": "fcm token",
      "notification": {
      "title": "Breaking News",
       "body": "New news story available."
 
          },
         "apns": {
           "payload": {
           "aps": {
         "category" : "NEW_MESSAGE_CATEGORY",
         "sound": "Eigenintro.aiff"
        }
        }
       }
       }
      }`

**Comment by rafaelsetragni** [comment]
You need to protect your media resources from minification and obfuscation. There is a topic dedicated to this in our documentation and also in the Android documentation.

**Comment by rafaelsetragni** [comment]
Hi! Sorry for taking so long to respond to your issue on GitHub. I was focused on releasing the new 0.7.0 version of `awesome_notifications` and `awesome_notifications_fcm` and i didn't had time enough to do both. But now I can answer all your questions.

So now i'm asking you to recreate this topic using the new issue template. There's a lot of missing informations that i need to understand your problem, and all the instructions are already in the new issue template. Also, remember to check beforehand if your issue was posted by another user.

So I will automatically close all previous issues so far.
Sorry for the inconvenience and i will be waiting for your new issue request.

Thank you so much for your support!
