### ISSUE TITLE
example don't work with MissingPluginException

### ISSUE THREAD

**Issue by JLFFFF** [rafaelsetragni/awesome_notifications#532]
when I run the example in a real device(android 12), the ERROR was like this:
[ +850 ms] E/flutter (23401): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method initialize on channel awesome_notifications)
[        ] E/flutter (23401): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
[        ] E/flutter (23401): <asynchronous suspension>
[        ] E/flutter (23401): #1      AwesomeNotifications.initialize (package:awesome_notifications/src/awesome_notifications_core.dart:174:18)
[        ] E/flutter (23401): <asynchronous suspension>

[ +220 ms] E/flutter (23401): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method isNotificationAllowed on channel awesome_notifications)
[        ] E/flutter (23401): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
[        ] E/flutter (23401): <asynchronous suspension>
[        ] E/flutter (23401): #1      AwesomeNotifications.isNotificationAllowed (package:awesome_notifications/src/awesome_notifications_core.dart:314:9)
[        ] E/flutter (23401): <asynchronous suspension>
[        ] E/flutter (23401): 

and when the button was tapped,the ERROR was the same MissingPluginException error.

I tried `flutter clean`, it  did not work.

anyone can help me ~~~~~~

**Comment by rafaelsetragni** [comment]
You're trying to use the plugin while it's not registered on flutter engine. I saw that happen when you run any process inside isolate on iOS. On these cases, you need to register the plugin with the native registrar methods. You can check how to do it in the readme file, on extra iOS steps.

Also, this happens when you manually detach the plugins from flutter engine.

Have you took a look at the example app in our GitHub repository?

**Comment by JLFFFF** [comment]
It showed an Warning  before：Warning: Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. And Build failed due to use of deprecated Android v1 embedding. So，I build --ignore-deprecation.

**Comment by JLFFFF** [comment]
It showed a warning before：Warning: Your Flutter application is created using an older version of the Android
embedding. It's being deprecated in favor of Android embedding v2. And Build failed due to use of deprecated Android v1 embedding. So, I build `--ignore-deprecation. `and it causes the plugin not register on flutter engine.  

I try to remove this line  `android:name="io.flutter.app.FlutterApplication"` in  AndroidManifest.xml. it works~
