### ISSUE TITLE
me.carda.awesome_notifications.notifications.exceptions.AwesomeNotificationException: Notification channel 'notifications' does not exist.

### ISSUE THREAD

**Issue by toblinkz** [rafaelsetragni/awesome_notifications#553]
I  created channel name with notification but this error is showing only in release mode and using awesome_notifications: ^0.6.21

 me.carda.awesome_notifications.notifications.exceptions.AwesomeNotificationException: Notification channel 'notifications' does not exist.
W/System.err(19827): 	at me.carda.awesome_notifications.notifications.models.NotificationContentModel.validate(NotificationContentModel.java:283)
W/System.err(19827): 	at me.carda.awesome_notifications.notifications.models.NotificationModel.validate(NotificationModel.java:130)
W/System.err(19827): 	at me.carda.awesome_notifications.notifications.NotificationSender.send(NotificationSender.java:77)
W/System.err(19827): 	at me.carda.awesome_notifications.AwesomeNotificationsPlugin.channelMethodCreateNotification(AwesomeNotificationsPlugin.java:1040)
W/System.err(19827): 	at me.carda.awesome_notifications.AwesomeNotificationsPlugin.onMethodCall(AwesomeNotificationsPlugin.java:478)
W/System.err(19827): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
W/System.err(19827): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
W/System.err(19827): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:319)
W/System.err(19827): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)
W/System.err(19827): 	at android.os.Handler.handleCallback(Handler.java:883)
W/System.err(19827): 	at android.os.Handler.dispatchMessage(Handler.java:100)
W/System.err(19827): 	at android.os.Looper.loop(Looper.java:237)
W/System.err(19827): 	at android.app.ActivityThread.main(ActivityThread.java:8167)
W/System.err(19827): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(19827): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
W/System.err(19827): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by rafaelsetragni** [comment]
Now the last versions are `awesome_notifications: ^0.7.2` and  `awesome_notifications_fcm: ^0.7.2`.

**Comment by haleem13** [comment]
I had the same problem. and I forgot to initialize the local notification, which got the desired channel defined in it.
So if anyone else get this problem, Please make sure you initialize the Awesome local notification in your main.dart
