### ISSUE TITLE
NotificationCategory.Alarm does not work on iOS

### ISSUE THREAD

**Issue by tatraef** [rafaelsetragni/awesome_notifications#554]
Tried NotificationCategory.Alarm, on android it repeats the sound until you click on the notification, but not on iOS, the sound is played only once.
```
NotificationContent(
      id: Random().nextInt(2147483647),
      channelKey: content['channelKey'],
      title: content['title'],
      body: content['body'],
      notificationLayout: NotificationLayout.BigText,
      category: NotificationCategory.Alarm,
    )
```

Flutter Version : 3.3.0
Awesome Notification Version : 0.7.0-beta.6+1

**Comment by WillowWisp** [comment]
Got the same issue with iPhone 13 (iOS 15.5). It seems like what affected this is an app's notification setting called "Banner Style", which is set to "Temporary" by default. After manually switching it to "Persistent", this would behave as expected.

Is there any way to set the "Banner Style" to "Persistent" on runtime when the `category` is set to `NotificationCategory.Alarm`?

**Comment by tatraef** [comment]
@WillowWisp when you manually switching it to "Persistent", the sound is played many times? I have only once, unlike android, the sound is looped there.

**Comment by rafaelsetragni** [comment]
On iOS calls are not handle by notifications, instead they use `CallKit`.

Also, on iOS there is not locked / persistent notifications. According our heuristics, Awesome tries to use the maximum resources as possible to create the notifications, but if the resource does not exists, it will be ignored. And there is so differences between Android distributions as between Android and iOS, this is the best approach in most cases.
