### ISSUE TITLE
APK Release Background Notifications

### ISSUE THREAD

**Issue by appwebprogrammer** [rafaelsetragni/awesome_notifications#555]
I use awesome notification of call category in flutter and it works perfect in debug mode, when i build apk or build release apk the notification not working, note: i use firebase fcm to display notification, in foreground works fine but when app is terminated or background not displayed

@rafaelsetragni  can you help me to solve this issue this stop my company project

**Comment by rmasarovic** [comment]
hi i have same problem 
    • Flutter version 3.3.2 on channel stable at D:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (6 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

**Comment by appwebprogrammer** [comment]
> hi i have same problem 
>     • Flutter version 3.3.2 on channel stable at D:\flutter
>     • Upstream repository https://github.com/flutter/flutter.git
>     • Framework revision e3c29ec00c (6 days ago), 2022-09-14 08:46:55 -0500
>     • Engine revision a4ff2c53d8
>     • Dart version 2.18.1
>     • DevTools version 2.15.0
> 

yes it happened with me also and i put all code that be written

**Comment by rmasarovic** [comment]
My clue is: new flutter sdk or dart  is reason why that background notification stop working

**Comment by rmasarovic** [comment]
i found solution here is https://github.com/firebase/flutterfire/issues/9446 add this annotation @pragma('vm:entry-point')
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async{....}

**Comment by appwebprogrammer** [comment]
> i found solution here is https://github.com/firebase/flutterfire/issues/9446 add this annotation @pragma('vm:entry-point')
> Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async{....}

onBackground in my app is working fine and firebase notification received, but when i use awesome notifications in release mode the background handler not appear the awesome notifications i try to send firebase notification it  received did you understand my point @rmasarovic @rafaelsetragni

**Comment by rmasarovic** [comment]
yes i had same issue but i update liberies awesome_notifications: ^0.7.0-beta.6+1,firebase_messaging: 13.0.2 and this  @pragma('vm:entry-point') must have in you code.

**Comment by rmasarovic** [comment]
and IOS have still same issues https://github.com/firebase/flutterfire/issues/9563 just waiting...

**Comment by appwebprogrammer** [comment]
> and IOS have still same issues https://github.com/firebase/flutterfire/issues/9563 just waiting...

my background handler for firebase is working fine and i receive firebase notification but when i use awesome notification the notification not created this my issue in debug all working but in release not working

**Comment by appwebprogrammer** [comment]
E/flutter (29521): [ERROR:flutter/lib/ui/dart_runtime_hooks.cc(38)] Dart Error: Unhandled exception:
E/flutter (29521): NoSuchMethodError: No top-level getter '_backgroundHandler' declared.
E/flutter (29521): Receiver: top-level
E/flutter (29521): Tried calling: _backgroundHandler
E/flutter (29521): #0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:225)
E/flutter (29521): #1      FfiTrampoline___getCallbackFromHandle$Method$FfiNative$Ptr (dart:ffi)
E/flutter (29521): #2      _getCallbackFromHandle (dart:ui/natives.dart:141)
E/flutter (29521): #3      PluginUtilities.getCallbackFromHandle.<anonymous closure> (dart:ui/plugins.dart:81)
E/flutter (29521): #4      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:524)
E/flutter (29521): #5      PluginUtilities.getCallbackFromHandle (dart:ui/plugins.dart:80)
E/flutter (29521): #6      _firebaseMessagingCallbackDispatcher.<anonymous closure> (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:40)
E/flutter (29521): #7      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:555)
E/flutter (29521): #8      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:548)
E/flutter (29521): #9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:393)
E/flutter (29521): #10     _invoke2 (dart:ui/hooks.dart:183)
E/flutter (29521): #11     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40)
E/flutter (29521): #12     _Channel.push (dart:ui/channel_buffers.dart:130)
E/flutter (29521): #13     ChannelBuffers.push (dart:ui/channel_buffers.dart:326)
E/flutter (29521): #14     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:663)
E/flutter (29521): #15     _dispatchPlatformMessage (dart:ui/hooks.dart:86)

this the error in background release mode when using awesome notification
@rmasarovic @rafaelsetragni

**Comment by mister-rao** [comment]
guys if your facing error similar to
` Dart Error: Dart_LookupLibrary: library `
its because of Flutter 3.3 upgrade

 add
`@pragma('vm:entry-point')`
on top of your message handler function. THis should fix it.
refer below issue on Firebase messaging:
https://github.com/firebase/flutterfire/issues/9446#issuecomment-1240554285


Spent a good 3 days on figuring what went wrong. Should be mentioned in release notes.

**Comment by rafaelsetragni** [comment]
Yes! Using `@pragma('vm:entry-point')` locks the dart address to not be changed at any time.
I already applied this markdown to new beta release. Thanks @mister-rao for sharing it with us!
