### ISSUE TITLE
Can i run action function without open app?

### ISSUE THREAD

**Issue by thize** [rafaelsetragni/awesome_notifications#56]
Can i run action function without open app? or just open in background?

**Comment by thize** [comment]
It is already in the [next steps:](https://github.com/rafaelsetragni/awesome_notifications#next-steps)
Add an option to choose if a notification action should bring the app to foreground or not.

**Comment by saharvx9** [comment]
https://github.com/rafaelsetragni/awesome_notifications/issues/242#issuecomment-891831987
