### ISSUE TITLE
Detect which notification was responsible to trigger app launch (Similar to getInitialMessage of fcm).

### ISSUE THREAD

**Issue by abhay-s-rawat** [rafaelsetragni/awesome_notifications#565]
**Is your feature request related to a problem? Please describe.**
This solves the navigation issue when app is in terminated state.

**Describe the solution you'd like**
If we can pass the arguments when a notification is pressed (actionType: ActionType.Default and app is in terminated state), we can use those arguments to navigate to required screen.
eg: I am currently using FCM background handler to trigger custom notifications (using data from message, notification property is removed from request), when app is in terminated state , the notification should take user to required screen.

**Additional context**
I understand java but I did not developed for android, but I want a minor overview on (2 line overiew) of things used then I can make it work for android for sure.

**Comment by rafaelsetragni** [comment]
You can use the payload property from NotificationContentModel to pass all the data you need to redirect the user to the desired page.

But to use background handler to create notification is not a good approach, because it will use background process and consumes battery life. That's why i created the `awesome_notifications_fcm` plugin, with it you only gonna need to push the notification containing the payload data to firebase and receive the notification action from the user. Everything between will be handle by fcm plugin.

**Comment by abhay-s-rawat** [comment]
Actually I am using fcm background handler which will listen for push notifications .
But puch notifications will not have 'notification' key it will have 'data' key and a cutsom notification will be generated according to that data.
This is only for when app is in terminated state.
```
eg: 
FirebaseMessaging.onBackgroundMessage(hiveIsolated);
```
Now can I pass data to main function when a notification is clicked ? Do I have to add a code like below ?
```
<intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
                <data android:mimeType="text/plain"/>
            </intent-filter>
```
```
line 858 notificationbuilder.java
PendingIntent actionPendingIntent = null;
            if (buttonProperties.enabled) {

                if(android.os.Build.VERSION.SDK_INT < Build.VERSION_CODES.N){
                    actionIntent.setAction(Intent.ACTION_MAIN);
                    actionIntent.putExtra("maindata", "kb main data");  //<<------ Something like this
                    actionIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                }
```
```
Future<void> main({String? intentData}) async { // <--------- receive paload
  WidgetsFlutterBinding.ensureInitialized();
  await ObjectBoxHelper.instance.initFCM();
  await ObjectBoxHelper.instance.init();
  await AwesomeNotificationsHelper.instance.init();
  runApp(const MyApp());
}
```

**Comment by rafaelsetragni** [comment]
Yes, as you are implementing through Firebase, you will need to get the silent push using `onBackgroundMessage` and then set the desired values ​​to redirect the user inside the `payload` property of NotificationContent`. When the user tap on notification, you can retrieve these payload values from the receivedAction object.

**Comment by abhay-s-rawat** [comment]
Yes I am doing like that but the background handler has its own isolate.

See what’s happening
Step 1: Firebase is sending data to the device
Step 2: Firebase background handler runs the function. Background handler
function runs in separate isolate and app is still in terminated state.
Step 3: Handler updates the database and creates a custom notification
about messages received from particular user.
Step 4: Remember app is still in terminated state. When user clicks on
notification (actiontype is default, which should start the app) app gets
launched  as expected and home page gets displayed.

I want to implement such that when in step 4 user clicks the notification
the payload data gets transferred to the main function of the app so that
when app gets launched I can use that payload to redirect user to correct
screen. Eg: chat screen not homepage when chat notification gets tapped.

So I found the piece of code / intent which is triggering app launch( from
killed to foreground).

**Comment by abhay-s-rawat** [comment]
I finally got code for latest beta version in pub.dev.
This package is different from ones with git versions.

I need to ask 1 thing.
Can you please tell me from where the main activity is getting launched when app is in terminated state.

What I am thingkng to do is
```
// And somwhere in package will add
            Intent launchIntent = binding.getActivity().getIntent();
            launchIntent.putExtra("initialAwesomeNotificationsPayload","test payload data");
```
```
//mainActivity.java
package com.example.awnotifications;

import androidx.annotation.NonNull;

import java.util.HashMap;
import java.util.Map;

import io.flutter.embedding.android.FlutterActivity;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.plugin.common.MethodChannel;

public class MainActivity extends FlutterActivity {
  private static final String CHANNEL = "com.example.awnotifications/initial_payload";

  @Override
  public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
  super.configureFlutterEngine(flutterEngine);
    new MethodChannel(flutterEngine.getDartExecutor().getBinaryMessenger(), CHANNEL)
        .setMethodCallHandler(
          (call, result) -> {
            if (call.method.equals("getInitialAwesomeNotificationsPayload")) {
                String initialData = getIntent().getStringExtra("initialAwesomeNotificationsPayload");
                result.success(initialData);
              } else {
                result.notImplemented();
              }
          }
        );
  }
}

```
```
// will call this function on awesome notifications initialize or somwhere where I can route
  Future<String?> getInitialPayload() async {
    try {
      const platform =
          MethodChannel('com.example.awnotifications/initial_payload');
      final String? result =
          await platform.invokeMethod('getInitialAwesomeNotificationsPayload');
      return result;
    } catch (e) {
      return e.toString();
    }
  }
```
And when the main function is called, I will call the methodchannel from flutter side to check which notification triggered the launch of app(killed state to launch state).
Then I can route to specific page according to the payload.

Can you help me know from where notification on tap code is written which is bringing app from killed to launching state ?

**Comment by abhay-s-rawat** [comment]
I cannot see other classes now when I rigth click and see implementations it says "Decompiled .class file, bytecode version: 52.0 (Java 8)". How to edit such files I ahave not Idea , I started with flutter so no Idea about Android code.

**Comment by abhay-s-rawat** [comment]
Can you please send latest version zip file where I can access core files like notificationbuilder.java.
I can see core files in [0.7.0-beta.7](https://pub.dev/packages/awesome_notifications/versions/0.7.0-beta.7) but is very old as there is no requireInputText and actionType properties there are streams instead of callbacks. New versions have core classes in bytecode.

My plan is to implement arguments passing so that when app is terminated and notification is clicked and it is designed to launch app, then I can check the payload after main function is called s that user can route to specific screens. This solves issues with background message handlers of fcm.

Step 1: I will find the code that is launching app from terminated state , it will most probably be intent/pending intent. There I will pass payload (launchIntent.putExtra("initialAwesomeNotificationsPayload","test payload data");).
That intent is calling mainactivity that means I can access that intent in mainactivity.

Step 2: I will register a method channel in mainactivity.java so that I can read intent payload (getIntent().getStringExtra("initialAwesomeNotificationsPayload")) and return.

Step 3: During initialization of awesomenotification , I will use invoke method to check initial payoad that triggered app launch and route according to it.

With this users who are using fcm backgroundhandler can control what should be the initial route for app.

**Comment by rafaelsetragni** [comment]
> I want to implement such that when in step 4 user clicks the notification the payload data gets transferred to the main function of the app so that when app gets launched I can use that payload to redirect user to correct screen. Eg: chat screen not homepage when chat notification gets tapped. So I found the piece of code / intent which is triggering app launch( from killed to foreground).

You just need to put the payload data inside the payload property of `NotificationContent` object. After you set the listeners, the action events will be fired and then you redirect the user to the desired page. 


> I finally got code for latest beta version in pub.dev. This package is different from ones with git versions.

But is the exact code, i guess this is not the newest one. Check if you're in this version of [Awesome Notifications](https://pub.dev/packages/awesome_notifications/versions/0.7.0-beta.7+5)  and [Awesome Notifications FCM](https://pub.dev/packages/awesome_notifications_fcm/versions/0.7.0-alpha.1).


> Can you help me know from where notification on tap code is written which is bringing app from killed to launching state ?

I don't know yet everything that flutter engine does to load everything and i believe there's an entire world between the native startup and the firs Flutter main method. The probability to forgot to do something important in between is considerable. Be careful.


> I cannot see other classes now when I rigth click and see implementations it says "Decompiled .class file, bytecode version: 52.0 (Java 8)". How to edit such files I ahave not Idea , I started with flutter so no Idea about Android code.

Yes, i extract the core to a java library to be reused by another libraries. The source code is already in the same awesome's Git repository.

> Can you please send latest version zip file where I can access core files like notificationbuilder.java. I can see core files in [0.7.0-beta.7](https://pub.dev/packages/awesome_notifications/versions/0.7.0-beta.7) but is very old as there is no requireInputText and actionType properties there are streams instead of callbacks. New versions have core classes in bytecode.

This is not the last version. The last versions are [Awesome Notifications 0.7.0-beta.7+5](https://pub.dev/packages/awesome_notifications/versions/0.7.0-beta.7+5)  and [Awesome Notifications FCM 0.7.0-alpha.1](https://pub.dev/packages/awesome_notifications_fcm/versions/0.7.0-alpha.1).



> Step 1: I will find the code that is launching app from terminated state , it will most probably be intent/pending intent. There I will pass payload (launchIntent.putExtra("initialAwesomeNotificationsPayload","test payload data");). That intent is calling mainactivity that means I can access that intent in mainactivity.
> 
> Step 2: I will register a method channel in mainactivity.java so that I can read intent payload (getIntent().getStringExtra("initialAwesomeNotificationsPayload")) and return.
> 
> Step 3: During initialization of awesomenotification , I will use invoke method to check initial payoad that triggered app launch and route according to it.
> 
> With this users who are using fcm backgroundhandler can control what should be the initial route for app.

I guess what are you trying to do. You're trying to know what action the user took, because the app was started by an intent action that already contains the information, and you wanna redirect the user directly to the target page, without anything between. And thats the point, you are doing what we call as [Premature Optimization](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwiF1vWmxL36AhVPBbkGHY5RDk8QFnoECA0QAQ&url=https%3A%2F%2Fstackify.com%2Fpremature-optimization-evil%2F&usg=AOvVaw1lvwXXDmbMKHnPU2N8D8n2).

Believe me, what you're trying to do is unnecessary and vastly more complex than a simple solution to do in less than one hour. The approach that i recommend you is what 99.99% of the apps do and any user notice the difference. I did the events firing after the setListeners method because there some things that must happen before on flutter to the user being correctly redirected.

Maybe you're noticing some difference because your app is in debug mode. But this mode is way less performative exactly because of the extra debug code and processing steps in it. Try to execute your app with `flutter run --release` to see the difference.

**Comment by abhay-s-rawat** [comment]
rafaelsetragni : You just need to put the payload data inside the payload property of NotificationContent object. After you set the listeners, the action events will be fired and then you redirect the user to the desired page.

Me: Bro payload property is there but the thing is FirebaseMessaging.onBackgroundMessage runs on different isolate. That's when when app is terminated and user clicks notification , app just launchs. I cannot do anything in that isolate to route in main isolate. Got it ?


rafaelsetragni : I guess what are you trying to do. You're trying to know what action the user took, because the app was started by an intent action that already contains the information, and you wanna redirect the user directly to the target page, without anything between. And thats the point, you are doing what we call [Premature Optimization].

Me: See awesome notification is using intents to trigger launch (mainactivity.java is called as this is the activity defined in manifest.xml) of app when app is terminated. I just want to pass a map/string data with that intent.
Now when app gets launched and void main gets called when everything is setup by app , I will use methodchannel to ask mainactivity.java that "is it triggered by a notification , if yes give me payload(map/string) or else return null". If I get payload I will route it to desired page. Here I can route because now things are in main isolate.

**Comment by abhay-s-rawat** [comment]
Can you please tell me how can I get core library , I need to do and test changes and that's successful that it will be a new feature, will polish it more to make it more easier to get routing done with FirebaseMessaging.onBackgroundMessage.

How to use that core when it is in different project ? Can you give me combined or different zip files here ? for core and latest package version.

**Comment by rafaelsetragni** [comment]
> Me: Bro payload property is there but the thing is FirebaseMessaging.onBackgroundMessage runs on different isolate. That's when when app is terminated and user clicks notification , app just launchs. I cannot do anything in that isolate to route in main isolate. Got it ?

So this is your problem. You need to move the execution from background isolate to main isolate, and to do that you can use ReceivePort to send data between isolates.

So, you initialize the listener `ReceivePort`  on the initialization process (which just happen on the main isolate) and as soon you run another isolates, you repass the execution using `SendPort`. If there is no one listen to, so there is no main isolate running on. Take a look:

[How to pass data between isolates in flutter dart](https://stackoverflow.com/questions/72322937/how-to-pass-data-between-isolates-in-flutter-dart)](https://stackoverflow.com/questions/72322937/how-to-pass-data-between-isolates-in-flutter-dart)

**Comment by rafaelsetragni** [comment]
> Can you please tell me how can I get core library , I need to do and test changes and that's successful that it will be a new feature, will polish it more to make it more easier to get routing done with FirebaseMessaging.onBackgroundMessage.
> 
> How to use that core when it is in different project ? Can you give me combined or different zip files here ? for core and latest package version.

It's on Github repository, inside the example app Android Folder.

**Comment by abhay-s-rawat** [comment]
I downloaded latest version from https://pub.dev/packages/awesome_notifications/versions. But I did not found the core library in the example/Android.
Can I use core from https://github.com/rafaelsetragni/awesome_notifications/tree/release-0-7-0 ?

**Comment by rafaelsetragni** [comment]
Yes, this is the latest version.

**Comment by abhay-s-rawat** [comment]
So I just have to move core folder from https://github.com/rafaelsetragni/awesome_notifications/tree/release-0-7-0 to https://pub.dev/packages/awesome_notifications/versions and do the changes, right ?

**Comment by rafaelsetragni** [comment]
No, the files are already on the places where i developed. You Just nerd to remove the gradle reference from the online repository and uncomment the local references.

**Comment by abhay-s-rawat** [comment]
I am getting it . I cannot find the local references too (new to android structure and java, sorry about it).
Can you please send the core url ? I will downlaod files from there and try to paste inside https://pub.dev/packages/awesome_notifications/versions latest.

**Comment by abhay-s-rawat** [comment]
> No, the files are already on the places where i developed. You Just need to comment the gradle reference from the online repository and uncomment the local references.
> 
> To use the cloned local plugin in your flutter project you gonna need to modify your pubspec.yaml, changing the version reference to `path` reference..

Will do the local reference part in pubspec but I need the core files that are referenced because I am not able to find them.

**Comment by rafaelsetragni** [comment]
https://github.com/rafaelsetragni/awesome_notifications/tree/release-0-7-0/example%2Fandroid%2Fawn_core

**Comment by abhay-s-rawat** [comment]
So If I copy contents of https://github.com/rafaelsetragni/awesome_notifications/tree/release-0-7-0/example/android/awn_core/src/main/java/me/carda/awesome_notifications/core to the latest version me/carda/awesome_notifications/core, it will work right ?

**Comment by abhay-s-rawat** [comment]
Am I doing something wrong below ? The logs are not getting called .
Do I have to change imports in java files to ?
  
plugin:
    platforms:
      android:
        path: android/src/main/java/me/carda/awesome_notifications/core # this is relative to pubspec.yaml
        package: me.carda.awesome_notifications
        pluginClass: AwesomeNotificationsPlugin
      ios:
        pluginClass: AwesomeNotificationsPlugin
      linux:
        pluginClass: AwesomeNotificationsPlugin
      macos:
        pluginClass: AwesomeNotificationsPlugin
      windows:
        pluginClass: AwesomeNotificationsPluginCApi
      web:
        pluginClass: AwesomeNotificationsWeb
        fileName: awesome_notifications_web.dart

**Comment by abhay-s-rawat** [comment]
> > Me: Bro payload property is there but the thing is FirebaseMessaging.onBackgroundMessage runs on different isolate. That's when when app is terminated and user clicks notification , app just launchs. I cannot do anything in that isolate to route in main isolate. Got it ?
> 
> So this is your problem. You need to move the execution from background isolate to main isolate, and to do that you can use ReceivePort to send data between isolates.
> 
> So, you initialize the listener `ReceivePort` on the initialization process (which just happen on the main isolate) and as soon you run another isolates, you repass the execution using `SendPort`. If there is no one listen to, so there is no main isolate running on. Take a look:
> 
> [How to pass data between isolates in flutter dart](https://stackoverflow.com/questions/72322937/how-to-pass-data-between-isolates-in-flutter-dart)

Well that's flutter part and I am sure it will not work like that because FirebaseMessaging.onBackgroundMessage runn on different isolate and how that isolate is spawn is upto firebase.
Actually when app is terminated ,firebase service keeps on running in background (part of google play service) which listens for notifications and when it gets a notifications it launches code inside FirebaseMessaging.onBackgroundMessage(handler_function) into a diffrent isolate.
When notification is clicked it launches app that's it . Newly created main isolate cannot communicate with that anonymous isolate as long as notification does not pass anything to mainactivity as intent and that intent is read by invoke method from flutter side. This is exactly what I am trying to do on flutter side. I love to play with isolates, its one of my speciality you can say. But this time control is in firebase hands to launch that isolate.
FCM usually have that kind of functionality in which user can listen to the notification that triggered app launch but for that you need to specify the notification key in fcm message and fcm will handle the notification. But in my case the message will be encrypted so I am using data key in fcm message for data transfer and decyrpting using your package to show notifications.

Just give me a chance , may be in chat I am not clear to you but when you will se when I do changes, you will understand easily what I was trying to do.

**Comment by abhay-s-rawat** [comment]
Below is the git repo where I placed core folder , can you please see that folder is palced correctly ?
https://github.com/abhay-s-rawat/awesome-notifications/tree/main/android/src/main/java/me/carda/awesome_notifications

**Comment by rafaelsetragni** [comment]
Dude... what are you trying to do hahahaaha, you only need to uncomment and comment out two lines of code to run using local source code. Just look for the folder called 'awn_core'.

> Well this is part of flutter and I'm sure it won't work that way because FirebaseMessaging.onBackgroundMessage runs on a different isolate and how that isolate is generated depends on Firebase.

You already know before you even try. That sounds great, especially for someone just starting out.

Dude, you're fighting a windmill, and I'm not going to embark on your magical adventure. I even have time to do this.
When you discover that you don't need to do any of this and that the solution already exists and is much more simple, call me.

**Comment by abhay-s-rawat** [comment]
> Dude... what are you trying to do hahahaaha, you only need to uncomment and comment out two lines of code to run using local source code. Just search for the folder called 'awn_core'.
I am not familiar with android code bro, needed a minor help.
> 
> > Well this is part of flutter and I'm sure it won't work that way because FirebaseMessaging.onBackgroundMessage runs on a different isolate and how that isolate is generated depends on Firebase.
I am new to platform specific code but not to the flutter side.
> 
> You already know before you even try. That sounds great, especially for someone just starting out.
Already tried everything, I can't believe you still don't understand what is the problem here.
> 
> Dude, you're fighting against a windmill, and I'm not going to embark on your magical adventure. I even don't have time to do this. When you discover that you don't need to do any of this and that the solution already exists and is much more simple, call me.
I am not asking to do it bro , I will do it, I am just asking you to atleast put both in same project so that I can use it locally.

**Comment by abhay-s-rawat** [comment]
Let me go once again , I  know you will not listen but still last try 👍 
I will break things into cases.

Case 1 :
App status : Foreground
Notification got generated and user tapped the notification, easy you can listen for action callbacks to see what tapping action was done and redirect easily with your router (whichever you are using). Here you can access router beacuse you initialized notifications in main isolate and callbacks are also in same main isolate.

Case 2:
App status : Background but not killed
-> FCM push a message to your device. 
-> FCM started a different isolate which will run a top level function defined when you last time initialized it . Parameter to FirebaseMessaging.onBackgroundMessage is that top level function.
-> There in that function user initiliaizes notifications and generates custom notification and kills that isolate.
-> If user taps it you can listen beacause in main isolate you are listening for action and you can route accordingly.

Case 3: Which is my concern
App status : App terminated/ killed
->  FCM push a message to your device. 
-> FCM started a different isolate which will run a top level function defined when you last time initialized it . Parameter to FirebaseMessaging.onBackgroundMessage is that top level function.
-> There in that function user initiliaizes notifications and generates custom notification and kills that isolate.
-> Now If user taps it you can't listen beacuse your app is not running to listen it. If you now tap notification and if action type for it is default which will launch the app, Now if app is launched you cannot determine which notification triggered the app launch. User will always be thrown to homepage.
```
FCM has below to solve this but only if you are using notification generated by FCM.
FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage event) {
// Here you can determine which notifiction triggered app launch but it will not trigger with this package
      print("fcm opened app");
    });
```

Solution:
Step 1: OSM notification side: Look for the intent which launches the app , that intent will be calling MainActivity most probably to launch. Just add payload to that intent . eg: intent.putExtra method

Step 2: MainActivity.java: Define a channel and a function which will return the payload from the intent which called main activity. Main activity will look somewhat like below
```
public class MainActivity extends FlutterActivity {
  private static final String CHANNEL = "com.example.awnotifications/initial_payload";

  @Override
  public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
  super.configureFlutterEngine(flutterEngine);
    new MethodChannel(flutterEngine.getDartExecutor().getBinaryMessenger(), CHANNEL)
        .setMethodCallHandler(
          (call, result) -> {
            if (call.method.equals("getInitialAwesomeNotificationsPayload")) {
                String initialData = getIntent().getStringExtra("initialAwesomeNotificationsPayload");
                result.success(initialData);
              } else {
                result.notImplemented();
              }
          }
        );
  }
}
```

Step 3: Flutter side => When app gets started and when user wants to know which notification started the app just call code below:
```
Future<String?> getInitialPayload() async {
    try {
      const platform =
          MethodChannel('com.example.awnotifications/initial_payload');
      final String? result =
          await platform.invokeMethod('getInitialAwesomeNotificationsPayload');
      return result;
    } catch (e) {
      return e.toString();
    }
  }
```

Now you know the payload and you can route easily. Got what I am trying to do ?
I just need your code to be arranged, I have to add 1 line to this package to make it work .eg: intent.putExtra method.
I have no Idea how you are calling those android libs , soon will figure it out. Thanks for your time.

**Comment by abhay-s-rawat** [comment]
Just Imagine your app is not running and fcm send a message your backgroundhandler generated a call notification.
You tapped that notification and when app gets launched user is thrown to homepage not the page that handles call.
FUNNY ISN'T IT ........

**Comment by rafaelsetragni** [comment]
I decided to implement it as I started to realize that you won't be the only one asking for it.

But you need to wait for the first `initState` to be able to redirect the user to any page. Flutter is not a native app, you have to wait for the flutter engine to start. I really don't know how this is going to help you be faster, but I'm going to do it anyway. Then you decide what to do next.

**Comment by abhay-s-rawat** [comment]
I am just trying to do like below:
RemoteMessage? msg = await FirebaseMessaging.instance.getInitialMessage();
Firebase already has this feature but nobody uses it for showing notification due to lack of customizations.
```
Future<RemoteMessage?> getInitialMessage()
Type: Future<RemoteMessage?> Function() package:firebase_messaging/firebase_messaging.dart

If the application has been opened from a terminated state via a [RemoteMessage] (containing a [Notification]), it will be returned, otherwise it will be null.

Once the [RemoteMessage] has been consumed, it will be removed and further calls to [getInitialMessage] will be null.

This should be used to determine whether specific notification interaction should open the app with a specific purpose (e.g. opening a chat message, specific screen etc).
```
Let me also try on my side . I made changes to add local project (awn_core) but no luck. Still throws error 
"Caused by: org.gradle.api.UnknownProjectException: Project with path ':awn_core' could not be found in project ':awesome_notifications'."

awn_core is currenlty location inside android folder on awesome_notifications plugin
```
android/build.gradle
dependencies {
    implementation project(':awn_core')
    //implementation "me.carda:androidcore:0.7.0-alpha.6"
```
```
android/settings.gradle

rootProject.name = 'awesome_notifications'
include 'awn_core'
//project(':awn_core').projectDir = new File('awn_core')
```

**Comment by abhay-s-rawat** [comment]
> I decided to implement it as I started to realize that you won't be the only one asking for it.
> 
> But you need to wait for the first `initState` to be able to redirect the user to any page. Flutter is not a native app, you have to wait for the flutter engine to start. I really don't know how this is going to help you be faster, but I'm going to do it anyway. Then you decide what to do next.
will use route after initstate and initial build finishes like below
WidgetsBinding.instance.addPostFrameCallback((_) => checkForInitialRoute()); // this will be inside initstate

**Comment by rafaelsetragni** [comment]
> android/settings.gradle
> 
> rootProject.name = 'awesome_notifications'
> include 'awn_core'
> //project(':awn_core').projectDir = new File('awn_core')


No, you can't comment the last line. You just need to uncomment the `include 'awn_core'` to include the native livrary project inside the folder "awn_core".

This is how everything will looks like:

![image](https://user-images.githubusercontent.com/40064496/193426667-98f4a1eb-427b-4c56-aad1-53bbd709968c.png)
...and then you do:
![image](https://user-images.githubusercontent.com/40064496/193426708-ab3f68de-f554-4c97-b044-edda932f674f.png)
...and on `interceptInitialCallActionRequest` you do:
![image](https://user-images.githubusercontent.com/40064496/193426689-3c50f078-0f76-42ba-9010-37c10291bfe1.png)
...and for last:
![image](https://user-images.githubusercontent.com/40064496/193426761-1affe6c1-c1a0-432b-bb1d-36836ef449d8.png)

Is that what you're looking for?

**Comment by abhay-s-rawat** [comment]
Wow looks , awesome. Can I get the rar file of this ? I want to see few things .
email: abhayrawat.official@gmail.com

**Comment by rafaelsetragni** [comment]
It's on the last commit, but i did not replicate the changes on iOS side:
https://github.com/rafaelsetragni/awesome_notifications/commit/57b680214b86c8102bfc501ccdf46e5a61d9bcf1

**Comment by rafaelsetragni** [comment]
https://user-images.githubusercontent.com/40064496/193429222-59b0c9a3-ea7a-436a-ae94-51ebc67b57a6.mp4

**Comment by abhay-s-rawat** [comment]
Everything is working perfect. Absolute beast package now. 
Told you sometimes when writing its not clear what is someone asking, I am glad in last I elaborated by putting different cases and the one which I was talking about.
Please make sure to switch to online version of awn_core when you push to pub.dev.

Thanks a lot for your time.

**Comment by rafaelsetragni** [comment]
Hi @abhay-s-rawat !
Your enhancement its on live! You can check it in version `awesome_notifcations: ^0.7.0+1`

**Comment by abhay-s-rawat** [comment]
Thanks a lot.
