### ISSUE TITLE
Adding an option to start notification interval after a specific DateTime

### ISSUE THREAD

**Issue by StefanDimov** [rafaelsetragni/awesome_notifications#566]
**Is your feature request related to a problem? Please describe.**
I am building an app where the user can set recurring notification to remind them to do specific tasks. The notification fires everyday at a specific time. But if the user has already done the task prior to the notification displaying, it should not be displayed for the day, but it should fire again on the next day when the task is due to be done again.

Currently the interval feature serves the purpose to schedule the notifications for each day. But it can't handle the skip the day case.

**Describe the solution you'd like**
If it would be possible to configure the notification interval to start after a specific DateTime, it would be possible to cancel the current notification interval and schedule it with a start DateTime of tomorrow, so the current day will be skipped in the interval, but tomorrow it will be right on track again.

**Describe alternatives you've considered**
An alternative that could work is to cancel the notification schedule when the task is completed prior to the notification displaying and scheduling it again in a background task at midnight so it can fire the next day. But I believe it will be error prone, due to how unpredictable background work is handled on mobile. It's in my backlog to try this.

#420

**Comment by rafaelsetragni** [comment]
I tried to add this feature in the past, but on iOS this is no longer possible. Since iOS 10, Apple took this feature away and never put it back, even with many people demanding it on their support forums.

I also can't emulate this feature by creating too many looped scheduled notifications as iOS has a lower limit of 64 notifications per App.

**Comment by StefanDimov** [comment]
Not problem. Your points are valid. Hopefully Apple will put it back in the future.
