### ISSUE TITLE
Reply button brings the app to foreground on sending the text

### ISSUE THREAD

**Issue by ashishbeck** [rafaelsetragni/awesome_notifications#568]
## **1 - Describe the bug**

The user puts the app in background and it receives a notification. When they press the reply button, write the text and send the message, the message is sent but the app is brought into foreground. This might unnecessarily cause the user to accidentally open the app when they did not intend to do so.
This is a resubmission of #125 

[Demo Video](https://i.imgur.com/fqsip1p.mp4)

## **2 - Provide us as much information as possible**

* The issue is present in both the Android and iOS platforms
* I have tried both the emulator and physical devices
* The issue is inherent in the nature so the example app is good enough for reproduction

<details>
  <summary>Flutter Doctor</summary>
  
  ```
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale en-IN)
    • Flutter version 3.3.2 on channel stable at /Users/ashishbeck/Dev/Tools/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (2 weeks ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/ashishbeck/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (3 available)
    • iPhone 14 Pro Max (mobile) • B56603A2-EB6F-4B2D-ACDA-CCAA1B99C67D • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-16-0 (simulator)
    • macOS (desktop)            • macos                                • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 106.0.5249.91

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
  ```
</details>

## **3 - How To Reproduce the Error**

1. Open the example app
2. Scroll down to the "Action Buttons" section
3. Tap "Show notification with reply and action button"
4. Put the app in the background
5. Expand the notification and hit reply to write any message and send

## **4 - Expected behavior**
After the message has been sent, the notification should either disappear or update with new data.

**Comment by rafaelsetragni** [comment]
This is already implemented in 0.7.0 version using `ActionType.SilentAction` or `ActionType.SilentBackgroundAction`. Take a look at [awesome_notifications 0.7.0-beta.7+5](https://pub.dev/packages/awesome_notifications/versions/0.7.0-beta.7+5)

**Comment by ashishbeck** [comment]
Yes, it does work now. However, when the reply is sent, it makes the notification sound one more time which could be a little distracting to the user.
Great work btw!

**Comment by rafaelsetragni** [comment]
Try to set the property `onlyAlertOnce` in your NotificationChannel to true.

**Comment by ashishbeck** [comment]
After setting it to true, it's still making the notification sound. I even added `onlyAlertOnce: true` to all the notification channels in `example/lib/notifications/notifications_controller.dart` of the example app.
