### ISSUE TITLE
Carousel Notification 

### ISSUE THREAD

**Issue by 0Franky** [rafaelsetragni/awesome_notifications#569]
Hi @rafaelsetragni 
first of all thank you for your work and your contribution!

I'm here to ask you if it is possible to implement a new style for notifications. 
In particular it would be nice to implement a notification that contains an image carousel. 

Here I am attaching some useful links:

Android package
https://github.com/shaileshmamgain5/Carousel-Notification

iOS package:
https://documentation.onesignal.com/docs/ios-image-carousel-push-notifications

Thanks again and have a nice day.

**Comment by rafaelsetragni** [comment]
Hi Franky! 

Thank you so much for your project links. They are and will be very useful, in fact.
It's on my future plans to implement it. For now i need to finish the FCM add-on plugin first and the web portal to implement it. I believe i will take 3 months to reach that point.

I added to the project planing this enhancement, and you can track the progress there. 👍
