### ISSUE TITLE
actionStream unstable

### ISSUE THREAD

**Issue by hauphidao** [rafaelsetragni/awesome_notifications#57]
when app in background, click notification (firebase) actionLifeCycle is NotificationLifeCycle.AppKilled (test in android)

**Comment by rafaelsetragni** [comment]
I couldnt reproduce your error. What android version and plugin version are you using?
Can you build a simple test application and send me with this error?

**Comment by adrianvintu** [comment]
I got the "AppKilled" error when I ran  ```AwesomeNotifications().initialize``` twice.

**Comment by rafaelsetragni** [comment]
The initialize method should not get called twice, but ive put an extra protection to avoid things like this.

**Comment by adrianvintu** [comment]
@rafaelsetragni thank you very much!
