### ISSUE TITLE
i want to remove notification when app get killed how to do it?

### ISSUE THREAD

**Issue by saigopin** [rafaelsetragni/awesome_notifications#570]
I am listening for changes to AppLifecycleState in main.dart and closing notification in AppLifecycleState.detached but it is not closing the application.

any idea how to fix it?

thank you.

**Comment by AdamNSmith** [comment]
Was this resolved on another thread? I'm also interested in how to get notifications to be removed when the app is killed from the system launcher.

**Comment by AdamNSmith** [comment]
As a note for anyone in the future, I figured out that if you start the notification on Android as a foreground service, then when the app is force-quit the service is killed also which in-turn closes the system notification.
