### ISSUE TITLE
Line break for long notification titles

### ISSUE THREAD

**Issue by nietsmmar** [rafaelsetragni/awesome_notifications#571]
**Is your feature request related to a problem? Please describe.**
When my notification has a long title it is not shown fully. See this screenshot:

![122087051-9d595300-ce04-11eb-8851-618041bf564e](https://user-images.githubusercontent.com/9265181/193802664-af0444cd-369f-4ba7-a7e0-d9456403e18a.png)

**Describe the solution you'd like**
I would love to have the option of setting multiple line titles. So that there is a line break instead of having it cut off.

**Describe alternatives you've considered**
I could not think of any alternative.

**Additional context**
--

**Comment by rafaelsetragni** [comment]
I've implemented html in the notifications, but not all platforms accept breaklines, especially in the title. And this acceptance depends on which NotificationLayout you chose.
But the conversion is already there, in case any platform enable this feature, it will work automatically.

**Comment by nietsmmar** [comment]
Is this since version 7? I am currently using version 0.6.21 and still have to update. Is there something breaking when I update? Can I just use html in the title or do I need to set a flag when doing so?

also I am using the plugin to receive messages from firebase. Do I need to switch to `awesome_notifications_fcm` plugin? Or what is the difference now?

**Comment by rafaelsetragni** [comment]
For this breakline feature, this is the only way to do it. And I strongly recommend you to update to the latest version.
Yes, you need to use `awesome_notifications_fcm` now. And the good news is that most of the steps taken to configure the Android and iOS folder are probably already done 😃.

**Comment by nietsmmar** [comment]
Okay, that is unfortunate. But thanks a lot! 

So I use only `awesome_notifications_fcm` or both packages? Is there any migration guide? It is very important for me not to make any mistakes by upgrading as my app is strongly relying on notifications.

**Comment by rafaelsetragni** [comment]
Only `awesome_notifications_fcm`. Im still creating the documentation, but you can find all support needed from our community on [Awesome Notifications Discord Server](https://discord.awesome-notifications.carda.me)

**Comment by nietsmmar** [comment]
Thanks a lot for your work. I will try to upgrade and get it running.
