### ISSUE TITLE
IOS notification with firebase not working

### ISSUE THREAD

**Issue by Mashood97** [rafaelsetragni/awesome_notifications#574]
I am getting this error while receiving notification from firebase:

Warning: Application delegate received call to -application:didReceiveRemoteNotification:fetchCompletionHandler: but the completion handler was never called.

It's really annoying as the app redirections are not working properly, Kindly fix this issue.

**Comment by priyanshu-cilected** [comment]
Hy @Mashood97 
refer to this link and add a entry point to your firebase background and Initialize firebase app in it. Hope this one solve your issue

[https://pub.dev/packages/firebase_messaging/example](url)

**Comment by Mashood97** [comment]
But it's in foreground state @priyanshu-cilected

**Comment by priyanshu-cilected** [comment]
can you please share the code??

**Comment by Mashood97** [comment]
Hi @priyanshu-cilected I just check my code and it was a totally blunder by myself. Thanks for your reply i just fixed and updated it. Thanks and cheers !
