### ISSUE TITLE
Add setTimeoutAfter Notification 

### ISSUE THREAD

**Issue by maulikchak** [rafaelsetragni/awesome_notifications#576]
Android supports the ability to timeout a notification after a period of time. It seems reasonable to have that functionality here as well.
I don't know iOS  support or not?

https://developer.android.com/reference/android/app/Notification.Builder#setTimeoutAfter(long)

**Comment by rafaelsetragni** [comment]
Yes, on Android it is possible, but on iOS it is not. But definitely I will study a solution to implement this feature in the near future. It will be great if I can. Thanks for your tip!

**Comment by gruvw** [comment]
Hello,  
I was wondering if this is now possible ?

In the README it's written that
> Awesome Notifications contains all features available in `flutter_local_notifications` plugin [...]

However, this is a feature I am missing as I am migrating from `flutter_local_notifications` to `awesome_notifications`.  
When can we expect this feature to be implemented in `awesome_notifications` ?  
Is there any workaround till then ?

Thank you.

**Comment by rafaelsetragni** [comment]
There's a feature to expire a notification on Android or iOS? Do you know which parameters name are?

**Comment by gruvw** [comment]
It's for android.

```dart
AndroidNotificationDetails(
  'Timeout',
  'Timeout',
  timeoutAfter: 4 * 60 * 1000,
),
```

**Comment by rafaelsetragni** [comment]
Sure! I will implement this feature for the next release!

**Comment by ebelevics** [comment]
Would be cool if you could separate android vs ios only features, and shared stay as it is. For example, fullScreenIntent is Android only feature, and with seeing on Android config it would not confuse people. Same goes to iOS separate section.

https://notifee.app/react-native/docs/ios/appearance which is react-native implementation does documentation and implementation job pretty neat and clear.

**Comment by rafaelsetragni** [comment]
Hi @gruvw, i just uploaded the new release versions of 0.7.5-dev.2+1 versions of [awesome_notifications](https://pub.dev/packages/awesome_notifications/versions/0.7.5-dev.2+1) and [awesome_notifications_fcm](https://pub.dev/packages/awesome_notifications_fcm/versions/0.7.5-dev.2+1) to fix this issue. Please, check it out to see if this issue is solved on these new versions.

The new field calls `timeoutAfter` and is located inside NotificationContent class.

Also, don't forget to join in your [Discord Beta team](https://discord.com/channels/888523488376279050/933445281243082772) to request fixes and new updates.

**Comment by gruvw** [comment]
Can't find this new field `timeoutAfter`. Where is it ?

See: https://github.com/search?q=repo%3Arafaelsetragni%2Fawesome_notifications+timeoutAfter&type=code

**Comment by rafaelsetragni** [comment]
> Can't find this new field `timeoutAfter`. Where is it ?
> 
> See: https://github.com/search?q=repo%3Arafaelsetragni%2Fawesome_notifications+timeoutAfter&type=code
 
here: https://github.com/rafaelsetragni/awesome_notifications/blob/56715fb87f7e6139e75b2b0b83a328ef9871de64/lib/src/models/base_notification_content.dart#L68

The BaseNotificationContent class is abstract and is inherited by NotificationContent.

**Comment by gruvw** [comment]
But how are we supposed to set it ?

It is not available from the `NotificationContent` constructor, and there is no setter for it either.
