### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by hardik-weenggs** [rafaelsetragni/awesome_notifications#58]
- how can i display notifications in different languages? (my app is supports multiple languages)
- If user is not logged in, notification should not be displayed to that user and the notification should be displayed if the user is logged in. How can I manage this? 

is there any callback like **_onBackgroundMessage_** in this plugin? so i can manage it locally in the background.

**Comment by rafaelsetragni** [comment]
> how can i display notifications in different languages? (my app is supports multiple languages)

Send the notification with the last user's selected language. Store and sync on your server his configurations and send the text notification corresponding with his last language. Store this kind of information is good even to pre load his configurations in a new device.

> If user is not logged in, notification should not be displayed to that user and the notification should be displayed if the user is logged in. How can I manage this?

When the user logged out, disable the respective notification channels. If the channel is disabled or does not exist, the notification will be discarted.

**Comment by hardik-weenggs** [comment]
> Localization

can you add feature like "onBackgroundMessage"? like "firebase_messaging" plugin. so i can handle it in app.

**Comment by rafaelsetragni** [comment]
Like "createStream" does?

**Comment by hardik-weenggs** [comment]
yes. but it only works if the app is running. It does not work if the app is closed(killed). so how can i get notification callback when app is closed.?
can you add any "backgroundStream"?

**Comment by rafaelsetragni** [comment]
I dont know how to run dart code when your app is killed or in background for iOS.

**Comment by rafaelsetragni** [comment]
This feature will be available on version 0.7.0.

**Comment by ash0080** [comment]
> This feature will be available on version 0.7.0.

@rafaelsetragni  I have a further question, how to localize channel names and group names?
