### ISSUE TITLE
Date is not more valid

### ISSUE THREAD

**Issue by mehrdad78** [rafaelsetragni/awesome_notifications#586]
hi there!
i have an app scheduling to notification on some special dates that i get theme from a offline database.
when i set a notification i got  the warning in my debug console **`" Date is not more valid"`**.
what does it mean?

**Comment by rafaelsetragni** [comment]
This means that the appointment date you set is in the past. In this way your notification is discarded.

**Comment by mehrdad78** [comment]
> This means that the appointment date you set is in the past. In this way your notification is discarded.

thanks for your response.
so what should i do?in my code in `initstate `i check if there is a date on today or no if no then i set the next date.

**Comment by rafaelsetragni** [comment]
I put some scheduling examples in the Example app, maybe one of them could be useful for you.
You can find it inside the example folder here on GitHub.

**Comment by JakubPristas** [comment]
Hi, can you assign this issue to me ?

**Comment by mehrdad78** [comment]
> Hi, can you assign this issue to me ?

how can i do this?

**Comment by mehrdad78** [comment]
> I put some scheduling examples in the Example app, maybe one of them could be useful for you. You can find it inside the example folder here on GitHub.

thank you i Rafael,i'll watch examples,, but another question i have that is when: i want to set next datetime i should use `getNextDate` or i call `createnotification` again?

**Comment by rafaelsetragni** [comment]
`getNextDate` is just a query method to discovery what will be the next schedule date. To set a next schedule, you must use `createNotification` again
