### ISSUE TITLE
Notification icon is the wrong colour

### ISSUE THREAD

**Issue by ScottishRoss** [rafaelsetragni/awesome_notifications#588]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**

When the notification is displayed, the colour of the icon is black, instead of white. I am using a png with a transparent background and a white logo, but for some reason the white logo is black.

## **2 - Provide us as much information as possible**

To help us to understand your issue, provide with your bug report all the relevant informations, such as:

* Your plugins list inside the file `pubspec.yaml` (at least all notification plugins)
N/A
* What platform did you found the issue
Android
* What devices did you found the issue
PIxel 6 Pro
* How are you initializing the plugin
```_notifications.initialize(
      'resource://drawable/app_icon',
      <NotificationChannel>[
        _notificationChannelReminders,
      ],
      channelGroups: <NotificationChannelGroup>[
        NotificationChannelGroup(
          channelGroupkey: kNotificationsChannelGroupKey,
          channelGroupName: kNotificationsChannelGroupName,
        )
      ],
      debug: true,
    );
```
* How are you creating the notification
```
final NotificationContent _notificationContentReminders = NotificationContent(
    id: 1,
    channelKey: kNotificationChannelKeyReminders,
    title: 'Celebrate your Little Victories!',
    body: 'Celebrating your Victories daily will help your wellbeing.',
    wakeUpScreen: true,
    category: NotificationCategory.Reminder,
  );

_notifications.createNotification(
      content: _notificationContentReminders,
    );
```
* The output of `flutter doctor` command
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.4, on Microsoft Windows [Version 10.0.19044.2006], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.71.0)
[√] Connected device (4 available)
    ! Device emulator-5562 is offline.
[√] HTTP Host Availability

! Doctor found issues in 1 category.

```

## **3 - How To Reproduce the Error**

1. Add a png with a white image and transparent background.
2. Use this in the notification initialization.
3. Fire a notification.

## **4 - Expected behavior**
I expected to see the icon being white. 
![app_icon](https://user-images.githubusercontent.com/25175556/194942681-b483d12f-40fe-49aa-9e86-25f5e8780898.png)

## **5 - Screenshots**
![Screenshot_20221010-204600](https://user-images.githubusercontent.com/25175556/194942374-f9126881-8f2a-4c7d-a542-88fb731d5276.png)

**Comment by rafaelsetragni** [comment]
Can you post a screenshot of the problem?
I have a suspicion of what it might be, but I need to see some image to confirm.

**Comment by ScottishRoss** [comment]
Updated with more information. Hope that helps!

**Comment by rafaelsetragni** [comment]
This is a feature from Android 12. Im trying to find the android documentation now to send to you.
But I recommend you check how your icon looks in versions lower than Android 12.

**Comment by rafaelsetragni** [comment]
This is the work mode/ bedtime. It's a mode added in Android 12 that is supposed to help you avoid distraction (and notifications), removing colors. I tried to find a way to deactivate it, but i didn't found any.

**Comment by ScottishRoss** [comment]
It's interesting that the icon is black though, right? Shouldn't it be white?

**Comment by ScottishRoss** [comment]
I've figured it out. It's all about the light/dark theme. I don't know if there's a way to ignore that but I doubt it. This can be closed, thanks for looking into it!
