### ISSUE TITLE
Disable the transition to system settings when the user turned off the permission before

### ISSUE THREAD

**Issue by VitaliBov** [rafaelsetragni/awesome_notifications#59]
Hello! Excellent library, I really like API and functionality.

Unfortunately, our project doesn't need logic to go to system settings in iOS.. Can you add a parameter to the permission request method? For example like this:

```
  Future<bool> requestPermissionToSendNotifications(bool openSettingsWhenDenied) async {
    // TODO: Add [openSettingsWhenDenied] to platform channel arguments
    final bool isAllowed =
        await _channel.invokeMethod(CHANNEL_METHOD_REQUEST_NOTIFICATIONS);
    return isAllowed;
  }
```

**Comment by rafaelsetragni** [comment]
And what should happen when the user want to allow the permission inside your app?

I got it. Are you sending a dialog message to the user warning him about the blocked permission or are just calling the requestPermissionToSendNotifications?

You need to inform the user with a dialog message before call this function. Dont forget about it.

**Comment by VitaliBov** [comment]
Yes you're right. I am calling requestPermissionToSendNotifications without showing the dialog. I'll fix this in my implementation.

Thanks again for the great library!
