### ISSUE TITLE
[DEMO] in Notification Title in Release Mode

### ISSUE THREAD

**Issue by totalard** [rafaelsetragni/awesome_notifications#590]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**

In Debug Mode the Notification  Working as Fine, and also show images, But in Release Mode, as i downloaded From Play Store, I getting this [DEMO] in the Notification Title, also Images Not Showing

## **2 - Provide us as much information as possible**

![WhatsApp Image 2022-10-12 at 8 16 47 AM](https://user-images.githubusercontent.com/15087079/195238316-68c1f9a9-c9db-4f0e-9d57-310b879bd946.jpeg)

**Comment by rafaelsetragni** [comment]
You need to acquire the license key.

The license key is a digital signature that enable push notifications in release mode without the watermark [DEMO]. All FCM features work the same in any mode, except for the watermark in release mode.

The license key is exclusive for each app, and once generated is perpetual. It will never expire. Also it don't require internet connection to be validated. The matching is done using RSA public keys.


The price is $ 9.99/app, including:
* 4 app IDs variations
* 1 Year updates
* 2 dedicated live support
* 1 Year of exclusive discord channel support


The web portal where you manage your applications as well as the FCM documentation are in the final stages of construction. 

So, for now, if you want to purchase a license, click on the Paypal link below and we will contact you by e-mail as soon your payment gets confirmed:
https://www.paypal.com/invoice/p/#66Q6F4M5ZKC5Q82A

OBS: In case your country does not support paypal payments, you can send a donation with the necessary amount to our _Buy me a coffee_ account and send the print screen or payment voucher to email payments@carda.me or in discord in a private message and i will contact you to generate the license key and its variations:
https://www.buymeacoffee.com/rafaelsetragni

**Comment by totalard** [comment]
What you mean by 

 4 variations of Application IDs\Bundle IDs

please give me answer with example, i cant understand this

**Comment by rafaelsetragni** [comment]
The same Flutter app can have different App IDs, depending on which platform is running. This is a very common situation on Flutter development. Bundle ID / App ID ar that inverted domain app that you define to be a unique ID of your app installation.

To know what your bundle ID is, you can check it in your _build.gradle_ file and in the XCode project, but also this App ID / Bundle ID is printed in the console with the license message. The last way is the best option as it is exactly what the validation process will read from your application.

**Comment by totalard** [comment]
I have done payment

mail id totalard@gmail.com / 39X99254LN081691T
