### ISSUE TITLE
android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground()

### ISSUE THREAD

**Issue by tzt1994** [rafaelsetragni/awesome_notifications#591]
my flutter environment:
[✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm (Rosetta), locale zh-Hans-CN)
    • Flutter version 3.3.2 on channel stable at /Users/tangzhentao/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e3c29ec00c (4 weeks ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/tangzhentao/Library/Android/sdk
    • Platform android-33, build-tools 32.0.0
    • ANDROID_HOME = /Users/tangzhentao/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.13+0-b1751.21-8125866)
    • All Android licenses accepted.

I am getting this error while using Andorid foreground service, below is my code calling

my flutter code:
  in main.dart:
 `void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  /// 缓存数据类初始化
  await CacheDataManager.instance.init();
  /// 设置百度ak
  if (Platform.isIOS) {BMFMapSDK.setApiKeyAndCoordType(App.iosBaiduAk, BMF_COORD_TYPE.COMMON);}
  /// 强制竖屏
  SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
    DeviceOrientation.portraitDown
  ]);
  /// 设置通知相关
  AwesomeNotifications().initialize(
    'resource://drawable/ic_launcher.png',
    [
      NotificationChannel(
          channelGroupKey: 'foreground_notification',
          channelKey: App.bcpChannelKey,
          channelName: '后台持续定位',
          channelDescription: '${App.name}需要后台持续定位以便更好的服务'
      )
    ]
  );
  runApp(MultiProvider(
    providers: [
      ChangeNotifierProvider<UserViewModel>(create: (_) => UserViewModel()),
      ChangeNotifierProvider<OrderViewModel>(create: (_) => OrderViewModel())
    ],
    child: const MyApp(),
  ));
  /// 设置状态栏
  SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    statusBarBrightness: Brightness.light,
    statusBarIconBrightness: Brightness.light,
  ));
}`

 in Androidmanifest.xml:
`
       <service android:name="me.carda.awesome_notifications.awesome_notifications_core.services.ForegroundService"
           android:enabled="true"
           android:exported="false"
           android:stopWithTask="true"
           android:foregroundServiceType='location'
           tools:targetApi="ice_cream_sandwich" />`

 use code:
 ` /// 发送通知
      final isAllowed = await AwesomeNotifications().requestPermissionToSendNotifications();
      if (isAllowed) {
        AndroidForegroundService.startAndroidForegroundService(
          foregroundStartMode: ForegroundStartMode.stick,
          foregroundServiceType: ForegroundServiceType.location,
          content: NotificationContent(
            id: App.bcpChannelId,
            channelKey: App.bcpChannelKey,
            title: '${App.name}正在为您服务',
            body: '${App.name}将持续监听您的定位',
            category: NotificationCategory.Service)
        );
      }`

**Comment by tzt1994** [comment]
I have solved it myself.
This error occurs when the foreground service is started according to your documentation settings.
The reason is that there is a problem with the AndroidManifest.xml configuration service in the documentation
Need to be set like this, hope to know

![image](https://user-images.githubusercontent.com/15625580/195258108-a6c44f4b-e4c1-4ce6-9045-1177f28c6fb1.png)
The full pathname of the service in the documentation is wrong

**Comment by rafaelsetragni** [comment]
Thanks! I will update it!

**Comment by tzt1994** [comment]
I still have a problem, when the foreground service notification is started, the set title and content do not take effect
My code:
`/// 发送通知
      final isAllowed = await AwesomeNotifications().requestPermissionToSendNotifications();
      if (isAllowed) {
        AndroidForegroundService.startAndroidForegroundService(
          foregroundStartMode: ForegroundStartMode.stick,
          foregroundServiceType: ForegroundServiceType.location,
          content: NotificationContent(
            id: App.bcpChannelId,
            channelKey: App.bcpChannelKey,
            title: '为您服务\n${App.name}将持续监听您的定位',
            body: '${App.name}将持续监听您的定位',
            category: NotificationCategory.Service)
        );
      }`

Demonstration effect:
![WechatIMG95](https://user-images.githubusercontent.com/15625580/195472580-2c18d810-71a9-48d3-ad70-6fd0805751dc.jpeg)

**Comment by tzt1994** [comment]
I also set NotificationLayout.BigPicture according to the document, and also set BigPicture, but it will report an error:
BigPicture is Invalid

I set the value of BigPiture to be the same as the notification icon, and the notification icon is effective.

**Comment by rafaelsetragni** [comment]
Paste me your big picture url.

**Comment by tzt1994** [comment]
![image](https://user-images.githubusercontent.com/15625580/195734345-90e77f71-90ac-41ab-8a08-df1616f1ac1c.png)

**Comment by tzt1994** [comment]
![image](https://user-images.githubusercontent.com/15625580/195734612-dedaf280-54d0-4b13-a633-f30cef267901.png)
