### ISSUE TITLE
 NotificationLayout.MediaPlayer about actionButtons

### ISSUE THREAD

**Issue by zyk-miao** [rafaelsetragni/awesome_notifications#595]
NotificationLayout.MediaPlayer
if actionButton without  icon even if   it has label ,the actionButton won't show.
How can i use actionButton without icon?

**Comment by rafaelsetragni** [comment]
Sorry, but i gonna ask you to repost your issue, not erasing the form content. Also, try to use the form for `Ask a Question`, instead of bug reports.

I gonna close this issue and mark it as invalid.
