### ISSUE TITLE
onlyAlertOnce time

### ISSUE THREAD

**Issue by mayder** [rafaelsetragni/awesome_notifications#6]
Is it possible to set onlyAlertOnce true for longer? My alert is hidden in 4 seconds.

**Comment by rafaelsetragni** [comment]
OnlyAlertOnce is a flag to tell to notifications center to play the notification sound, vibration and tickers only if it's not already showed on a active notification with the same id.

Please explain your issue in more details, so I can help you.

OBS: E ai breno! kkk

**Comment by mayder** [comment]
Fala Rafael, eu nem tinha visto que era você, que mundo pequeno, depois olha a mensagem que te mandei lá no Instagram.

Cara, meu problema é o seguinte, eu estou fazendo um App tipo Whatsapp e seu plugin foi o melhor que achei. Na parte de chamada, quando estou ligando para uma pessoa eu envio um push pelo firebase e já fico conectado ao socket esperando a outra pessoa, quando a outra pessoa recebe o push ela clica em Aceitar ou Rejeitar, quando ela Aceita eu conecto ela ao socket e junto as duas pernas.

Igual Whatsapp faz. Mas tipo, neste caso eu tive este problema do alerta sair da tela sozinho com quase 4 segundos, ai o tel para de vibrar e para de chamar, eu queria manter o alerta aberto, com tel vibrando e o som em loop até a pessoa ter uma ação. 
A vibração dura só um pouquinho também, mas vi que é pq depois de configurar o canal ela fica salva nas configurações e depois de remover o app e instalar de novo ele pega a nova configuração.
O som do push dura até a música que eu escolher como padrão acabar, se tivesse como entrar em loop também ia ser legal.

Um outro detalhe também é que o action button quando não esta no alerta fica encolhido, se tivesse como ele ficar sempre visível igual o Whatsapp também ia ser legal.

Mesmo com estes detalhes seu plugin é o melhor que vi, fora que é o mais fácil para configurar. Parabéns.

Ah, tem um detalhe na configuração que vc precisa colocar na documentação dele, nesta v2 que o Flutter esta pedindo para atualizar, eu precisei incluir o registro do plugin assim no meu Application.kt:

override fun registerWith(registry: PluginRegistry) {
    AwesomeNotificationsPlugin.registerWith(registry?.registrarFor("me.carda.awesome_notifications"))
    FirebaseCloudMessagingPluginRegistrant.registerWith(registry)
  }

**Comment by rafaelsetragni** [comment]
This problem was fixed on the example created for the topic bellow:

[MissingPluginException(No implementation found for method createNewNotification on channel awesome_notifications)](https://github.com/rafaelsetragni/awesome_notifications/issues/18)
