### ISSUE TITLE
Are Notification Action Buttons available for local notifications?

### ISSUE THREAD

**Issue by AbdulMalikDev** [rafaelsetragni/awesome_notifications#60]
the buttons that come with a notification, since flutter_local_notification does not support that and there are many people needing that

**Comment by rafaelsetragni** [comment]
Yes, all features works for local and push notifications. Some advanced layouts and schedule unfortunately are not working on iOS for a while, but all action buttons functionality are available for both platforms and for local and push notifications.

OBS: This plugin are not related to flutter_local_notifications and should not be used simultaneously with it.

**Comment by AbdulMalikDev** [comment]
Thank you so much @rafaelsetragni  for your work. I really mean it. Please continue developing it as flutter really lacks in this area. Thank you again !
