### ISSUE TITLE
Notification not received on IOS after first click on it

### ISSUE THREAD

**Issue by Niko-by** [rafaelsetragni/awesome_notifications#601]
## **1 - Describe the bug**
Hello!

I send a notification to iOS, it arrives successfully, I click on it and the application opens. Then I close the app with a swipe up and try to send a new notification, but it doesn't get delivered. Then I hit submit again (third notification) and it's successfully received.

That is, after clicking on a notification and closing the application, the next notification will not be delivered.

Tell me what could be the problem?

## **2 - Provide us as much information as possible**

```Dart
```

## **3 - How To Reproduce the Error**

1. Close the application with a swipe up.
2. Send a notification.
3. Click on the notification.
4. Close the application with a swipe up.
5. Send a notification (it won't be delivered)
6. Send another notification (now successfully delivered)

## **4 - Expected behavior**
I expect that after clicking on a notification and closing the app, the next sent notification will also be delivered.

## **6 - Additional context**
awesome_notifications: ^0.7.2
firebase_messaging: ^13.1.0

**Comment by rafaelsetragni** [comment]
If your app is closed with terminated (forced to stop) status, on any platform, any push until the app is reopened by the user will be denied. The concept of forced to stop may change between Android distributions.

**Comment by Niko-by** [comment]
Maybe I explained badly

1. We use iOS, not Android
2. Notifications are delivered via Firebase. We are using a push token from Firebase. The notification is sent from the server side, DATA section, and through Awesome they are displayed. AwesomeNotifications().createNotificationFromJsonData
3. Earlier I described how to reproduce. After closing the application, the first notification is not delivered. Everything else is delivered. This only happens when you clicked on the notification before closing the app. BUT, if you open the app directly and close it with a swipe up, the notifications are successfully delivered! This is very strange behaviour.

How to reproduce the error:
- Close the app with a swipe up.
- Send notification.
- Click on notification.
- Close the app with a swipe up.
- Send notification (it will not be delivered)
- Send another notification (now successfully delivered). But we didn't run the app. Why is this notification delivered and the previous one not?

**Comment by rafaelsetragni** [comment]
Try to get your device log using "Console.app" on macOS and you can find out why your notification is not being delivered.

![image](https://user-images.githubusercontent.com/40064496/196704028-60f9cb74-5be2-4720-9b45-07d5638bd8fd.png)

**Comment by Niko-by** [comment]
But I have an old code implementation, I still use awesome with firebase_messaging.

I will try to transfer the project to awesome_notifications_fcm as you suggested, and later I will write back whether it helped or not.

**Comment by Niko-by** [comment]
> Take a look at this:
> https://developer.apple.com/forums/thread/661351?page=3

It turned out that this error does not apply to us. It disappeared when I switched from TestFlight to the version from the Appstore.

Therefore, the question remains open, I do not understand why the first notification does not come after the application is closed. But all subsequent notifications successfully reach, although the application still remains completely closed. I didn't notice any other errors in the console.

Can you test this behavior for yourself? The notification is sent from the server, here is the configuration:

> {
        data: {
          content: JSON.stringify({
            id: id,
            channelKey: 'real_construction_channel_key',
            title: title,
            body: desc,
            icon: 'resource://drawable/push',
            color: '#0774EA',
            showWhen: true,
            payload: payload ? payload : {},
          }),
        },
        android: {
          priority: "high",
        },
        apns: {
          payload: {
            aps: {
              contentAvailable: true,
            },
          },
          headers: {
            "apns-push-type": "background",
            // Must be `5` when `contentAvailable` is set to true.
            "apns-priority": "5",
            "apns-topic": "com.realconstruction.ios",
          },
        },
        tokens: tokens,
        content_available: true,
        priority: "high",
      }

**Comment by rafaelsetragni** [comment]
```Json
"apns": {
    "payload": {
        "aps": {
            "contentAvailable": true,
        },
    },
    "headers": {
        "apns-push-type": "background",
        // Must be 5 when contentAvailable is set to true.
        "apns-priority": "5",
        "apns-topic": "com.realconstruction.ios",
    },
},
```

This can be problematic. as you're using your push as a silent mode with `background` and `contentAvailable`. This makes your push be handle as background processing and suffer for some execution restrictions. You gonna do this instead:

```Javascript
{
    tokens: tokens,
    mutable_content: true,
    priority: "high",
    notification: {
        title: title,
        body: desc,
    },
    data: {
        content: JSON.stringify({
            id: id,
            channelKey: 'real_construction_channel_key',
            title: title,
            body: desc,
            icon: 'resource://drawable/push',
            color: '#0774EA',
            showWhen: true,
            payload: payload ? payload : {},
        }),
    },
}
```

That's why i created the FCM addon plugin, this way you can use normal push notifications and they are more reliable than silent ones.

**Comment by Niko-by** [comment]
But if we add a block
notification: {
    title: title,
    body:desc
}
then the app will show 2 notifications. The first is from firebase and the second is from awesome. This behavior has been seen on Android. Because I am processing the content through createNotificationFromJsonData. At least that's how it used to be. That's why I use silent notification.

In addition, quick buttons (actionButtons) will not work on ios if you send a notification with a block
notification: {
    title: title,
    body:desc
}

**Comment by rafaelsetragni** [comment]
> But if we add a block notification: { title: title, body:desc } then the app will show 2 notifications. The first is from firebase and the second is from awesome. This behavior has been seen on Android. Because I am processing the content through createNotificationFromJsonData. At least that's how it used to be. That's why I use silent notification.

This is a sign that youre using firebase_messaging, right?

**Comment by Niko-by** [comment]
> This is a sign that youre using firebase_messaging, right?

Yes. So far, we have the old implementation in the code. Is this fixed in awesome_notifications_fcm?

**Comment by Niko-by** [comment]
Ok. I will try and tell you later the result
