### ISSUE TITLE
bigPicture not wrok on ios

### ISSUE THREAD

**Issue by xypmhxy** [rafaelsetragni/awesome_notifications#602]
await AwesomeNotifications().createNotification(
        content: NotificationContent(
            id: 11,
            channelKey: 'Key',
            title: 'Big picture (Network)',
            body:
                'Big picture content (Network)',
            largeIcon:
                'https://media.wired.com/photos/598e35994ab8482c0d6946e0/master/w_2560%2Cc_limit/phonepicutres-TA.jpg',
            bigPicture:
            'https://media.wired.com/photos/598e35994ab8482c0d6946e0/master/w_2560%2Cc_limit/phonepicutres-TA.jpg',
            notificationLayout: NotificationLayout.BigPicture));

in iosEmulator show
 [AWESOME NOTIFICATIONS] Unrecognized attachment file type (NotificationBuilder:568)
but your example is Correct.

How do I solve this problem？i don‘t know why
thanks

**Comment by rafaelsetragni** [comment]
As per the community rules, I will close this issue with invalid status, as the rules were not followed and the requested form was not filled out (was erased).
