### ISSUE TITLE
Build fails with Awesome notification 0.7.3 but works with 0.6.21

### ISSUE THREAD

**Issue by RagehAz** [rafaelsetragni/awesome_notifications#604]
I'm having this problem where the app fails to build, and ran out of options, I tried all solutions mentioned in below link but with no success

https://stackoverflow.com/questions/61930007/how-to-solve-execution-failed-for-task-appcompileflutterbuilddebug

_i tried different versions_

- 0.7.3 fails to build
- 0.7.2 fails to build
- 0.7.1 fails to build
- 0.7.0+1 fails to build
- 0.7.0 fails to build

- 0.6.21 succeeds to build as I'm currently using it,, but lacks the action streams update which is cruicial

```
/C:/flutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/awesome_notifications-0.7.1/lib/src/utils/resource_image_provider.dart:41:26: Error: Type 'DecoderBufferCallback' not found.
      ResourceImage key, DecoderBufferCallback decode) {
                         ^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/awesome_notifications-0.7.1/lib/src/utils/resource_image_provider.dart:49:26: Error: Type 'DecoderBufferCallback' not found.
      ResourceImage key, DecoderBufferCallback decode) async {
                         ^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/awesome_notifications-0.7.1/lib/src/utils/resource_image_provider.dart:22:7: Error: The non-abstract class 'ResourceImage' is missing implementations for these members:
 - ImageProvider.load
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ResourceImage extends ImageProvider<ResourceImage> {
      ^^^^^^^^^^^^^
/C:/flutter/flutter/packages/flutter/lib/src/painting/image_provider.dart:567:24: Context: 'ImageProvider.load' is defined here.
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/awesome_notifications-0.7.1/lib/src/utils/resource_image_provider.dart:41:26: Error: 'DecoderBufferCallback' isn't a type.
      ResourceImage key, DecoderBufferCallback decode) {
                         ^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/awesome_notifications-0.7.1/lib/src/utils/resource_image_provider.dart:49:26: Error: 'DecoderBufferCallback' isn't a type.
      ResourceImage key, DecoderBufferCallback decode) async {
                         ^^^^^^^^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s
Exception: Gradle task assembleDebug failed with exit code 1
```

Any Ideas how to fix this ? I'm out of options

**Comment by mathiasgodwin** [comment]
I'm likewise facing this issue, this is my flutter doctor -v

[✓] Flutter (Channel stable, 3.0.5, on Ubuntu 22.04 LTS 5.15.0-35-generic, locale en_NG)
• Flutter version 3.0.5 at /home/empty/fvm/versions/stable
• Upstream repository https://github.com/flutter/flutter.git
• Framework revision f1875d570e (3 months ago), 2022-07-13 11:24:16 -0700
• Engine revision e85ea0e79c
• Dart version 2.17.6
• DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
• Android SDK at /home/thececilia/Android/Sdk
• Platform android-33, build-tools 33.0.0
• Java binary at: /home/empty/android-studio/jre/bin/java
• Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
• All Android licenses accepted.

[✓] Chrome - develop for the web
• Chrome at google-chrome

[✓] Linux toolchain - develop for Linux desktop
• Ubuntu clang version 14.0.0-1ubuntu1
• cmake version 3.22.1
• ninja version 1.10.1
• pkg-config version 0.29.2

[✓] Android Studio (version 2021.1)
• Android Studio at /home/empty/android-studio
• Flutter plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
🔨 https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.70.2)
• VS Code at /usr/share/code
• Flutter extension version 3.50.0

[✓] Connected device (3 available)
• TECNO BA2 (mobile) • 052553706N010932 • android-arm    • Android 8.1.0 (API 27)
• Linux (desktop)    • linux            • linux-x64      • Ubuntu 22.04 LTS 5.15.0-35-generic
• Chrome (web)       • chrome           • web-javascript • Google Chrome 106.0.5249.119

[✓] HTTP Host Availability
• All required HTTP hosts are available

**Comment by rafaelsetragni** [comment]
> [✓] Flutter (Channel stable, 3.0.5, on Ubuntu 22.04 LTS 5.15.0-35-generic, locale en_NG) • Flutter version 3.0.5 at /home/empty/fvm/versions/stable • Upstream repository https://github.com/flutter/flutter.git • Framework revision f1875d570e (3 months ago), 2022-07-13 11:24:16 -0700 • Engine revision e85ea0e79c • Dart version 2.17.6 • DevTools version 2.12.2

You also need to update your version of Flutter.

**Comment by mathiasgodwin** [comment]
Good call @rafaelsetragni  It worked after updating flutter to version 3.3.5 but no matter what I've tried, scheduled notification still doesn't work! perhaps I'll have to open an issue on this one. Thanks for your time though.

**Comment by rafaelsetragni** [comment]
Nice! Yes, create a new issue in case you're not getting your schedules to be displayed. I gonna close this now.
