### ISSUE TITLE
Why notifications doesn't work if close application immediately after scheduling

### ISSUE THREAD

**Issue by ValeriusGC** [rafaelsetragni/awesome_notifications#608]
Steps to reproduce:

- Install from scratch
- Push button 'Show notification at every single minute o\'clock' (see toast that everything is all right)
- Close application (remove from memory)
- Result – no notifications 

But if one gets first notification in foreground and then closes application then after that everithing works fine – notifications go and go.

Realme XT, Android 11

Flutter 3.3.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18a827f393 (3 weeks ago) • 2022-09-28 10:03:14 -0700
Engine • revision 5c984c26eb
Tools • Dart 2.18.2 • DevTools 2.15.0

**Comment by ValeriusGC** [comment]
I found strange behavior in my device. When i launch on emulator i got permission dialog 
![image](https://user-images.githubusercontent.com/3320861/197340712-e82a51dd-0fe6-48a3-9c82-7b46613c681e.png)
But i got no such dialog when launch on my device. It's very, very strange.

**Comment by awaik** [comment]
It should be because of different Android versions - since Android 13 it is mandatory to ask permission.

**Comment by awaik** [comment]
> I found strange behavior in my device. When i launch on emulator i got permission dialog ![image](https://user-images.githubusercontent.com/3320861/197340712-e82a51dd-0fe6-48a3-9c82-7b46613c681e.png) But i got no such dialog when launch on my device. It's very, very strange.

It should be because of different Android versions - since Android 13 it is mandatory to ask permission.

**Comment by rafaelsetragni** [comment]
> Steps to reproduce:
> 
> * Install from scratch
> * Push button 'Show notification at every single minute o'clock' (see toast that everything is all right)
> * Close application (remove from memory)
> * Result – no notifications
> 
> But if one gets first notification in foreground and then closes application then after that everithing works fine – notifications go and go.
> 
> Realme XT, Android 11
> 
> Flutter 3.3.3 • channel stable • https://github.com/flutter/flutter.git Framework • revision 18a827f393 (3 weeks ago) • 2022-09-28 10:03:14 -0700 Engine • revision 5c984c26eb Tools • Dart 2.18.2 • DevTools 2.15.0

Thats happen because Android clear all intents sent by your app in debug mode, to ensure the next execution will not have residuals from the last execution. If you build your app to release, the schedules will not be erased as soon you stop to run it.



> I found strange behavior in my device. When i launch on emulator i got permission dialog
> ![image](https://user-images.githubusercontent.com/3320861/197340712-e82a51dd-0fe6-48a3-9c82-7b46613c681e.png)
> But i got no such dialog when launch on my device. It's very, very strange.

You need to set the property `targetSdkVersion` to 33 in build.gradle file. Without it, Android 13 will request permission to show notifications as soon the app starts.

**Comment by ValeriusGC** [comment]
> That happen because Android clear all intents sent by your app in debug mode, to ensure the next execution will not have residuals from the last execution. If you build your app to release, the schedules will not be erased as soon you stop to run it.

It is very useful information, thanks!


> You need to set the property `targetSdkVersion` to 33 in build.gradle file. Without it, Android 13 will request permission to show notifications as soon as your app starts.

I use your example, and this version is already set in it.
