### ISSUE TITLE
Version of flutter_driver from sdk depends on platform 3.0.0-nullsafety.2 and not correspond to awesome_notifications 0.0.5+2

### ISSUE THREAD

**Issue by orodrigue12** [rafaelsetragni/awesome_notifications#61]
Because every version of flutter_driver from sdk depends on platform 3.0.0-nullsafety.2 and awesome_notifications 0.0.5+2 depends on platform ^2.2.0, flutter_driver from sdk is incompatible with awesome_notifications 0.0.5+2.

**Comment by rafaelsetragni** [comment]
I can only ensure to use the most updated dependencies version in the stable bracket, because this is the official one.

But you can manually change the dependencies in your local files, with no problem.

**Comment by rafaelsetragni** [comment]
Check this topic and look if this solution works fine for you:
https://github.com/rafaelsetragni/awesome_notifications/issues/49#issuecomment-735338152

**Comment by orodrigue12** [comment]
Well. Thanks

Le mar. 15 déc. 2020 à 15:00, rafaelsetragni <notifications@github.com> a
écrit :
