### ISSUE TITLE
Crash when compiling file awesome_notifications

### ISSUE THREAD

**Issue by ahmadbintariq4u** [rafaelsetragni/awesome_notifications#623]
![image](https://user-images.githubusercontent.com/75003816/198865342-9cf4690e-171e-4b8e-8f5b-fdfe45be391a.png)

![image](https://user-images.githubusercontent.com/75003816/198865370-7aac84bb-f4bf-4923-9fcc-c5d21d1717ae.png)

**Comment by rafaelsetragni** [comment]
Sorry, but i have to drop this issue and mark it as invalid, because you didn't follow the community rules to publish your issue.
