### ISSUE TITLE
Unproper documentation for 'Message' or 'Group Message' notifications. 

### ISSUE THREAD

**Issue by TomasWard1** [rafaelsetragni/awesome_notifications#627]
I am trying to program  'Message' or 'Group Message' notifications like WhatsApp uses, which group the notifications according to the user that sent them or the group that they are coming from. I do not see how to appropriately set and manage these. Could you update the documentation or send an explanation from here?

**Comment by rafaelsetragni** [comment]
On the example app there is a full example on how to implement message layout, including with response text option.
You only need to start the example app with main_complete.dart
