### ISSUE TITLE
MediaPlayer Notification largeIcon Low Resolution on Android API 33

### ISSUE THREAD

**Issue by AdamNSmith** [rafaelsetragni/awesome_notifications#629]
## **1 - Describe the bug**

The `largeIcon` used in the notification on Android API level 33 appears with very low resolution. This is when the `notificationLayout` is `MediaPlayer`.

## **2 - Provide us as much information as possible**

I've tried with the `largeIcon` being a `Network`, `File`, and `Resource` media source type and the image appears equally low-quality on all methods.

Additionally, this doesn't seem to be an issue on lower versions of Android.

* To help us to understand your issue, provide with your bug report all the relevant informations, such as:

* Your plugins list inside the file `pubspec.yaml` (at least all notification plugins)
I'm not using any other notification plugins
 
* What platform did you found the issue
Android API level 33

* What devices did you found the issue
Google Pixel 5

* How are you creating the notification
```Dart
      NotificationContent(
        id: MEDIA_NOTIFICATION_ID,
        channelKey: NotificationChannels.MEDIA.channelKey!,
        title: title,
        body: body,
        notificationLayout: NotificationLayout.MediaPlayer,
        locked: true,
        largeIcon: backgroundImageUrl,
        category: NotificationCategory.Transport,
      );
```

## **3 - How To Reproduce the Error**

1. Display a `MediaPlayer` notification with a `largeIcon` set on it on Android API level 33.
2. Notice the image appears very low-resolution, even if the image is large / high-quality.

## **4 - Expected behavior**
The image appears high-quality

## **5 - Screenshots**
Not needed.

## **6 - Additional context**
Not needed.

**Comment by rafaelsetragni** [comment]
I couldn't reproduce this error. Can you take a print screen of this issue and send me your notification creation method?

**Comment by AdamNSmith** [comment]
Here it is on API 32 (good):
![Screenshot_1667833542](https://user-images.githubusercontent.com/6300971/200344649-846c6761-2749-4bc4-8e3d-3c51da471264.png)

And here it is on API 33 (bad):
![Screenshot_1667833756](https://user-images.githubusercontent.com/6300971/200344746-74d10a47-bc90-404c-81a8-517d7aec4a73.png)

Creating the notification:
```Dart
      NotificationContent(
        id: MEDIA_NOTIFICATION_ID,
        channelKey: NotificationChannels.MEDIA_CHANNEL_KEY,
        title: 'Test title',
        body: 'Test body',
        notificationLayout: NotificationLayout.MediaPlayer,
        autoDismissible: false,
        largeIcon: 'resource://drawable/test',
        category: NotificationCategory.Transport,
        locked: true,
      );
```

And then I'm just calling `createNotification` with that.

**Comment by rafaelsetragni** [comment]
I'm trying to find an Android 13 device to test it out. I'll post my tests here soon. But for now, you can try using asset images instead of native resources.

**Comment by GjoAbrahamN** [comment]
@praxder praxder Did you get any solution for the issue? if yes can you explain? i also having the same problem.

**Comment by praxder** [comment]
We've had enough issues with awesome_notifications that we pivoted away from using it.
