### ISSUE TITLE
Getting receiveNotification: notification discarted

### ISSUE THREAD

**Issue by jwiesmann** [rafaelsetragni/awesome_notifications#63]
> If the service does not wake up and do not get called, the attatch process will keep waiting forever. Sometimes the target extension is not wake up imediately after your app goes up, but instead when a new push notification arives. Put a break point on the first instruction inside didReceive method from AwesomeServiceExtension class:
> 
> https://github.com/rafaelsetragni/awesome_notifications/blob/0a0ac6a16036d2d4c1ae5e2764b64a38efbfa7fb/ios/Classes/lib/Services/AwesomeServiceExtension.swift#L21
> 
> If even in this cases the service extension is not beeing called, so theres something missing on your project configuration to activate your notification service extension.

Hi, 

first of all thank you for this nice plugin! I am having some trouble making it work in IOS though. I am getting exactly the same error like @bysano and followed all tips from here, but i still cannot resolve it. 
Like you stated above, that this method should be called, it is not in my case and i am running out of ideas.

I created everything and even compared it with the settings from https://github.com/bayuramadeza/Awesome-Notification-FCM.

I am getting all kinds of infos, that it is initiated and so on and everything is running fine on android f.e.
`"Awesome Notifications - App Group : group.AwesomeNotifications.....`
`"AwesomeNotificationsPlugin: Awesome Notification service initialized"`

but whenever i receive a notification i am getting:
`"receiveNotification: notification discarted"` 

debuging shows that there is a message, but like you stated above, it is empty and 'didReceive method from AwesomeServiceExtension' is never called.

any ideas?

Thank you!

Edit: Apparently this only happens when the app is running, in the background or terminated it works fine ... 

Edit2: 
Looks like the same behaviour happens with your demo application:
`2020-12-15 14:20:33.402160+0100 Runner[1426:376053] Metal API Validation Enabled
2020-12-15 14:20:33.487702+0100 Runner[1426:376053] [User Defaults] Couldn't read values in CFPrefsPlistSource<0x283120c80> (Domain: group.AwesomeNotifications.com.geektechware.do, User: kCFPreferencesAnyUser, ByHost: Yes, Container: (null), Contents Need Refresh: Yes): Using kCFPreferencesAnyUser with a container is only allowed for System Containers, detaching from cfprefsd
"Awesome Notifications - App Group : group.AwesomeNotifications.com.geektechware.do"
2020-12-15 14:20:33.491409+0100 Runner[1426:376280] 6.34.0 - [Firebase/Core][I-COR000003] The default Firebase app has not yet been configured. Add `[FIRApp configure];` (`FirebaseApp.configure()` in Swift) to your application initialization. Read more: https://goo.gl/ctyzm8.
2020-12-15 14:20:33.517902+0100 Runner[1426:376295] flutter: Observatory listening on http://127.0.0.1:52729/6bgLJaLs9U4=/
2020-12-15 14:20:33.528743+0100 Runner[1426:376274] 6.34.0 - [Firebase/Analytics][I-ACS023007] Analytics v.60900000 started
2020-12-15 14:20:33.528865+0100 Runner[1426:376274] 6.34.0 - [Firebase/Analytics][I-ACS023008] To enable debug logging set the following application argument: -FIRAnalyticsDebugEnabled (see http://goo.gl/RfcP7r)
2020-12-15 14:20:33.530028+0100 Runner[1426:376274] 6.34.0 - [Firebase/Messaging][I-FCM001000] FIRMessaging Remote Notifications proxy enabled, will swizzle remote notification receiver handlers. If you'd prefer to manually integrate Firebase Messaging, add "FirebaseAppDelegateProxyEnabled" to your Info.plist, and set it to NO. Follow the instructions at:
https://firebase.google.com/docs/cloud-messaging/ios/client#method_swizzling_in_firebase_messaging
to ensure proper integration.
2020-12-15 14:20:33.721138+0100 Runner[1426:376281] 6.34.0 - [Firebase/Analytics][I-ACS800023] No pending snapshot to activate. SDK name: app_measurement
2020-12-15 14:20:33.734969+0100 Runner[1426:376281] 6.34.0 - [Firebase/Analytics][I-ACS023012] Analytics collection enabled
2020-12-15 14:20:33.735102+0100 Runner[1426:376281] 6.34.0 - [Firebase/Analytics][I-ACS023220] Analytics screen reporting is enabled. Call +[FIRAnalytics logEventWithName:FIREventScreenView parameters:] to log a screen view event. To disable automatic screen reporting, set the flag FirebaseAutomaticScreenReportingEnabled to NO (boolean) in the Info.plist
"AwesomeNotificationsPlugin: Awesome Notification service initialized"
2020-12-15 14:20:34.334012+0100 Runner[1426:376284] flutter: Firebase token: f98igwOi3UIbvOzxIcfIUq:APA91bFS8JTxekpzK0z3es4XZcbHrsOY_OjI1NR6YtQRHHXpnfsDuTZYo6bt00Bj84sh3vgfk7yRnJ7DXzFzVEK2eITxPWV9aqc5o_8mYzyepEe-WaamiQ5wJkGHemLJ6rCz9W4yYXsg
"receiveNotification: notification discarted"`

**Comment by jwiesmann** [comment]
After some research aso i figured it is not a 'code' - Problem but how you send the message.
I wasn´t aware if the importance of the flag called `mutable-content`. Since i am using FCM from a node backend, the message **must** have the following format: 
`
const payload: any = {
            notification: {
              title: title,
              body: body,
            },
            android: {
              notification: {
                channel_id: 'high_importance',
                icon: 'ic_launcher_round',
                color: '#00AFF0',
              }
            },
            apns: {
              payload: {
                aps: {
                  channelKey: 'high_importance',
                  sound: 'tone_alarm.wav',
                  'mutable-content': 1,
                }
              },
            },
            data: data,
            token: user.token,
          };
`

if you add the `'mutable-content': 1` in the payload (like stated in the documentation) your message will be rejected. (Invalid content ...jadijadi..)

I also learned, that a custom notification implementation on the IOS side is **NEVER** triggered, if you do not provide that flag. I hope it helps someone and/or you could update the documentation. 
Thank you for your awesome plugin!

**Comment by rafaelsetragni** [comment]
Have you tried to send your notification using the documentation package pattern?

[How to send Push Notifications using Firebase Cloud Messaging (FCM)](https://github.com/rafaelsetragni/awesome_notifications#how-to-send-push-notifications-using-firebase-cloud-messaging-fcm)

**Comment by jwiesmann** [comment]
Yes, but that seems to be the legacy implementation and is not supported if you use Firebase Admin SDK.
You can find more info here:

https://firebase.google.com/docs/cloud-messaging/send-message

for example:
```js
    "to" : "[YOUR APP TOKEN]",
    "mutable_content" : true,
````
are not allowed, you will not be able to send a message from your backend, it is just ignored with an error message.
as well as stated in one of the defects here, you have to `stringify` your content in data, or, again, your message is just rejected.

You can find the documentation here:
https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages

As you can see here, data now only accepts the type: `string:string`. that means you cannot write anything like

```js
     data: {
          content: {
                 title: 'myTitle'
          }
     }
````

Here is a fully working example for android and ios send from the Firebase Admin SDK with a nodejs backend.

```js
const flutterAwesomeMsgContent: any = {
    id: 100,
    title: 'mytitle',
    channelKey: 'myChannel',
    body: 'myBody',
    icon: 'ic_launcher_round',
    payload: {
      custom: 'property'
      uid: uid,
    }
  };
  
  const data: any = {
    content: JSON.stringify(flutterAwesomeMsgContent)
  };

  const payload: any = {
    notification: {
      title: einsatz.header,
      body: einsatz.text,
    },
    android: {
      notification: {
        channel_id: 'myChannel',
        icon: 'ic_launcher_round',
        color: '#00AFF0',
      }
    },
    apns: {
      payload: {
        aps: {
          'mutable-content': 1,
        }
      },
    },
    data: data,
    token: user.token,
  };
  admin.messaging().send(payload).then(() => {
    console.log('message send to: ' + user.name + ' ' + user.email);
  }).catch(err => {
    console.log('message NOT send to: ' + user.name + ' ' + user.email);
    console.error(err);
  });
``` 

Hope it helps. As stated before, your implementation works fine :).
It´s just how you send the message!

Have a great day and stay healthy!

**Comment by rafaelsetragni** [comment]
I implemented the notification to use  the default title and body override the default awesome package standard, in case you do not send they empty, as the example in documentation. But that could mask the AwesomeExtension's problem if you are just sending text notifications. Be careful.

The icon, priority and channel_id are implementend also inside the standard awesome's package notification and channels. If you use it apart, i cannot ensure the correct execution.

The empty notification displayed is result of AwesomeServiceExtension not beein executed and the notification is discarted while the app is in foreground because it arives inside onReceive method without the expected awesome_notification data package. If you send the standard notification package empty and the title and body fields fulfiled, but keeps seeing empty notifications, i have 100% of sure that AwesomeServiceExtension is not beeing called.

But, if send the package like youre doing is working for you, no problem. But again, be careful.

But you called my attention to your need to change the icon for each notification. This is a good idea. I gonna implement a new version with icon field for each notification, as you did in your example.

**Comment by rafaelsetragni** [comment]
Since the icon implementation was done in last update, i gonna close this topic.
