### ISSUE TITLE
Platform Exception (Unable to establish connection)

### ISSUE THREAD

**Issue by Mashood97** [rafaelsetragni/awesome_notifications#633]
I am using awesome notifications with action buttons having action type as silent background action and on button action I need to update data on fire store now the issue is it's doing great with Android but on IOS it always gives this error Platform Exception (Unable to establish the connection) on foreground, background, and kill state. 

In AppDelegate.swift I've also added this code as explained in the docs of awesome notifications:
```
  SwiftAwesomeNotificationsPlugin.setPluginRegistrantCallback { registry in          
           SwiftAwesomeNotificationsPlugin.register(
              with: registry.registrar(forPlugin: "io.flutter.plugins.awesomenotifications.AwesomeNotificationsPlugin")!)
              
              }
```
 Please guide what I am doing wrong here as I am really into it for approx 2 days. Thanks

**Comment by rafaelsetragni** [comment]
Hi @Mashood97 , i need you to fill the form questions about your environment, etc, that is presented when you request a new issue. Specially in your case, those informations are extremely required to proceed. I just can do nothing to help you without those informations.

As described in the issue rules, I will mark this issue as invalid and i will be waiting for your new repost.
