### ISSUE TITLE
action button

### ISSUE THREAD

**Issue by MohamedSaad80** [rafaelsetragni/awesome_notifications#636]
I use awesome_notification version 0.6.21
i create notification as this:
await AwesomeNotifications().createNotification(
                      content: NotificationContent(
                        id: widget.notificationId,
                        channelKey: widget.channelId,
                        title: widget.notificationTitle,
                        body: widget.notificationBody,
                        wakeUpScreen: true,
                        category: NotificationCategory.Alarm,
                        fullScreenIntent: true,
                        roundedBigPicture: true,
                      ),
                      actionButtons: [
                        NotificationActionButton(
                          key: "dismiss",
                          label: "Dismiss Alarm",
                          autoDismissible: true,
                        ),
                      ],
                      schedule: NotificationCalendar.fromDate(
                        date: DateTime.now().add(
                          const Duration(minutes: 5),
                        ),
                      ),
                    );

and when the app be in kill state and after press the dismiss button take a few second to dismiss the notification and lunch the app

**Comment by rafaelsetragni** [comment]
When you created this issue, did you see any form to fill out with questions?
