### ISSUE TITLE
request permission to send notification always return false on Web

### ISSUE THREAD

**Issue by EmadBeltaje** [rafaelsetragni/awesome_notifications#639]
`AwesomeNotifications().requestPermissionToSendNotifications()`
always return false when i use it on flutter web

**Comment by rafaelsetragni** [comment]
Yes, the web support was not implemented yet, as described in the main page.

![](https://user-images.githubusercontent.com/40064496/155188371-48e22104-8bb8-4f38-ba1a-1795eeb7b81b.png)
