### ISSUE TITLE
Non-removable notification - feature request

### ISSUE THREAD

**Issue by jabirmayar** [rafaelsetragni/awesome_notifications#64]
Hey, thank you for this awesome - plugin. Is there any possibility of adding non-removable functionality to notifications in android?
Thank you

**Comment by ahmetakil** [comment]
You can achieve this by settings locked: true in your payload

**Comment by ashuvssut** [comment]
> You can achieve this by settings locked: true in your payload

    Future<void> showNotificationWithActionButtons(int id) async {
      await AwesomeNotifications().createNotification(
          content: NotificationContent(
              id: id,
              channelKey: 'basic_channel',
              title: 'Anonymous says:',
              body: 'Hi there!',
              payload: {'uuid': 'user-profile-uuid', 'locked': 'true'}), //<<<<<<<<<<<<<<<<<<<<<<<<<<<
          actionButtons: [
            NotificationActionButton(
                key: 'READ', label: 'Mark as read', autoCancel: false),
            NotificationActionButton(
                key: 'PROFILE', label: 'Profile', autoCancel: true, enabled: false)
          ]);
    }


You mean like this? Actually, It did not work. Can you tell where did it go wrong

**Comment by rafaelsetragni** [comment]
Try this one:

https://github.com/rafaelsetragni/awesome_notifications#notificationcontent-content-in-push-data---required

**Comment by ashuvssut** [comment]
Future<void> showLockedNotification(int id) async {
      AwesomeNotifications().setChannel(NotificationChannel(
          channelKey: "locked_notification",
          channelName: "Locked notification",
          channelDescription: "Channel created on the fly with lock option",
          ));
    
      await AwesomeNotifications().createNotification(
          content: NotificationContent(
              id: id,
              channelKey: 'basic_channel',
              title: 'Locked notification',
              body: 'This notification is locked and cannot be dismissed',
              payload: {'uuid': 'uuid-test'},
              locked:true)); //<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
    }


**trigger**

    SimpleButton(
                'Show notification with\nsimple Action buttons (one disabled)',
                onPressed: () => showLockedNotification(3)
            ),

**Comment by ashuvssut** [comment]
Hello @rafaelsetragni 

Sir there is a mistake in you `notification_util.dart`

mistake near line 213
```
Future<void> showLockedNotification(int id) async {
  AwesomeNotifications().setChannel(NotificationChannel(
      channelKey: "locked_notification",
      channelName: "Locked notification",
      channelDescription: "Channel created on the fly with lock option",
      locked: true //<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<XXXXXXXX
));

  await AwesomeNotifications().createNotification(
      content: NotificationContent(
          id: id,
          channelKey: 'basic_channel',
          title: 'Locked notification',
          body: 'This notification is locked and cannot be dismissed',
          payload: {'uuid': 'uuid-test'}));
}
```

...

Correct One
```
Future<void> showLockedNotification(int id) async {
  AwesomeNotifications().setChannel(NotificationChannel(
      channelKey: "locked_notification",
      channelName: "Locked notification",
      channelDescription: "Channel created on the fly with lock option",
      ));

  await AwesomeNotifications().createNotification(
      content: NotificationContent(
          id: id,
          channelKey: 'basic_channel',
          title: 'Locked notification',
          body: 'This notification is locked and cannot be dismissed',
          payload: {'uuid': 'uuid-test'},
          locked:true)); //<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<Right place
}
```

**Comment by rafaelsetragni** [comment]
No thanks, there was no mistake. You defined the blocked channel for the "locked_notification" key, but sent the message on a "basic_channel" channel.

But there is no problem, you can set the locked property on channel or the notification. Remember, the notification's property has priority over the channel's one.

**Comment by jabirmayar** [comment]
Thank you everyone for the help. I will close this now.
