### ISSUE TITLE
Custom vibration pattern not used

### ISSUE THREAD

**Issue by gruvw** [rafaelsetragni/awesome_notifications#640]
## **1 - Describe the bug**

The custom vibration pattern is not being registered in a simple example.

## **2 - Provide us as much information as possible**

To help us to understand your issue, provide with your bug report all the relevant informations, such as:

* Your plugins list inside the file `pubspec.yaml` (at least all notification plugins): `awesome_notifications: ^0.7.4+1`
* What platform did you found the issue: Android
* What devices did you found the issue: Xiaomi Mi 9T Pro
* The output of `flutter doctor` command: `No issues found!`

Simple application using custom vibration pattern:
```Dart
const String channelKey = 'vibration_issue';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  AwesomeNotifications().initialize(
    null,
    [
      NotificationChannel(
        channelKey: channelKey,
        channelName: 'Vibration Issue',
        channelDescription: 'Vibration Issue Description',
        enableVibration: true,
        vibrationPattern: Int64List.fromList([0, 2000]),
      )
    ],
  );

  AwesomeNotifications().isNotificationAllowed().then((isAllowed) {
    if (!isAllowed) {
      AwesomeNotifications().requestPermissionToSendNotifications(
        channelKey: channelKey,
        permissions: NotificationPermission.values,
      );
    }
  });

  await AwesomeNotifications().createNotification(
    content: NotificationContent(
      id: 0,
      channelKey: channelKey,
      title: 'Simple Notification',
      body: 'Simple body',
      actionType: ActionType.Default,
    ),
  );

  runApp(const MaterialApp(title: 'Vibration Issue'));
}
```

## **3 - How To Reproduce the Error**

1. Create new application with above source code
2. Run `flutter pub add awesome_notifications`
3. Go through https://pub.dev/packages/awesome_notifications#-configuring-android
4. Run application on Android

## **4 - Expected behavior**

Use of the provided custom vibration pattern. Instead, the default one is used.

## **5 - Screenshots**

N/A

## **6 - Additional context**

I did uninstall the app and renamed the `channelKey` multiple times but it did not change the issue.

The custom vibration pattern is working correctly on the same device using `package:flutter_local_notifications` along with the minimal code below.

Minimal working custom vibration pattern example using `package:flutter_local_notifications` (on the same android device):
```dart
void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await FlutterLocalNotificationsPlugin()
      .resolvePlatformSpecificImplementation<
          AndroidFlutterLocalNotificationsPlugin>()!
      .requestPermission();

  await FlutterLocalNotificationsPlugin().initialize(
    const InitializationSettings(
        android: AndroidInitializationSettings('@mipmap/ic_launcher')));

  FlutterLocalNotificationsPlugin().show(
    0,
    "Vibration Working",
    "Vibration Working",
    NotificationDetails(
        android: AndroidNotificationDetails(
      "vibration_working",
      "Vibration Working",
      vibrationPattern: Int64List.fromList([0, 2000]),
    )),
  );

  runApp(const MaterialApp(title: 'Vibration Working'));
}
```

**Comment by rafaelsetragni** [comment]
I'm trying to find an Android 13 device to test it out. I'll post my tests here soon. But for now, you can try using asset images instead of native resources.

**Comment by gruvw** [comment]
I would just like to add that I tried to use `package:vibration/vibration.dart` (`vibration: ^1.7.6`) to generate custom vibration patterns (still on the same exact android device).  
When I call `await Vibration.vibrate(pattern: [0, 2000]);` it is working exactly as expected.  
It does not seem to be an issue with my device or with flutter/android/vibration combination.

**Comment by gruvw** [comment]
Can we reopen please ?

**Comment by rafaelsetragni** [comment]
Sure!

**Comment by gruvw** [comment]
Could you please provide an estimation of when will this be fixed ?  
This is currently putting a project of mine on halt.  
I understand that you cannot fix it at the moment, but can you please give some kind of ETA ?

Thanks a lot.

**Comment by rafaelsetragni** [comment]
Hi @gruvw, i just uploaded the new release versions of 0.7.5-dev.2+1 versions of [awesome_notifications](https://pub.dev/packages/awesome_notifications/versions/0.7.5-dev.2+1) and [awesome_notifications_fcm](https://pub.dev/packages/awesome_notifications_fcm/versions/0.7.5-dev.2+1) to fix this issue. Please, check it out to see if this issue is solved on these new versions.

Also, don't forget to join in your [Discord Beta team](https://discord.com/channels/888523488376279050/933445281243082772) to request fixes and new updates.

**Comment by gruvw** [comment]
Thx, I can't find the commit that solved the issue, can you reference it please ?

**Comment by gruvw** [comment]
I get an error in your library while compiling the fix you provided (@rafaelsetragni):

```dart
: Error: The argument type 'ImmutableBuffer' can't be assigned to the parameter type 'Image'.
resource_image_provider.dart:61
 - 'ImmutableBuffer' is from 'dart:ui'.
 - 'Image' is from 'dart:ui'.
    return decode(buffer);
                  ^
: Error: A value of type 'void' can't be returned from an async function with return type 'Future<Codec>'.
resource_image_provider.dart:61
 - 'Future' is from 'dart:async'.
 - 'Codec' is from 'dart:ui'.
    return decode(buffer);
```

**Comment by rafaelsetragni** [comment]
Remembering that iOS does not have custom vibration patterns, unfortunately. And also some android distributions have some disturbance control to not allow abuse of this feature, as is the case with Xiaomi devices.

**Comment by gruvw** [comment]
The issue is resolved for me.
