### ISSUE TITLE
heads-up notification not poping up

### ISSUE THREAD

**Issue by razfazz** [rafaelsetragni/awesome_notifications#641]
The code / parameters I am using

`AwesomeNotifications().initialize(
    // set the icon to null if you want to use the default app icon
      null,
      [
        NotificationChannel(
            channelKey: 'alerts',
            channelName: 'Alerts',
            channelDescription: 'Notification tests as alerts',
            playSound: true,
            onlyAlertOnce: true,
            groupAlertBehavior: GroupAlertBehavior.All,
            importance: NotificationImportance.High,
            defaultPrivacy: NotificationPrivacy.Public,
            defaultColor: Colors.deepPurple,
            ledColor: Colors.deepPurple)
      ],
      debug: true,

  );`

and then 

`AwesomeNotifications().createNotification(
    content: NotificationContent(
      id: 15,
      channelKey: 'high_importance_channel',
      title: "fdsa",
      body: "fdasfds",
      //bigPicture: message.notification.android.imageUrl,
      // notificationLayout: NotificationLayout.BigPicture,
      displayOnBackground: true,
      displayOnForeground: true,
      // largeIcon: message.notification.android.imageUrl,
    ),
  );`

but the notification does not pop up on the user screen.

thanks in advance for the help

**Comment by rafaelsetragni** [comment]
That could happen because of silent modes or battery save modes. If the device, app or the channel does not have permission to display notifications with hight importance, your notification will not pop up on the screen.

**Comment by rafaelsetragni** [comment]
Definitely this is caused by a device configuration. But to shortcut your work and eliminate some variables, do this instead:

- Test your app in another device (can be an emulator).
- Run the example app in another device.

Then, if everything is okay, you can back to your first device to try to figure out what mode is causing this issue.

Also, you can try to set this high priority manually in you app notification's page.

**Comment by razfazz** [comment]
thank you very much @rafaelsetragni I worked through your example ( https://github.com/rafaelsetragni/awesome_notifications/tree/master/example ) and fixed the issue.
