### ISSUE TITLE
version 0.6.21 for ios

### ISSUE THREAD

**Issue by MohamedSaad80** [rafaelsetragni/awesome_notifications#644]
### Discussed in https://github.com/rafaelsetragni/awesome_notifications/discussions/643

<div type='discussions-op-text'>

<sup>Originally posted by **MohamedSaad80** November  8, 2022</sup>
when I seclude more than 4 notifications in IOS delete from the first to add new notification</div>

**Comment by rafaelsetragni** [comment]
Closing this issue because its progress is still on the discussion thread.
