### ISSUE TITLE
How to show a notification from background AFTER main flutter app is killed by system? 

### ISSUE THREAD

**Issue by zogol** [rafaelsetragni/awesome_notifications#649]
According to my tests, it works very well to display a notification from the background. I currently use the plugin flutter_background_service for this.
Although displaying notifications from the background after boot works but there is one exception.
When the main application is killed by the system due to high resource load. Then the plugin flutter_background_service starts again but notifications are not shown anymore.
Is there any binding to activities that could cause the problem?

**Comment by rafaelsetragni** [comment]
Can you send me your device logs at this moment?

**Comment by zogol** [comment]
I do not have any logs at the moment but I try get more into the issue later and let you know! Thank you

**Comment by zogol** [comment]
I think I fixed the issue. it was just important to initialize the plugin also inside the backgroundservice start method. thank you for support and fast answer!
