### ISSUE TITLE
Displayed Stream only triggers for the latest notification if the app is in background on Ios

### ISSUE THREAD

**Issue by ahmetakil** [rafaelsetragni/awesome_notifications#65]
So whenever a notification arrives to the ios  device if the application is either in background or terminated if there is only 1 notification whenever the app is opened createdStream (or displayedStream both behave identically) triggers with that notification.

But if there is more than one notification only the latest one triggers the streams the prior ones are discarded. 

Example: app is terminated I first send notification with title NOTIFICATION1 then 10 seconds later I send NOTIFICATION2 if I open the app I only see it triggers for NOTIFICATION2.

**Comment by ahmetakil** [comment]
@rafaelsetragni do you know what might cause this? I tried to investigate the notification service extension but I wasn't able to find anything

**Comment by rafaelsetragni** [comment]
I don't inspect it yet, but could be the save manager classes or their data shared between the target extensions and the main app.

This shared is only possible if you configure it with the correct name in your capabilities.

**Comment by rafaelsetragni** [comment]
Is this expected behavior what you think is right? This plugin is still in development and details like this can be changed.

**Comment by ahmetakil** [comment]
I think my error is the notification id's i forgot about that but unfortunately i can't build the app right now the extensions throw 'Could not find or use auto-linked framework 'Flutter' ' errors 

I will take a deeper look once im able to build the app
Again thank you for the response

**Comment by rafaelsetragni** [comment]
@ahmetakil if you think this substitution behaviour is not the correct one we still can change this, this plugin is not in final release.
i've been thinking about it and now i starting to thing the replacement behaviour is not the correct one.

**Comment by ahmetakil** [comment]
Changing the ids to random values fixed the issue for us but right now we need help with the #69
