### ISSUE TITLE
2 Types are not being found when building the app

### ISSUE THREAD

**Issue by LiamCJ** [rafaelsetragni/awesome_notifications#650]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**

When i build my app, the build fails due to three files producing `Error: Type '{TypeName}' not found` 

OBS: avoid to use the expression **"its not working"** or **"is working"** or any other variation. These expressions can mean anything and at same time doesn´t bring any useful information. As soon you rewrite these expressions, you naturally going to be more precise and clear.

## **2 - Provide us as much information as possible**

To help us to understand your issue, provide with your bug report all the relevant informations, such as:

* Your plugins list inside the file `pubspec.yaml` (at least all notification plugins)
none other than Awesome_Notifications
* What platform did you found the issue
MacOs to Build which was going to be built to an Android device
* What devices did you found the issue
Macbook Pro
* How are you initializing the plugin
```Dart
'Future<void> createNotification() async {
    String localTimeZone =
        await AwesomeNotifications().getLocalTimeZoneIdentifier();
    String utcTimeZone =
        await AwesomeNotifications().getLocalTimeZoneIdentifier();
  }';
```
As well as the initialization steps as per the instructions in the documentation
* How are you creating the notification
 I have not created it yet
* The output of `flutter doctor` command
`Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.5, on macOS 12.6 21G115 darwin-x64, locale en-ZA)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
`

OBS: To post a source code in your issue, please use the markdown below:

```Dart
print('Your source code goes here');
```

## **3 - How To Reproduce the Error**
I dont know what to put here since the only steps i took to get the error was the instructions in the documentation for the plugin

...or if you prefer, you can provide us a simple example app on GitHub with the issue already reproduced instead of the steps 2 and 3.

## **4 - Expected behavior**
For the app to build

## **5 - Screenshots**
![image](https://user-images.githubusercontent.com/53043741/201060003-b8f57de5-8ced-421e-ba69-0391897937bc.png)

**Comment by rafaelsetragni** [comment]
You need to update your flutter and dart versions. Use the command `flutter upgrade` to do it.
