### ISSUE TITLE
Run code when scheduled notification without body and title finish

### ISSUE THREAD

**Issue by MrNB0dy** [rafaelsetragni/awesome_notifications#651]
I have scheduled a notification with no title and body, but when finished it is not received by any of the listeners. 

_I think it would be useful to have a stream for this type of notification so that I can perform "scheduled" actions without bothering the user._

**Comment by rafaelsetragni** [comment]
Unfortunately, it's not possible to do it due iOS limitations to execute scheduled source code while the app is in background or terminated. On iOS, your app is freeze while on background and on terminated you cannot execute scheduled tasks in a precise time.

**Comment by MrNB0dy** [comment]
@rafaelsetragni I don't mean the execution of an action at a specific time, I would simply like to be able to listen to notifications without body or title

**Comment by rafaelsetragni** [comment]
Yes, it will not. Because no notification wasn't displayed. Instead you can use `onNotificationCreatedMethod`. Check out the entire notification life cycle:


![](https://user-images.githubusercontent.com/40064496/197368144-7bfcee7e-644a-4bdc-80f1-b4d38c2eaaff.png)

**Comment by MrNB0dy** [comment]
> 
Thank you for your response.
With onNotificationCreatedMethod I receive the event only at creation...is there no way to make it receive an event at the end of the schedule? I know this is not in line with the notification lifecycle, but I think it would be useful

**Comment by rafaelsetragni** [comment]
The schedules never happen if there is no title and body, as you can see in the flowchart.

**Comment by pradeep-spikey-tech** [comment]
Hi @rafaelsetragni, 
I have been testing setListeners for onNotificationDisplayedMethod call on iOS  

The onNotificationDisplayedMethod call fires correctly when the app is in the background if its not a scheduled local notification. 
If it is a scheduled notification, the onNotificationDisplayedMethod listener does not fire when in the background. But instead fires once the app is reopened. 

Is this a default mechanism of how the listener works for scheduled notifications? If not, is there a way to fix the issue? 

I really appreciate any info you can provide. Thanks in advance.
