### ISSUE TITLE
i am having a problem

### ISSUE THREAD

**Issue by faithyoussef** [rafaelsetragni/awesome_notifications#653]
my application cannot run
Running Gradle task 'assembleDebug'...
../../Desktop/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.7.4+1/lib/src/utils/resource_image_provider.dart:40:26: Error: Type 'DecoderBufferCallback' not found.
      ResourceImage key, DecoderBufferCallback decode) {
                         ^^^^^^^^^^^^^^^^^^^^^
../../Desktop/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.7.4+1/lib/src/utils/resource_image_provider.dart:48:26: Error: Type 'DecoderBufferCallback' not found.
      ResourceImage key, DecoderBufferCallback decode) async {
                         ^^^^^^^^^^^^^^^^^^^^^
../../Desktop/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.7.4+1/lib/awesome_notifications_method_channel.dart:186:10: Error: Type 'Uint8List' not found.
  Future<Uint8List?> getDrawableData(String drawablePath) async {
         ^^^^^^^^^
../../Desktop/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.7.4+1/lib/src/utils/resource_image_provider.dart:21:7: Error: The non-abstract class 'ResourceImage' is missing implementations for these members:
 - ImageProvider.load
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class ResourceImage extends ImageProvider<ResourceImage> {
      ^^^^^^^^^^^^^
../../Desktop/flutter/flutter/packages/flutter/lib/src/painting/image_provider.dart:567:24: Context: 'ImageProvider.load' is defined here.
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^^^^
../../Desktop/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.7.4+1/lib/src/utils/resource_image_provider.dart:40:26: Error: 'DecoderBufferCallback' isn't a type.
      ResourceImage key, DecoderBufferCallback decode) {
                         ^^^^^^^^^^^^^^^^^^^^^
../../Desktop/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.7.4+1/lib/src/utils/resource_image_provider.dart:48:26: Error: 'DecoderBufferCallback' isn't a type.
      ResourceImage key, DecoderBufferCallback decode) async {
                         ^^^^^^^^^^^^^^^^^^^^^
../../Desktop/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/awesome_notifications-0.7.4+1/lib/src/utils/resource_image_provider.dart:50:5: Error: 'Uint8List' isn't a type.
    Uint8List? bytes =
    ^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\HP\Desktop\flutter\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1156

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\HP\Desktop\flutter\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 29s
Exception: Gradle task assembleDebug failed with exit code 1
that's the unexpected out form.
it was supposed to produce local notifications on the application.
below are the lines of the notification page.
i am using riverpod and awesome notification
class AppRouter extends _i4.RootStackRouter {
  AppRouter([_i5.GlobalKey<_i5.NavigatorState>? navigatorKey])
      : super(navigatorKey);

  @override
  final Map<String, _i4.PageFactory> pagesMap = {
    NotificationRoute.name: (routeData) {
      return _i4.MaterialPageX<dynamic>(
        routeData: routeData,
        child: _i1.notification(
        ),);
    },
    OrangeRoute.name: (routeData) {
      final args = routeData.argsAs<OrangeRouteArgs>();
      return _i4.MaterialPageX<dynamic>(
        routeData: routeData,
        child: _i2.notification(
          key: args.key,
         // centeredPageText: args.centeredPageText,
        ),
      );
    },
    PurpleRoute.name: (routeData) {
      final args = routeData.argsAs<PurpleRouteArgs>();
      return _i4.MaterialPageX<dynamic>(
        routeData: routeData,
        child: _i3.notification(
          key: args.key,
          //centeredPageText: args.centeredPageText,
        ),
      );
    },
  };

  @override
  List<_i4.RouteConfig> get routes => [
    _i4.RouteConfig(
      NotificationRoute.name,
      path: '/',
    ),
    _i4.RouteConfig(
      OrangeRoute.name,
      path: '/orange-page',
    ),
    _i4.RouteConfig(
      PurpleRoute.name,
      path: '/purple-page',
    ),
  ];
}

/// generated route for
/// [_i1.NotificationPage]
class NotificationRoute extends _i4.PageRouteInfo<void> {
  const NotificationRoute()
      : super(
    NotificationRoute.name,
    path: '/',
  );

  static const String name = 'NotificationRoute';
}

/// generated route for
/// [_i2.OrangePage]
class OrangeRoute extends _i4.PageRouteInfo<OrangeRouteArgs> {
  OrangeRoute({
    _i5.Key? key,
    required String centeredPageText,
  }) : super(
    OrangeRoute.name,
    path: '/orange-page',
    args: OrangeRouteArgs(
      key: key,
      centeredPageText: centeredPageText,
    ),
  );

  static const String name = 'OrangeRoute';
}

class OrangeRouteArgs {
  const OrangeRouteArgs({
    this.key,
    required this.centeredPageText,
  });

  final _i5.Key? key;

  final String centeredPageText;

  @override
  String toString() {
    return 'OrangeRouteArgs{key: $key, centeredPageText: $centeredPageText}';
  }
}

/// generated route for
/// [_i3.PurplePage]
class PurpleRoute extends _i4.PageRouteInfo<PurpleRouteArgs> {
  PurpleRoute({
    _i5.Key? key,
    required String centeredPageText,
  }) : super(
    PurpleRoute.name,
    path: '/purple-page',
    args: PurpleRouteArgs(
      key: key,
      centeredPageText: centeredPageText,
    ),
  );

  static const String name = 'PurpleRoute';
}

class PurpleRouteArgs {
  const PurpleRouteArgs({
    this.key,
    required this.centeredPageText,
  });

  final _i5.Key? key;

  final String centeredPageText;

  @override
  String toString() {
    return 'PurpleRouteArgs{key: $key, centeredPageText: $centeredPageText}';
  }
} 
that's route.gr
as this code almost has been made.
https://github.com/alper-efe-sahin/awesome_notifications_with_riverpod/tree/main/lib/presentation/pages/orange_page

**Comment by rafaelsetragni** [comment]
Update your flutter version using `Flutter upgrade`
