### ISSUE TITLE
mySilentDataHandle not listening for background notifications

### ISSUE THREAD

**Issue by toblinkz** [rafaelsetragni/awesome_notifications#656]
AwesomeNotificationsFcm().initialize(
        onFcmSilentDataHandle: AwesomeNotificationController.mySilentDataHandle,
        onFcmTokenHandle: AwesomeNotificationController.myFcmTokenHandle,
        onNativeTokenHandle: AwesomeNotificationController.myNativeTokenHandle,
        // This license key is necessary only to remove the watermark for
        // push notifications in release mode. To know more about it, please
        // visit http://awesome-notifications.carda.me#prices
        licenseKeys: null,
        debug: debug);
        
        I'm passing the mysilentDataHandle to the AwesomeNotificationFcm initialize function but it still not listening for actions I want to perform in my mySilentDataHandle function

**Comment by rafaelsetragni** [comment]
You mean, mysilentDataHandle being called when the user taps over notification? Because this is an action event, and will fire onActionNotificationHandle from AwesomeNotifications. mySilentDataHandle is callend when you send silent push notifications.

**Comment by lorenzorheinicke** [comment]
> mySilentDataHandle is callend when you send silent push notifications.

@rafaelsetragni We have a similar issue when our app is in the background. The app receives the silent push, which we can see in logcat, but the onFcmSilentDataHandle does not get triggered. 

The onFcmSilentDataHandle does get triggered when the app is in the foreground and we send a silent push. Most likely we are missing an obvious config, but I can't see what else I need to setup.

**Comment by MohamedMegahed77** [comment]
any updates ? 
i have the same issue .

**Comment by rafaelsetragni** [comment]
Guys, try to certify that you're using static global methods to receive notifications, exactly as is done in the example page on pub.dev. You cannot use lambda functions to wrap your static methods on setListeners.
