### ISSUE TITLE
Recreate scheduled notification by same id 

### ISSUE THREAD

**Issue by AlexeyIWS** [rafaelsetragni/awesome_notifications#657]
When used scheduling with same notificationId will be shown only last created notification
Example: 

```
AwesomeNotifications().createNotification(
      content: NotificationContent(
        id: 1,
        channelKey: 'alerts',
        title: 'title',
        body: 'body',
        payload: {'notificationId': '1234567890'},
      ),
      schedule: NotificationCalendar.fromDate(date: DateTime.now().add(const Duration(seconds: 20))),
    );

AwesomeNotifications().createNotification(
    content: NotificationContent(
      id: 1,
      channelKey: 'alerts',
      title: 'title2',
      body: 'body2',
      payload: {'notificationId': '1234567890'},
    ),
    schedule: NotificationCalendar.fromDate(date: DateTime.now().add(const Duration(seconds: 40))),
  );
```
As result the first notification (title: 'title', body: 'body') won't shown

Expectation:  Add the field in NotificationSchedule, for example, "notificationId", that for default null save current logic but for   int value perform override id from NotificationContent
 
This logic will allow show notifications within one unit. Old logic create many notifications without opportunity cancel previous notification.

**Comment by rafaelsetragni** [comment]
And how it should behave in case both notifications had being created, but not fired, and:

- You wanna to cancel only one of the schedules.
- You wanna to update only one of the schedules.

**Comment by AlexeyIWS** [comment]
I'm sorry. Schedules should be with different NotificationContent.id:
```
await AwesomeNotifications().createNotification(
      content: NotificationContent(
        id: 1,
        channelKey: 'alerts',
        title: 'title',
        body: 'body',
        payload: {'notificationId': '1234567890'},
      ),
      schedule: NotificationCalendar.fromDate(date: DateTime.now().add(const Duration(seconds: 20))),
    );

await AwesomeNotifications().createNotification(
    content: NotificationContent(
      id: 2,
      channelKey: 'alerts',
      title: 'title2',
      body: 'body2',
      payload: {'notificationId': '1234567890'},
    ),
    schedule: NotificationCalendar.fromDate(date: DateTime.now().add(const Duration(seconds: 40))),
  );
```

> And how it should behave in case both notifications had being created, but not fired, and:
> 
> You wanna to cancel only one of the schedules.

In this case canceling will being by NotificationContent.id. Due to notification had being created, but not fired, it won't shown  after canceling schedule  

> You wanna to update only one of the schedules.

Also by NotificationContent.id

Only if notifications had being fired, it will can be cancelled by NotificationSchedule.notificationId

**Comment by rafaelsetragni** [comment]
>  > And how it should behave in case both notifications had being created, but not fired, and:
> > You wanna to cancel only one of the schedules.
> 
> In this case canceling will being by NotificationContent.id. Due to notification had being created, but not fired, it won't shown after canceling schedule
> 
> > You wanna to update only one of the schedules.
> 
> Also by NotificationContent.id
> 
> Only if notifications had being fired, it will can be cancelled by NotificationSchedule.notificationId

Doing all this using different IDs is already covered by the plugin.

**Comment by AlexeyIWS** [comment]
> Doing all this using different IDs is already covered by the plugin.

Now not opportunity for creating several scheduler process  that will be send in one notification with same id.
Best way probably to do for NotificationContent own notificationId, but for NotificationSchedule own scheduleId

the schedule will be cancelled by cancelSchedule(scheduleId:...)
the notification will be cancelled by cancelNotification(notificationId:...)

if this logic will embed in the lib it is good due to the result is the best variation
