### ISSUE TITLE
Notifications on foreground

### ISSUE THREAD

**Issue by joankabello** [rafaelsetragni/awesome_notifications#66]
Does this package support notifications on foreground when the app is running on foreground?

**Comment by rafaelsetragni** [comment]
Of course. This is one of the major functionalities.

**Comment by joankabello** [comment]
Thanks for the reply.
I was trying to test the example app, i tried all the notifications but none of them did display on foreground.

**Comment by joankabello** [comment]
![Screenshot_20201220-144540_Samsung Internet.jpg](https://user-images.githubusercontent.com/38832279/102714895-18b4ce80-42d2-11eb-8bd2-2e021f5de954.jpg)

This is what i mean as foreground notification (when the app is running)

**Comment by MaheshPeri19** [comment]
Yes. I found same issue. It is not displaying as headsup notification. Coming notification in system tray, but when we swipe down notification bar, it is appearing. FYI attached screenshots.


![2](https://user-images.githubusercontent.com/58836654/102718345-abbf2a00-430d-11eb-9820-584c99c3f00f.jpg) 


![1](https://user-images.githubusercontent.com/58836654/102718341-a7930c80-430d-11eb-9cda-cddbb448ee6c.jpg)

**Comment by rafaelsetragni** [comment]
Im not understanding the problem. This is not the expected behavior? First, the notification appears as pop up (depending of his priority) and after ti stills on notification bar?

**Comment by MaheshPeri19** [comment]
It is not showing as pop up. Directly appearing in system tray like silent notification with sound. When we swipe down notification bar only we can see it.

**Comment by joankabello** [comment]
I tried all the priority levels and still the heads-up notifications doesn't appear. All the time it stays on the tray.

**Comment by MaheshPeri19** [comment]
I am using Android 10 OS, the same problem occurs.

Samsung Galaxy M30S
Android 10
One UI core 2.0

**Comment by joankabello** [comment]
> I am using Android 10 OS, the same problem occurs.
> 
> Samsung Galaxy M30S
> Android 10
> One UI core 2.0
> 

Yeah, i was wrong in fact, because to make it work you should go to notification settings and choose the options to change the notification priority from 'Sound' to 'Sound & pop up' after you change this on the phone it seems to work. But the `Importance` parameter seems to not make its work with this. Maybe the problem is with the importance or priority level.

**Comment by hardik-weenggs** [comment]
[https://github.com/rafaelsetragni/awesome_notifications/issues/35](url)

**Comment by joankabello** [comment]
Closing issue since it is a duplicate.

> [https://github.com/rafaelsetragni/awesome_notifications/issues/35](url)
