### ISSUE TITLE
MediaPlayer notification layout problem with action buttons v0.7.4.

### ISSUE THREAD

**Issue by sakiraykurt** [rafaelsetragni/awesome_notifications#661]
I have a MediaPlayer notification layout problem. 
Actions buttons not visible on default size.
It works on v0.6.21.
It doesn't work on v0.7.4

![Untitled](https://user-images.githubusercontent.com/20169843/203633076-589548b4-ce4b-4985-8752-9a84085309ee.png)
![Untitled2](https://user-images.githubusercontent.com/20169843/203633091-be72251b-78b4-4926-81dc-077b9aab378b.png)

```
_plugin.createNotification(
content: NotificationContent(
        id: 1,
        channelKey: 'player',
        title: title,
        body: body,
        wakeUpScreen: false,
        autoDismissible: false,
        notificationLayout: NotificationLayout.MediaPlayer),
    actionButtons: [
      playing
          ? NotificationActionButton(
              key: 'pause',
              label: 'Pause',
              icon: 'resource://drawable/res_pause',
              autoDismissible: false,
              // actionType: ActionType.SilentAction
        )
          : NotificationActionButton(
              key: 'play',
              label: 'Play',
              icon: 'resource://drawable/res_play',
              autoDismissible: false,
              // actionType: ActionType.SilentAction
        ),
    ])

**Comment by rafaelsetragni** [comment]
Sorry, but I need the information that was requested on the form you deleted when publishing this issue.
Because of this, as the community rules were not followed, I'm going to close this thread and mark it as invalid.

Please, create a new issue, answering all the information requested in the form.
