### ISSUE TITLE
whatapp call like notification

### ISSUE THREAD

**Issue by ghost** [rafaelsetragni/awesome_notifications#67]
Is it possible to create a whatzapp call like notification with action buttons

**Comment by ashuvssut** [comment]
Create Notification with action buttons
```dart
Future<void> showNotificationWithActionButtonsAndReply(int id) async {
  await AwesomeNotifications().createNotification(
      content: NotificationContent(
          id: id,
          channelKey: 'basic_channel',
          title: 'Anonymous says:',
          body: 'Hi there!',
          payload: {'uuid': 'user-profile-uuid'}),//<<define whatever data you wanna pass
      actionButtons: [
        NotificationActionButton(
          key: 'REPLY',
          label: 'Reply',
          autoCancel: true,
          buttonType: ActionButtonType.InputField,
        ),
        NotificationActionButton(
            key: 'READ', label: 'Mark as read', autoCancel: true),
        NotificationActionButton(
            key: 'ARCHIVE', label: 'Archive', autoCancel: true)
      ]);
}
```
listen to actions recieved when user interacts with the notification/ action buttons

```
AwesomeNotifications().actionStream.listen((receivedNotification) {
      processDefaultActionReceived(receivedNotification);// do whatever you want to do when action is recieved
    });
```

closes #67

**Comment by ashuvssut** [comment]
@rafaelsetragni  has implemented all these in his example app in the example folder. @nsumithradeveloper  kindly look into it.

Good Luck

**Comment by nsumithradeveloper** [comment]
Thanks . It worked perfectly fine. Just one small issue. Notification is hiding in tray after 7 seconds . Is it possible to customize the hiding timer of notification ?

**Comment by ashuvssut** [comment]
Ah no...😅. I dont know about that. I have not seen any examples related to this timer thing. Is it not possible to do so I think.

> see https://stackoverflow.com/questions/5399229/how-to-remove-the-notification-after-the-particular-time-in-android.

Even here the answers say to call `Notification.cancel` using a "timer". So, create a timer. That timer will fire a callback which cancels the Notification. The function to cancel the notification is given in the `Notification_utils.dart` ( search in `./example/lib/' for the file).

Hope this helps.


If this issue is solved then you may close this one.

**Comment by MaheshPeri19** [comment]
Check below issue link with my code, it should keep custom timer.

https://github.com/rafaelsetragni/awesome_notifications/issues/35

If this package provide timer flag, it would be great.

**Comment by rafaelsetragni** [comment]
Is possible to do the same functionality on iOS?

**Comment by MaheshPeri19** [comment]
I havent found anything related to iOS. I checked for setTimeoutAfter() and Category_All equivalent to Android. But i havent found. 

And also checked with Triggers and Notification Categories, but no luck with it.

https://developer.apple.com/documentation/usernotifications

**Comment by rafaelsetragni** [comment]
Now ive added two new layouts to create notifications with chats, like whatsapp. Please take a look.
