### ISSUE TITLE
Module awesome_notifications not found

### ISSUE THREAD

**Issue by awaik** [rafaelsetragni/awesome_notifications#672]
## **1 - Describe the bug**

This is a weird bug, when I ran the app from XCode I get a error
`/ios/Runner/GeneratedPluginRegistrant.m:12:9 Module 'awesome_notifications' not found`

At the same time, if I ran the app with `flutter run` it works.

## **2 - Provide us as much information as possible**

Xcode version Version 14.1 (14B47b)

```
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.3
  awesome_notifications: ^0.7.4
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.0.1 22A400 darwin-arm, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
[✓] VS Code (version 1.73.1)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```

## **4 - Expected behavior**
App should run with XCode

**Comment by Flutter-Tg** [comment]
I have the same issues

**Comment by awaik** [comment]
Switched to the local_notifications plugin.

**Comment by H-Khoujani** [comment]
I have the same issues 
local_notifications not supporting button in notification
