### ISSUE TITLE
Provide flag to enable/disable logging

### ISSUE THREAD

**Issue by Pante** [rafaelsetragni/awesome_notifications#674]
**Is your feature request related to a problem? Please describe.**
Presently, `awesome_notifications` logs all scheduling of notifications regardless of whether debug mode is enabled. This can produce a lot of messages within a short timespan, making it hard to read through the logs during development.
 
![latest](https://user-images.githubusercontent.com/9427324/205884183-4f17c7e7-ed51-4e8c-ae40-25cdb28c25b9.png)

**Describe the solution you'd like**
It will be nice if logging can be enabled/disabled via a flag.

**Comment by rafaelsetragni** [comment]
This flag that you're looking for is the debug parameter in initialization. Set it to false and these log messages will not be printed anymore.
