### ISSUE TITLE
Dynamic notification titles

### ISSUE THREAD

**Issue by MiguelSOliveira** [rafaelsetragni/awesome_notifications#678]
**Is your feature request related to a problem? Please describe.**
I want to have a list of messages to display to the user at a interval, for example:
- The user has a list of ["Hello", "World", "This", "Is", "Me"]

I then would like to schedule daily notifications that would iterate over that list and send a different element every day:
- On day 1 it would send "Hello"
- On day 2 it would send "World"
- etc....

**Describe the solution you'd like**
What I've described above

**Describe alternatives you've considered**
The only alternative that I could think of, is every time the user logs into the app, I would clear the scheduled notification and replace it with a new one pointing to a different element in the list. But this is messy and requires the user to open the app everyday.

**Additional context**
None.

**Comment by MiguelSOliveira** [comment]
Is this completed?

**Comment by rafaelsetragni** [comment]
Sorry, i had seen this post. This is not possible to implement. You can create scheduled notifications, each one with different body and different title, but you can't code notifications like this. To update this values you can create a recurrent background task to make this updates and update an entire week ahead each time.
