### ISSUE TITLE
receiveNotification: notification discarted

### ISSUE THREAD

**Issue by venki889220** [rafaelsetragni/awesome_notifications#68]
Hi,

unable to get the push notifications the error printed in the xcode console is "receiveNotification: notification discarted".Kindly help out in fixing this issue.

Thanks in advance

**Comment by rafaelsetragni** [comment]
Please, check if this topic can help you:

[https://github.com/rafaelsetragni/awesome_notifications/issues/41](https://github.com/rafaelsetragni/awesome_notifications/issues/41)
