### ISSUE TITLE
autoDismissible bug

### ISSUE THREAD

**Issue by SerJoG** [rafaelsetragni/awesome_notifications#681]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**

I run my app on background and it shows notifications but then the only way to dismiss it is with the dismiss action even if auto dismissible is set to true. If I swipe or click clear notification nothing happen.

OBS: avoid to use the expression **"its not working"** or **"is working"** or any other variation. These expressions can mean anything and at same time doesn´t bring any useful information. As soon you rewrite these expressions, you naturally going to be more precise and clear.

## **2 - Provide us as much information as possible**

To help us to understand your issue, provide with your bug report all the relevant informations, such as:

* Your plugins list inside the file `pubspec.yaml` (at least all notification plugins)
* * awesome_notifications: ^0.7.4+1
* What platform did you found the issue
* * Android sdk 33 (9 to 13)
* What devices did you found the issue
* * Realme 9 pro
* * Xiaomi unknown version
* * other android devices in release mode
* How are you initializing the plugin
* * From main I call initializeAwesomeNotifications that call initiale to create the channels
* * 
![image](https://user-images.githubusercontent.com/23215134/207939801-661d92f9-d558-4d78-87fb-9ae5455ecd3f.png)
* * From main I call interceptInitialCallActionRequest that call getInitialNotificationAction but not used (I have proble to understand how to use it and how to pass some data to it indeed I bypass it)
* * From app_name class in init state called initialize notificationseventlistener but I'm pretty sure it's not used
* * Then from a bloc method i call the showNotification method that call createNotification
* How are you creating the notification
* * with createNotification after setting up the channels
* * 
![image](https://user-images.githubusercontent.com/23215134/207939500-03dcd2a4-c7ca-47cc-b520-e54b7a74684f.png)
* The output of `flutter doctor` command
![image](https://user-images.githubusercontent.com/23215134/207937626-9a12e465-eb52-4176-bd6a-e70d2f6c2e39.png)
![image](https://user-images.githubusercontent.com/23215134/207937956-cb47133f-b0d3-4efc-bc20-1e32f06e4e52.png)

OBS: To post a source code in your issue, please use the markdown below:

```Dart
print('Your source code goes here');
```

## **3 - How To Reproduce the Error**

1. Create channel like in the figure above
2. call a method that use createnotification from a bloc method

## **4 - Expected behavior**
The notification is created and showed but is not dismissible. The only way is The button with the "DISMISS" text.

## **5 - Screenshots**
Not open source app.

**Comment by rafaelsetragni** [comment]
If your notification is set locked to true the user can no longer dismiss the notification from the notification tray. This kind of notification is only dismissed when the user close the app or the app programatically dismiss the notification.

autoDismissible is the option to set the notification behavior after the user taps over it. If this option is set to true, the notification will be dismissed after the user taps on it, but the user can dismiss the notificaiton swiping it.

And, for last, ActionType.dimissAction is a button option to make the notification action activates onDismissedMethod instead of the default onActionReceivedMethod.

**Comment by SerJoG** [comment]
Thank you very much. There're some examples on how to use the event configured in the notificationeventlistener? I copied and pasted the event like in the example you made but it's not used and I don't understand how to use it.
