### ISSUE TITLE
Foreground services section improvement

### ISSUE THREAD

**Issue by SupremeDeity** [rafaelsetragni/awesome_notifications#682]
The foreground services section needs to have more information.

1) Replace the `<service>` tag sample with:
```xml
<service android:name="me.carda.awesome_notifications.core.services.ForegroundService"
          android:enabled="true"            
          android:exported="false"
          android:stopWithTask="true"
          tools:replace="android:foregroundServiceType"
          android:foregroundServiceType="dataSync" />
></service>
```
It is to be noted that i had to add `tools:replace="android:foregroundServiceType"` to the `<service>` tag and `xmlns:tools="http://schemas.android.com/tools"` to the `<manifest>` tag for my program to even compile(maybe add to a note or something in case this isnt a issue and just some relating to the setup of my app). This also shows how to set the ServiceType.

2) A better example for updating a foreground service should be added for those using the ProgressBar layout. If not, atleast a small explanation of how to update the foreground service. While I'm not sure if this is the correct way, seeing how its done normally in android and trying something like this worked for me.

**Create Service:**
```dart
final int notifID = 1;
AndroidForegroundService.startAndroidForegroundService(
        foregroundStartMode: ForegroundStartMode.stick,
        foregroundServiceType: ForegroundServiceType.dataSync,
        content: NotificationContent(
          id: notifID,
          channelKey: 'notif',
          title: "Service Notif",
          category: NotificationCategory.Service,
          notificationLayout: NotificationLayout.ProgressBar,
        ),
        actionButtons: [
          NotificationActionButton(key: 'CANCEL', label: 'Cancel')
        ]);
```

**Update notification service with a `AwesomeNotifications().createNotification()`**:
```dart
AwesomeNotifications().createNotification(
          content: NotificationContent(
            id: notifID,
            channelKey: 'notif',
            title:
                'Service Notif',
            body: "name",
            category: NotificationCategory.Service,
            notificationLayout: NotificationLayout.ProgressBar,
            progress: progress,
            autoDismissible: false,
            locked: true,
          ),
          actionButtons: [
            NotificationActionButton(key: 'CANCEL', label: 'Cancel')
          ]);
```
**Stop the foreground service after you are done**
```dart
AndroidForegroundService.stopForeground(notifID);
```

Foreground service still gets updated with `AndroidForegroundService.startAndroidForegroundService()`, however doing it this way shows the notification in a less jittery manner.

**Comment by Musta-Pollo** [comment]
❤️ Thank you!
