### ISSUE TITLE
Notification of type alarm stops playing when expanding notification panel

### ISSUE THREAD

**Issue by rrnicolay** [rafaelsetragni/awesome_notifications#683]
## **1 - Describe the bug**

A notification of type **"alarm"** is not working properly (at least on **Android 13**). When the **notification panel gets expanded**, the **sound stops playing**. The expected behavior would be keep playing the alarm until the notication gets dismissed, snoozed, stopped, etc

## **2 - Provide us as much information as possible**

* Android 13
* Using the **example app from version 0.7.3**
* Flutter doctor output:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.5, on Ubuntu 20.04.5 LTS 5.15.0-56-generic, locale
    en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2021.2)
[✓] VS Code
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!
```
* Even on latest version (0.7.4+1), creating a notification like shown below produces the same result described above.

```Dart
await AwesomeNotifications().createNotification(
    content: NotificationContent(
      id: createUniqueId(),
      channelKey: 'scheduled_channel',
      title: 'Alarm',
      body: 'It\'s time to wake up!',
      notificationLayout: NotificationLayout.Default,
      wakeUpScreen: true,
      category: NotificationCategory.Alarm,
      autoDismissible: true,
    ),
    ...
```

## **3 - How To Reproduce the Error**

1. Install the example app from version 0.7.3 on Android 13.
2. Click on "Show alarm notification" (Notifications Special Category section)
3. Expand the notification panel (slide from top to botton)
4. See error (alarm stops playing)

## **4 - Expected behavior**
Alarm should keep playing until some action from user side.

## **6 - Additional context**
First of all, congratulations for the plugin development! Good job!
Some off-topics:
1. Using notifications is the recommended way to implement an alarm nowadays in Flutter. Right?
2. How to dodge silent mode and play the alarm sound?

**Comment by rafaelsetragni** [comment]
This is the default behavior on Android. When you expand the notification tray, the sound stops.

**Comment by rrnicolay** [comment]
Ow! I didn't know that! That's unfortunate.
So I guess I will have to use a service to play the sound for me until user clicks an ActionButton.
Closing the bug.
Thanks!
