### ISSUE TITLE
iOS foreground app can not receive notifications

### ISSUE THREAD

**Issue by longvhv** [rafaelsetragni/awesome_notifications#70]
I have setup awesome_notifications step by step, build app successfully, everything work well in Android, but in iOS, I only received notifications push from server (by firebase), but cannot receive notifications when the app is in foreground. Kindly help out in fixing this issue.

Thanks in advance

**Comment by rafaelsetragni** [comment]
Please, check if this topic can help you:

[https://github.com/rafaelsetragni/awesome_notifications/issues/41](https://github.com/rafaelsetragni/awesome_notifications/issues/41)

**Comment by longvhv** [comment]
> Please, check if this topic can help you:
> 
> #41
Thank you, but I can not find the answer for my case :(
