### ISSUE TITLE
Don't get a callback onActionReceivedMethod in terminated mode when clicking on action buttons in the push notification

### ISSUE THREAD

**Issue by anocean2** [rafaelsetragni/awesome_notifications#701]
Hello! 
I have a flutter application that receives FCM Data messages.

I create a local notification on each data message using the awesome_notifications. I have action button on the notification. The action button click when the application is in the foreground or background(paused) work fine. 

But the same click action doesn't work when the app is terminated/killed. 

I can't get callback to onActionReceivedMethod in terminated mode when click on action button. 

Code create push notification with action button:

```
 static Future<bool> showNotification(Notification notification) async {
      return await AwesomeNotifications().createNotification(
        content: NotificationContent(
            id: math.Random.secure().nextInt(1000),
            channelKey: 'channel_id',
            title: fetchTitle(notification),
            body: fetchDescription(notification),
            notificationLayout: NotificationLayout.Messaging,
            summary: 'Summary',
            payload: notification.payload.toJson().map((key, value) => MapEntry(key, value?.toString()))),
        actionButtons: [
          NotificationActionButton(
              key: ActionButtonKey.pushMessengerAnswer.name,
              label: ActionButtonKey.pushMessengerAnswer.label,
              requireInputText: true)
        ],
      );    
}
```

**Comment by rafaelsetragni** [comment]
You need to use LogCat on Android or Console.app on iOS to get the app logs while the app is terminated. Not all resources are available when the application is terminated.

Also, you need to initialize all plugins manually to be used on terminated state, following the [Extra iOS Setup for Background Actions](https://pub.dev/packages/awesome_notifications#-extra-ios-setup-for-background-actions) and do the same for Awesome Notifications FCM.

**Comment by Kanwarpalsingh1986** [comment]
same issue
