### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by SeriousMonk** [rafaelsetragni/awesome_notifications#707]
Hi, really incredible package, so simple to integrate compared to firebase_messaging.

Is web support being worked on?
Because currently, notifications on web are not supported anywhere even by flutter_local_notifications.

I tried using ([Notification](https://api.dart.dev/stable/2.18.7/dart-html/Notification-class.html))class from dart:html but it is very low level and does not support setting action buttons.

The best way for now is using firebase_messaging package and the [showNotification](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification) method in the service worker. However even there handling the user interaction with the notification is impossible.

**Comment by hatemragab** [comment]
Any updates here?
