### ISSUE TITLE
Can't build release APK

### ISSUE THREAD

**Issue by joankabello** [rafaelsetragni/awesome_notifications#71]
When i try to build a release apk, flutter logs this errors. It looks like errors from awesome_notifications.
Flutter version: 1.22.0
awesome_notifications: ^0.0.5+4
Below im attaching the logs that i get from flutter.

> Launching lib/main.dart on SM G965F in release mode...
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Could not determine the dependencies of task ':app:lintVitalRelease'.   
> Could not resolve all artifacts for configuration ':app:debugAndroidTestRuntimeClasspath'.
   > Could not resolve com.google.code.findbugs:jsr305:{strictly 1.3.9}.
     Required by:                                                       
         project :app                                                   
      > Cannot find a version of 'com.google.code.findbugs:jsr305' that satisfies the version constraints: 
           Dependency path 'android:app:unspecified' --> 'androidx.test.espresso:espresso-core:3.1.1' --> 'com.google.code.findbugs:jsr305:2.0.1'
           Constraint path 'android:app:unspecified' --> 'com.google.code.findbugs:jsr305:{strictly 1.3.9}' because of the following reason: debugRuntimeClasspath uses version 1.3.9
           Dependency path 'android:app:unspecified' --> 'me.carda.awesome_notifications:awesome_notifications:1.0' --> 'com.google.guava:guava:24.1-jre' --> 'com.google.code.findbugs:jsr305:1.3.9'
                                                                        
   > Could not resolve com.google.code.findbugs:jsr305:2.0.1.           
     Required by:                                                       
         project :app > androidx.test.espresso:espresso-core:3.1.1      
      > Cannot find a version of 'com.google.code.findbugs:jsr305' that satisfies the version constraints: 
           Dependency path 'android:app:unspecified' --> 'androidx.test.espresso:espresso-core:3.1.1' --> 'com.google.code.findbugs:jsr305:2.0.1'
           Constraint path 'android:app:unspecified' --> 'com.google.code.findbugs:jsr305:{strictly 1.3.9}' because of the following reason: debugRuntimeClasspath uses version 1.3.9
           Dependency path 'android:app:unspecified' --> 'me.carda.awesome_notifications:awesome_notifications:1.0' --> 'com.google.guava:guava:24.1-jre' --> 'com.google.code.findbugs:jsr305:1.3.9'
                                                                        
   > Could not resolve com.google.code.findbugs:jsr305:1.3.9.           
     Required by:                                                       
         project :app > com.google.guava:guava:24.1-jre                 
      > Cannot find a version of 'com.google.code.findbugs:jsr305' that satisfies the version constraints: 
           Dependency path 'android:app:unspecified' --> 'androidx.test.espresso:espresso-core:3.1.1' --> 'com.google.code.findbugs:jsr305:2.0.1'
           Constraint path 'android:app:unspecified' --> 'com.google.code.findbugs:jsr305:{strictly 1.3.9}' because of the following reason: debugRuntimeClasspath uses version 1.3.9
           Dependency path 'android:app:unspecified' --> 'me.carda.awesome_notifications:awesome_notifications:1.0' --> 'com.google.guava:guava:24.1-jre' --> 'com.google.code.findbugs:jsr305:1.3.9'
                                                                        
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org                              
                                                                        
BUILD FAILED in 3s                                                      
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                       4.5s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin flutter_blue...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                    3.4s
✓ Built build/app/outputs/repo.
Building plugin awesome_notifications...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                    0.0s

/usr/bin/env: ‘bash\r’: No such file or directory

Exception: The plugin awesome_notifications could not be built due to the issue above.

**Comment by joankabello** [comment]
Looks like a problem with this `com.google.code.findbugs:jsr305:1.3.9'` plugin.
If i override it on build.gradle 

`
configurations.all {
 resolutionStrategy.force 'com.google.code.findbugs:jsr305:1.3.9'
}
`
It works fine. Maybe it should be upgraded into a newer version ?

**Comment by rafaelsetragni** [comment]
Sure! Upgrade you Android to AndroidX and the other libraries too

But, before make those upgrade process, do a backup of your project. This is very important.

**Comment by joankabello** [comment]
In fact my project is using AndroidX and other libraries too.

When i remove the `awesome_notification` plugin from `pubspec.yaml` the error doesn't show anymore.

I was thinking that the plugins or libraries of `awesome_notification` should be upgraded, since the error tells me that my project uses `com.google.code.findbugs:jsr305:2.0.1` and `awesome_notification` uses `com.google.code.findbugs:jsr305:1.3.9`.
