### ISSUE TITLE
mySilentDataHandle not show the notification

### ISSUE THREAD

**Issue by MohamedMegahed77** [rafaelsetragni/awesome_notifications#712]
i have an issue/bug in myslientDataHanlde event .
the problem is that when pushing fcm the event is fired but the notification not appear and this is the message from application log 

**Awesome Notifications FCM detached from Android 33** 

**my code** 

  @pragma("vm:entry-point")
  static Future<void> mySilentDataHandle(FcmSilentData silentData) async {
    print('"SilentData": ${silentData.toString()}');

    await AwesomeNotifications().createNotification(
      content: NotificationContent(
        id: -1,
        channelKey: 'alerts',
        title:  silentData.data!["title"]?.toString(),
        body: silentData.data!["body"]?.toString(),
        payload: silentData.data,
        wakeUpScreen: true,
        fullScreenIntent: true,
        autoDismissible: false,
        category: NotificationCategory.Call,
        locked: true,
        criticalAlert: true,
        showWhen: true,
        displayOnForeground: true,
      ),
      actionButtons: [
        NotificationActionButton(
          key: 'accept',
          label: 'Accept',
          actionType: ActionType.Default,
        ),
        NotificationActionButton(
          isDangerousOption: true,
          key: 'reject',
          label: 'Reject',
          actionType: ActionType.DismissAction,
        ),
      ],
    );
    if (silentData.createdLifeCycle != NotificationLifeCycle.Foreground) {
      print("bg");
    } else {
      print("FOREGROUND");
    }

    print('mySilentDataHandle received a FcmSilentData execution');
    await executeLongTaskInBackground();
  }

**yaml**

  awesome_notifications: ^0.7.4+1
  awesome_notifications_fcm: ^0.7.4+1

**Comment by rafaelsetragni** [comment]
First, you shouldn't use myslientDataHanlde to display notifications. To display notifications, you need to use the normal push notification instead. Then, send me your logs while the silent push is sent.
