### ISSUE TITLE
repeatPreciseThreeTimes() error of the provided examples 

### ISSUE THREAD

**Issue by myksh7** [rafaelsetragni/awesome_notifications#714]
Hi thank you for providing local notification solution....

flutter version : 3.3.1 and 3.3.10
awesome :  latest version (0.7.4+1)
os : android
1. provide sample : 
static Future<void> repeatPreciseThreeTimes() async {
    await AwesomeNotifications().createNotification(
        content: NotificationContent(
            id: -1,
            channelKey: 'scheduled',
            title: 'Notification scheduled to play precisely 3 times',
            body: 'This notification was schedule to play precisely 3 times.',
            notificationLayout: NotificationLayout.BigPicture,
            bigPicture: 'asset://assets/images/melted-clock.png'),
        schedule: NotificationAndroidCrontab(preciseSchedules: [
          DateTime.now().add(Duration(minutes: 10)).toUtc(), // seconds -> minutes
          DateTime.now().add(Duration(minutes: 25)).toUtc(),
          DateTime.now().add(Duration(minutes: 45)).toUtc()
        ], repeats: true));
  }

exceute result:
 A) debug console : E/Android: [Awesome Notifications](32200): Schedule time is invalid (NotificationCrontabModel:58)
 B) error message : Exception has occurred. PlatformException (PlatformException(INVALID_ARGUMENTS, Schedule time is invalid, arguments.invalid.notificationCrontab, null))
 C) debuging error
   code:"INVALID_ARGUMENTS"
  details:"arguments.invalid.notificationCrontab"
  message:"Schedule time is invalid"
  stacktrace:null
  hashCode:1061009555
  runtimeType:Type (PlatformException)	
D) real error position : NotificationCrontabModel.java ( getNextValidDate method)

2. another crontab malfunction 
provide sample:
static Future<void> repeatMultiple5Crontab() async {
    String localTimeZone =
        await AwesomeNotifications().getLocalTimeZoneIdentifier();            
    await AwesomeNotifications().createNotification(
        content: NotificationContent(
            id: 989898, //-1,
            channelKey: 'scheduled',
            title: 'Notification at every 5 seconds for 1 minute',
            body:
                'This notification was schedule to repeat at every 5 seconds.'),
        schedule: NotificationAndroidCrontab(
            initialDateTime: DateTime.now().add(Duration(seconds: 10)).toUtc(),
            expirationDateTime:
                DateTime.now().add(Duration(seconds: 10, minutes: 10)).toUtc(),
            crontabExpression: '/20 * * * * ? *', // 5
            timeZone: localTimeZone,
            repeats: true));
  }

execute result :  
   0.7.4 :  every 20 second expected but always every 5 second alarm repeate
   0.7.4+1 : every 20 second expected but always every 1 second alarm repeate

* do you know this error or malfunction reason ?
  nor correct next upgrade version ?
I need this function.. sincerely asking....

thank you

**Comment by rafaelsetragni** [comment]
Hello,

We have confirmed that the issue you reported is indeed a bug. Rest assured, we will address this in our upcoming 0.7.5 release. Once the pre-release version becomes available, we will update you here.

Thank you for bringing this to our attention!

**Comment by rafaelsetragni** [comment]
Hi @myksh7, i just uploaded the new release versions of 0.7.5-dev.2+1 versions of [awesome_notifications](https://pub.dev/packages/awesome_notifications/versions/0.7.5-dev.2+1) and [awesome_notifications_fcm](https://pub.dev/packages/awesome_notifications_fcm/versions/0.7.5-dev.2+1) to fix this issue. Please, check it out to see if this issue is solved on these new versions.

Also, don't forget to join in your [Discord Beta team](https://discord.com/channels/888523488376279050/933445281243082772) to request fixes and new updates.
