### ISSUE TITLE
onNotificationDisplayed & onNotificationDismissed callback not working IOS

### ISSUE THREAD

**Issue by TomasWard1** [rafaelsetragni/awesome_notifications#717]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**
onNotificationCreated will be called but onNotificationDisplayed & onNotificationDismissed do not work. Neither in background nor in foreground.

The notification DOES ARRIVE correctly, but if I swipe to dismiss it, the handler is not called. If I tap on it, the handler onActionReceived IS called. onNotificationCreated is called when fcm notification arrives, yet when notification is displayed onNotificationDisplayed IS NOT called.

Note: Debug set to true or false does not change behavior. Works on android.

## **2 - Provide us as much information as possible**
Using IOS physical device to receive notifications, IOS simulator to send them.
Using fcm extension of awesome notifications
Plugin initialization:
```Dart
AwesomeNotifications().initialize(
      null,
      [
        NotificationChannel(
            channelGroupKey: 'basic_channel_group',
            importance: NotificationImportance.Max,
            channelKey: 'basic_channel',
            channelName: 'Basic notifications',
            channelDescription: 'Main channel.',
            defaultColor: Color(0xFF53E7DF),
            ledColor: Color(0xFF53E7DF))
      ],
      channelGroups: [
        NotificationChannelGroup(channelGroupKey: 'basic_channel_group', channelGroupName: 'Basic group')
      ],
      debug: false);

  FcmManager.initializeRemoteNotifications(debug: false);
e

  AwesomeNotifications().setListeners(
      onActionReceivedMethod: FcmManager.onActionReceivedMethod,
      onNotificationCreatedMethod: FcmManager.onNotificationCreatedMethod,
      onNotificationDisplayedMethod: FcmManager.onNotificationDisplayedMethod,
      onDismissActionReceivedMethod: FcmManager.onDismissActionReceivedMethod);
```

## **3 - How To Reproduce the Error**

1. Use IOS physical device
2. send notification to fcm token of that device with notification section in JSON post request
3. onNotificationCreated will be called but onNotificationDisplayed & onNotificationDismissed do not work. Neither in background nor in foreground

## **4 - Expected behavior**
callbakcs are called

## **6 - Additional context**
Here are my callback methods:
```Dart
/// Use this method to detect every time that a new notification is displayed
  @pragma("vm:entry-point")
  static Future<void> onNotificationDisplayedMethod(ReceivedNotification receivedNotification) async {
    print("onNotificationDisplayedMethod");
    //this is not called ever
    try {
      print(receivedNotification.toMap());
      FrediNotification frediNotification = FrediNotification.fromMap(receivedNotification.toMap());
      await NotificationManager().handleNotification(frediNotification);
      FlutterAppBadger.updateBadgeCount(Get.find<FrediUserController>().notificationCount);
    } catch (e, s) {
      print(e.toString() + ' stakctrace $s');
    }
  }

  /// Use this method to detect when a new notification or a schedule is created
  @pragma("vm:entry-point")
  static Future<void> onNotificationCreatedMethod(ReceivedNotification receivedNotification) async {
    // Your code goes here
    print('onNotificationCreatedMethod');
    //this is called correctly
  }



  /// Use this method to detect if the user dismissed a notification
  @pragma("vm:entry-point")
  static Future<void> onDismissActionReceivedMethod(ReceivedAction receivedAction) async {
    print('onDismissActionReceivedMethod');
    //this is not called ever
    try {
      FrediNotification frediNotification = FrediNotification.fromMap(receivedAction.toMap());
      await NotificationManager().markArrivedNotificationAsRead(frediNotification);
    } catch (e, s) {
      print(e.toString() + ' stakctrace $s');
    }
  }

  /// Use this method to detect when the user taps on a notification or action button
  @pragma("vm:entry-point")
  static Future<void> onActionReceivedMethod(ReceivedAction receivedAction) async {
    print('onActionReceivedMethod');
    //this is called correctly
    try {
      FrediNotification frediNotification = FrediNotification.fromMap(receivedAction.toMap());
      NotificationManager().handleAction(frediNotification);
      await NotificationManager().markArrivedNotificationAsRead(frediNotification);
    } catch (e,s) {
      print('error with notification $e: ${receivedAction.toMap()} $s');
    }
  }

  static Future<void> initializeRemoteNotifications({required bool debug}) async {
    await AwesomeNotificationsFcm().initialize(
        onFcmSilentDataHandle: myFCMSilentDataHandle,
        onFcmTokenHandle: myFcmTokenHandle,
        onNativeTokenHandle: myNativeTokenHandle,
        licenseKeys: [
          // me.carda.awesomeNotificationsFcmExample
          'B3J3yxQbzzyz0KmkQR6rDlWB5N68sTWTEMV7k9HcPBroUh4RZ/Og2Fv6Wc/lE'
              '2YaKuVY4FUERlDaSN4WJ0lMiiVoYIRtrwJBX6/fpPCbGNkSGuhrx0Rekk'
              '+yUTQU3C3WCVf2D534rNF3OnYKUjshNgQN8do0KAihTK7n83eUD60=',

          // me.carda.awesome_notifications_fcm_example
          'UzRlt+SJ7XyVgmD1WV+7dDMaRitmKCKOivKaVsNkfAQfQfechRveuKblFnCp4'
              'zifTPgRUGdFmJDiw1R/rfEtTIlZCBgK3Wa8MzUV4dypZZc5wQIIVsiqi0Zhaq'
              'YtTevjLl3/wKvK8fWaEmUxdOJfFihY8FnlrSA48FW94XWIcFY=',
        ],
        debug: debug);
  }
```

**Comment by rafaelsetragni** [comment]
The notification events are only delivered after setListeners method being called, and they are not always delivered at same time as they happen. Also, iOS can deny the dissmiss event delivery sometimes due to user privacity. Take a look at:

[⚡️ Notification Events](https://pub.dev/packages/awesome_notifications#-notification-events)

**Comment by TomasWard1** [comment]
Thanks for the reply. setListeners is being called in main.dart before initializing the main screen, so that is not the problem. User privacy/denial should be a problem either because, as I mentioned, some listeners are called and some aren't (on the same notification). As you state in your docs:

> onNotificationDisplayedMethod (optional): Fires when a notification is displayed on system status bar

...and this is not happening. Please examine if there is another solution or if you have more questions, I am happy to provide more code, etc. 

Thanks

**Comment by TomasWard1** [comment]
Has this happened to anyone else or just me? Any updates?

**Comment by haily2706** [comment]
Did you find a solution for this issue? @TomasWard1 and @rafaelsetragni ? please share with me the approach to deal with it.  Thank You!

**Comment by rafaelsetragni** [comment]
Hi @haily2706 and @TomasWard1, i just uploaded the new release versions of 0.7.5-dev.2+1 versions of [awesome_notifications](https://pub.dev/packages/awesome_notifications/versions/0.7.5-dev.2+1) and [awesome_notifications_fcm](https://pub.dev/packages/awesome_notifications_fcm/versions/0.7.5-dev.2+1) to fix this issue. Please, check it out to see if this issue is solved on these new versions.

Also, don't forget to join in your [Discord Beta team](https://discord.com/channels/888523488376279050/933445281243082772) to request fixes and new updates.

**Comment by sunguard** [comment]
In my case (not about onNotificationDismissed, just for onNotificationDisplayed),
the listener worked well after I create an immediate notification without schedule.

```
static Future<void> initializeListeners() async {
    if (await Permission.notification.isGranted) {
      await _instance.createNotification(
        content: NotificationContent(
          id: -1,
          channelKey: 'channel_key',
          displayOnForeground: false,
          displayOnBackground: false,
        ),
      );
    }
  }
```

**Comment by abdulBuildIT** [comment]
This issue appeared again

**Comment by pedrohsampaioo** [comment]
It's happening yet
