### ISSUE TITLE
icon doesn't show right, it turns into white block

### ISSUE THREAD

**Issue by Mae623** [rafaelsetragni/awesome_notifications#719]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**

I set the right icon path in initialize function, and I set the right icon file in the right file. Notifications could be created and displayed, but the icon doesn't show right, it turns into white block.

## **2 - Provide us as much information as possible**

* Your plugins list inside the file `pubspec.yaml` (at least all notification plugins)
   awesome_notifications: ^0.7.4+1
* What platform did you found the issue
  Android
* How are you initializing the plugin
```Dart      
      AwesomeNotifications().initialize(
      'resource://drawable/launcher_icon',
      <NotificationChannel>[
        NotificationChannel(
          channelKey: keyRemindChannel,
          channelName: '提醒',
          channelDescription: '自律帮的提醒功能使用这个通知。',
          channelShowBadge: false,
          playSound: true,
          enableVibration: true,
          enableLights: true,
        ),
        NotificationChannel(
          channelKey: keyTimingChannel,
          channelName: '计时器',
          channelDescription: '自律帮的计时器提醒功能使用这个通知。',
          channelShowBadge: false,
          playSound: false,
          enableVibration: false,
          locked: true,
          onlyAlertOnce: true,
        ),
        NotificationChannel(
          channelKey: keyTimerFinishChannel,
          channelName: '计时到时提醒',
          channelDescription: '自律帮的计时到时提醒功能使用这个通知。',
          channelShowBadge: false,
          playSound: true,
          enableVibration: true,
          locked: true,
          onlyAlertOnce: true,
          enableLights: true,
        ),
      ],
    );
```
* How are you creating the notification
```Dart        
        final TimeOfDay time = TimeOfDay(
          hour: int.parse(reminder.remindAt.substring(9, 11)),
          minute: int.parse(reminder.remindAt.substring(11)));
        AwesomeNotifications()
          .createNotification(
        content: NotificationContent(
          id: reminder.createdAt ~/ 1000,
          channelKey: keyRemindChannel,
          title: reminder.title ?? '无标题',
        ),
        schedule: NotificationCalendar(
          hour: time.hour,
          minute: time.minute,
          month: reminder.month,
          day: reminder.day,
          weekday: reminder.weekday,
          allowWhileIdle: true,
          preciseAlarm: true,
        ),
      )
```
* The output of `flutter doctor` command
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.8, on macOS 13.2 22D49 darwin-arm, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.74.3)
[✓] Connected device (4 available)
[✓] HTTP Host Availability

## **3 - How To Reproduce the Error**

1. Use Android physical or virtual device
2. Set the icon file and initialize
3. Create a notification

## **4 - Expected behavior**
<img width="543" alt="image" src="https://user-images.githubusercontent.com/38620932/215688534-9394a597-2bb1-4cd9-b1f1-c3f063473174.png">

## **5 - Screenshots**
![image](https://user-images.githubusercontent.com/38620932/215688055-fd02f279-2f5b-45ee-80b2-bcf9f54c6839.png)

## **6 - Additional context**
my icon file
![image](https://user-images.githubusercontent.com/38620932/215689161-160dde81-ca73-4bf7-9704-0b2651d3e953.png)

my folder screenshot
![image](https://user-images.githubusercontent.com/38620932/215688404-b3f78f80-40d1-4e07-9d1f-49672cd7fff1.png)

![image](https://user-images.githubusercontent.com/38620932/215688259-88dd8d0e-ed71-4b4a-89f0-2b26a0d9fc82.png)

**Comment by rafaelsetragni** [comment]
You must create your icon using transparency and it needs to be monochrome. You are using the same app icon in your notifications and this icon must be different. If the Android distribution accepts a different type of icon, like the colored icon you are trying to get in your example, Android itself will bring your app's icon and replace it, like xiaomi devices do. You don't have to do anything about it, it's beyond your control.

**Comment by Mae623** [comment]
At yesterday afternoon, I think what you reply is the only way I can solve this question.
However, at yesterday night, the notification icon displayed on phone turned into colorful pattern as I expected. I can't know the reason, because I think I do nothing to it.
Anyway, the question has solved.
Thank you very much!
