### ISSUE TITLE
myNotificationDisplayedMethod handler ONLY called once

### ISSUE THREAD

**Issue by ahodroj74** [rafaelsetragni/awesome_notifications#724]
## **1 - Describe the bug**

I created a scheduled notification and tested on a real iOS device.

myNotificationDisplayedMethod handler is executed ONLY once the first time and then never again.

## **2 - Provide us as much information as possible**

setListeners is initialized earlier in the app in main.dart
Every time the scheduled notification is displayed: 
the console shows:

D/Swift: [AWESOME NOTIFICATIONS] Awesome Notifications - UTC timezone : GMT (fixed) (DefaultsManager:62)
D/Swift: [AWESOME NOTIFICATIONS] Awesome Notifications - Local timezone :  (autoupdatingCurrent) (DefaultsManager:63)
D/Swift: [AWESOME NOTIFICATIONS] Awesome Notifications - last displayed date : 2023-02-06 03:45:15 GMT (DefaultsManager:69)

Nothing from myNotificationDisplayedMethod event handler except for first time it is displayed.
The only event handler that is called everytime is: myActionReceivedMethod when a notification is tapped

## **3 - How To Reproduce the Error**

static Future<bool> createScheduledNotification({
    required String title,
    required String body,
    required int intervalSeconds,
    Map<String, String>? payload,
  }) {
    return AwesomeNotifications().createNotification(
      content: NotificationContent(
        id: Utils.createUniqueId(),
        channelKey: _channel_key,
        title: title,
        body: body,
        payload: payload,
      ),
      actionButtons: [
        NotificationActionButton(key: 'ACCEPT', label: 'Accept'),
        NotificationActionButton(
            key: 'BACKGROUND',
            label: 'Background',
            actionType: ActionType.SilentBackgroundAction),
        NotificationActionButton(
            key: 'DENY', label: 'Deny', isDangerousOption: true)
      ],
      schedule: NotificationInterval(
        repeats: true,
        allowWhileIdle: true,
        interval: intervalSeconds,
      ),
    );
  }

And to test it:
    createScheduledNotification(
      title: 'test title scheduled',
      body: 'test body scheduled',
      intervalSeconds: 61,
      payload: {'test': 'testvalue'},
    );

in my notification controller
  @pragma("vm:entry-point")
  static Future<void> myNotificationDisplayedMethod(
      ReceivedNotification receivedNotification) async {
    print(receivedNotification);
  }

As mentioned, this event handler is ONLY called once the first time. 

## **4 - Expected behavior**
Event handler called every time a notification is displayed

## **6 - Additional context**
Any thoughts on this issue?
Also, the docs say when title or body is skipped, a notification will be created but not displayed.
How can I schedule a silent notification and capture it in the event handler to run something in the background? 
Is this even possible?

Thanks

**Comment by rafaelsetragni** [comment]
On iOS almost all apps are freezes while in background and is not possible to execute any exact schedule code on terminated. This way is impossible to register where each notification is displayed. So, when the app goes on foreground on Awesome, i generate all previous events at run time, imitating the android's behavior. But today only the last event is created for each notification. Now I'm changing this behavior to replicate all events in this meantime and this will be available at version 0.7.5.
