### ISSUE TITLE
iOS customSound not playing 

### ISSUE THREAD

**Issue by offline-first** [rafaelsetragni/awesome_notifications#732]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**

Custom sound is not playing.
 

## **2 - Provide us as much information as possible**

customSound = 'notification_1.aiff'
The customSound is defined inside NotificationContent, but the sound is not playing. 
The sound ist imported with XCode and "copy items if needed" is checked.

* Version: awesome_notifications: ^0.7.4+1 
* Platform iOS
* Android not tested 

```Dart
static void testNotification({required String title}) {
    AwesomeNotifications().createNotification(
        content: NotificationContent(
            id: 999999999,
            channelKey: testChannelKey,
            title: title,
            customSound: 'notification_1.aiff',
            autoDismissible: false,
            payload: {'test': "true"}
        ),
        schedule: NotificationCalendar.fromDate(date: DateTime.now().add(const Duration(seconds: 1))),
    );
  }
```

```Dart
@pragma("vm:entry-point")
  static Future <void> onNotificationCreatedMethod(ReceivedNotification receivedNotification) async {
    debugPrint('notify::onNotificationCreatedMethod:${receivedNotification.toMap()}');
  }
```

```log
flutter: notify::onNotificationCreatedMethod:{id: 999999999, channelKey: test_notification, groupKey: null, title: Test Sound 🔈, body: null, summary: null, showWhen: true, icon: null, payload: {test: true}, largeIcon: null, bigPicture: null, customSound: null, autoDismissible: false, privacy: Private, category: null, actionType: Default, color: 4278190080, backgroundColor: null, wakeUpScreen: false, fullScreenIntent: false, criticalAlert: false, roundedLargeIcon: false, roundedBigPicture: false, createdSource: Schedule, createdLifeCycle: Foreground, displayedLifeCycle: Foreground, createdDate: 2023-02-27 10:15:25, displayedDate: 2023-02-27 10....
```

## **3 - How To Reproduce the Error**

1. Drag and drop 'notification_1.aiff' file to XCode Runner folder and make sure "copy items if needed" is checked
2. ```testNotification(title: "Test")```

## **4 - Expected behavior**
* Sound should play when notification appear 
* onNotificationCreatedMethod, receivedNotification.customSound should be applied and not be null

**Comment by rafaelsetragni** [comment]
And if you use this audio file in the channel configuration, the same happens?

**Comment by offline-first** [comment]
Ok I have figured it out, the customSound path must be defined like that: ```customSound:  "resource://raw/notification_1"```
Maybe it should be clarified because this string looks like an native android implementation.

**Comment by 1encore** [comment]
same here!

**Comment by Rahil-Griphhy** [comment]
anyone have any idea???
still facing issue in **awesome_notifications: ^0.8.2**
