### ISSUE TITLE
requestPermissionToSendNotifications() completes immediately

### ISSUE THREAD

**Issue by MatyasK** [rafaelsetragni/awesome_notifications#733]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**

 AwesomeNotifications().requestPermissionToSendNotifications(); finnished immiditally, which makes no sense and the result also useless. My use case is that I have to wait for the permission request to be done and continue with 

## **2 - Provide us as much information as possible**

To help us to understand your issue, provide with your bug report all the relevant informations, such as:

* Your plugins list inside the file `pubspec.yaml` (at least all notification plugins)
* What platform did you found the issue
* What devices did you found the issue
* How are you initializing the plugin
* How are you creating the notification
* The output of `flutter doctor` command

OBS: To post a source code in your issue, please use the markdown below:

```Dart
print('Your source code goes here');
```

## **3 - How To Reproduce the Error**

...or if you prefer, you can provide us a simple example app on GitHub with the issue already reproduced instead of the steps 2 and 3.

**Comment by rafaelsetragni** [comment]
Well, as no other information was provided, the only thing that i can imagine is that you're may forgot to use the keyword await in front of any method with Future returned.

**Comment by MatyasK** [comment]
I did added await, and it still completes without waiting for the user interaction.

**Comment by rafaelsetragni** [comment]
@MatyasK i need you to fill the other informations requested in the form. I can't help you without these informations.
