### ISSUE TITLE
removeChannel

### ISSUE THREAD

**Issue by hardik-weenggs** [rafaelsetragni/awesome_notifications#74]
- removeChannel() not working in iOS.

>  iPhone 5s (v12.2)

>  iPhone 6 (v12.4.9)

**Code:**
`await AwesomeNotifications().removeChannel(channelKey);`

**Error:**

`[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: PlatformException(methodNotFound, method not found, removeNotificationChannel, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
<asynchronous suspension>
#2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
#3      AwesomeNotifications.removeChannel (package:awesome_notifications/src/awesome_notifications_core.dart:291:44)`

**Comment by rafaelsetragni** [comment]
This is definitely a missing function for iOS. I gonna fix it in the next release.

**Comment by rafaelsetragni** [comment]
New version released. Check to see if the problem is resolved.
