### ISSUE TITLE
 onActionNotificationMethod is not a valid global or static method.

### ISSUE THREAD

**Issue by phuoctan4141** [rafaelsetragni/awesome_notifications#740]
I wrote code from the example but it's sometime show error.

![image](https://user-images.githubusercontent.com/16333797/224731426-1f4ab76b-a8d4-45d1-ac68-3e25e7727330.png)

**Comment by MohammadSharafi** [comment]
@phuoctan4141  i have the same issue how can I solve it?

**Comment by phuoctan4141** [comment]
> @phuoctan4141 i have the same issue how can I solve it?

https://github.com/phuoctan4141/ToDoon/blob/main/lib/src/controllers/notifications/notifications_controller.dart

this is my project that fixed it.
