### ISSUE TITLE
All notification cancelled on reinstall

### ISSUE THREAD

**Issue by apoleo88** [rafaelsetragni/awesome_notifications#742]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**

When I reinstall the application, all the notifications scheduled are been deleted.

## **2 - Provide us as much information as possible**

Tested on a real device **Android** Samsung S10, in Debug mode. 
When I hit Debug the application is being rebuilt and reinstalled on the device.

`awesome_notifications: ^0.7.4+1`

This problem was not present on 0.6.x

```Dart
Flutter 3.7.6 • channel stable • https://github.com/flutter/flutter.git  
Framework • revision 12cb4eb7a0 (2 weeks ago) • 2023-03-01 10:29:26 -0800
Engine • revision ada363ee93                                             
Tools • Dart 2.19.3 • DevTools 2.20.1   
```

## **3 - How To Reproduce the Error**

1. Create a Notification
2. Rebuild and reinstall the app

## **4 - Expected behavior**
Notification persists on reinstall.

## **6 - Additional context**

Does this also mean that when the user updates the App the Notifications will be canceled?

**Comment by rafaelsetragni** [comment]
Yes, but all apps in all platforms erase all data when reinstalled. This is the expected behavior.

**Comment by apoleo88** [comment]
Well, all other data are maintained when updating an app, I was quite sure the same happened with notifications.

**Comment by rafaelsetragni** [comment]
Reinstall an app is different than just update the same app. Try to explain with as much details as possible how are you finding this issue.

**Comment by apoleo88** [comment]
Ok, I am running on a real device with IntelliJ, in Debug.

App is Installed and some notifications are created.

**Comment by apoleo88** [comment]
I am running in debug mode with IntelliJ on a real Device.

I create some notifications.

I hit hot restart the notifications stay. 

I hit stop.
I hit again Debug.


The application is then rebuilt and installed again.
```
Running Gradle task 'assembleMyAppDebug'...
√  Built build\app\outputs\flutter-apk\app-myapp-debug.apk.
Installing build\app\outputs\flutter-apk\app-myapp-debug.apk...
```

At this point, the notifications disappeared.

I would have expected that the notifications like all the other data are kept.

**Comment by rafaelsetragni** [comment]
In IntelliJ, the setting to restart activities automatically when launching a debug session is called "Always Restart Activities" and it is enabled by default. To disable this setting, you can follow these steps:

Open your project in IntelliJ and navigate to the "Run" menu.
Select "Edit Configurations".
In the left panel, select the configuration that you are using to run your app in debug mode.
In the "General" tab, locate the "Miscellaneous" section.
Uncheck the "Always Restart Activities" checkbox.
After disabling this setting, your app should no longer automatically restart all activities in their previous states when launching a new debug session. This means that notifications and other data should persist across app restarts, as long as your app is properly saving and retrieving this data from a persistent storage mechanism.

**Comment by apoleo88** [comment]
Mmmh I am not sure what are you referring to. There is no General Tab or Miscellaneous section.

There is no reference in the documentation or google about "Always Restart Activities" option.

I am encountering this problem only with the Notifications, all the other data persists.

**Comment by apoleo88** [comment]
Did you really replied with a nonsense ChatGPT-generated answer that only made me lose time and will make it lose it to all people that will find this topic?

**Comment by rafaelsetragni** [comment]
First things first, I think you need to learn the fundamentals about mobile apps, but I'm glad you found the answer you were looking for.
