### ISSUE TITLE
onNotificationDisplayedMethod - is not called on iOS

### ISSUE THREAD

**Issue by haily2706** [rafaelsetragni/awesome_notifications#743]
onNotificationCreated will be called but onNotificationDisplayedMethod does not work. Neither in background nor in foreground.

Note: Debug set to true or false does not change behavior. Works PERFECTLY on android.

2 - Provide us as much information as possible

Using IOS physical device to receive notifications

Plugin initialization:

AwesomeNotifications().initialize(
      null,
      [
        NotificationChannel(
            channelGroupKey: 'basic_channel_group',
            importance: NotificationImportance.Max,
            channelKey: 'basic_channel',
            channelName: 'Basic notifications',
            channelDescription: 'Main channel.',
            defaultColor: Color(0xFF53E7DF),
            ledColor: Color(0xFF53E7DF))
      ],
      channelGroups: [
        NotificationChannelGroup(channelGroupKey: 'basic_channel_group', channelGroupName: 'Basic group')
      ],
      debug: false);
e

  AwesomeNotifications().setListeners(
      onActionReceivedMethod: FcmManager.onActionReceivedMethod,
      onNotificationCreatedMethod: FcmManager.onNotificationCreatedMethod,
      onNotificationDisplayedMethod: FcmManager.onNotificationDisplayedMethod,
      onDismissActionReceivedMethod: FcmManager.onDismissActionReceivedMethod);

3 - How To Reproduce the Error

Use IOS physical device:

Schedule a local notification,

onNotificationCreatedMethod will be called but onNotificationDisplayedMethod does not work. Neither in background nor in foreground

4 - Expected behavior

callbacks are called

5 - Screenshots

6 - Additional context

Here are my callback methods:

/// Use this method to detect every time that a new notification is displayed
  @pragma("vm:entry-point")
  static Future<void> onNotificationDisplayedMethod(ReceivedNotification receivedNotification) async {
    print("onNotificationDisplayedMethod");
 
  }

  /// Use this method to detect when a new notification or a schedule is created
  @pragma("vm:entry-point")
  static Future<void> onNotificationCreatedMethod(ReceivedNotification receivedNotification) async {
    print('onNotificationCreatedMethod');
  }

  /// Use this method to detect if the user dismissed a notification
  @pragma("vm:entry-point")
  static Future<void> onDismissActionReceivedMethod(ReceivedAction receivedAction) async {
    print('onDismissActionReceivedMethod');
 
  }

  /// Use this method to detect when the user taps on a notification or action button
  @pragma("vm:entry-point")
  static Future<void> onActionReceivedMethod(ReceivedAction receivedAction) async {
    print('onActionReceivedMethod');
  }

In AppDelegate.swift

import UIKit
import Flutter
import awesome_notifications
import shared_preferences_foundation

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
    override func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {
        GeneratedPluginRegistrant.register(with: self)
        
        SwiftAwesomeNotificationsPlugin.setPluginRegistrantCallback { registry in
          SwiftAwesomeNotificationsPlugin.register(
            with: registry.registrar(forPlugin: "io.flutter.plugins.awesomenotifications.AwesomeNotificationsPlugin")!)
          SharedPreferencesPlugin.register(
            with: registry.registrar(forPlugin: "io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin")!)
        }
        
        return super.application(application, didFinishLaunchingWithOptions: launchOptions)
    }
}

**Comment by haily2706** [comment]
@rafaelsetragni - I check the iOS package, and I see you implement it. But I could not figure out why the onDismissActionReceivedMethod is not called on iOS. Am I missing somethings, please guide me through - thank you!

**Comment by rafaelsetragni** [comment]
On iOS almost all apps are freezes while in background and is not possible to execute any exact schedule code on terminated. This way is impossible to register where each notification is displayed. So, when the app goes on foreground on Awesome, i  generate all previous events at run time, imitating the android's behavior. But today only the last event is created for each notification. Now I'm changing this behavior to replicate all events in this meantime and this will be available at version 0.7.5.

**Comment by haily2706** [comment]
@rafaelsetragni - thank you so much for your response! Could you let me know when 0.7.5 is available? I am planning to use onNotificationDisplayedMethod to record all displayed notifications in the app.

**Comment by haily2706** [comment]
@rafaelsetragni I am using the code in this notification-interval-fix branch, onNotificationDisplayedMethod is called as expectation on foreground and background, NOT IN TERMINATED 

Expected behavior:

All events that happen during TERMINATED state should be saved and notified when the app goes foreground.

**Comment by rafaelsetragni** [comment]
Its impossible to do anything on terminated state on iOS, including register events. Im recreating the events at runtimeafter the app goes to foreground and this branch is in development stage.

**Comment by haily2706** [comment]
@rafaelsetragni 

"recreating the events" means, all notification events are in the terminated state. will be recreated and fired after the app goes to the foreground, it is right ?. It is important to us because we rely on it to record all visible notifications.

Thank you for your quick response!

**Comment by Dancas93** [comment]
Same issue, there is any release date for version 0.7.5?

**Comment by alim971** [comment]
Same problem, my application relies on the notificationDisplayed to do some stuff, and I just now found out this callback is never called on iOS, which is a major problem, and is not documented anywhere

**Comment by alim971** [comment]
Also, the dismiss action notification does not fire the onDismissed callback either

**Comment by rafaelsetragni** [comment]
Hi @alim971, @Dancas93 and @haily2706, i just uploaded the new release versions of 0.7.5-dev.2+1 versions of [awesome_notifications](https://pub.dev/packages/awesome_notifications/versions/0.7.5-dev.2+1) and [awesome_notifications_fcm](https://pub.dev/packages/awesome_notifications_fcm/versions/0.7.5-dev.2+1) to fix this issue. Please, check it out to see if this issue is solved on these new versions.

Also, don't forget to join in your [Discord Beta team](https://discord.com/channels/888523488376279050/933445281243082772) to request fixes and new updates.

**Comment by edwardmp** [comment]
@rafaelsetragni seeing same issue. Even upgrading to `0.7.5-dev.2+1` doesn't seem to make any change.

**Comment by rafaelsetragni** [comment]
Now the last version is 0.7.5-dev.3

**Comment by edwardmp** [comment]
@rafaelsetragni unfortunately couldn't try it, because the FCM package apparently isn't compatible yet with `0.7.5-dev.3` (even when also using `0.7.5-dev.3`) for that one)

Is there any documentation around needing that notification service extension? I also noticed that other handlers stopped working, like `onActionReceivedMethod`, is that also due to needing a notification service extension?

**Comment by rafaelsetragni** [comment]
You should not use firebase_messaging with awesome_notifications_fcm and the documentation is on readme files.

**Comment by edwardmp** [comment]
Not talking about firebase_messaging, I don't use it. talking about `awesome_notifications_fcm` not being compatible with `awesome_notifications`.

I see the documentation in the README, but nowhere does it mention under what conditions it is necessary to implement.
So with v0.7.4 `onActionReceivedMethod` works fine but `onNotificationDisplayedMethod` is never called.

On `0.7.5-dev.3` neither is called.

Can you confirm that both should work, and that the service extension is needed for this? I don't care about custom notifications or buttons, so normally a service extension shouldn't be necessarily.

Thanks!

**Comment by Mamasodikov** [comment]
Same issue here. Any workarounds are highly appreciated!

**Comment by sunguard** [comment]
In my case, the listener worked well after I create an immediate notification without schedule on `0.7.4+1`

```
static Future<void> initializeListeners() async {
    if (await Permission.notification.isGranted) {
      await _instance.createNotification(
        content: NotificationContent(
          id: -1,
          channelKey: 'channel_key',
          displayOnForeground: false,
          displayOnBackground: false,
        ),
      );
    }
  }
```
