### ISSUE TITLE
animated-bell is not in the assets of the example app

### ISSUE THREAD

**Issue by TheCarpetMerchant** [rafaelsetragni/awesome_notifications#752]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**

`animated-bell.gif` is not in the assets folder of the example app.

## **2 - Provide us as much information as possible**

```dart
======== Exception caught by image resource service ================================================
The following assertion was thrown resolving an image codec:
Unable to load asset: "assets/animated-bell.gif".

Exception: Asset not found
When the exception was thrown, this was the stack: 
#0      PlatformAssetBundle.loadBuffer (package:flutter/src/services/asset_bundle.dart:295:7)
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:731:35)
#2      AssetBundleImageProvider.loadBuffer (package:flutter/src/painting/image_provider.dart:695:14)
#3      ImageProvider.resolveStreamForKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:513:13)
#4      ImageCache.putIfAbsent (package:flutter/src/painting/image_cache.dart:384:22)
#5      ImageProvider.resolveStreamForKey (package:flutter/src/painting/image_provider.dart:511:81)
#6      ScrollAwareImageProvider.resolveStreamForKey (package:flutter/src/widgets/scroll_aware_image_provider.dart:106:19)
#7      ImageProvider.resolve.<anonymous closure> (package:flutter/src/painting/image_provider.dart:358:9)
#8      ImageProvider._createErrorHandlerAndKey.<anonymous closure> (package:flutter/src/painting/image_provider.dart:473:24)
<asynchronous suspension>
Image provider: AssetImage(bundle: null, name: "assets/animated-bell.gif")
Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#3eb36(), name: "assets/animated-bell.gif", scale: 1.0)
====================================================================================================
D/EGL_emulation( 4287): app_time_stats: avg=4120.02ms min=326.29ms max=7913.76ms count=2
Lost connection to device.
```

## **3 - How To Reproduce the Error**

Click the leftmost button on the example app.

## **4 - Expected behavior**
Don't know, I'm trying to make a media notification

## **5 - Screenshots**
None

## **6 - Additional context**
None

**Comment by TheCarpetMerchant** [comment]
Yes, but it should be at the assets root. At least that's where the code expects it to be, so the code and the folder structure will have to come to an agreement 😅

**Comment by rafaelsetragni** [comment]
Hi @TheCarpetMerchant , i just uploaded the new release versions of 0.7.5-dev.2+1 versions of [awesome_notifications](https://pub.dev/packages/awesome_notifications/versions/0.7.5-dev.2+1) and [awesome_notifications_fcm](https://pub.dev/packages/awesome_notifications_fcm/versions/0.7.5-dev.2+1) to fix this example issue. Please, check it out to see if this issue is solved on these new versions.

Also, don't forget to join in your [Discord Beta team](https://discord.com/channels/888523488376279050/933445281243082772) to request fixes and new updates.
