### ISSUE TITLE
IOS app not working  - IosAwnCore/StatusBarManager 

### ISSUE THREAD

**Issue by dichuk-mykhailo** [rafaelsetragni/awesome_notifications#756]
awesome_notifications: ^0.7.4+1

Unexpectedly found nil while unwrapping an Optional value
2023-04-12 16:22:37.184876+0300 Runner[10276:580968] IosAwnCore/StatusBarManager.swift:116: Fatal error: Unexpectedly found nil while unwrapping an Optional value

* thread #1, queue = 'com.apple.main-thread', stop reason = Fatal error: Unexpectedly found nil while unwrapping an Optional value
    frame #0: 0x00000001820cd23c libswiftCore.dylib`_swift_runtime_on_report
libswiftCore.dylib`:
->  0x1820cd23c <+0>: ret
libswiftCore.dylib`:
    0x1820cd240 <+0>: b      0x1820cd23c               ; _swift_runtime_on_report
libswiftCore.dylib`:
    0x1820cd244 <+0>: adrp   x8, 366052
    0x1820cd248 <+4>: ldrb   w0, [x8, #0x994]
Target 0: (Runner) stopped.
Lost connection to device.

**Comment by rafaelsetragni** [comment]
Are you combining awesome notifications with third party notification packages?
