### ISSUE TITLE
Invalid Notification Content

### ISSUE THREAD

**Issue by Lawrene16** [rafaelsetragni/awesome_notifications#76]
Hi, this has been an awesome plugin so far. However, i have one issue. As stated in the documentation

"Issue: Invalid notification content

Fix: The notification sent via FCM services MUST respect the types of the respective Notification elements. Otherwise, your notification will be discarded as invalid one. Also, all the payload elements MUST be a String, as the same way as you do in Local Notifications using dart code.

To see more information about each type, please go to https://github.com/rafaelsetragni/awesome_notifications#notification-types-values-and-defaults"

I am sending my payload from firebase functions and the guide doesnt show much on how to send payload in the specified format using cloud functions

**Comment by rafaelsetragni** [comment]
The firebase console test page is limited. To test it with more resources try to use Postman software. I let an example ready to use on README file.

**Comment by Lawrene16** [comment]
Thanks a lot for your response. When i send a cloud message using postman or any other rest api tool it works very fine. 

However, I will prefer not using http to send cloud messages. I want to use cloud functions to achieve this and when i do, it always says "Invalid Notification Content"

Is there a way i can get this to work with using cloud functions instead of HTTP?

**Comment by Lawrene16** [comment]
Hello. I will be closing this issue since so far, using HTTP to send the notifications hasnt been a bad idea. Thanks a lot for your help

**Comment by rafaelsetragni** [comment]
???

Ok, no problem. Good luck with your project. I hope you gonna find the answer for tour need.
