### ISSUE TITLE
Override a deprecated API warning in the log

### ISSUE THREAD

**Issue by guyluz11** [rafaelsetragni/awesome_notifications#761]
Override a deprecated API warning in the log

Run 
`flutter build appbundle --release`

Observe the log and you will see

```dart
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\guy\AppData\Local\Pub\Cache\hosted\pub.dev\awesome_notifications_fcm-0.7.4+1\android\src\main\java\me\carda\awesome_notifications_fcm\FcmDartBackgroundExecutor.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\Users\guy\AppData\Local\Pub\Cache\hosted\pub.dev\awesome_notifications_fcm-0.7.4+1\android\src\main\java\me\carda\awesome_notifications_fcm\AwesomeNotificationsFcmPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

```

**Comment by rafaelsetragni** [comment]
Yes, these deprecations are still preserved due support to old devices and will be replaced as soon as the support for these devices turns deprecated.

**Comment by rafaelsetragni** [comment]
Lets close this issue, as Im already tracking these deprecations to remove them in future releases.

**Comment by guyluz11** [comment]
I hope it will be soon because this release is way too big unnecessarily.

Releases should not strive to be gigantuous and change/fix everything at once, also small issues could be fixed faster with quicker release's.

**Comment by rafaelsetragni** [comment]
I agreed with you, but the users are taking the current branch in development, using it without my knowledgement and complaining about issues mixed with current version. I was hard to track everyone and to solve it i put all their requirements in a single release. But in next ones i will release small ones instead.

**Comment by rafaelsetragni** [comment]
You're talking about the deprecations? They will be kept as they are necessary for backward compatibility with older devices.
