### ISSUE TITLE
The link to awesome_notifications_fcm in readme is incorrect

### ISSUE THREAD

**Issue by guyluz11** [rafaelsetragni/awesome_notifications#762]
In the readme the link to awesome_notifications_fcm is incorrect 

Under Features section line:

> Send Push Notifications using add-on plugins, as [awesome_notifications_fcm](https://pub.dev/packages/awesome_notifications)

![image](https://user-images.githubusercontent.com/9304740/233381341-1f44a28a-dc5d-47f9-8ee9-4f3f6c171a58.png)

**Comment by rafaelsetragni** [comment]
Hi guy, thanks for the tip! Im rewriting all documentation now and I will ensure the correct link on it. Thanks!
