### ISSUE TITLE
Plugin shows notification even when app is in foreground

### ISSUE THREAD

**Issue by Lawrene16** [rafaelsetragni/awesome_notifications#77]
How can i stop the plugin from showing notifications when app is in foreground

**Comment by rafaelsetragni** [comment]
Use the option displayOnForeground equals to false. This way, the notification is not displayed while your app is in foreground, but all the respective streams are fired.

**Comment by Lawrene16** [comment]
Thanks for the response friend. Is this on initialization?

**Comment by Lawrene16** [comment]
Thanks. I have just put this in the body of the http request... As a property of the content object and it works very well. Thank you very much for this and all the awesome work you have been doing. Its highly appreciated
