### ISSUE TITLE
Error running 0.7.5-dev.1

### ISSUE THREAD

**Issue by guyluz11** [rafaelsetragni/awesome_notifications#770]
# Rules

## **1 - Describe the bug**

Error running the package version `awesome_notifications: 0.7.5-dev.1` from pub.dev with `awesome_notifications_fcm: ^0.7.4+1`

## **2 - Provide us as much information as possible**

After changing the version number I get an error about intl version so added override
```
 dependency_overrides:
  intl: ^0.18.1
```

After that pub gets exit successfully.
But when compiling/running the app for Android I am getting the following error

```
Launching lib/main.dart on sdk gphone arm64 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/userName/.pub-cache/hosted/pub.dev/awesome_notifications-0.7.5-dev.1/android/build.gradle' line: 41

* What went wrong:
A problem occurred evaluating project ':awesome_notifications'.
Project with path ':awn_core' could not be found in project ':awesome_notifications'.

* Try:
Run with --stacktrace option to get the stack trace.
Run with --info or --debug option to get more log output.
Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

BUILD FAILED in 3s
Exception: Gradle task assembleDebug failed with exit code 1
```

## **3 - How To Reproduce the Error**

1. Open a new project 
2. Added the pacakges
3. Run on android

## **6 - Additional context**
As I remember from my previous attempts with this package I got this error when trying to use the new branch outside of the example, in the example it worked for me (previously, didn't check now).

**Comment by rafaelsetragni** [comment]
As i described in our discord community, this first release is incomplete and i will release pretty soon the complete version.

**Comment by AppetiteTeam** [comment]
same

**Comment by guyluz11** [comment]
You're not supposed to use 7.0.5-dev.1 version, please change pubspec dependency to ^0.7.4+1

```
dependencies:
  awesome_notifications: ^0.7.4+1
```

If this issue happens with the version 0.7.4+1 you probably have this issue which also have a workaround around posted
https://github.com/rafaelsetragni/awesome_notifications/issues/774#issuecomment-1546026744

**Comment by rafaelsetragni** [comment]
Hi @guyluz11, @AppetiteTeam and @akhilgorantala, i just uploaded the new release versions of 0.7.5-dev.2+1 versions of [awesome_notifications](https://pub.dev/packages/awesome_notifications/versions/0.7.5-dev.2+1) and [awesome_notifications_fcm](https://pub.dev/packages/awesome_notifications_fcm/versions/0.7.5-dev.2+1) to fix this issue. Please, check it out to see if this issue is solved on these new versions.

Also, don't forget to join in your [Discord Beta team](https://discord.com/channels/888523488376279050/933445281243082772) to request fixes and new updates.
