### ISSUE TITLE
How to avoid this error

### ISSUE THREAD

**Issue by rr8733380** [rafaelsetragni/awesome_notifications#771]
Hi.

In my android app, notifications come via FCM and are shown to the user using awesome_notifications.
But on iOS, notifications are shown using pure apns, without using FCM. That is, notifications are displayed by themselves, without any processing.

I want to listen to the notification opening on ios, but it gives such an error from your package (Everything works fine on android):
```
[AWESOME NOTIFICATIONS] The action content doesn't contain any awesome information (AwesomeExceptionReceiver:54)
```
Is there any way to avoid this mistake?

**Comment by rafaelsetragni** [comment]
Are you using another notification plugin with awesome ones?

**Comment by rafaelsetragni** [comment]
This error happens when you receive a notification that wasnt created by awesome library. Because of this, some required meta informations are not present in notification content and the respective ReceivedAction object cannot be create.
