### ISSUE TITLE
 problem Channel 'basic_chanel' does not exist

### ISSUE THREAD

**Issue by dongosiddik** [rafaelsetragni/awesome_notifications#772]
Good evening, I am unable to display the notification. It is generating an error.

flutter ( 5605): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(**INVALID_ARGUMENTS, Channel 'basic_chanel' does not exist, arguments.invalid.channel.notFound.basic_chanel, null)**
E/flutter ( 5605): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653)
E/flutter ( 5605): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315)
E/flutter ( 5605): <asynchronous suspension>
E/flutter ( 5605): #2      MethodChannelAwesomeNotifications.createNotification (package:awesome_notifications/awesome_notifications_method_channel.dart:101)

this my code

  Future triggerNotification() async {
    AwesomeNotifications().createNotification(
        content: NotificationContent(
            id: Random().nextInt(10),
            channelKey: 'basic_chanel',
            title: "numéro",
            body:    "  exemple",
           
           ));
  }

  Future initializeNotification() async {
    AwesomeNotifications().initialize(
      //'resource://drawable/notification_icon',
      null,
      [
        // notification icon
        NotificationChannel(
          channelKey: 'basic_chanel',
          channelName: 'eUrgence notification',
          channelDescription: 'eUrgence notification',
          channelShowBadge: true,
          importance: NotificationImportance.High,
          enableVibration: true,
        ),
      ],
     // debug: true,
    );
  }

  Future hasPermissionNotification() async {
    AwesomeNotifications().isNotificationAllowed().then((isAllowed) {
      if (!isAllowed) {
        AwesomeNotifications().requestPermissionToSendNotifications();
      }
    });
  }
}

**Comment by rafaelsetragni** [comment]
You need to initialize awesome notifications, creating the channels and also set the respective channel in notification creation, otherwise you gonna face this error message. Follow the topic "Getting Started" from awesome_notifications documentation and you gonna solve this issue. And don't forget to reinstall your app, because the channel configurations can only be set once for Android devices greater or equal than version 8.

**Comment by rafaelsetragni** [comment]
But there is already an simple example on pub.dev page that you only need to copy and paste the content into a new project to test the plugin.
