### ISSUE TITLE
no such module '__objc'

### ISSUE THREAD

**Issue by muhdluqman** [rafaelsetragni/awesome_notifications#773]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Cannot make notification using awsome_notification in ios.but it work well in android.It keep going said no such module '__objc'*

OBS: avoid to use the expression **"its not working"** or **"is working"** or any other variation. These expressions can mean anything and at same time doesn´t bring any useful information. As soon you rewrite these expressions, you naturally going to be more precise and clear.

## **2 - Provide us as much information as possible**

To help us to understand your issue, provide with your bug report all the relevant informations, such as:

* Your plugins list inside the file `pubspec.yaml` (at least all notification plugins)
* What platform did you found the issue
* What devices did you found the issue
* How are you initializing the plugin
* How are you creating the notification
* The output of `flutter doctor` command

OBS: To post a source code in your issue, please use the markdown below:

```Dart
print('Your source code goes here');
```

## **3 - How To Reproduce the Error**

...or if you prefer, you can provide us a simple example app on GitHub with the issue already reproduced instead of the steps 2 and 3.

**Comment by rafaelsetragni** [comment]
Your project is missing the steps 3 and greater of awesome_notifications_fcm's Getting Started topic. Without accomplish these steps, flutter and awesome libraries will not be copied into your NSE and you gonna face this library error.

**Comment by dai10512** [comment]
I faced in this issue.
Is this newer error??


```
Launching lib/main.dart on iPhone 14 Pro in debug mode...
main.dart:1
Xcode build done.                                           16.8s
Failed to build iOS app
Swift Compiler Error (Xcode): Using bridging headers with module interfaces is unsupported

Uncategorized (Xcode): Command SwiftDriver emitted errors but did not return a nonzero exit code to indicate failure

Error (Xcode): no such module '__ObjC'
/Users/myname/Library/Developer/Xcode/DerivedData/Runner-gmqnzbwoaejlazfihcxflirzqhwa/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/arm64/Runner.private.swiftinterface:9:18

Error (Xcode): failed to verify module interface of 'Runner' due to the errors above; the textual interface may be broken by project issues or a compiler bug
/Users/myname/Library/Developer/Xcode/DerivedData/Runner-gmqnzbwoaejlazfihcxflirzqhwa/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/arm64/Runner.private.swiftinterface:0:0

Error (Xcode): no such module '__ObjC'
/Users/myname/Library/Developer/Xcode/DerivedData/Runner-gmqnzbwoaejlazfihcxflirzqhwa/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/arm64/Runner.swiftinterface:9:18

Error (Xcode): failed to verify module interface of 'Runner' due to the errors above; the textual interface may be broken by project issues or a compiler bug
/Users/myname/Library/Developer/Xcode/DerivedData/Runner-gmqnzbwoaejlazfihcxflirzqhwa/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/arm64/Runner.swiftinterface:0:0

Could not build the application for the simulator.
Error launching application on iPhone 14 Pro.
```
device :iPhone14 simulator
pubspec.yaml
```
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons:
  pedantic_mono:
  flutter_riverpod:
  date_time_picker:
  flutter_datetime_picker:
  # flutter_localizations:
  #   sdk: flutter
  uuid:
  drift:
  http:
  device_info:
  image:
  hive:
  hive_flutter:
  # modal_bottom_sheet: ^3.0.0-pre
  awesome_notifications: ^0.7.4+1
  flutter_native_timezone: ^2.0.0
  timezone:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.1.11
  flutter_launcher_icons: "^0.9.2"
```

**Comment by rafaelsetragni** [comment]
No, this is not a new error. If your project did not copied the awesome and flutter libraries into your Notification Service Extension, you gonna face this issue.

But as Im seeing in your pubspec file, you're not using awesome_notifications_fcm to need to create target extensions. Have you created it for your own for another proposes?

**Comment by dai10512** [comment]
In my case,  I don't use FCM. So it looks kind of weired.

my necessory function is below 
- scheduled and repeate local notification.
- 
I choosed awesome notification because of schedule function. This package can set every weekOfMonth

**Comment by dai10512** [comment]
thank you mesage.

In my case, I don't use FCM. So it looks kind of weired.

my necessory function is below.
- schedule and repeate local notification.
- set every week of month schedule( like every 2nd Monday)

Local notification package is also almost looks fine. But it is difficult to set every week of month notification. 
Otherwhile awesome notification package is usefull in that point. So I choose it withoud FCM.

**Comment by dai10512** [comment]
Version 0.6. is fine. 
But 0.7 happen above error 👀 💦 
Any hint??

**Comment by dai10512** [comment]
Ok, I will try it.
Thank you!

**Comment by molorane** [comment]
Hello, I added awesome_notifications: ^0.7.4+1 to my pubspec.yaml file. Just adding it, I got the following error afterwards.

Failed to build iOS app
Swift Compiler Error (Xcode): Using bridging headers with module interfaces is unsupported


Uncategorized (Xcode): Command SwiftDriver emitted errors but did not return a nonzero exit code to indicate failure


Error (Xcode): no such module '__ObjC'
/Users/mothusi/Library/Developer/Xcode/DerivedData/Runner-egapamdvlbevvfapfletqhylotzk/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/x86_64/R
unner.swiftinterface:11:18

I get the same error if I add flutter_local_notifications: ^13.0.0. 
Please how do I resolve this error?

**Comment by molorane** [comment]
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.4, on macOS 13.4 22F66 darwin-arm64, locale en-ZA)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2023.1.1)
[✓] VS Code (version 1.79.0)
[✓] Connected device (3 available)
[✓] Network resources

• No issues found!

**Comment by OpenSphereSoftware** [comment]
should not be closed ! facing the same issue   just added awesome_notification without fcm   
no module type Obj_C

**Comment by dev-frid** [comment]
This still happens.

**Comment by pupubird** [comment]
Same issue! 
Could it be because flutter version? as when I search for build libraries distribution in build settings it did not show up
<img width="1013" alt="Screenshot 2023-10-12 at 5 30 21 PM" src="https://github.com/rafaelsetragni/awesome_notifications/assets/35325976/0d00605d-0f9d-4c0c-89c3-af5e4704a0a3">

**Comment by jonasermert** [comment]
> I faced in this issue. Iam confused cuz I am editing this Application and code first time in 1 year ago Is this newer error??
> 
> ```
> Launching lib/main.dart on iPhone 14 Pro in debug mode...
> main.dart:1
> Xcode build done.                                           16.8s
> Failed to build iOS app
> Swift Compiler Error (Xcode): Using bridging headers with module interfaces is unsupported
> 
> Uncategorized (Xcode): Command SwiftDriver emitted errors but did not return a nonzero exit code to indicate failure
> 
> Error (Xcode): no such module '__ObjC'
> /Users/myname/Library/Developer/Xcode/DerivedData/Runner-gmqnzbwoaejlazfihcxflirzqhwa/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/arm64/Runner.private.swiftinterface:9:18
> 
> Error (Xcode): failed to verify module interface of 'Runner' due to the errors above; the textual interface may be broken by project issues or a compiler bug
> /Users/myname/Library/Developer/Xcode/DerivedData/Runner-gmqnzbwoaejlazfihcxflirzqhwa/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/arm64/Runner.private.swiftinterface:0:0
> 
> Error (Xcode): no such module '__ObjC'
> /Users/myname/Library/Developer/Xcode/DerivedData/Runner-gmqnzbwoaejlazfihcxflirzqhwa/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/arm64/Runner.swiftinterface:9:18
> 
> Error (Xcode): failed to verify module interface of 'Runner' due to the errors above; the textual interface may be broken by project issues or a compiler bug
> /Users/myname/Library/Developer/Xcode/DerivedData/Runner-gmqnzbwoaejlazfihcxflirzqhwa/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/arm64/Runner.swiftinterface:0:0
> 
> Could not build the application for the simulator.
> Error launching application on iPhone 14 Pro.
> ```
> 
> ```
> 
>   # The following adds the Cupertino Icons font to your application.
>   # Use with the CupertinoIcons class for iOS style icons.
>   cupertino_icons:
>   pedantic_mono:
>   flutter_riverpod:
>   date_time_picker:
>   flutter_datetime_picker:
>   # flutter_localizations:
>   #   sdk: flutter
>   uuid:
>   drift:
>   http:
>   device_info:
>   image:
>   hive:
>   hive_flutter:
>   # modal_bottom_sheet: ^3.0.0-pre
>   awesome_notifications: ^0.7.4+1
>   flutter_native_timezone: ^2.0.0
>   timezone:
> 
> dev_dependencies:
>   flutter_test:
>     sdk: flutter
> 
>   # The "flutter_lints" package below contains a set of recommended lints to
>   # encourage good coding practices. The lint set provided by the package is
>   # activated in the `analysis_options.yaml` file located at the root of your
>   # package. See that file for information about deactivating specific lint
>   # rules and activating additional ones.
>   flutter_lints: ^2.0.0
>   hive_generator: ^1.1.3
>   build_runner: ^2.1.11
>   flutter_launcher_icons: "^0.9.2"
> ```

It looks like the error is related to the use of bridging headers with module interfaces in Swift, and it might be causing issues during the build process. The error message indicates a problem with the module interface of 'Runner' and mentions a missing module '__ObjC'.

**Comment by zionnite** [comment]
> > I faced in this issue. Iam confused cuz I am editing this Application and code first time in 1 year ago Is this newer error??
> > ```
> > Launching lib/main.dart on iPhone 14 Pro in debug mode...
> > main.dart:1
> > Xcode build done.                                           16.8s
> > Failed to build iOS app
> > Swift Compiler Error (Xcode): Using bridging headers with module interfaces is unsupported
> > 
> > Uncategorized (Xcode): Command SwiftDriver emitted errors but did not return a nonzero exit code to indicate failure
> > 
> > Error (Xcode): no such module '__ObjC'
> > /Users/myname/Library/Developer/Xcode/DerivedData/Runner-gmqnzbwoaejlazfihcxflirzqhwa/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/arm64/Runner.private.swiftinterface:9:18
> > 
> > Error (Xcode): failed to verify module interface of 'Runner' due to the errors above; the textual interface may be broken by project issues or a compiler bug
> > /Users/myname/Library/Developer/Xcode/DerivedData/Runner-gmqnzbwoaejlazfihcxflirzqhwa/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/arm64/Runner.private.swiftinterface:0:0
> > 
> > Error (Xcode): no such module '__ObjC'
> > /Users/myname/Library/Developer/Xcode/DerivedData/Runner-gmqnzbwoaejlazfihcxflirzqhwa/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/arm64/Runner.swiftinterface:9:18
> > 
> > Error (Xcode): failed to verify module interface of 'Runner' due to the errors above; the textual interface may be broken by project issues or a compiler bug
> > /Users/myname/Library/Developer/Xcode/DerivedData/Runner-gmqnzbwoaejlazfihcxflirzqhwa/Build/Intermediates.noindex/Runner.build/Debug-iphonesimulator/Runner.build/Objects-normal/arm64/Runner.swiftinterface:0:0
> > 
> > Could not build the application for the simulator.
> > Error launching application on iPhone 14 Pro.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > 
> >   # The following adds the Cupertino Icons font to your application.
> >   # Use with the CupertinoIcons class for iOS style icons.
> >   cupertino_icons:
> >   pedantic_mono:
> >   flutter_riverpod:
> >   date_time_picker:
> >   flutter_datetime_picker:
> >   # flutter_localizations:
> >   #   sdk: flutter
> >   uuid:
> >   drift:
> >   http:
> >   device_info:
> >   image:
> >   hive:
> >   hive_flutter:
> >   # modal_bottom_sheet: ^3.0.0-pre
> >   awesome_notifications: ^0.7.4+1
> >   flutter_native_timezone: ^2.0.0
> >   timezone:
> > 
> > dev_dependencies:
> >   flutter_test:
> >     sdk: flutter
> > 
> >   # The "flutter_lints" package below contains a set of recommended lints to
> >   # encourage good coding practices. The lint set provided by the package is
> >   # activated in the `analysis_options.yaml` file located at the root of your
> >   # package. See that file for information about deactivating specific lint
> >   # rules and activating additional ones.
> >   flutter_lints: ^2.0.0
> >   hive_generator: ^1.1.3
> >   build_runner: ^2.1.11
> >   flutter_launcher_icons: "^0.9.2"
> > ```
> 
> It looks like the error is related to the use of bridging headers with module interfaces in Swift, and it might be causing issues during the build process. The error message indicates a problem with the module interface of 'Runner' and mentions a missing module '__ObjC'.

able to resolve this issues?

**Comment by khayyamov** [comment]
@zionnite 
same issue

**Comment by zionnite** [comment]
Okay, I was able to resolve the issue,
What I did what's that I updated my awesome notification to the latest, then I update the iOS in my pod file to 14 and I then run pod install and everything work out for me

**Comment by guilhermebene** [comment]
> Okay, I was able to resolve the issue, What I did what's that I updated my awesome notification to the latest, then I update the iOS in my pod file to 14 and I then run pod install and everything work out for me

This has not solved the issue for me. Anyone else got another solution?

**Comment by guilhermebene** [comment]
The solution discussed in the [topic](https://github.com/rafaelsetragni/awesome_notifications/issues/874) worked for me!
