### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)

### ISSUE THREAD

**Issue by briouyahasnae** [rafaelsetragni/awesome_notifications#775]
I got Thread 1: EXC_BAD_ACCESS (code=1, address=0x0) when I want run my application on IOS for flutter version 3.10.0 
My app crashed I guess this snippet of code causing an error     
public static func register(with registrar: FlutterPluginRegistrar) {
        let flutterChannel = FlutterMethodChannel(
            name: Definitions.CHANNEL_FLUTTER_PLUGIN,
            **binaryMessenger: registrar.messenger()**)
        
        SwiftAwesomeNotificationsPlugin()
            .AttachAwesomeNotificationsPlugin(
                usingRegistrar: registrar,
                throughFlutterChannel: flutterChannel)
    }
Any solution??

**Comment by rafaelsetragni** [comment]
@briouyahasnae without any more details, the only thing that i can do for you is to recommend to update the library to the last version. Also, in case you wish to, you can use the pre-release versions, that are in active development. This way i can update any issue faster than other versions.

Also, don't forget to join in your [Discord Beta team] (https://discord.com/channels/888523488376279050/933445281243082772) to request fixes and new updates.
