### ISSUE TITLE
schedule a notification in IOS with date and time to start, and when it riggers, it repeats every 2 seconds

### ISSUE THREAD

**Issue by moosalim** [rafaelsetragni/awesome_notifications#779]
**Is your feature request related to a problem? Please describe.**
schedule a notification in IOS with date and time to start, and when it starts, it repeats every 2 seconds

**Describe the solution you'd like**
I'm trying to figure out how the alarm clock app Alarmy is sending local notifications at 2-second intervals while the app is terminated.

There are two ways to schedule local notifications:

UNCalendarNotificationTrigger: Repeat at a day and time
UNTimeIntervalNotificationTrigger: Repeats at an interval that has to be 60 seconds or longer

Now you can send a notification at a certain time but you can't have it repeat at 2 second intervals.

You can set a trigger to repeat every 60 seconds, but you can't set a time for it to start repeating if the app is terminated.

You could schedule a bunch of UNCalendarNotificationTriggers to repeat every 2 seconds from the set date and time, but you can only schedule 64 notifications before the old ones get overridden.

With Alarmy, if you set an alarm and then kill the application (not leave it in background). The app will then send you a local notification every 2 seconds when your alarm timer is met. And this will run indefinitely (more than 64 scheduled notifications).

These notifications can't trigger any callbacks in the app that would allow it to schedule more notifications, so how are they doing this?

They're not using push notifications because the app works in Airplane mode with no wifi.

Anyone have any idea?

**Describe alternatives you've considered**
--
**Additional context**
--

**Comment by rafaelsetragni** [comment]
Hi @moosalim , unfortunately this is not possible due to iOS limitations. I already requested this feature on the Apple Developers forum 3 years ago, but they never got back to me.

**Comment by moosalim** [comment]
I wounded how Alarmy app could do it despite it is not supported by Apple

**Comment by rafaelsetragni** [comment]
Exactly. I need to give support to Apple devices. On Android everything is possible.

**Comment by moosalim** [comment]
Not sure if you understood me, this app (Alarmy) : https://apps.apple.com/us/app/alarmy-alarm-clock-sleepsound/id1163786766

does this feature, schedule a notification in IOS with date and time to trigger and it repeats every 2 seconds. 
There must be a way to do it as long as it is already working in this app. I have tested it by my self

**Comment by guyluz11** [comment]
Possibly connected to https://github.com/rafaelsetragni/awesome_notifications/issues/628
@moosalim I think you can schedule repeating notifications in the package [flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications) so @rafaelsetragni probably talks about something else.
