### ISSUE TITLE
Scheduled notification showing instantly

### ISSUE THREAD

**Issue by ghost** [rafaelsetragni/awesome_notifications#78]
Hello, my scheduled notification isnt working as a schedule, instead it shows up instantly even as i have put the schedule property. Any help will be appreciated

Thanks 

`"to": snap.data()["token"],
        "mutable_content": true,
        "notification": {"title": " "},
        "data": {
          "content": {
            "id": channelId,
            "channelKey": "app_channel",
            "title": "Time for appointment",
            "body": "Your appointment is due right now!!",
            "showWhen": true,
            "autoCancel": true,
            // "locked": true,
            "notificationLayout": "BigText",
            "privacy": "Private",
            "payload": {
              "type": "appointment",
              "agora_token_url": adminAgoraTokenUrl,
              "call_type": callType,
              "channel_id": channelId,
              "other_user": {
                "id": widget.partner["id"],
                "name": widget.partner["name"],
                "online_presence": widget.partner["online_presence"],
                "profile_photo": widget.partner["profile_photo"]
              }
            }
          },
          "actionButtons": [
            {"key": "START CALL", "label": "Start Call", "autoCancel": true},
          ],
          "schedule": {
            "initialDateTime": "2021-01-02 23:30:00",
            // "crontabSchedule": "5 38 20 ? * MON-FRI *",
            "allowWhileIdle": true,
            // "preciseSchedules": []
          }`

**Comment by rafaelsetragni** [comment]
What version and platform are you facing this problems?

**Comment by rafaelsetragni** [comment]
I gonna close this issue for now, since there is no more activity in 6 months. But you can reopen it, in case you judge necessary.
