### ISSUE TITLE
Example project does not support dart 3

### ISSUE THREAD

**Issue by guyluz11** [rafaelsetragni/awesome_notifications#787]
Example project use the pacakge [giffy_dialog](https://pub.dev/packages/giffy_dialog) which does not support dart 3, so currently updated flutter version can't run example project.

I found the package [giff_dialog](https://pub.dev/packages/giff_dialog) which is a fork of it that we can just switch to.

**Comment by rafaelsetragni** [comment]
Yes, thank you for the tip. But this was already made on version 0.7.5-dev.2+1, and i used exactly `giff_dialog` as replacement.
