### ISSUE TITLE
iOS notifications are not receiving through FCM payload

### ISSUE THREAD

**Issue by rutaba1** [rafaelsetragni/awesome_notifications#79]
Hi! First of all thanks fro creating this amazing plugin. I have used it in one of my projects and Android notifications seems to be working great. However, on iOS, Notification are received if I send it directly from the app but if I send via Postman(the FCM payload) I'm not receiving notifications at all, instead Firebase onMessage function is being triggered and I'm not sure why this has been happening.

**Comment by rafaelsetragni** [comment]
Push notifications on IOS is not that easy, unfortunately.

Check if you set the correct parameters on your target extensions, such minimum iOS version. The push notifications will only work if you target extensions are correctly configured and working.

**Comment by rutaba1** [comment]
Thanks for the reply.... I got mine working by configuring AwesomeContentExtension as well. Previously I was not adding AwesomeContentExtension because I only needed to use AwesomeServiceExtension. Seems like its important to add both services to get it working in iOS.

**Comment by arsalanj** [comment]
Will this package received the notifications from APNS directly without firebase?

**Comment by rafaelsetragni** [comment]
Now you need to implement it by yourself. That way, you can do everything possible related to push notifications.
