### ISSUE TITLE
Error trying to run in release mode: SHARED_PREFERENCES_NOT_AVAILABLE

### ISSUE THREAD

**Issue by PabloCir** [rafaelsetragni/awesome_notifications#791]
# **Error trying to run in release mode**

Hello, I have a problem when implementing the plugin in my project. When compiling it in 'debug' mode, there is no problem, but when running the 'flutter run --release' command, the app is left blank with the following error in the console:

![image](https://github.com/rafaelsetragni/awesome_notifications/assets/47547913/7b68505d-b7ed-44b7-a447-bb4547b98e60)

This error occurs both with my project, and using the example provided in the plugin, if you could help me, here is my pubspec:

`environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  animate_do: ^3.0.2
  auto_size_text: ^3.0.0
  awesome_notifications: ^0.7.4+1
  basics: ^0.10.0
  calendar_date_picker2: ^0.5.2
  calendar_view: ^1.0.2
  card_swiper: ^2.0.4
  cupertino_icons: ^1.0.2
  device_info_plus: ^8.1.0 
  dropdown_button2: ^2.0.0
  encrypt: ^5.0.1
  firebase_core: ^2.10.0
  firebase_messaging: ^14.4.1
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.0.0
  flutter_datetime_picker: ^1.5.1
  flutter_easyloading: ^3.0.5
  flutter_keyboard_visibility: ^5.4.0
  flutter_localizations:
    sdk: flutter
    version: any
  flutter_rating_bar: ^4.0.1
  flutter_signin_button: ^2.0.0
  flutter_verification_code: ^1.1.6
  font_awesome_flutter: ^9.0.0
  geolocator: ^9.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.2.2
  google_maps_flutter_web: ^0.4.0+5
  group_button: ^5.2.2
  intl: any
  intl_phone_number_input: ^0.7.1
  logger: ^1.1.0
  persistent_bottom_nav_bar: ^5.0.2
  responsive_framework: ^1.0.0
  rflutter_alert: ^2.0.4
  rounded_loading_button: ^2.1.0
  sizer: ^2.0.15
  universal_platform: ^1.0.0+1
  upgrader: ^6.2.0
  url_launcher: ^6.1.10

dev_dependencies:
  build_runner: ^2.3.3
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon/icon.png"
  min_sdk_android: 21 

Thanks.

**Comment by rafaelsetragni** [comment]
Try to upgrade to the version 0.7.5-dev.2+1 to see if the problem is solved.

**Comment by PabloCir** [comment]
I updated to version 0.7.5-dev.2+1, now the application compiles, it works, but it keeps giving the same error. I also tried updating to the latest version of Flutter and the error is the same.

**Comment by rafaelsetragni** [comment]
0.7.5-dev.2+1 does not use shared preferences anymore. Probably this error is getting caused in another library in your app.
