### ISSUE TITLE
update packages intl and others

### ISSUE THREAD

**Issue by sgehrman** [rafaelsetragni/awesome_notifications#803]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**

out of date packages

OBS: avoid to use the expression **"its not working"** or **"is working"** or any other variation. These expressions can mean anything and at same time doesn´t bring any useful information. As soon you rewrite these expressions, you naturally going to be more precise and clear.

## **2 - Provide us as much information as possible**

To help us to understand your issue, provide with your bug report all the relevant informations, such as:

* Your plugins list inside the file `pubspec.yaml` (at least all notification plugins)
* What platform did you found the issue
* What devices did you found the issue
* How are you initializing the plugin
* How are you creating the notification
* The output of `flutter doctor` command

OBS: To post a source code in your issue, please use the markdown below:

```Dart
print('Your source code goes here');
```

## **3 - How To Reproduce the Error**

...or if you prefer, you can provide us a simple example app on GitHub with the issue already reproduced instead of the steps 2 and 3.

**Comment by ps6067966** [comment]
please add intl 0.18.0 support

**Comment by rafaelsetragni** [comment]
You can use `dependency_override` to set whatever package version you want for the entire app.

```Yaml  
dependency_overrides:
  http: ^1.0.0
  intl: ^0.18.1
```

**Comment by LarsRefsgaard** [comment]
maybe you can make one release that includes intl 0.18.0 so that version solving doesn't fail.

**Comment by Charlinjoeaht** [comment]
```
Because awesome_notifications >=0.6.20 <0.7.5-dev.1 depends on intl ^0.17.0 and awesome_notifications >=0.7.5-dev.1 depends on intl ^0.18.1, awesome_notifications >=0.6.20 requires intl ^0.17.0 or ^0.18.1.
And because every version of my_notifications from path depends on awesome_notifications ^0.7.4+1 and every version of flutter_localizations from sdk depends on intl 0.18.0, my_notifications from path is incompatible with flutter_localizations from sdk.
So, because myexample depends on both flutter_localizations from sdk and my_notifications from path, version solving failed.
```

Above error is blocking me to use this package. Solution with `dependency_overrides` is not working too

**Comment by minebastiii** [comment]
My error that leads me here :

```
What went wrong:
A problem occurred evaluating project ':awesome_notifications'.
Project with path ':awn_core' could not be found in project ':awesome_notifications'.
```



Is there now a way to get it working? dependency_overrides doesn't work indeed.
