### ISSUE TITLE
Readme Notification channels missing channelGroupKey

### ISSUE THREAD

**Issue by guyluz11** [rafaelsetragni/awesome_notifications#807]
`channelGroupKey` attribute is missing from `Attribute` list in the readme.
Not to get confused with `groupKey` which have a close name but is not the same can be found.

**Comment by guyluz11** [comment]
Don't close

**Comment by rafaelsetragni** [comment]
Yes, this property is missing on documentation. Well noticed! I will add it in the next release.

**Comment by rafaelsetragni** [comment]
Change made and its already on development pipeline!
https://github.com/rafaelsetragni/awesome_notifications/tree/development

**Comment by guyluz11** [comment]
Thanks :)
Will close this issue
