### ISSUE TITLE
requestPermissionToSendNotifications returns false on below Android 11

### ISSUE THREAD

**Issue by guyluz11** [rafaelsetragni/awesome_notifications#821]
`awesome_notifications: ^0.7.4+1`
Calling `requestPermissionToSendNotifications` on Android version 10 and below reruns is always false.

Checking on the Android clock app there is no notification permission on it, so I suspect Android 10 and below don't include an option for notification permission.
So I expect calling `requestPermissionToSendNotifications` will return true for it.

Important to mention that calling 

```dart
 AwesomeNotifications().isNotificationAllowed().then((isAllowed) {
      if (!isAllowed) {
        return awesome.requestPermissionToSendNotifications();
      }
      return true;
    });
```

works because isNotificationAllowed works return isAllowd = true

**Comment by michael-wang** [comment]
I have to use following workaround:

```dart
bool _permissionGranted() async {
    final instance = AwesomeNotifications();
    if (await instance.isNotificationAllowed()) {
        return true;
    }

    final granted = await instance.requestPermissionToSendNotifications();
    if (granted) {
        return true;
    }

    // Double check because above function could returns false while user granted permission.
    return await instance.isNotificationAllowed();
}
```

**Comment by rafaelsetragni** [comment]
`isNotificationAllowed` just check for the global permission to send notifications, but there are sub permissions to request. When you request permissions, by default you request sound, badge and alarms. If you request 3 permissions but only 2 of them was given, so the `requestPermissionToSendNotifications` method returns false.

**Comment by guyluz11** [comment]
.
