### ISSUE TITLE
Turn off badg counter

### ISSUE THREAD

**Issue by guyluz11** [rafaelsetragni/awesome_notifications#829]
I would love to turn off/remove the badge counter popup above my app icon.

Is it possible to do so?
![image](https://github.com/rafaelsetragni/awesome_notifications/assets/9304740/88f4ebaa-9d70-4b69-b3f7-d40500dc9549)

**Comment by Leffe108** [comment]
When you call initialize() omit the Badge permission, and iOS will not show any badge for notifications.

```dart
      AwesomeNotifications().requestPermissionToSendNotifications(
        channelKey: "123",
        permissions: [
          NotificationPermission.Alert,
          //NotificationPermission.Badge, // Exclude the Badge permission
          NotificationPermission.Light
        ],
      );
```

**Comment by Leffe108** [comment]
You can at runtime remove the badge by setting the count to zero: `AwesomeNotifications().setGlobalBadgeCounter(0);`

**Comment by guyluz11** [comment]
Correct thanks @Leffe108 
Also found that I set `channelShowBadge` to true while initializing which is exactly what I have searched.
