### ISSUE TITLE
Progress bar notifications for IOS plarform

### ISSUE THREAD

**Issue by vqthanh1412489** [rafaelsetragni/awesome_notifications#830]
**Is your feature request related to a problem?
For Android, I can create Progress bar notifications on the tray, but for IOS I don't do it

**Describe the solution you'd like**
Support API for creating Progress bar notifications for IOS

**Describe alternatives you've considered**
<...>

**Additional context**
<...>

**Comment by rafaelsetragni** [comment]
This change will be achieved with custom notifications. For now i need to extend the support to web and desktop and after that i will implement custom notifications.
