### ISSUE TITLE
White Screen on IOS

### ISSUE THREAD

**Issue by EmadBeltaje** [rafaelsetragni/awesome_notifications#832]
i faced white screen on my ios simulator while using 
```dart
await AwesomeNotifications().requestPermissionToSendNotifications()
```
the weird thing is that i tried to put the code on try catch and it doesn't show any error its like the code only stops there and that is why it block the code and show white screen 

*** update**
I tried to remove **await** and everything worked fine
```dart
// remove await
AwesomeNotifications().requestPermissionToSendNotifications();
```

more info:
- flutter version: 3.10.6
- iam using ios simulator
- i already gave the permission to show notification so the problem happen after the first run

**Comment by rafaelsetragni** [comment]
Can you paste here your full initialization?

**Comment by EmadBeltaje** [comment]
This is my full initialization [code](https://github.com/EmadBeltaje/flutter_getx_template/blob/master/lib/utils/awesome_notifications_helper.dart) and as i said when i removed **await** from line number **21** everything worked just fine,
