### ISSUE TITLE
iOS app crashes when receiving push notification while app is killed

### ISSUE THREAD

**Issue by waleedqaefi** [rafaelsetragni/awesome_notifications#835]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**

The app crashes after receiving the push notification while the app state is killed , the crash only occur if the app is downloaded from the apple store . The crash does not appear once the app run locally using flutter run --release .  Here is the log from crashlytics

Fatal Exception: NSInvalidArgumentException
Attempt to insert non-property list object { 5 = { actionType = Default; autoDismissible = 1; channelKey = "default_channel"; color = 4294967295; createdDate = "2023-08-07 19:55:48 GMT"; createdLifeCycle = AppKilled; createdSource = Local; displayOnBackground = 1; displayOnForeground = 1; displayedDate = "2023-08-07 19:55:48 GMT"; displayedLifeCycle = AppKilled; hideLargeIconOnExpand = 0; id = 5; locked = 0; notificationLayout = Default; payload = { aps = "{content-available: 1.0}"; chatId = "415aSA0tuYb2UVki6XHTEwqh8FO2-kpfqjyHUvAdN4wUmw86d7z87FfF3"; createdDate = "2023-08-07 19:55:48.000Z"; createdLifeCycle = AppKilled; createdSource = Firebase; "gcm.message_id" = 1691438147040709; "google.c.fid" = "eOM3l0xM00S1p-7gEz_yHQ"; "google.c.sender.id" = 922938767693; id = "<null>"; photo = "https://firebasestorage.googleapis.com/v0/b/taaly-staging.appspot.com/o/tutor_profile%2F415aSA0tuYb2UVki6XHTEwqh8FO2?alt=media&token=a3b0035b-2ca6-4492-8f7b-4fd49529cc9c"; title = "Taaly Tutor"; type = chat; }; showWen = 1; ticker = ""; title = "you have a new message from Taaly Tutor"; }; } for key created

In Xcode the crash is pointing to this function in the createdManager

public static func saveCreated(received:NotificationReceived) {
        shared.set(received.toMap(), referenceKey: String(received.id!))
    }

1. Kill the app 
2. Receive Push Notification '....'
3. App Crashes'....'

**Comment by antont** [comment]
is this resolved somehow maybe, i guess @waleedqaefi has not been bitten by this for 1,5 months?
