### ISSUE TITLE
A background message could not be handled in Dart because there is no dart background handler registered

### ISSUE THREAD

**Issue by Musta-Pollo** [rafaelsetragni/awesome_notifications#840]
## **1 - Describe the bug**
ActionType.SilentBackgroundAction is not working when new flutter project is created and example code is added. Also ActionType.SilentAction is changed to ActionType.SilentBackgroundAction.

For my current flutter project the SilentAction is also causing the same error.

(ActionType.default works correctly)

## **2 - Provide us as much information as possible**

I tested  it on a real device and it outputs this error when a button is pressed of SilentBackgroundAction type:
![Screenshot 2023-08-19 at 13 49 15](https://github.com/rafaelsetragni/awesome_notifications/assets/68862752/e0fbcaf8-a631-4223-80cc-eb39ff8dfbb7)

When running the "complete" example app it works correctly. So it could be issues of dependencies for whatever reason. But changing dependencies as specified here https://pub.dev/packages/flutter_background_service, is not working.
```
in android/build.gradle classpath 'com.android.tools.build:gradle:7.1.2'
in android/gradle/wrapper/gradle-wrapper.properties distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-all.zip
```
-------------------------------------------------
Setup:
Device: Xiaomi Readmi Note 11 with battery optimalization disabled
[✓] Flutter (Channel stable, 3.13.0, on macOS 13.2.1 22D68 darwin-arm64, locale en-CZ)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)

## **3 - How To Reproduce the Error**

-  Create a new flutter project
-  Copy example code into main.dart

Just this setup: https://github.com/Musta-Pollo/awesome_inbackground

## **4 - Expected behavior**
After pressing on the action button with SilentBackgroundAction it will execute code in the background.

**Comment by rafaelsetragni** [comment]
This issue arises because the static method managing background execution is invalid, causing Flutter to return 0 when making awesome requests for the address to call. For native to successfully call your background execution, the method `onActionReceivedMethod` or `onFcmSilentDataHandle` needs to be global or static. Additionally, ensure to use @pragma('vm:entry-point') to maintain the same address in subsequent executions.

**Comment by Musta-Pollo** [comment]
Sorry for delayed response.
----------------------------
I think I did this correctly:

```
class NotificationController {
  static Future<void> initializeNotificationsEventListeners() async {
    await AwesomeNotifications().setListeners(
      onActionReceivedMethod: onActionReceivedMethod,
      onNotificationCreatedMethod: onNotificationCreatedMethod,
      onNotificationDisplayedMethod: onNotificationDisplayedMethod,
      onDismissActionReceivedMethod: onDismissActionReceivedMethod,
    );
  }

  @pragma('vm:entry-point')
  static Future<void> onActionReceivedMethod(
    ReceivedAction receivedAction,
  ) async {
   
  }
  ...
}
```

**Comment by rafaelsetragni** [comment]
Try to update your library to the last version to see if its resolved.

```yaml
awesome_notifications_core: ^0.7.6
awesome_notifications: any
awesome_notifications_fcm: any
```

**Comment by Musta-Pollo** [comment]
I tested it in my app and in the example app. It is still not working.

Just changing in example/main.dart on line 219: SilentAction to SilentBackgroundAction. Causes this:

```
D/Android: [Awesome Notifications](22451): New notification creation event (AwesomeEventsReceiver:209)
D/Android: [Awesome Notifications](22451): New notification display event (AwesomeEventsReceiver:229)
D/Android: [Awesome Notifications](22451): Notification created and displayed in 692ms (NotificationSender:202)
D/Android: [Awesome Notifications](22451): New action received (NotificationActionReceiver:36)
D/Android: [Awesome Notifications](22451): A new Dart background service has started (BackgroundService:24)
E/Android: [Awesome Notifications](22451): A background message could not be handled in Dart because there is no dart background handler registered. (BackgroundService:58)
W/System.err(22451): me.carda.awesome_notifications.core.exceptions.AwesomeNotificationsException: A background message could not be handled in Dart because there is no dart background handler registered.
W/System.err(22451):    at me.carda.awesome_notifications.core.exceptions.ExceptionFactory.registerNewAwesomeException(ExceptionFactory.java:76)
W/System.err(22451):    at me.carda.awesome_notifications.core.services.AwesomeBackgroundService.onHandleWork(AwesomeBackgroundService.java:46)
W/System.err(22451):    at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:396)
W/System.err(22451):    at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:387)
W/System.err(22451):    at android.os.AsyncTask$3.call(AsyncTask.java:394)
W/System.err(22451):    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/System.err(22451):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err(22451):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err(22451):    at java.lang.Thread.run(Thread.java:923)
D/Android: [Awesome Notifications](22451): New notification display event (AwesomeEventsReceiver:229)
D/Android: [Awesome Notifications](22451): Notification displayed in 548ms (NotificationSender:202)
```

**Comment by GeraldDev25** [comment]
@Musta-Pollo I had the same issue. Try to use this :
`awesome_notifications: 0.7.4+1
  awesome_notifications_fcm: 0.7.4+1` without `^` on the package. It will solve the error.

**Comment by Musta-Pollo** [comment]
Yeah, it works 👍 . Thank you!

**Comment by rmasarovic** [comment]
and some solution for new versions?

**Comment by GeraldDev25** [comment]
@rmasarovic No, still waiting.

**Comment by rmasarovic** [comment]
i found bug in AWNandroid core... it same like this https://github.com/rafaelsetragni/awesome_notifications/issues/887

**Comment by GeraldDev25** [comment]
@omer-ayyildiz Please remove `^` and try again.

**Comment by omer-ayyildiz** [comment]
I will try it thank you.

**Comment by daniel1414** [comment]
Hi, any progress with this error?

**Comment by kardenvan7** [comment]
Having the same error with the following versions:

```yaml
  awesome_notifications: 0.8.2
  awesome_notifications_core: 0.9.0
```

Declared static method with @pragma annotation and the error message is the same.
