### ISSUE TITLE
locked: true , not working when use NotificationLayout.MediaPlayer.

### ISSUE THREAD

**Issue by SaiMyinTzaw** [rafaelsetragni/awesome_notifications#844]
locked: true , not working when use NotificationLayout.MediaPlayer . I want user not to remove notification of media.

  content: NotificationContent(
          locked: true,
          wakeUpScreen: true,
            id: id,
            channelKey: 'media_player',
            category: NotificationCategory.Message,
            title: mediaNow.title,
         //   body: mediaNow.title,
            summary: homeController.isPlayingVideo ? 'Now playing' : '',
            notificationLayout: NotificationLayout.MediaPlayer,
            largeIcon: 'asset://assets/images/logo.png',
         //  color: Colors.purple.shade700,
            criticalAlert: true,
            ),

**Comment by RomanSoviak** [comment]
Have the same issue
