### ISSUE TITLE
Disclude example folder from pacakge

### ISSUE THREAD

**Issue by guyluz11** [rafaelsetragni/awesome_notifications#852]
Downloading the package from pub.dev includes the example folder

This is redundant and appears in IDE searches.

As written here https://github.com/dart-lang/pub-dev/issues/5862 you need to manually add `example` folder to `.pubignore`

![image](https://github.com/rafaelsetragni/awesome_notifications/assets/9304740/0becbb81-fb1a-4dc0-898b-302f05ce7005)

**Comment by rafaelsetragni** [comment]
In the comment at https://github.com/dart-lang/pub-dev/issues/5862#issuecomment-1713648350:

> > Pub packages are self-contained, they include `test/`, `tool/` and `example/` among others. If a package author doesn't want to ship those they can ignore them with `.pubignore`.
> 
> Since this comment was being used to argue for excluding examples in many issues (linked above), I want to clarify here that it's unlikely that developers are going to actually exclude `example/` because doing so would remove the example from the `pub.dev` page for the package.

This is the exact reason why i don't agree to remove the example folder. I need to offer the example at pub.dev page.

**Comment by guyluz11** [comment]
Didn't knew it will removed it from pub.dev, will close this issue
