### ISSUE TITLE
Can't handle onTap event in Notification

### ISSUE THREAD

**Issue by VimeshLunagariya** [rafaelsetragni/awesome_notifications#854]
Navigate the screen on Notification onTapevent not working also throw the below error:

[Awesome Notifications - ERROR]: onActionNotificationMethod is not a valid global or static method. (MethodChannelAwesomeNotifications:441)

=======================================================

static Future<void> startListeningNotificationEvents() async {
    await AwesomeNotifications().setListeners(
      onActionReceivedMethod: (ReceivedAction receivedAction) async {
        await NotificationController.onActionReceivedMethod(receivedAction);
      },
    );
  }
  
  
 // - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
 class NotificationController {
  @pragma('vm:entry-point')
  static Future<void> onActionReceivedMethod(ReceivedAction receivedAction) async {
             print(receivedAction.payload);
            // Navigation Code here.........,
  }
}

**Comment by rafaelsetragni** [comment]
The method sent as reference for onActionReceivedMethod is a dynamic method, not static.

```Dart
(ReceivedAction receivedAction) async {
   // your code
}
```

This is a dynamic method.

**Comment by VimeshLunagariya** [comment]
I tried to put the code here, but not getting the result, 
I put the print statement here, but when I press on notification, print statement is not working.
