### ISSUE TITLE
Customizable Notification Intervals with Start and End Times

### ISSUE THREAD

**Issue by AbdullahAli1993** [rafaelsetragni/awesome_notifications#855]
Currently, I'm trying to set up notifications to repeat every 15 minutes while excluding the nighttime hours. My current approach involves using a nested for loop, as shown below:

for (int hour = 8; hour <= 22; hour++) {
    for (int min = 5; min <= 50; min += 15) {
        await audioNotification(hour, min);
    }
}

Future<bool> audioNotification(int hour, int minute) async {  
    return await awesomeNotifications.createNotification(
      content: NotificationContent(
          id: uniqueId,
          channelKey: 'audio_channel',
          title: 'test title',
          body:'test body'
          autoDismissible: false,
          customSound: 'resource://raw/res_audio',
          category: NotificationCategory.Reminder,
   
      schedule: NotificationCalendar(
        hour: hour,
        minute: minute,
        second: 0,
        millisecond: 0,
        allowWhileIdle: true,
        preciseAlarm: true,
        repeats: true,
      ),
    );
  }
  
It would be better if the user could define a notification interval with specific start and end times, providing more flexibility in scheduling notifications.

maybe like this:

    schedule: NotificationInterval(
        interval: 15 * 60,
        //Add time interval for start and end hour 
        timeInterval:TimeInterval(from:8,to:23),
        allowWhileIdle: true,
        preciseAlarm: true,
        repeats: true,
      ),

**Comment by rafaelsetragni** [comment]
Unfortunately, its not possible to do it on iOS, and this limits what i can do on Android side. I was possible to do it before iOS 10, but for some unknown reason they removed.

**Comment by AbdullahAli1993** [comment]
This is sad, thank you for your great effort
