### ISSUE TITLE
receiveNotification: notification discarted [iOS]

### ISSUE THREAD

**Issue by joankabello** [rafaelsetragni/awesome_notifications#86]
Hello,

I am using `awesome_notification` and `flutter_local_notifications` both of them in my project for different functionalities in my project.

I get the error `receiveNotification: notification discarded` when i try to execute a notification from `flutter_local_notifications` plugin.

Also i saw other issues regarding this problem but with FCM which is not my case, but anyway i made the required configuration on AwesomeServiceExtension on iOS, and still the error persist.

Am i missing smth ?

**Comment by rafaelsetragni** [comment]
awesome_notification and flutter_local_notifications must not be used simultaneously. Since both make global functionality, one ends up interfering with the other.

Notification Discarded happen when the data package are not in the expected format. This could happen when you send an wrong json data or when you missconfigured the target extensions for iOS.

**Comment by joankabello** [comment]
I don't use the plugin at the same time to run 2 notifications, i use both of them in different conditions.

From what i saw on swift code, when the notification from flutter_local_notification was launched. The json data of the awesome_notification was nil.

A question that i had when i debuged my code is that, should the awesome_notifcation plugin be triggered when i launch a notification from other plugins?

Because if i can bypass the triggering of awesome_notificatiom swift code, this will solve the problem.

**Comment by rafaelsetragni** [comment]
Theres some functionality to receive the notification action that you can only do using flutter_local_notifications?

**Comment by joankabello** [comment]
Sorry i don't think i understood your question.

But the notification from flutter_local_notification plugin doesn't pop up at all.

**Comment by rafaelsetragni** [comment]
There is something that you cannot to do using only awesome_notifications? There is something that only flutter_local_notifications can do?

**Comment by joankabello** [comment]
Yes in fact i am using flutter_local_notification only because it allows me to add soundSource for each notification instead of adding it only in the channel.

If you can add this feature for awesome_notificatiom too it would be so nice.

**Comment by joankabello** [comment]
If you noticed i opened an issue for this feature request.

**Comment by rafaelsetragni** [comment]
So your wish will become true on next update! 🎉

**Comment by joankabello** [comment]
Thanks a lot 🚀

**Comment by joankabello** [comment]
Can i ask if you have any estimation about this feature or how can i help ?

**Comment by rafaelsetragni** [comment]
I gonna try to deliver this new version today, but im facing problems to develop using Mac on a virtual machine, and i can only deliver it after test on both platforms.

**Comment by joankabello** [comment]
> I gonna try to deliver this new version today, but im facing problems to develop using Mac on a virtual machine, and i can only deliver it after test on both platforms.

@rafaelsetragni I have a macOS on my office, i can help you with the development :)

**Comment by rafaelsetragni** [comment]
Of course! I will finish the coding and share with you on GitHub to you test it for me

**Comment by joankabello** [comment]
Okay great

**Comment by rafaelsetragni** [comment]
Try to use the parameter `customSound`, inside your notification's content.

**Comment by joankabello** [comment]
Did you pushed on any branch?

**Comment by rafaelsetragni** [comment]
Im not beeing able to set the sound to work for each notification on Android Oreo and above. Seems like the notification channel is disabling and overrinding the sound customization for each notification, and it seems that the google team  was intented to be like that.

The source that i made until now is on [https://github.com/rafaelsetragni/awesome_notifications/tree/content-custom-sound](https://github.com/rafaelsetragni/awesome_notifications/tree/content-custom-sound)

**Comment by joankabello** [comment]
https://stackoverflow.com/a/31398504/13189028

Does this answer help you, looks like for the Android above 7.0 a check of sdk is needed ?

Also the way how its made on the Android side of flutter_local_notification might help you.

**Comment by joankabello** [comment]
On the NotificationCompat.Builder()
you can add this line?

```
setSound("your sound uri",AudioManager.STREAM_NOTIFICATION)
```

**Comment by rafaelsetragni** [comment]
I already done that, but seems like my changes are being ignored by Android.

On iOS it's already all done, but not tested yet. You can test it right now. Just on Android the setSound and the channel's update are not working.

**Comment by MaheshPeri19** [comment]
> soundSource

soundSource parameter is working fine. We have to give complete path of custom sound or ringtone like below

`soundSource: 'resource://raw/res_s4_ringtone',
`
Please copy your custom sound or ringtone in res -> raw folder. It should work.

If you simply assigh soundSource: 'res_s4_ringtone', it will throw you error audio not found.

**Comment by joankabello** [comment]
@MaheshPeri19 We are not speaking about the parameter of soundSource, that works for only one Notification channel.

We are trying to add another `customSound` parameter to each notification to play different sounds for different notifications.


@rafaelsetragni Hello, So for the iOS did u encountered any problems ?.
I will try to see how i can help for the Android code to make it possible to work on Oreo and above. Very strange behavior.

**Comment by rafaelsetragni** [comment]
For iOS everything should work just fine. You can test it with the git branch that i let for you.

If you got some difficult to put it on your pubspec.yaml tell me here than i help you too.

**Comment by joankabello** [comment]
On iOS works fine.

**Comment by joankabello** [comment]
Any idea how flutter_local_notifications plugin, manages the issue on Andoroid, seem to work fine there with 8.1 and up

**Comment by rafaelsetragni** [comment]
Its not changing the notification sound, and it seems to be intented by Android team to be like that.

Take a look at [this topic](https://stackoverflow.com/questions/49605594/how-to-change-notification-sound-dynamically-in-android-o)

**Comment by rafaelsetragni** [comment]
There is a solution, but i cannot put it inside the plugin. You need to implement it by yourself.

[Changing sound and vibration for Notification Channel on Oreo 8.1](https://stackoverflow.com/questions/53316786/changing-sound-and-vibration-for-notification-channel-on-oreo-8-1)

**Comment by rafaelsetragni** [comment]
I get it! I had created a new channel inside Android OS for every channel's data change, calculated with the MD5 over all fields. Its transparent for the plugin users, but allows  now to fully update the channels, even on Android Oreo and above.

Please, test it for me again. I had upload a new version on [https://github.com/rafaelsetragni/awesome_notifications/tree/content-custom-sound](https://github.com/rafaelsetragni/awesome_notifications/tree/content-custom-sound)

**Comment by joankabello** [comment]
Okay, im testing it now

**Comment by joankabello** [comment]
Its working!! Tested on debug & release mode.

**Comment by joankabello** [comment]
The test in iOS passed successfully.
But some errors should be fixed on the swift code. On the function `channelMethodGetNextDate` before its released on the next version.

**Comment by joankabello** [comment]
@rafaelsetragni Any idea when this branch will be merged with the main one ?

**Comment by rafaelsetragni** [comment]
I've red-evaluate this method and i found a problem. When the channel is updated, every active notification is closed.

So, I cannot keep the customSound field, because it can induce the developers to mistakes. Instead, i gonna create a updateChannelMethod and warning the developers about his downside on Android oreo and above.

For you, theres not a big change at all. I gonna release an new version in this weekend.

**Comment by rafaelsetragni** [comment]
I've added `forceUpdate` option on `setChannel` method, to allows to full update an channel on Android Oreo and above without need to reinstall the app, with the downside to close all current notifications.

This functionality will be availabe on next release.
