### ISSUE TITLE
Awesome notification is not running on ios

### ISSUE THREAD

**Issue by shakilhossain38** [rafaelsetragni/awesome_notifications#866]
'awesome_notifications' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.

**Comment by ReinierKorth** [comment]
I have this same problem

**Comment by wjmetcalfiiii** [comment]
I have this same problem with sensors_plus 3.1.0 

https://github.com/fluttercommunity/plus_plugins/discussions/2280

**Comment by Fima2003** [comment]
Has it been solved?

**Comment by rudiigun** [comment]
same

**Comment by nesehic** [comment]
same

**Comment by Mistic92** [comment]
Still no solution? 
```
The 'awesome_notifications' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.
```

**Comment by revtut** [comment]
Same issue here, it happens when I invoke the createNotification method.

```
  // Schedule a notification to be sent at a certain time
  Future<bool> scheduleNotification({
    required NotificationContent content,
    required DateTime dateTime,
  }) async {
    final providerNotifications = AwesomeNotifications();

    final isAllowed = await providerNotifications.isNotificationAllowed();
    if (!isAllowed) return false;

    return providerNotifications.createNotification(
      content: content,
      schedule: NotificationCalendar.fromDate(
        date: dateTime,
        allowWhileIdle: true,
        preciseAlarm: true,
      ),
    );
  }
```

[ERROR:flutter/shell/common/shell.cc(1038)] The 'awesome_notifications' channel sent a message from native to Flutter on a non-platform thread. Platform channel messages must be sent on the platform thread. Failure to do so may result in data loss or crashes, and must be fixed in the plugin or application code creating that channel.
           See https://docs.flutter.dev/platform-integration/platform-channels#channels-and-platform-threading for more information.

**Comment by minhdanh** [comment]
Hi @rafaelsetragni, I'm still seeing this error when creating a new notification.  I'm using `awesome_notifications: ^0.9.3+1`. iOS 17 (simulator). As I see you have updated this as completed and closed the issue on Mar 16, can I check what is the solution/fix for this issue?

**Comment by felipecosta-dev** [comment]
Are there any updates on this issue? Seems scheduled local notifications are not working in iOS because of this

**Comment by drooxie** [comment]
@rafaelsetragni why is the issue closed? the problem is still reproducing

**Comment by sametiyigun** [comment]
Is there a solution that we can't find? @rafaelsetragni

**Comment by Arpit-Verma1** [comment]
@rafaelsetragni  i still face this issue . i sent notifiication through firebase console and it receive on iOS but through push notification  i don't able to receive it
