### ISSUE TITLE
Sound source for each notification

### ISSUE THREAD

**Issue by joankabello** [rafaelsetragni/awesome_notifications#87]
Hello, 

Is it possible to add a soundSource for each notification on `createNotification()` method, instead on adding it on the notification channel.
In this way every notification can have its own notification sound.

Thanks in advance

**Comment by madd-project** [comment]
Yes, You can use this, ```soundSource: "resource://raw/alert_simple",``` in every new channel you prepare,

**Comment by madd-project** [comment]
To Remember, alert_simple is the name of my sound file
also uninstall the app before making the use it, 
Also, you put the file in ```android\app\src\main\res\raw\alert_simple.wav``` otherwise it will be waste, fine. any more queries?

**Comment by NOTtheKRish** [comment]
can we use .mp3 media files or is it compulsory to use .wav format sounds??
