### ISSUE TITLE
Icon doesnt show up in the notification

### ISSUE THREAD

**Issue by Verschwiegener** [rafaelsetragni/awesome_notifications#88]
Whenever i create a notification i get a black square instead of the actual icon of the App

This is the initialization code:
 AwesomeNotifications().initialize(
      // set the icon to null if you want to use the default app icon
        "resource://drawable/logo_gls_ks",
        [
          NotificationChannel(
            //icon: "resource://drawable/logo_gls_ks",
              channelKey: 'basic_channel',
              channelName: 'Basic notifications',
              channelDescription: 'Notification channel for basic tests',

              //defaultColor: Color(0xFF9D50DD),
              importance: NotificationImportance.Max,
              ledColor: Colors.white
          )
        ]
    );
And this the notification code:
AwesomeNotifications().createNotification(
                      content: NotificationContent(
                          id: 1,
                          channelKey: 'basic_channel',
                          title: 'Notification',
                          body: 'Simple body',
                        //icon: null,
                      )
                  );
Ant this is the result i am getting
![Notification](https://user-images.githubusercontent.com/51762258/104108332-f526e780-52c3-11eb-9ab2-044ae09d821d.PNG)

And i have the picture in the drawable folder
Any help would be appreciated

**Comment by rafaelsetragni** [comment]
This is the default behavior. The image is override by the color that you choose. You need to include a transparent layer on your icon.

**Comment by Verschwiegener** [comment]
And how exactly can I do this?

**Comment by Verschwiegener** [comment]
Or should I make the icon itself transparent so the this comes true my background?

**Comment by myrkgard** [comment]
> Or should I make the icon itself transparent so the this comes true my background?

In your favorite drawing application, create a PNG with transparent background. Draw your logo in a single color (black) on that transparent background. In the notification, the notification's background color will shine through the transparent areas. The areas you painted black will be drawn using the color specified by ```color``` in your ```NotificationContent```.

**Comment by Verschwiegener** [comment]
Perfect thanks i got it working as intended
