### ISSUE TITLE
Cannot set BUILD_LIBRARY_FOR_DISTRIBUTION and APPLICATION_EXTENSION_API_ONLY to Codemagic

### ISSUE THREAD

**Issue by kydoaod** [rafaelsetragni/awesome_notifications#884]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**

We are having issue for building this app in codemagic with this error "Using bridging headers with module interfaces is unsupported ". I know that you mentioned that we can set 

Build libraries for distribution => NO
Only safe API extensions => NO
.. and in your Notification Extension target:
Build libraries for distribution => NO
Only safe API extensions => YES

But the thing is we cannot do this in codemagic. Is there any solutions for this for us to build this properly in CI/CD as we wont have obviously a XCode UI there?

## **2 - Provide us as much information as possible**

We simply use this module and also building it in codemagic as described above

* Your plugins list inside the file `pubspec.yaml` (at least all notification plugins): 
  _fe_analyzer_shared 64.0.0 (65.0.0 available)
  analyzer 6.2.0 (6.3.0 available)
  archive 3.4.3 (3.4.6 available)
  collection 1.17.2 (1.18.0 available)
  file 6.1.4 (7.0.0 available)
  firebase_core 2.16.0 (2.19.0 available)
  firebase_core_platform_interface 4.8.0 (5.0.0 available)
  firebase_core_web 2.8.0 (2.8.1 available)
  flutter_riverpod 2.4.1 (2.4.4 available)
  freezed 2.4.3 (2.4.5 available)
  google_mobile_ads 3.0.0 (3.1.0 available)
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.9.1 (1.11.0 available)
  petitparser 5.4.0 (6.0.1 available)
  platform 3.1.2 (3.1.3 available)
  riverpod 2.4.1 (2.4.4 available)
  shared_preferences 2.2.1 (2.2.2 available)
  shared_preferences_linux 2.3.1 (2.3.2 available)
  shared_preferences_windows 2.3.1 (2.3.2 available)
  stack_trace 1.11.0 (1.11.1 available)
  stream_channel 2.1.1 (2.1.2 available)
  test_api 0.6.0 (0.6.1 available)
  vector_graphics 1.1.7 (1.1.9 available)
  vector_graphics_codec 1.1.7 (1.1.9 available)
  vector_graphics_compiler 1.1.7 (1.1.9 available)
  visibility_detector 0.3.3 (0.4.0+2 available)
  web 0.1.4-beta (0.3.0 available)
  webview_flutter 4.3.0 (4.4.1 available)
  webview_flutter_wkwebview 3.9.0 (3.9.1 available)
  xml 6.3.0 (6.4.2 available)
* What platform did you found the issue: Codemagic
* What devices did you found the issue: iOS
* How are you initializing the plugin: See below code
* How are you creating the notification: Scheduled
* The output of `flutter doctor` command: Codemagic did not do this but I assume it should be a normal one

OBS: To post a source code in your issue, please use the markdown below:

```Dart
import 'package:awesome_notifications/awesome_notifications.dart';
...
AwesomeNotifications().initialize(
  // set the icon to null if you want to use the default app icon
  'resource://drawable/res_app_icon',
  [
    NotificationChannel(
        channelGroupKey: 'basic_channel_group',
        channelKey: 'basic_channel',
        channelName: 'Basic notifications',
        channelDescription: 'Notification channel for basic tests',
        defaultColor: Color(0xFF9D50DD),
        ledColor: Colors.white)
  ],
  // Channel groups are only visual and are not required
  channelGroups: [
    NotificationChannelGroup(
        channelGroupKey: 'basic_channel_group',
        channelGroupName: 'Basic group')
  ],
  debug: true
);
```

## **3 - How To Reproduce the Error**

- Attach a repo to codemagic
- Build only using iOS.
- This error will appear
Swift Compiler Error (Xcode): Using bridging headers with module interfaces is unsupported

Uncategorized (Xcode): Command SwiftDriver emitted errors but did not return a nonzero exit code to indicate failure

...or if you prefer, you can provide us a simple example app on GitHub with the issue already reproduced instead of the steps 2 and 3.

## **4 - Expected behavior**
Should build with no errors

**Comment by majo482** [comment]
Any solution? I have same problem
