### ISSUE TITLE
No Dart Background Handler Registered

### ISSUE THREAD

**Issue by ewingapp** [rafaelsetragni/awesome_notifications#887]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**

I'm trying to implement FCM message notification with reply action button that will emit data to a socket when the send button is pressed. Whenever I tried to press the send button, it throws this error:
```Dart
A background message could not be handled in Dart because there is no dart background handler registered. (BackgroundService:58)
```

## **2 - Provide us as much information as possible**

To help us to understand your issue, provide with your bug report all the relevant informations, such as:

* Your plugins list inside the file `pubspec.yaml` (at least all notification plugins)
  firebase_core: ^2.17.0
  firebase_crashlytics: ^3.3.7
  firebase_analytics: ^10.5.1
  awesome_notifications_core: ^0.8.1
  awesome_notifications: any
  awesome_notifications_fcm: any

* What platform did you found the issue
Android.

* What devices did you found the issue
Emulator.

* How are you initializing the plugin
```Dart
static Future<void> initializeLocalNotification() async {
    AwesomeNotifications().initialize(
      // set the icon to null if you want to use the default app icon
      'resource://drawable/ic_stat_notification',
      [
        NotificationChannel(
          channelKey: 'high_importance_channel',
          channelName: 'High Importance Channel',
          channelDescription: 'Notification channel for high importance notifications',
          importance: NotificationImportance.Max,
          ledColor: Colors.white,
        )
      ],
      debug: true,
    );

    await AwesomeNotifications().isNotificationAllowed().then((isAllowed) async {
      if (!isAllowed) {
        await AwesomeNotifications().requestPermissionToSendNotifications();
      }
    });

    await AwesomeNotifications().setListeners(
      onActionReceivedMethod: NotificationServices.onActionReceivedMethod,
      onDismissActionReceivedMethod: NotificationServices.onDismissActionReceivedMethod,
      onNotificationCreatedMethod: NotificationServices.onNotificationCreatedMethod,
      onNotificationDisplayedMethod: NotificationServices.onNotificationDisplayedMethod,
    );
  }
```

```Dart
static Future<void> initializeRemoteNotification() async {
    await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
    AwesomeNotificationsFcm().initialize(
      onFcmSilentDataHandle: NotificationServices.silentDataHandler,
      onFcmTokenHandle: NotificationServices.fcmTokenHandler,
      onNativeTokenHandle: NotificationServices.nativeTokenHandler,
      licenseKeys: null,
      debug: true,
    );

    await initializeIsolateReceivePort();
  }
```

```Dart
static Future<void> getInitialNotificationAction() async {
    // Get any messages which caused the application to open from
    // a terminated state.
    ReceivedAction? initialAction = await AwesomeNotifications().getInitialNotificationAction();

    // If the initial action isn't null, handle the notification.
    if (initialAction != null) {
      handleNotification(initialAction);
    }
  }
```

* How are you creating the notification
Sent from backend, it will be created whenever there is a new message.

* The output of `flutter doctor` command
[√] Flutter (Channel stable, 3.13.6, on Microsoft Windows [Version 10.0.22621.2506], locale en-ID)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[!] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.26)
    X The current Visual Studio installation is incomplete. Please reinstall Visual Studio.
[√] Android Studio (version 2022.3)
[√] VS Code (version 1.83.1)
[√] Connected device (4 available)
[√] Network resources

## **3 - How To Reproduce the Error**

1. Send or create a push notification with Messaging layout and a reply NotificationActionButton labeled 'Reply' with SilentBackgroundaction actionType and requiredInputText set to true.
2. Input some text.
3. Press the the send button to send the reply.
4. The send button will be loading indefinitely and the error is thrown.

## **4 - Expected behavior**
User able to send the reply successfully.

## **5 - Screenshots**
![Screenshot (1050)](https://github.com/rafaelsetragni/awesome_notifications/assets/71771336/9dff7429-928f-4993-bff9-f2a5db060ba8)

## **6 - Additional context**
Currently none.

**Comment by rmasarovic** [comment]
@rafaelsetragni 
I  think bug is in code  AwN Android Core library, because nowhere set SilentCallbackDispacher.

I think awesomeNotifications.setEventsHandle(
                createdCallback,
                displayedCallback,
                actionCallback,
                dismissedCallback); must by set somehow set silentCallback
