### ISSUE TITLE
SubscribeToTop on FCM

### ISSUE THREAD

**Issue by tashone** [rafaelsetragni/awesome_notifications#89]
How can I to subscribe to topic for FCM?
_firebaseMessaging.subscribeToTopic('all');
something this...

**Comment by rafaelsetragni** [comment]
Please, explain to us what this function does.

**Comment by tashone** [comment]
I'm sorry for long answer.
https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/FirebaseMessaging?hl=ru
there are has description about this method of FCM.
It  need for send throwe API FMC.
 "to" : "[YOUR APP TOKEN]",
use no TOKEM
and use 
"to":"/topic/all"
for sending for all devices or some other topics

**Comment by Mohammad-Adam** [comment]
@rafaelsetragni yes, how to subscribe to a firebase messaging topic, like using `firebaseMessaging.subscribeToTopic('topic')` and `firebaseMessaging.unsubscribeFromTopic('topic')`

**Comment by tashone** [comment]
this is I know, but I used awesome without including FMC.
Close this issue, in new version plugin it will not actual.
