### ISSUE TITLE
After the vibration mode is enabled, the notification is triggered several times, and only one vibration is generated

### ISSUE THREAD

**Issue by laterdayi** [rafaelsetragni/awesome_notifications#897]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**

After the vibration mode is enabled, the notification is triggered several times, and only one vibration is generated

## **2 - Provide us as much information as possible**

Android 13

xiaomi

## **3 - How To Reproduce the Error**

...or if you prefer, you can provide us a simple example app on GitHub with the issue already reproduced instead of the steps 2 and 3.

**Comment by rafaelsetragni** [comment]
I just can't even understand the problem because it was added basically none information about it. Thank you.
