### ISSUE TITLE
Awesome Notifications not initializing caused by setListeners

### ISSUE THREAD

**Issue by ribalassaf** [rafaelsetragni/awesome_notifications#898]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **Awesome notifications is throwing a Platform Exception Error
 PlatformException(UNKNOWN_EXCEPTION, java.lang.Integer cannot be cast to java.lang.Long, unexpectedError.ClassCastException, null)**

2 - here is the call stack 
E/flutter ( 3472): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
E/flutter ( 3472): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
E/flutter ( 3472): <asynchronous suspension>
E/flutter ( 3472): #2      MethodChannelAwesomeNotifications.setListeners (package:awesome_notifications/awesome_notifications_method_channel.dart:357:19)
E/flutter ( 3472): <asynchronous suspension>
E/flutter ( 3472): #3      NotificationController.setUpNotificationListeners (package:haki/notifications/notification_controller.dart:107:5)
E/flutter ( 3472): <asynchronous suspension>
E/flutter ( 3472): #4      NotificationController.initNotifications (package:haki/notifications/notification_controller.dart:86:5)
E/flutter ( 3472): <asynchronous suspension>
E/flutter ( 3472): #5      main (package:haki/main.dart:36:3)
E/flutter ( 3472): <asynchronous suspension>
E/flutter ( 3472):

**Comment by rafaelsetragni** [comment]
Guess what, i just can't help you because you didn't follow the rules and do not provide me all informations needed.
On the next version, if possible, i will fix it.
