### ISSUE TITLE
I get this error about icon when I run the example code

### ISSUE THREAD

**Issue by Eecekkaratas** [rafaelsetragni/awesome_notifications#9]
java.lang.IllegalArgumentException: Invalid notification (no valid small icon): Notification(channel=basic_channel pri=1 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x11 color=0xff9d50dd vis=UNKNOWN(2) semFlags=0x0 semPriority=0 semMissedCount=0)

**Comment by Eecekkaratas** [comment]
fixed it, never mind

**Comment by amangautam1** [comment]
@Eecekkaratas How did you fix it? I am also getting same issue.

**Comment by ishwaryamamidi** [comment]
@Eecekkaratas I have the same issue. Can you please tell me how you fixed it?

**Comment by rafaelsetragni** [comment]
Se the icon on initialization method (where you create your firsts notification channels) to null or paste the real file into you native resource folder for Android.

All the steps are more detailed in the README file.

**Comment by Verschwiegener** [comment]
You should probably put this in the docs but thanks keep it up nice library
