### ISSUE TITLE
me.carda:AndroidAwnCore not found

### ISSUE THREAD

**Issue by ohari5336** [rafaelsetragni/awesome_notifications#908]
Launching lib/main.dart on moto one action in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find me.carda:AndroidAwnCore:0.7.5.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/me/carda/AndroidAwnCore/0.7.5/AndroidAwnCore-0.7.5.pom
       - https://repo.maven.apache.org/maven2/me/carda/AndroidAwnCore/0.7.5/AndroidAwnCore-0.7.5.pom
       - https://storage.googleapis.com/download.flutter.io/me/carda/AndroidAwnCore/0.7.5/AndroidAwnCore-0.7.5.pom
       - https://jitpack.io/me/carda/AndroidAwnCore/0.7.5/AndroidAwnCore-0.7.5.pom
       - https://jcenter.bintray.com/me/carda/AndroidAwnCore/0.7.5/AndroidAwnCore-0.7.5.pom
       - https://www.jitpack.io/me/carda/AndroidAwnCore/0.7.5/AndroidAwnCore-0.7.5.pom
     Required by:
         project :app > project :awesome_notifications

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by amit548** [comment]
same problem

**Comment by amit548** [comment]
I fixed this problem by changing flutter channel mater to stable!

**Comment by RagehAz** [comment]
> I fixed this problem by changing flutter channel mater to stable!

did not work with me

**Comment by rafaelsetragni** [comment]
Open your android folder using the android studio and resync your project. Sometimes the jitpack server fails to delivery the package download.

**Comment by ohari5336** [comment]
Restart Android Studio also solved this error, i faced it again 10 minutes ago.
