### ISSUE TITLE
 [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(SHARED_PREFERENCES_NOT_AVAILABLE, class c3.b isn't parameterized, sharedPreferences.get, null)

### ISSUE THREAD

**Issue by rouni78** [rafaelsetragni/awesome_notifications#909]
hello I hope you are well I find your plugin great and I am working on an application which requires notifications when I initialize the genial_notification plugin they work correctly in debug mode but when I use it in release mode I encounter this problem: 

E/flutter (18712): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(SHARED_PREFERENCES_NOT_AVAILABLE, class c3.b isn't parameterized, sharedPreferences.get, null)
E/flutter (18712): #0 StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651)
E/flutter (18712): #1 MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334)
E/flutter (18712): <asynchronous suspension>
E/flutter (18712): #2 MethodChannelAwesomeNotifications.initialize (package:awesome_notifications/awesome_notifications_method_channel.dart:299)
E/flutter (18712): <asynchronous suspension>
E/flutter (18712): #3 NotificationService.initialzeNotification (package:reservoo/notification/notification_service.dart:8)
E/flutter (18712): <asynchronous suspension>
E/flutter (18712): #4 main (package:reservoo/main.dart:14)
E/flutter (18712): <asynchronous suspension>
E/flutter (18712):
  and here is my code: void main() async{
   WidgetsFlutterBinding.ensureInitialized();
   await AwesomeNotifications().initialize(
     "resource://drawable/flutter_logo",
       [
         NotificationChannel(
           channelKey: 'basic_channel',
           channelName: 'Basic notifications',
           channelDescription: 'Notification channel for basic notifications',
         ),
       ],
     debug:true
   );
   /*Workmanager().initialize(
     callbackDispatcher, // The top level function, aka callbackDispatcher
   );*/
   SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]).
   then((value) {
     initializeDateFormatting().then((_) =>
         runApp(
             const reserve()
         )
     );
   });
}

I need your help to resolve this problem please thank you!

**Comment by adrianvintu** [comment]
Same here, on Flutter sdk 3.16.5,  compileSdkVersion 34, distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-all.zip

**Comment by adrianvintu** [comment]
This breaks the app hard - it cannot start!

**Comment by ndusart** [comment]
https://github.com/rafaelsetragni/awesome_notifications/issues/814#issuecomment-1850478345

**Comment by adrianvintu** [comment]
@ndusart thank you a million times! this bug has absolutely killed my apps!
