### ISSUE TITLE
Scheduled notification not shown after mobille reboot 

### ISSUE THREAD

**Issue by ghost** [rafaelsetragni/awesome_notifications#92]
I have scheduled some notifications .they works fine even after the app is terminated but not after a reboot.But the .listScheduledNotifications() shows the scheduled notification even after the scheduled time(initialDateTime) help me please

**Comment by rafaelsetragni** [comment]
What platform and which version are you making these tests?

**Comment by Ameenul176** [comment]
Android studio - 4.0.0
Dart sdk - 2.12.0
Flutter - 1.25.0
awesome_notifications: ^0.0.5+4
device used : Realme 3 pro android 10

**Comment by Ameenul176** [comment]
here is my main.dart which i used to test in my device

adding 2 minutes to current time so it will show notification after two minutes and it does show the notification even after the app termination but not after a reboot

import 'package:flutter/material.dart';

import 'package:awesome_notifications/awesome_notifications.dart';

void main(){
  WidgetsFlutterBinding.ensureInitialized();
  AwesomeNotifications().initialize(
    // set the icon to null if you want to use the default app icon
      'resource://drawable/ic_launcher',
      [
        NotificationChannel(
          channelKey: 'basic_channel',
          channelName: 'Basic notifications',
          channelDescription: 'Notification channel for basic tests',
          defaultColor: Color(0xFF9D50DD),
          ledColor: Colors.white,

        )
      ]
  );
  runApp(MyApp());
}



Future<void> showNotification() async {
  AwesomeNotifications().isNotificationAllowed().then((isAllowed) {
    if (!isAllowed) {
      AwesomeNotifications().requestPermissionToSendNotifications();
    }
  });
  AwesomeNotifications().createNotification(
    content: NotificationContent(
      id: 10,
      channelKey: 'basic_channel',
      title: 'Simple Notification',
      body: 'Simple body',
      autoCancel: false,
    ),
    schedule: NotificationSchedule(
      initialDateTime: DateTime.now().add(Duration(minutes: 2)).toUtc(), //
      allowWhileIdle: true,

    ),
  );

}

void viewScheduledNotifications() {
  AwesomeNotifications().listScheduledNotifications().then((value) {
    value.forEach((element) {
      print(element.toString());
    });
  });
}



class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      home: Material(
        child: Scaffold(
          appBar: AppBar(
            title: Text("local notifications"),
          ),
          body: Center(
            child: Column(
              children: [
                RaisedButton(
                  child: Text("schedule notification"),
                  onPressed: showNotification,
                ),
                RaisedButton(
                  child: Text("view scheduled notifications"),
                  onPressed: viewScheduledNotifications,
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

**Comment by Ameenul176** [comment]
Its not a problem with the package .Its a problem with my mobile phone .The start up manager of my mobile blocked the app from running in background even it receives BOOT_COMPLETED. By the way is there any way to configure to that start up permission programmatically to allow the app to start on reboot immediately after app installation instead of manually asking the user to turn it on in settings.
![Screenshot_2021-01-23-21-16-47-33](https://user-images.githubusercontent.com/53428964/105607024-81f09b80-5dc2-11eb-84f7-4a987b416dbc.jpg)

**Comment by julianbraasch** [comment]
I have the same issue. Notifications are listed as scheduled after a reboot, but they either don't appear at all or delayed. I'm using Flutter 1.22.6, awesome_notifications 0.0.0+5 on Android 11.

**Comment by rafaelsetragni** [comment]
New version released. Check to see if the problem is resolved.

**Comment by younasud** [comment]
Problem is not resolved yet we can see Notifications are listed as scheduled after a reboot, but they either don't appear at all or delayed
awesome_notifications: ^0.0.5+8
Flutter 2.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b1395592de (6 days ago) • 2021-04-01 14:25:01 -0700
Engine • revision 2dce47073a
Tools • Dart 2.12.2

**Comment by rafaelsetragni** [comment]
This problem was solved in version 0.6.13. Please take a look and update to the last version.
