### ISSUE TITLE
Background Notification not displaying

### ISSUE THREAD

**Issue by Abdulbasheer095** [rafaelsetragni/awesome_notifications#921]
Notifications are not displaying after the app is terminated, please suggest me how to resolve this issue and display the notification every minute even though the app is terminated by the user
Thanks in advance.

**Comment by DenisMrGnusa** [comment]
same issue here,

this my device info:
device : Xiaomi 11T Pro
Android : 13
MIUI : 14.0.4
awesome_notifications: 0.9.2

Trying with scheduled notification, and notification are not display while in background, although it runs smoothly when the application is on.

thank you, regards

**Comment by Liortra** [comment]
Look at Common Known Issues

**Comment by anmolstuteja** [comment]
Any update on the issue?
