### ISSUE TITLE
"[Demo]" appended in the subject of android device

### ISSUE THREAD

**Issue by Livingstone99** [rafaelsetragni/awesome_notifications#922]
@derBeukatt 
@tek08 
@ndusart 
@efraespada 
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**

OBS: avoid to use the expression **"its not working"** or **"is working"** or any other variation. These expressions can mean anything and at same time doesn´t bring any useful information. As soon you rewrite these expressions, you naturally going to be more precise and clear.

## **2 - Provide us as much information as possible**

To help us to understand your issue, provide with your bug report all the relevant informations, such as:

* Your plugins list inside the file `pubspec.yaml` (at least all notification plugins)
* What platform did you found the issue
* What devices did you found the issue
* How are you initializing the plugin
* How are you creating the notification
* The output of `flutter doctor` command

OBS: To post a source code in your issue, please use the markdown below:

```Dart
 await AwesomeNotifications().initialize(
        'resource://drawable/app_icon', //
        [
          NotificationChannel(
              channelKey: 'basic_channel',
              channelName: 'basic_channel',
              channelDescription: 'Notification tests as alerts',
              playSound: true,
              onlyAlertOnce: false,
              groupAlertBehavior: GroupAlertBehavior.All,
              importance: NotificationImportance.High,
              defaultPrivacy: NotificationPrivacy.Private,
              defaultColor: Colors.deepPurple,
              ledColor: Colors.deepPurple),
        ],
        debug: false);
```

## **3 - How To Reproduce the Error**
push notification from a remote server, its works fine for IOS devices, but appendeds demo in the subject of android devices.

## **5 - Screenshots**
expected result on ios device
![IMG_80D9D5541BFF-1](https://github.com/rafaelsetragni/awesome_notifications/assets/39328877/dd14cd22-baf0-4dc0-a0ed-a6a15e0972ce)

unexpected result on android
![191c21dc-4cd0-4425-920e-e0e8ff238e61](https://github.com/rafaelsetragni/awesome_notifications/assets/39328877/b8a260b1-ac90-4132-9365-13fef9b99f44)

**Comment by tek08** [comment]
There is nowhere near enough info here for me to be able to help effectively, not to mention I'm not a maintainer of this repo, but you pinged me, so:

![0 WdAIH03rYPOt9EOb](https://github.com/rafaelsetragni/awesome_notifications/assets/875457/7468447a-956e-4a48-b70f-12ab0df8e97a)

To give a *completely* random, and likely wrong, guess: If by any chance you're using Firebase to send notifications to your devices, and in particular [`firebase_admin.messaging`](https://firebase.google.com/docs/reference/admin/node/firebase-admin.messaging), see docs here:  https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages    and double check that you haven't inadvertently provided a different title somewhere, e.g. in `android.notification.title`.

**Comment by Livingstone99** [comment]
@tek08 i just tagged randomly... this issue is driving me crazy fr
