### ISSUE TITLE
MissingPluginException: FCM background Msg

### ISSUE THREAD

**Issue by a7mdragab** [rafaelsetragni/awesome_notifications#93]
Hello,
I have a problem with FCM background messages!
I used the code ```https://github.com/bayuramadeza/Awesome-Notification-FCM``` but no notifications received!

So, I have implemented 

```
_firebaseMessaging.configure(
      onMessage: (message) {
        AwesomeNotifications().createNotification(
            content: NotificationContent()
                .fromMap(jsonDecode(message['data']['content'])),
            );
        return;
      },
      onBackgroundMessage: myBackgroundMessageHandler,
    );

----------------------------------------------------------------------------------------------------
Future<void> myBackgroundMessageHandler(Map<String, dynamic> message) async {
     AwesomeNotifications().createNotification(
            content: NotificationContent()
                .fromMap(jsonDecode(message['data']['content'])),
      );
}
```
It works fine for `onMessage`
But for `onBackgroundMessage`, the message is received correctly,  But I got the error:

```E/flutter (14286): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: MissingPluginException(No implementation found for method createNewNotification on channel awesome_notifications)```

Thanks.

**Comment by rafaelsetragni** [comment]
Read the README.file, please.

**Comment by a7mdragab** [comment]
> Read the README.file, please.

I made that many times!
Then?

**Comment by rafaelsetragni** [comment]
We recommended to not use the `flutter_local_notification` or `firebase_messaging` plugin at same time that this plugin.

But **dont worry about it any more**.

Since ive read your post here and many others with the same "mistake", that makes me change my mind and considering to revogue the push functionality from this plugin, letting  this role it with firebase_messaging only.

Maybe this plugin should not do all in one. Please, participate to help us to decide witch is the best solution for all.

**Comment by a7mdragab** [comment]
> We recommended to not use the `flutter_local_notification` or `firebase_messaging` plugin at same time as this plugin.
> 
> But **dont worry about it any more**.
> 
> Since ive read your post here and many others with the same "mistake", that makes me change my mind and considering to revogue the push functionality from this plugin, letting this role with firebase_messaging only.
> 
> Maybe this plugin should not do all in one. Please, participate to help us to decide witch is the best solution for all.

Thanks for your reply.
You mean I should remove ```firebase_messaging``` dependancy at all and just use this plugin?

**Comment by rafaelsetragni** [comment]
Maybe not.

Maybe this plugin should not do push notifications, only local notifications.

A lot of developers are using both of then and this could infering that this plugin is doing to much roles and even roles that the community do not need to.

**Comment by a7mdragab** [comment]
> Maybe not.
> 
> Maybe this plugin should not do push notifications, only local notifications.
> 
> A lot of developers are using both of then and this could infering that this plugin is doing to much roles and even roles that the community do not need to.
> 
> Dont change your project yet. Let the voting finish. Maybe the only thing that need to change is this plugin.

This should be respected.
But to make you know, You have made a very very good plugin.
If you could make it compatible with ```firebase_messaging```, It would be the best.
Everyone needs this.
I hope you could make it.

Thanks

**Comment by a7mdragab** [comment]
Hello,
It worked. 
Just remove ```firebase_messaging``` and it will work fine.
Thanks.

Just one problem: How to deal with topics?
I hope you add topics subscription support.

Thanks

**Comment by qianxuechao** [comment]
http://blog.z7ge.com/archives/flutter-missingpluginexception-bu-yao-huang 希望能帮到你

**Comment by a7mdragab** [comment]
Any reply?

**Comment by rafaelsetragni** [comment]
Yes, in version 0.0.6 the push functionality will be removed, so you not gonna face this problems anymore.
