### ISSUE TITLE
Error creating Foreground Service

### ISSUE THREAD

**Issue by masus04** [rafaelsetragni/awesome_notifications#946]
## **1 - Describe the bug**

When creating a Foreground Service according to the documentation, the following error is thrown:

```
.../android/app/src/debug/AndroidManifest.xml Error:
	Attribute service#me.carda.awesome_notifications.core.services.ForegroundService@foregroundServiceType value=(dataSync) from (unknown)
	is also present at [:awesome_notifications] AndroidManifest.xml:48:13-54 value=(phoneCall).
	Suggestion: add 'tools:replace="android:foregroundServiceType"' to <service> element at AndroidManifest.xml to override.
```

pointing to the AndroidManifest.xml. I have tried multiple variants, but no matter what `foregroundServiceType` I use, the error stays the same and the notification is displayed incorrectly.

I am using the Foreground Service in order to build a continuously updating notification (every second) that I would hope also implements a wearOS `Ongoing Activity`.

## **2 - Provide us as much information as possible**

* I ran the app on both an andoid mobile as well as an android wearOS emulator, with the same results.
* Flutter doctor shows no issues, the app is running smoothly without the Foreground Service
* The app also works smoothly with a regular Ongoing Notification using `AwesomeNotifications().createNotification` and the same configuration

Excerpt from AndroidManifest.xml
```
        <service
            android:name="me.carda.awesome_notifications.core.services.ForegroundService"
            android:enabled="true"
            android:exported="false"
            android:stopWithTask="true"
            android:foregroundServiceType="dataSync" />
```

## **3 - How To Reproduce the Error**
1. Create an app with a `Foreground Service` according to the documentation of the package: https://github.com/rafaelsetragni/awesome_notifications?tab=readme-ov-file#android-foreground-services-optional
2. Trigger the `AndroidForegroundService.startAndroidForegroundService` method every second in order to update its status
3. Start an emulator in Android Studio (Android Version 33+)
4. Run app on emulator

## **4 - Expected behavior**
* I expect a notification to be shown as soon as I move the app to the background.
* I expect the notification to be updated every second

## **5 - Screenshots**
App does not start because of error mentioned above.

## **6 - Additional context**
If I remove the `android:foregroundServiceType` attribute from `AndroidManifest.xml`, the app starts as expected. However, the notification is only updated every few seconds and stops being displayed entirely after a few iterations.
This might be a different issue however.

**Comment by craggy2593** [comment]
Same error. Suggests adding `tools:replace="android:foregroundServiceType"` to the `<service>` element. Haven't tested properly, but seems to start the app and displays the notification

```xml
<service
    android:name="me.carda.awesome_notifications.core.services.ForegroundService"
    android:enabled="true"
    android:exported="false"
    android:stopWithTask="true"
    android:foregroundServiceType="dataSync"
    tools:replace="android:foregroundServiceType" <===== THIS LINE
>
```

This also requires you add `xmlns:tools="http://schemas.android.com/tools"` to your `<manifest>` element
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools" <===== THIS LINE
   ...
>
```
