### ISSUE TITLE
Build for web fails

### ISSUE THREAD

**Issue by tigrenok00** [rafaelsetragni/awesome_notifications#948]
# Rules

To report a bug and help us to provide the solution as fast as possible, please follow the instructions below:

## **1 - Describe the bug**

Hi,

Suddenly flutter build web fails with the following:

```
Target dart2js failed: ProcessException: Process exited abnormally:
Error: Couldn't resolve the package 'awesome_notifications_core' in 'package:awesome_notifications_core/awesome_notifications_core_web.dart'.
.dart_tool/flutter_build/06edd3d07f0b028e0af881e89663c234/web_plugin_registrant.dart:11:8:
Error: Not found: 'package:awesome_notifications_core/awesome_notifications_core_web.dart'
import 'package:awesome_notifications_core/awesome_notifications_core_web.dart';
       ^
.dart_tool/flutter_build/06edd3d07f0b028e0af881e89663c234/web_plugin_registrant.dart:36:3:
Error: Undefined name 'AwesomeNotificationsCoreWeb'.
  AwesomeNotificationsCoreWeb.registerWith(registrar);
```

I've been using the package for a long time and its the first time I have an issue with building for web. Do you know what has changed? Is there something I need to configure in flutter to make it work / ignore this error? Running and debugging for web works fine, but not when I want to build and deploy...

## **2 - Provide us as much information as possible**

  awesome_notifications: ^0.9.2
  awesome_notifications_fcm: ^0.9.2
  
[√] Flutter (Channel stable, 3.13.9, on Microsoft Windows [Version 10.0.19045.4046], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.0.2)
[!] Android Studio (version 2021.1)
    X Unable to determine bundled Java version.
[√] Android Studio (version 2022.2)
[√] VS Code (version 1.87.0)
[√] Connected device (5 available)
[√] Network resources

To help us to understand your issue, provide with your bug report all the relevant informations, such as:

* Your plugins list inside the file `pubspec.yaml` (at least all notification plugins)
* What platform did you found the issue
* What devices did you found the issue
* How are you initializing the plugin
* How are you creating the notification
* The output of `flutter doctor` command

OBS: To post a source code in your issue, please use the markdown below:

```Dart
print('Your source code goes here');
```

## **3 - How To Reproduce the Error**

...or if you prefer, you can provide us a simple example app on GitHub with the issue already reproduced instead of the steps 2 and 3.

**Comment by BenjiFarquhar** [comment]
Is web supported?
