### ISSUE TITLE
swipe to dismiss notification.

### ISSUE THREAD

**Issue by vishnuvardhankota** [rafaelsetragni/awesome_notifications#950]
In the below code even i use locked: true and autoDismissible: false the notification is still dismissing if I swipe it. please fix the issue.  and there is no way to recognize that that notification is dismissed by swiping without any actions.

await AwesomeNotifications().createNotification(
        content: NotificationContent(
            id: notificationId,
            channelKey: 'amigos_channel_id_calls',
            title: 'Incoming call from $userName',
            body: 'Tap Answer or Decline',
            payload: {
              "sender": data['sender'],
            },
            locked: true,
            autoDismissible: false,
            notificationLayout: NotificationLayout.Default),
        actionButtons: [
          NotificationActionButton(key: 'ANSWER', label: 'Answer'),
          NotificationActionButton(key: 'DECLINE', label: 'Decline'),
        ]);

**Comment by sagnik-sanyal** [comment]
Hi there are you facing this on Android 14 device with call style notifications ?

**Comment by Nejc-Podlogar** [comment]
Hi @sagnik-sanyal 

We are facing the same problem as @vishnuvardhankota and to answer your question.
Yes the problem is on the **Android version 14**. 

Our code is:

Notification creation:
```dart
Future<void> createLocalInstantNotification(
    BuildContext context, Measurement measurement) async {
  await awesomeNotifications.createNotification(
      content: NotificationContent(
        id: 1,
        channelKey: 'basic_channel',
        title: S.of(context).addTheMeasurementText,
        body: S.of(context).measurementType(measurement.measurementType),
        autoDismissible: false,
        category: NotificationCategory.Alarm,
        wakeUpScreen: true,
        criticalAlert: true,
        locked: true,
      ),
      actionButtons: [
        NotificationActionButton(
            key: 'addMeasurement', label: S.of(context).titleAddMeasurement)
      ]
  );```
  
  For channel creation: 
  
```dart
Future<void> configuration() async {
  await awesomeNotifications.initialize(
      null,
      [
        NotificationChannel(
            channelKey: 'basic_channel',
            channelName: 'Basic Notification',
            defaultColor: Colors.teal,
            importance: NotificationImportance.High,
            channelShowBadge: true,
            channelDescription: 'Basic Instant Notification',
            locked: true
        ),
      ],
      debug: true
  );
}
```

**Comment by sagnik-sanyal** [comment]
Hi @Nejc-Podlogar It seems this occurs due to the behaviour change on Android 14 mentioned here https://developer.android.com/about/versions/14/behavior-changes-all#non-dismissable-notifications

**Comment by swarupbc** [comment]
Hi @sagnik-sanyal 

Also, this new behavior doesn't apply to notifications in the following use cases:

[CallStyle](https://developer.android.com/reference/androidx/core/app/NotificationCompat.CallStyle) notifications
Device policy controller (DPC) and supporting packages for enterprise
Media notifications
The default Search Selector package

is there any way I can use the CallStyle/Ongoing call notification, so my notification remain non-dismissible? like whatsapp ongoing call, I'm trying to achieve the same.
