### ISSUE TITLE
onActionReceivedMethod runs twice

### ISSUE THREAD

**Issue by uemirhanselim** [rafaelsetragni/awesome_notifications#961]
onActionReceivedMethod  runs twice and when notificaiton came and I click on ACCEPT, it navigates twice to the same page.

`      AwesomeNotifications().setListeners(
        
        onActionReceivedMethod: (receivedAction) async {
          if (receivedAction.buttonKeyPressed == "ACCEPT") {
            print("Accept button clicked $roomId");
            print("on foreground");

            
            await context.router.push(VideoCallRoute(pRoomId: roomId!));
            
            
            // TODO: aramaya giererse status ü değiştir aramadan çıkınca da değiştir.
          } else if (receivedAction.buttonKeyPressed == "DECLINE") {
            print("Decline button clicked");
          } else {
            print("clicked on notificaiton");
          }
        },
      );`

**Comment by fraboniface** [comment]
Could it be because you use getInitialNotificationAction without removeFromActionEvents: true ?
