### ISSUE TITLE
Notification not display

### ISSUE THREAD

**Issue by hardik-weenggs** [rafaelsetragni/awesome_notifications#98]
1) Notification doesn't show when app is on Foreground state (in both Android & iOS). it shows only when app is in Background/Killed. It works with action buttons. without action buttons it's not working on Foreground state. 
2) Action button not working in iOS. change `JsonUtils.fromJson` to `JsonUtils.fromJsonArr`

line no. 45
`mapData[Definitions.PUSH_NOTIFICATION_BUTTONS] = JsonUtils.fromJson(buttonsJsonData)`
to 
`mapData[Definitions.PUSH_NOTIFICATION_BUTTONS] = JsonUtils.fromJsonArr(buttonsJsonData)`

**Comment by rafaelsetragni** [comment]
Sure! Maybe an old source has been sent with the last version. Thank you so much! I gonna certify to update it on next version.

**Comment by rafaelsetragni** [comment]
New version released. Check to see if the problem is resolved.

**Comment by eslam-elswesy** [comment]
the same issue

**Comment by rafaelsetragni** [comment]
Have you tried to run the example app inside the plugin? The issue continues in the example app?

**Comment by hardik-weenggs** [comment]
### awesome_notifications: ^0.0.6+7

`Flutter (Channel stable, 2.2.0, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-GB)`
`Dart version 2.13.0`
`Xcode 12.3, Build version 12C33`
`CocoaPods version 1.10.1`

///////////////////
**iOS: 14.2**
- Foreground: working
- Background: not working
- App Killed: not working

**iOS: 12.4.9**
- Foreground: working
- Background: working
- App Killed: not working

- FCM notification does not received in iOS when app is killed/terminate.

**Comment by hardik-weenggs** [comment]
Thanks for your reply.
i have already tried with this today. but it still not working.

**Comment by hardik-weenggs** [comment]
```
{
    "to": "",
    "mutable_content": true,
    "content_available": true,
    "priority": "high",
    "data": {
        "content": {
            "id": 878686,
            "privacy": "Public",
            "channelKey": "local_appointment_alert",
            "title": "***Appointment Alert***",
            "body": "Incoming call",
            "showWhen": true,
            "autoCancel": true,
            "payload": {
                "data": "{\"id\":0,\"user_name\":\"Hardik Dhola\"}"
            }
        },
        "actionButtons": [
            {
                "key": "decline",
                "label": "Decline",
                "autoCancel": true,
                "buttonType": "KeepOnTop"
            },
            {
                "key": "answer",
                "label": "Answer",
                "autoCancel": true,
                "buttonType": "Default"
            }
        ]
    }
}
```
////////////////

```
"notification": {
        "title": "***Appointment Alert***",
        "body": "click here to open app"
    },
```

- it works when i pass **"notification"**, but **"actionButtons"** not display.

**Comment by rafaelsetragni** [comment]
I guess i got whats going on.
`firebase_messaging` does not have action buttons, but `awesome_notifications`, that is only local notifications, have action buttons.

When your application is killed, or you receive a `firebase_messaging` notification or you create a local notification with `awesome_notifications` using backgroundhandle AND data only notification. **Spoiler alert**: it not will work all the times and its expected on iOS.

I suggest that you read the firebase documentation, our documentation and how iOS works with background processing.

**Comment by rafaelsetragni** [comment]
To sendo `firebase_messaging` with action buttons, try to put the parameter `click_action` with all your button keys, in upper case and separated with coma, such as:

```Json
  "to" : "YOUR_PUSH_TOKEN",
  "notification": {
    "title": "This is my title",
    "body": "Some random body content",
    "click_action":"DECLINE,ANSWER"
  },
  "data": {
    "YOUR_CUSTOM_DATA": "DATA"
  }
```

**Comment by rafaelsetragni** [comment]
Its pretty bad how firebase_messaging was implemented. How `click_action` can mean different things in Android or iOS. I gonna need to implement it by my own. Its impossible to make things work fine with this inconsistencies.

**Comment by hardik-weenggs** [comment]
can you create new branch with implementation of `AwesomeServiceExtension`? 
(Flutter 2.2.0)

i have also tried with `awesome_notifications: '0.0.5+7'` but the code is not working in iOS. (it's working in Android only).

**Comment by rafaelsetragni** [comment]
Im developing right now a new plugin to work with current `awesome_notifications` to enable all features by using Firebase push notification.
