### ISSUE TITLE
IOS notification error

### ISSUE THREAD

**Issue by whatamelon** [rafaelsetragni/awesome_notifications#99]
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file awesome_notifications/SwiftAwesomeNotificationsPlugin.swift, line 395

So I changing code
`if actionReceived?.dismissedDate == nil {`
instead of
`if actionReceived!.dismissedDate == nil {`

then, any method does not implemented.

Here's my code.

```
 AwesomeNotifications().createdStream.listen((event) {

      print('created event :  $event');

      if (_mainNotifiID != event.id) {

        _notifiID = event.id;
        _mainNotifiID = event.id;

        AwesomeNotifications().createNotification(
            content: NotificationContent(
                id: _notifiID,
                channelKey: 'basic_channel',
                title: event.title,
                body: event.body
            )
        );
      }
    });

    AwesomeNotifications().displayedStream.listen((event) {
      print('display : $event');
    });

    AwesomeNotifications().dismissedStream.listen((event) {
      print('dismiss : $event');
    });

    AwesomeNotifications().actionStream.listen(
            (receivedNotification){
          print('action : $receivedNotification');

          var payload = receivedNotification.payload;
          print(payload);
          Map<String, dynamic> _viewData = {
            'route': payload['route'],
            'id': payload['id'],
            'event': payload['event'],
            'tab': payload['tab'],
            'searchText': payload['searchText'],
          };

          navigatorKey.currentState.pushAndRemoveUntil(
              MaterialPageRoute(builder: (context) => SplashPage(viewDataSplash: _viewData)), (Route<dynamic> route) => false);
        }
    );
```
As you can see, I printed all streams event. 
But I can't see any printed events.

Also, I implemented all preconditions.

Anyone get solution?

**Comment by rafaelsetragni** [comment]
You're totally right on your fix. Im facing troubles to develop on iOS, because I haven't a real mac to test it.

But, if you implement this changes on your fork and send it back to me, will help me a lot

So, i gonna test it and if everything is just fine, im gonna accept your changes and put your name as this project contributor.

**Comment by whatamelon** [comment]
@rafaelsetragni  thx to reply. 
My point is `if actionReceived?.dismissedDate == nil {` this code doesn't fix the problem that no streams fired.
So, I would try to fix it and renoticed through this issue page.

**Comment by rafaelsetragni** [comment]
Probably is a issue with iOS content extensions missconfigured.

But dont worry about it right now. We are close to decide to remove the push functionlity and let awesome_notifications 100% compatible wit firebase_messaging.

If you didnt vote yet, there is still time to let your contribution.

[https://github.com/rafaelsetragni/awesome_notifications/issues/97](https://github.com/rafaelsetragni/awesome_notifications/issues/97)

**Comment by andyjriley** [comment]
Can you try changing your call back to the following:
```
    AwesomeNotifications().dismissedStream.listen((ReceivedAction dismissedAction) {
      print("Notification dismissed: "+(dismissedAction.title ?? dismissedAction.body ?? dismissedAction.id.toString()));
    });
```
In the mean time I have opened a pull request that should at least unblock you.
